### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by KedarSadhu** [sewenew/redis-plus-plus#103]
Hello sir, I want to use this client on windows platform ...
But I am not able to do so ...can you guide me how to build this project on windows

**Comment by sewenew** [comment]
@KedarSadhu Windows support is still in progress. However, someone has successfully built it with visual studio 2019. Check [this](https://github.com/sewenew/redis-plus-plus/issues/38) for detail. I'll add Windows support these days.

Regards
