### ISSUE TITLE
Bugs in command_options.h

### ISSUE THREAD

**Issue by KedarSadhu** [sewenew/redis-plus-plus#104]
I am using C++ 17
on windows platform

Facing many issues while building the code 

command_options.h(65): warning C4003: not enough actual parameters for macro 'min'

command_options.h(67): warning C4003: not enough actual parameters for macro 'max'

command_options.h(65): error C2059: syntax error: ')'

command_options.h(65): error C2334: unexpected token(s) preceding ':'; skipping apparent function body

command_options.h(68): error C2143: syntax error: missing ')' before ';'

command_options.h(172): error C3412: 'sw::redis::RightBoundedInterval<std::string>': cannot specialize template in current scope

command_options.h(210): error C2059: syntax error: '}'

command_options.h(210): error C2143: syntax error: missing ';' before '}'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\list(28): error C2061: syntax error: identifier 'bidirectional_iterator_tag'

**Comment by KedarSadhu** [comment]
C++ 11 also giving me same error

**Comment by sewenew** [comment]
@KedarSadhu The link I gave you, in fact, already has solved the problem :)

You can add the following code in connection.h:

```
#ifdef _MSC_VER

#define NOMINMAX  // disable Windows' min/max macro

#include <winsock2.h> // for timeval

#endif 
```

I've already built redis-plus-plus static lib without enabling test, and runs some simple test. It works fine. However, I still need to fix how to build a shared lib and the test on Windows. If I have any progress, I'll let you know.

Regards

**Comment by sewenew** [comment]
@KedarSadhu Visual Studio 2019 support has been finished. You can check out the latest code on master branch, and have a try. If you still have any problem with it, feel free to let me know :)

Regards

**Comment by sewenew** [comment]
@KedarSadhu  redis-plus-plus supports building on Windows platform. You can check [this instruction](https://github.com/sewenew/redis-plus-plus#windows-support) for detail.

Regards.

**Comment by KedarSadhu** [comment]
Thank you so much...You are best @sewenew

**Comment by sewenew** [comment]
@KedarSadhu No worries :) If you have any problem on redis-plus-plus, feel free to let me know. If you like it, also feel free to star it :)

Regards
