### ISSUE TITLE
Transaction status

### ISSUE THREAD

**Issue by jrch2k20** [sewenew/redis-plus-plus#105]
Hi, is there any way to query if a transaction object is not empty before calling exec?

In my case i need to add as much commands to the transaction/pipeline as possible in a time range and then commit but if i hit a time when the object has no new transactions, it becomes invalid.

So, i though if the transaction/pipeline object  have anyway to expose if there is pending data, then i can skip exec() until then next iteration but checking the API is not obvious if this is possible.

Thanks in advance and thank you for your hard work

**Comment by sewenew** [comment]
@jrch2k20 There's no way to do that.

As I mentioned in the doc, creating a `Transaction` object is not a cheap operation, especially when you creating it with a new connection. So if you have no command to send with a transaction, you'd better not create one.

In your case, I'd suggest you not creating the `Transaction` object in advance. Instead, you should create it when you need to send a command with the transaction. Take the following code as an example:

```
std::unique_ptr<Transaction> tx;

for (command : commands) {
    if (!tx) tx = std::make_unique<Transaction>(redis.transaction());
    tx->command();
}

if (tx) {
    tx->exec();
}
```

Another solution (not recommended) is to count the number of command sent with the transaction in your application code:

```
Transaction tx;
int cnt = 0;

for (command : commands) {
    tx.command();
    ++cnt;
}

if (cnt > 0) {
    tx.exec();
}
```

Regards

**Comment by jrch2k20** [comment]
I see, ok i'll go with a queue approach then.

Thank you, for your time
