### ISSUE TITLE
after install redis-plus-plus can not find its library 

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#107]
I have installed hedis successfully, and can find its library in its dir;

but, after installing redis-plus-plus, in its installation dir, seems no library is produced, just there is no file named :libredis++.a 

and no error info retured when installed it. but, there were some lines like this:
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/..../redis-plus-plus/compile

why no redis-plus-plus library is produced? Thanks.

**Comment by sewenew** [comment]
@snlv182 It seems that you only run cmake command. After that, you should also run make to build redis-plus-plus. Check the [doc](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) for detail.

Regards

**Comment by snlv182** [comment]
![Uploading 图片.png…]()
 seems something wrong with your test from the error info

**Comment by snlv182** [comment]
seems you can not see my pic?  here is the info in the pic:

/home/****/redis-plus-plus/test/src/sw/redis++/test_****.cpp:4:19: error: expected ‘;’ before ‘:’ token
 using namespace sw:redis;
                   ^
/home/****/redis-plus-plus/test/src/sw/redis++/test_****.cpp:4:19: error: expected unqualified-id before ‘:’ token
/home/****/redis-plus-plus/test/src/sw/redis++/test_****.cpp:7:1: error: expected unqualified-id before ‘try’
 try{
 ^
make[2]: *** [test/CMakeFiles/test_redis++.dir/src/sw/redis++/test_****.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/test_redis++.dir/all] Error 2
make: *** [all] Error 2

**Comment by snlv182** [comment]
(2)sorry, also a simple question for you :
[snlv@nf5280n30-app redis-plus-plus]$ g++ -std=c++11 -I/home/snlv/local -o app app.cpp /home/snlv/local/redis-plus-plus/lib/libredis++.a /home/snlv/local/redis-plus-plus/lib/libredis++.a -pthread
g++: error: app.cpp: No such file or directory

what is app.cpp



> 
> 
> @snlv182 It seems that you only run cmake command. After that, you should also run make to build redis-plus-plus. Check the [doc](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) for detail.
> 
> Regards

o~  yep, sorry, I forgot. Thank you very much.

**Comment by snlv182** [comment]
(3)for the code in "Getting Started", can we write them in app.cpp, then run the following command:

which is in "
![1](https://user-images.githubusercontent.com/60073285/96419717-1a590c00-1227-11eb-9583-787f4c892cda.png)
Use redis-plus-plus In Your Project"

**Comment by snlv182** [comment]
(3)for the code in "Getting Started", can we write them in app.cpp, then run the following command:
g++ -std=c++11 -I/non-default/install/include/path -o app app.cpp /path/to/libredis++.a /path/to/libhiredis.a -pthread


which is in "Use redis-plus-plus In Your Project"


![1](https://user-images.githubusercontent.com/60073285/96419881-4eccc800-1227-11eb-81cd-d2d2dad243b6.png)

************sorry, first time
