### ISSUE TITLE
Can  redis-plus-plus support RedisJSON?

### ISSUE THREAD

**Issue by mjstudio** [sewenew/redis-plus-plus#110]
Hi,

Can redis-plus-plus support RedisJSON (https://github.com/RedisJSON/RedisJSON)?

**Comment by sewenew** [comment]
You can use the [generic interface](https://github.com/sewenew/redis-plus-plus#generic-command-interface) to send RedisJSON command. Take the following as an example:

```
auto redis = Redis("tcp://127.0.0.1");
redis.command<void>("JSON.SET", "doc", ".", R"({"foo" : "bar"})");
auto res = redis.command<OptionalString>("JSON.GET",  "doc", ".foo");
if (res)
  cout << *res << endl;
```

Regards
