### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#112]
(1)seems something wrong with your test from the error info?
I do not know why I can not add pic in the comments? can you add pic?

the error info is as following:

/home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected ‘;’ before ‘:’ token
using namespace sw:redis;
^
/home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected unqualified-id before ‘:’ token
/home//redis-plus-plus/test/src/sw/redis++/test_.cpp:7:1: error: expected unqualified-id before ‘try’
try{
^
make[2]: *** [test/CMakeFiles/test_redis++.dir/src/sw/redis++/test_****.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/test_redis++.dir/all] Error 2
make: *** [all] Error 2

**Comment by snlv182** [comment]
### **(2)for the code in "Getting Started",**
"
#include <sw/redis++/redis++.h>

using namespace sw::redis;

try {
    // Create an Redis object, which is movable but NOT copyable.
    auto redis = Redis("tcp://127.0.0.1:6379");

    // ***** STRING commands *****

    redis.set("key", "val");
    auto val = redis.get("key");    // val is of type OptionalString. See 'API Reference' section for details.
    if (val) {
        // Dereference val to get the returned value of std::string type.
        std::cout << *val << std::endl;
    }   // else key doesn't exist.

    // ***** LIST commands *****

    // std::vector<std::string> to Redis LIST.
    std::vector<std::string> vec = {"a", "b",...........................................................
"

 **_### can we write them in app.cpp, then run the following command:_**
g++ -std=c++11 -I/non-default/install/include/path -o app app.cpp /path/to/libredis++.a /path/to/libhiredis.a -pthread

which is in "Use redis-plus-plus In Your Project"

**Comment by sewenew** [comment]
> (1)seems something wrong with your test from the error info?
> I do not know why I can not add pic in the comments? can you add pic?
> 
> the error info is as following:
> 
> /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected ‘;’ before ‘:’ token
> using namespace sw:redis;
> ^
> /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected unqualified-id before ‘:’ token
> /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:7:1: error: expected unqualified-id before ‘try’
> try{
> ^
> make[2]: *** [test/CMakeFiles/test_redis++.dir/src/sw/redis++/test_****.cpp.o] Error 1
> make[1]: *** [test/CMakeFiles/test_redis++.dir/all] Error 2
> make: *** [all] Error 2

@snlv182 There's no *test_.cpp* file in *redis-plus-plus/test/src/sw/redis++/* directory. Is this a file you added? If you do, can you show me your code?

**Comment by sewenew** [comment]
> ### **(2)for the code in "Getting Started",**
> "
> #include <sw/redis++/redis++.h>
> 
> using namespace sw::redis;
> 
> try {
> // Create an Redis object, which is movable but NOT copyable.
> auto redis = Redis("tcp://127.0.0.1:6379");
> 
> ```
> // ***** STRING commands *****
> 
> redis.set("key", "val");
> auto val = redis.get("key");    // val is of type OptionalString. See 'API Reference' section for details.
> if (val) {
>     // Dereference val to get the returned value of std::string type.
>     std::cout << *val << std::endl;
> }   // else key doesn't exist.
> 
> // ***** LIST commands *****
> 
> // std::vector<std::string> to Redis LIST.
> std::vector<std::string> vec = {"a", "b",...........................................................
> ```
> 
> "
> 
> **_### can we write them in app.cpp, then run the following command:_**
> g++ -std=c++11 -I/non-default/install/include/path -o app app.cpp /path/to/libredis++.a /path/to/libhiredis.a -pthread
> 
> which is in "Use redis-plus-plus In Your Project"

YES, you can put these code into app.cpp, and compile it with the given command.

Regards

**Comment by snlv182** [comment]
> 
> 
> > (1)seems something wrong with your test from the error info?
> > I do not know why I can not add pic in the comments? can you add pic?
> > the error info is as following:
> > /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected ‘;’ before ‘:’ token
> > using namespace sw:redis;
> > ^
> > /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:4:19: error: expected unqualified-id before ‘:’ token
> > /home//redis-plus-plus/test/src/sw/redis++/test_.cpp:7:1: error: expected unqualified-id before ‘try’
> > try{
> > ^
> > make[2]: *** [test/CMakeFiles/test_redis++.dir/src/sw/redis++/test_****.cpp.o] Error 1
> > make[1]: *** [test/CMakeFiles/test_redis++.dir/all] Error 2
> > make: *** [all] Error 2
> 
> @snlv182 There's no _test_.cpp_ file in _redis-plus-plus/test/src/sw/redis++/_ directory. Is this a file you added? If you do, can you show me your code?

@sewenew  no, I did not change it. I did nothing, just do as your command

**Comment by snlv182** [comment]
> 
> 
> > ### **(2)for the code in "Getting Started",**
> > "
> > #include <sw/redis++/redis++.h>
> > using namespace sw::redis;
> > try {
> > // Create an Redis object, which is movable but NOT copyable.
> > auto redis = Redis("tcp://127.0.0.1:6379");
> > ```
> > // ***** STRING commands *****
> > 
> > redis.set("key", "val");
> > auto val = redis.get("key");    // val is of type OptionalString. See 'API Reference' section for details.
> > if (val) {
> >     // Dereference val to get the returned value of std::string type.
> >     std::cout << *val << std::endl;
> > }   // else key doesn't exist.
> > 
> > // ***** LIST commands *****
> > 
> > // std::vector<std::string> to Redis LIST.
> > std::vector<std::string> vec = {"a", "b",...........................................................
> > ```
> > 
> > 
> > "
> > **_### can we write them in app.cpp, then run the following command:_**
> > g++ -std=c++11 -I/non-default/install/include/path -o app app.cpp /path/to/libredis++.a /path/to/libhiredis.a -pthread
> > which is in "Use redis-plus-plus In Your Project"
> 
> YES, you can put these code into app.cpp, and compile it with the given command.
> 
> Regards

@sewenew    but, I am confused about the l**ibraries in your  "Use redis-plus-plus In Your Project"**

![图片](https://user-images.githubusercontent.com/60073285/96676717-92970d00-13a0-11eb-9a34-af22889d495b.png)

how can we decide which library should I use ?  Or every time only one library can we use to "g++"?

**Comment by sewenew** [comment]
By default, redis-plus-plus builds both a static lib and a dynamic lib. It depends on you to decide which one to use.
