### ISSUE TITLE
[ redis-plus-plus ] Build failure

### ISSUE THREAD

**Issue by JonLiu1993** [sewenew/redis-plus-plus#115]
**Host Environment**
- OS: [Windows10]
- Compiler: VS2017

**To Reproduce**
`./vcpkg install redis-plus-plus`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
````
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(75): warning C4200: nonstandard extension used: zero-sized array in struct/union
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(75): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(101): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(126): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(194): warning C4244: 'return': conversion from 'uint64_t' to 'size_t', possible loss of data
F:\test\vcpkg\buildtrees\redis-plus-plus\src\fe7b8200b1-fcbce11089.clean\src\sw\redis++\shards.cpp(42): error C2398: Element '1': conversion from 'unsigned __int64' to 'const _Ty1 &' requires a narrowing conversion
        with
        [
            _Ty1=sw::redis::Slot
        ]
F:\test\vcpkg\buildtrees\redis-plus-plus\src\fe7b8200b1-fcbce11089.clean\src\sw\redis++\shards.cpp(42): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const _Ty1', possible loss of data
        with
        [
            _Ty1=sw::redis::Slot
        ]
[9/17] C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\cl.exe   /TP -DNOMINMAX -Dredis_plus_plus_shared_EXPORTS -IF:\test\vcpkg\buildtrees\redis-plus-plus\src\fe7b8200b1-fcbce11089.clean\src\sw\redis++ -IF:\test\vcpkg\buildtrees\redis-plus-plus\src\fe7b8200b1-fcbce11089.clean\src\sw\redis++\no_tls -IF:\test\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\redis-plus-plus-shared.dir\src\sw\redis++\redis_cluster.cpp.obj /FdCMakeFiles\redis-plus-plus-shared.dir\ /FS -c F:\test\vcpkg\buildtrees\redis-plus-plus\src\fe7b8200b1-fcbce11089.clean\src\sw\redis++\redis_cluster.cpp
F:\test\vcpkg\installed\x86-windows\include\hiredis\sds.h(51): warning C4200: nonstandard extension used: zero-sized array in struct/union
````
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by sewenew** [comment]
@JonLiu1993 It seems that you built redis-plus-puls with x86 settings, and in this case, `size_t` is smaller than `unsigned long long`.

I fixed the problem by doing a `static_cast` explicitly. However, I don't have a Windows box near by, and cannot test it. Please try the latest code to see if it works. If you still have problem with it, feel free to let me know.

Thanks for finding this problem.

Regards

**Comment by sewenew** [comment]
@JonLiu1993 It seems that you built redis-plus-puls with x86 settings, and in this case, `size_t` is smaller than `unsigned long long`.

I fixed the problem by doing a `static_cast` explicitly. However, I don't have a Windows box near by, and cannot test it. Please try the latest code to see if it works. If you still have problem with it, feel free to let me know.

Thanks for finding this problem.

Regards

**Comment by JonLiu1993** [comment]
@sewenew , I tested your change method, it is effective, but I also used another method yesterday and it is effective, I have tested it, can you take a look [#14180](https://github.com/microsoft/vcpkg/pull/14180)

**Comment by sewenew** [comment]
@JonLiu1993 Yes, your change also works. However, you'd better cast it to `Slot`, instead of `std::size_t`. If `Slot` is defined to some other type in the future, this change might break again.

Regards

**Comment by sewenew** [comment]
Also thanks for your work to make redis-plus-plus work with vcpkg :)
