### ISSUE TITLE
quetion about transaction

### ISSUE THREAD

**Issue by gbuniv** [sewenew/redis-plus-plus#116]
`while (true) {
    try {
        // Watch a key.
        r.watch("key");

        // Get the old value.
        auto val = r.get("key");
        auto num = 0;
        if (val) {
            num = std::stoi(*val);
        } // else use default value, i.e. 0.

        // Incr value.
        ++num;

        // Execute the transaction.
        auto replies = tx.set("key", std::to_string(num)).exec();

        // Transaction has been executed successfully. Check the result and break.

        assert(replies.size() == 1 && replies.get<bool>(0) == true);

        break;
    } catch (const WatchError &err) {
        // Key has been modified by other clients, retry.
        continue;
    } catch (const Error &err) {
        // Something bad happens, and the Transaction object is no longer valid.
        throw;
    }
}`
hello, @sewenew .when using transaction,if something error bwtween watch and exec,shouldn't we send unwatch command,but i don't see this in  your example.

**Comment by sewenew** [comment]
@gbuniv As I mentioned in README.md and comment, if you get an exception other than `WatchError`, the `Transaction` object enters invalid state, and you should destroy it. In this case, when you destroy it, the underlying connection will be closed. So you don't need to send a `UNWATCH` command manually.

If your application code meets some error, and you cannot call `exec` any more. In this case, you should call `Transaction::discard` to discard the transaction, or destroy the `Transaction` object.

Regards

**Comment by gbuniv** [comment]
ok,thanks.i have tried to using Transaction::discard in that case,but met a error:"No command in transaction".and now i destroy the  object.

**Comment by sewenew** [comment]
Yes, if you didn't call any command with the `Transaction` object, and tries to run `discard` or `exec`, it will throw that error. In this case, you have to destroy it. I might change this behavior in the future to avoid this exception.

Regards
