### ISSUE TITLE
How to only use static lib with cmakelists.txt

### ISSUE THREAD

**Issue by Dashing-Nelson** [sewenew/redis-plus-plus#118]
Hello,
Am new to c++ and wanted to use your lib. I selected the option to only build with static lib.

Now i am running into the following issue

```
make[2]: *** No rule to make target '/usr/local/lib/libredis++.so', needed by 'demo'. Stop.
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/demo.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
make[3]: *** No rule to make target '/usr/local/lib/libredis++.so', needed by 'demo'. Stop.
make[2]: *** [CMakeFiles/Makefile2:95: CMakeFiles/demo.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/demo.dir/rule] Error 2
make: *** [Makefile:137: demo] Error 2
```

```
# <------------ add hiredis dependency --------------->
find_path(HIREDIS_HEADER hiredis)
target_include_directories(${PROJECT_NAME} PUBLIC ${HIREDIS_HEADER})

find_library(HIREDIS_LIB hiredis)
target_link_libraries(${PROJECT_NAME} ${HIREDIS_LIB})

# <------------ add redis-plus-plus dependency -------------->
# NOTE: this should be *sw* NOT *redis++*
find_path(REDIS_PLUS_PLUS_HEADER sw)
target_include_directories(${PROJECT_NAME} PUBLIC ${REDIS_PLUS_PLUS_HEADER})

find_library(REDIS_PLUS_PLUS_LIB redis++)
target_link_libraries(${PROJECT_NAME} ${REDIS_PLUS_PLUS_LIB})
```

What am i doing wrong?

**Comment by Dashing-Nelson** [comment]
got it.
did 
`/usr/local/lib/libredis++.a /usr/local/lib/libhiredis.a`
and it worked. But is there a better way?

**Comment by sewenew** [comment]
You can set -DCMAKE_PREFIX_PATH=/usr/local option to specify the installation path of hiredis and Redis++, when you run cmake to build your project.

**Comment by Dashing-Nelson** [comment]
I did that, but for static building, you need to mention it in the cmakelists.txt file

**Comment by sewenew** [comment]
Sorry, but I tried it on MacOS, and cannot reproduce the problem. The find_library function should located the static lib correctly when you set the prefix path. I’ll try it on Linux tomorrow.

**Comment by Dashing-Nelson** [comment]
No need. I made a docker image and tried and it worked. Seems like a configuration issue. Closing this.
