### ISSUE TITLE
redisAsyncContext support  for asynchronous command processing 

### ISSUE THREAD

**Issue by iasna** [sewenew/redis-plus-plus#119]

**Comment by sewenew** [comment]
Duplicate of #13

**Comment by sewenew** [comment]
Async support is out! Although, so far, Redis Cluster, Redis Sentinel, Transaction and Subscriber support are still on the way.

Please check the [doc](https://github.com/sewenew/redis-plus-plus#async-interface) for detail.

Regards

**Comment by sewenew** [comment]
Async support has been release with redis-plus-plus 1.3.0.

Regards
