### ISSUE TITLE
Where is the default installation path of Redis++ header?

### ISSUE THREAD

**Issue by NDelt** [sewenew/redis-plus-plus#12]
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
(my project)/REDIS_PLUS_PLUS_HEADER
```

I've installed Redis++ with default prefix, but CMake doesn't recognize `REDIS_PLUS_PLUS_HEADER`. `hiredis` directory exists in `/usr/local/include` but Redis++ doesn't.

How to I fix this?

**Comment by sewenew** [comment]
@NDelt ,

If you installed redis++ with default prefix, these headers should be located at: `/usr/local/include/sw/redis++/` directory.

**NOTE**: there's a ***sw*** directory. I think you might have the following line in your CMakeLists.txt:

```
find_path(REDIS_PLUS_PLUS_HEADER redis++)    ### <----- this is wrong!!!
```

Instead, you should use the following:

```
find_path(REDIS_PLUS_PLUS_HEADER sw)
```

Take the following CMakeLists.txt as an example:

```
usesr@712692f3ee8f:~/code/test$ls
CMakeLists.txt  src

usesr@712692f3ee8f:~/code/test$ls src
main.cpp
```

Content of CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0.0)
set(CMAKE_CXX_FLAGS "-std=c++11 -Wall -W -Werror -fPIC")
file(GLOB PROJECT_SOURCE_FILES "${PROJECT_SOURCE_DIR}/src/*.cpp")
add_executable(project_bin ${PROJECT_SOURCE_FILES})
# <------------ add hiredis dependency --------------->
find_path(HIREDIS_HEADER hiredis)
target_include_directories(project_bin PUBLIC ${HIREDIS_HEADER})
find_library(HIREDIS_LIB hiredis)
target_link_libraries(project_bin ${HIREDIS_LIB})
# <------------ add redis-plus-plus dependency -------------->
# NOTE: this should be *sw* NOT *redis++*
find_path(REDIS_PLUS_PLUS_HEADER sw)
target_include_directories(project_bin PUBLIC ${REDIS_PLUS_PLUS_HEADER})
find_library(REDIS_PLUS_PLUS_LIB redis++)
target_link_libraries(project_bin ${REDIS_PLUS_PLUS_LIB})
```

If you still have problem, feel free to let me know.

Regards.

**Comment by NDelt** [comment]
@sewenew I have no `../sw/redis++/` in `/usr/local/include/` directory. (But I have `libredis++.a` and `libredis++.so`)

**Comment by NDelt** [comment]
@sewenew It was my mistake. I forgot to run `sudo make install`. Thanks
