### ISSUE TITLE
Is opts.tls.cacert really optional when connecting to a Redis cluster?

### ISSUE THREAD

**Issue by nysenthil** [sewenew/redis-plus-plus#122]
Your documentation on the main GitHub page says the following.

 opts.tls.cacert = "/path/to/CA/certificate/file";   // Optional

When I tried to make a TLS connection from my C++ client application to a redis 6.0.9 cluster node without specifying cacert, it fails with an error, "Certificate verification failed.". Only after  pointing to a correct CA  certificate file obtained from the Redis  cluster machine, it allows my  TLS   connection. Does that mean, your documentation needs a correction?

**Comment by sewenew** [comment]
@nysenthil Yes, it's a little confusing. However, as I mentioned in the doc, you can set `tls.cacertdir` instead of `tls.cacert`. So `tls.cacert` is optional.

> Instead of specifying tls.cacert, you can also specify tls.cacertdir to the directory where certificates are stored.

Regards
