### ISSUE TITLE
ZADD - no key specified

### ISSUE THREAD

**Issue by ppapryczka** [sewenew/redis-plus-plus#123]
Hi! The issue I spotted is rather simple - it try to `ZADD` empty map and I get following message:

`  ZADD: no key specified`

I debug through code and find why such exception is throw, but maybe it will be easier for next users to point that such exception may be thrown by 'zadding' empty map/container?

**Comment by sewenew** [comment]
Yes, you're right. You cannot call `zadd`, `sadd`, `hmset` with empty containers. Otherwise, redis-plus-plus will throw an exception. I'll add some documentation for that, and maybe have a specific exception for it, e.g. EmptyRangeError.

Thanks for pointing it out!

Regards

**Comment by ppapryczka** [comment]
Thank You!
