### ISSUE TITLE
[Question] Achieve pipelining for redis cluster model

### ISSUE THREAD

**Issue by rajanarayan92** [sewenew/redis-plus-plus#127]
How can we achieve pipelining in the case of redis cluster model? Does redis plus plus natively support this?

Appreciate your help.

Thank you,
Raj

**Comment by sewenew** [comment]
@rajanarayan92 You can use `Pipeline RedisCluster::pipeline(const StringView &hash_tag, bool new_connection = true);` to create a `Redis` object, and do pipeline with this object. Please check the [doc and example part](https://github.com/sewenew/redis-plus-plus#pipeline-and-transaction) for detail.

Regards

**Comment by rajanarayan92** [comment]
Thanks for the quick response. Sorry, somehow I overlooked this part.
Regards,
Raj
