### ISSUE TITLE
ZPOP* functions throws ProtoError "NOT key-value PAIR reply"

### ISSUE THREAD

**Issue by twoixter** [sewenew/redis-plus-plus#129]
I'm using the **ZPOP*** family of functions and was surprised they throw `ProtoError` with message "_NOT key-value PAIR reply_" for an empty sorted set. The **SPOP** command doesn't throw for empty sets, and was expecting **ZPOPMIN**, etc, to do the same.

The definition of `zpopmin` function seems to suggest this is a bug:

```cpp
/// @brief Pop the member with lowest score from sorted set.
/// @param key Key where the sorted set is stored.
/// @return Member-score pair with the lowest score.
/// @note If sorted set is empty `zpopmin` returns    <<<<< Optional!!
///       `Optional<std::pair<std::string, double>>` (`std::nullopt`).
/// @see `Redis::bzpopmin`
/// @see https://redis.io/commands/zpopmin
Optional<std::pair<std::string, double>> zpopmin(const StringView &key);
^^^^^^^^ Optional pair
```

However, I'm getting the `ProtoError` exception.

**Versions**
Redis Server: `Redis server v=6.0.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=2c70595953426f5b`
Redis Plus Plus tag: `1.2.1` compiling from source
CMake version: `3.18.4` using C++17 Standard
Compiler and toolchain macOS 11 `clang version 12.0.0 (clang-1200.0.32.28) `

**Comment by sewenew** [comment]
@twoixter Yes, that's a bug! I've fixed the problem with [this](https://github.com/sewenew/redis-plus-plus/commit/1010a2bdac1e1c8e57a59431ffc02b943b4b7a97) commit. Please try the latest code on master branch.

Sorry for the inconvenience, and thanks for finding the bug!

Regards

**Comment by twoixter** [comment]
Wow! @sewenew that was fast! ;-) I just tried and worked like a charm, thank you!
