### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by gandeevan** [sewenew/redis-plus-plus#13]
Are there plans to introduce async support anytime soon? Thanks!

**Comment by sewenew** [comment]
Hi @gandeevan 

I'm sorry, but by now, there's no plan for async support.

In most cases, Redis is supper fast, and won't block the client for a long time. You can try the synchronous interface, and do some benchmark. If you DO need async interface, you can use the  hiredis lib, which supports [async api](https://github.com/redis/hiredis#asynchronous-api).

However, I'll add async support in a TODO list. When I'm not too busy with other stuffs, I'll try it.

Regards

**Comment by gandeevan** [comment]
Thanks!

**Comment by sewenew** [comment]
Async support is out! Although, so far, Redis Cluster, Redis Sentinel, Transaction and Subscriber support are still on the way.

Please check the [doc](https://github.com/sewenew/redis-plus-plus#async-interface) for detail.

Regards

**Comment by sewenew** [comment]
Hi all,

Async support has been release with redis-plus-plus 1.3.0.

Regards

**Comment by raghubk** [comment]
Is the Async support for Pub Sub in redis plus plus coming anytime soon? Thanks

**Comment by raghubk** [comment]
Thanks @sewenew. 

In our system, each application process is single threaded and uses epoll_wait() to handle events. Wondering how to use EventLoop of aysnc subscriber feature with epoll_wait(). 
I was thinking of adding a timer_fd in the epoll_event and whenever the timer fires... check for any message on the channel. Is this feasible? If a message arrives before the timer kicks, do we loose the message?
A sample reference would help. Thanks

**Comment by sewenew** [comment]
@raghubk By default, redis-plus-plus create a event loop thread for AsyncRedis, and async subscriber's callback runs in this thread. So normally, you don't need to make it work with epoll_wait. Instead, you only need to register callbacks and subscribe channels or patterns. In callbacks, you can handle messages you received. Check the doc for more detail.

Regards
