### ISSUE TITLE
DCMAKE OR CMAKE?

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#130]
![redis](https://user-images.githubusercontent.com/60073285/102854706-0798c880-445e-11eb-9af1-5a9e657316f0.png)
 
Hi, in the code, it is DCMAKE, but in the doc, it is CMAKE...
may will mislead someone? it should be DCMAKE, right~

Thanks.

**Comment by sewenew** [comment]
@snlv182 `CMAKE_PREFIX_PATH` is a cmake variable. However, in order to specify a value for the variable with command line argument, you need to prefix it with `-D`, e.g. `-DCMAKE_PREFIX_PATH=/path/to/hiredis`.

Please check cmake's doc for detail.

Regards

**Comment by snlv182** [comment]
o ~  got it, Thank you very much.
