### ISSUE TITLE
can not find redis++.h

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#132]
hi, I have written as the example shows in redis-plus-plus(the same direct as "src"):
![图片](https://user-images.githubusercontent.com/60073285/102871391-5738bd80-4479-11eb-97f5-a5a185277bbf.png)

but, when I run , it is as no redis++.h
![图片](https://user-images.githubusercontent.com/60073285/102871535-84856b80-4479-11eb-97d3-c031640641d0.png)

but , it is here:
![图片](https://user-images.githubusercontent.com/60073285/102871668-aa127500-4479-11eb-9029-7f93b40f52fd.png)

codes:
![图片](https://user-images.githubusercontent.com/60073285/102871712-b4cd0a00-4479-11eb-9768-36e0c036c929.png)
Thanks.

**Comment by sewenew** [comment]
@snlv182 You need to specify the installation path of header files and dynamic libraries with `-I` and `-L` options:

```
g++ -std=c++11 -I/non-default/install/include/path -L/non-default/install/lib/path -o app app.cpp -lredis++ -lhiredis -pthread
```

Please check the [doc](https://github.com/sewenew/redis-plus-plus#use-shared-libraries) for detail.

Regards

**Comment by snlv182** [comment]
so, it seams, the redis and hiredis `s header filers and dynamic libraries should better be in the same direct especially when you use your own direct then there is only one -I and -L in the command.

such as , if default, they are all in /usr/bin.
like: in the lib, you can see libhiredis.so,  libhiredis.a and libredis++.so, libredis++.a

**Comment by sewenew** [comment]
@snlv182 It's not a big deal. You can install them in different directories. Because you can have multiple `-I` and `-L` options. For example:

```
g++ -std=c++11 -I/path/to/hiredis/include -I/path/to/redis++/include -L/path/to/hiredis/lib -L/path/to/redis++/lib -o app app.cpp -lredis++ -lhiredis -pthread
```

Regards

**Comment by snlv182** [comment]
o ~~  got it, thank you very much. You are always so patient to me---
