### ISSUE TITLE
how to find code related to redis-cli

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#133]
when we use base redis, and there are more than one redis cluster, in order to use all of them, we use :
redis-cli    -c
 
when we use redis-plus-plus, we should use : RedisCluster??
such as :
auto redis_cluster = RedisCluster("tcp://password@IP:port");
??

but, error returned,

![图片](https://user-images.githubusercontent.com/60073285/103074728-2eddca00-4605-11eb-9544-64c8e8b0d2a6.png)

so, (1)is "RedisCluster" same as "redis-cli -c" ??
     (2)and the related code is in redis-cluster.h ??

Thanks.

**Comment by sewenew** [comment]
Yes, if you want to connect to Redis Cluster, you need to create a `RedisCluster` object.

However, from the error message you given, it seems that you got some DNS resolution problem. Are you constructing the uri with a host name instead of IP address? If you do, you need to ensure the host name can be correctly resolved.

Regards

**Comment by snlv182** [comment]
（1）I add hostname today as follows:

**auto redis_cluster = RedisCluster("tcp://tr730-appNet:passWord@10.221.1.21:9180");**

and errors:
![图片](https://user-images.githubusercontent.com/60073285/103128730-70d44200-46d1-11eb-8af3-e9c07737e82d.png)

the hostname I got is using "hostname" command in 10.221.1.21, it should be correct;

![图片](https://user-images.githubusercontent.com/60073285/103128954-04a60e00-46d2-11eb-952b-aa09d0ef706a.png)


（2）in fact, I have tried the " ConnectionOptions" with :

**ConnectionOptions connection_options;
  connection_options.host = "10.221.1.21";
  connection_options.port = 9180;
  connection_options.password = "passWord";**

and with "ConnectionOptions", successful value can be gotten when search with "key".
 which means the IP(10.221.1.21) and port(9180) and pass(passWord) are all right.

**Comment by sewenew** [comment]
@snlv182 The uri you specified is incorrect. Instead it should be: *tcp://passWord@10.221.1.21:9180*

Regards

**Comment by snlv182** [comment]
Hi, @sewenew 
this is my code:

**#include <iostream>
#include <sw/redis++/redis++.h>

using namespace sw::redis;

int main()
{
  ConnectionOptions connection_options;
  connection_options.host = "10.221.1.21";
  connection_options.port = 9180;
  connection_options.password = "password";

  //auto redis = Redis("tcp://10.221.1.21:9180");
  Redis redis1(connection_options);


  redis1.set("key", "valSnlv");
  auto val = redis1.get("key");

  if(val)
  {
    std::cout << *val << std::endl;
  }

  auto redis_cluster = RedisCluster("tcp://password@10.221.1.21:9180");

  return 0;
}**


and the print is :
![图片](https://user-images.githubusercontent.com/60073285/103199955-12080600-4927-11eb-8fe6-3e968e652ab1.png)

I really can not find why this error happened...... it is just unreasonable...

**Comment by sewenew** [comment]
Does 10.221.1.21:9180 is a single Redis instance or a node of a Redis Cluster? Also, does `auto redis = Redis("tcp://password:10.221.1.21:9180");` work?

Regards

**Comment by snlv182** [comment]
(1) it is a redis, see as follows:
![214](https://user-images.githubusercontent.com/60073285/103255061-c9058f80-49c2-11eb-9e91-68fb3719b51a.png)

sorry for masking ip and port, because it is related to work, not just myself to use , so, considering security , I mask them.
But, you can see, for  "10.221.1.21" it is cluster, and except 9180, there are some other port;

(2) I have test :  
auto redis = Redis("tcp://password:10.221.1.21:9180");

for this code, it is successful, but, when I set value into it, error return:
![图片](https://user-images.githubusercontent.com/60073285/103255846-dec88400-49c5-11eb-90db-42ab3fa9d9f3.png)

and this is the code:
![图片](https://user-images.githubusercontent.com/60073285/103256331-d8d3a280-49c7-11eb-9f27-4b414ffed626.png)

and this is the code from redis.h:
![图片](https://user-images.githubusercontent.com/60073285/103256349-f0ab2680-49c7-11eb-8790-8877044fb81c.png)

**Comment by sewenew** [comment]
So if you manually set `ConnectionOptions`, and it works. However, if you use URI to construct `Redis` or `RedisCluster`, it fails? Which version of redis-plus-plus are you using? The latest code in master branch? or release 1.2.1 ?

>auto redis = Redis("tcp://password:10.221.1.21:9180");
> for this code, it is successful, but, when I set value into it, error return:

Because `Redis` creates connection lazily, it only create the connection when you send command with it.

Also from your screen shot, the IP address is *10.221.163.xxx*, but in your sample code, the address is *10.221.1.21*. Is that a problem?

Regards

**Comment by snlv182** [comment]
(1)for this:
"so if you manually set ConnectionOptions, and it works. However, if you use URI to construct Redis or RedisCluster, it fails?"
yes, now, it acts like this;

(2)it is branch master, 
![图片](https://user-images.githubusercontent.com/60073285/103342217-ec643380-4ac3-11eb-9729-ecc8487629b4.png)

(3)for this:
"Also from your screen shot, the IP address is 10.221.163.xxx, but in your sample code, the address is 10.221.1.21. Is that a problem?"
 no, it is not a proplem. I have said above,
![图片](https://user-images.githubusercontent.com/60073285/103342333-3816dd00-4ac4-11eb-9a75-d9fb9af7b7bc.png)

because I am doing for my company, so, I can not give you my exact IP and port in the Internet.   in fact it is 10.221.163.xx,
but, I should mask it to 10.221.1.21 when I write it here , because of  "confidentiality" and "security".

(4)yes  , in the password, there is @,  and because of this:

![图片](https://user-images.githubusercontent.com/60073285/103342563-c55a3180-4ac4-11eb-86ac-43850d37cd2b.png)

so, only when I set value into it, error info is returned? and the error info not because of "set value into it ",but because of "tcp,,,,,",  when it is parsed,  error occured?~~~

(4)for redisCluter, except 
" auto redis_cluster = RedisCluster("tcp://........")
this method, is there any other method? 
such as "ConnectionOptions",   the URL and password are separated.



So!  this is the reason !!

**Comment by sewenew** [comment]
> so, only when I set value into it, error info is returned? and the error info not because of "set value into it ",but because of "tcp,,,,,", when it is parsed, error occured?~~~

Yes, when you try to send command with `Redis` object, it tries to create a connection with invalid host name, and throw the exception.

> is there any other method? such as "ConnectionOptions", the URL and password are separated.

Yes, you can create a `RedisCluster` object with `ConnectionOptions`:

```
ConnectionOptions connection_options;
connection_options.host = "10.221.1.21";
connection_options.port = 9180;
connection_options.password = "passWord";

auto cluster = RedisCluster(connection_options);
```

Please check the [doc](https://github.com/sewenew/redis-plus-plus/#connection-1) for detail, including other parameters for the constructor of `RedisCluster`.

Regards

**Comment by snlv182** [comment]
Oh, great~~  it seems I should read the doc again and serious.

Thanks very much and again & again.

Hope our system can use your redis-plus-plus after we try and analyze~~

**Comment by sewenew** [comment]
Thanks for choose redis-plus-plus! Feel free to spread it :)

Regards
