### ISSUE TITLE
sw::redis::ProtoError

### ISSUE THREAD

**Issue by ashwani29** [sewenew/redis-plus-plus#134]
I've to send the request in batches to the Redis server so i'm i creating a pipeline of command which consists of 50% set requests and 50% get requests , and i don't want to create new connection everytime for redis pipeline command, so i've passed false as a parameter to the pipeline command.

But it throws below error:
```
terminate called after throwing an instance of 'sw::redis::ProtoError'
  what():  Expect STATUS reply
Aborted (core dumped)

```

```
#include <sw/redis++/redis++.h>
#include <bits/stdc++.h>

using namespace std;
using namespace sw::redis;

int main(){

	    // ***** Pipeline *****
	    auto redis = Redis("tcp://192.168.122.50:6379");
	    // Create a pipeline.
	while(true){
		auto pipe = redis.pipeline(false);
	    for(int i=1; i<=500; i++){
		string s = to_string(i);
		if(i%2 == 1){
			pipe.set(s, s);
		}
		else {
			string st = to_string(i-1);
			pipe.get(st);		
		}
	    }
	    // Send mulitple commands and get all replies.
	    auto pipe_replies = pipe.exec();
	    // Parse reply with reply type and index.
	    auto set_cmd_result = pipe_replies.get<bool>(0);

	    auto get_cmd_result = pipe_replies.get<OptionalString>(1);

	    // rename command result
	    pipe_replies.get<void>(2);

	    auto rpush_cmd_result = pipe_replies.get<long long>(3);

	    std::vector<std::string> lrange_cmd_result;
	    pipe_replies.get(4, back_inserter(lrange_cmd_result));
	    pipe.discard();
	}

return 0;
}
```

Need help here. 

EDIT: How can I read the replies returned by the pipeline? specifically in this case.

**Comment by sewenew** [comment]
@ashwani29 You got the exception, because you were trying to parse a `bool` result as `void`, i.e. `pipe_replies.get<void>(2);`.

You can try the following code:

```
auto pipe = redis.pipeline(false);
for (int i=1; i<=500; i++) {
   string s = to_string(i);
   if (i%2 == 1){
       pipe.set(s, s);
   } else {
      string st = to_string(i-1);
      pipe.get(st);		
  }
}

auto pipe_replies = pipe.exec();

for (int i=1; i<=500; i++) {
   if (i%2 == 1) {
       auto set_result = pipe_replies.get<bool>(i);
   } else {
      OptionalString get_result = pipe_replies.get<OptionalString>(i);		
  }
```

Regards

**Comment by ashwani29** [comment]
Thanks for the answer, this works good but how can I print the return result, simple `cout` is giving a large number of warnings and 1 error for `cout<<get_result;`  but alone `cout<<set_result;` compiles successfully but throws below error on execution:
```
terminate called after throwing an instance of 'sw::redis::ProtoError'
  what():  Expect INTEGER reply
Aborted (core dumped)

```

**Comment by sewenew** [comment]
You cannot `cout` an `OptionalString` object. Instead, you need to deference it to a `std::string`.

```
for (int i=1; i<=500; i++) {
   if (i%2 == 1) {
       auto set_result = pipe_replies.get<bool>(i);
       cout << set_result << endl;
   } else {
      OptionalString get_result = pipe_replies.get<OptionalString>(i);	
      if (get_result)
          cout << *get_result << endl;	
     else
          cout << "key does not exist" << endl;
  }
}
```

Regards

**Comment by sewenew** [comment]
> where I can find the documentation for return replies types and methods?

You can check the [doc](https://github.com/sewenew/redis-plus-plus#return-type) for general explanation for return types. And for each method's return type, you can check *redis.h* file, which has Doxygen style comment.

**Comment by ashwani29** [comment]
still getting this error repeatedly
> ```
> terminate called after throwing an instance of 'sw::redis::ProtoError'
>   what():  Expect INTEGER reply
> Aborted (core dumped)
> ```
>

this is how i'm compiling it  : `g++ -std=c++11 -o hclient hclient.cpp -lredis++ -lhiredis`

was testing on compiling with  flag `-std=c++17`, it gives below error:

**Comment by sewenew** [comment]
@ashwani29 My bad! I didn't notice that your index in for loop is starting from 1, instead of 0...

The following code to print the result should work:

```
for (int i=1; i<=500; i++) {
      if (i%2 == 1) {
          auto set_result = pipe_replies.get<bool>(i - 1);      // <------ CHANGE HRER
          cout<<set_result<<"\n";
      } else {
          OptionalString get_result = pipe_replies.get<OptionalString>(i - 1);       // <-------- AND CHANGE HERE
          if (get_result)
              cout << *get_result << endl;
          else
              cout << "key does not exist" << endl;
      }
}
```

Also, in your case, you don't need to call `pipe.discard();` manually.

Regards

**Comment by sewenew** [comment]
> was testing on compiling with flag -std=c++17, it gives below error:

In order to compile with c++17, you need to rebuild redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17` as the cmake command line argument. Check the [doc](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) for detail.

**Comment by ashwani29** [comment]
Thanks, i thought the parameter `i` is the value of key instead of index of the pipe_result.
> @ashwani29 My bad! I didn't notice that your index in for loop is starting from 1, instead of 0...



already did this, don't  know why getting this error, will  build again using `stdc++=17` flag later, but it's working for now.
> In order to compile with c++17, you need to rebuild redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17` as the cmake command line argument. Check the [doc](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) for detail.

one question, 1) does my code makes sure that, it is using only a single connection to the server? 2) even on using `pipe.discard()`?

I'm new to this redis, and in my case,  there will be a scenario where redis server will send responses much later, say will take seconds, is there a chance that client's connection will break? If it is then how can i prevent this, as i do not want this. I want that once a client is connected, the connection is live, it should not break doesn't matter whether client is not  sending data or server is taking too long to respond.

**Comment by sewenew** [comment]
> one question, 1) does my code makes sure that, it is using only a single connection to the server? 2) even on using pipe.discard()?

Yes. Since you create a Pipeline object with `redis.pipeline(false)`, it won't create a new connection.

> I want that once a client is connected, the connection is live, it should not break doesn't matter whether client is not sending data or server is taking too long to respond.

NO, there's no such guarantees. There're many possible situations that the connection might broken, e.g. the network might have some problem, and the connection will be closed; Redis server might close idle connections.

Regards

**Comment by ashwani29** [comment]
Ok got it, Thanks for the reply.
