### ISSUE TITLE
Redis connect timeout error

### ISSUE THREAD

**Issue by ashwani29** [sewenew/redis-plus-plus#136]
Below code is getting a connection timeout error.

```
int main(){

	    // ***** Pipeline *****
	    auto redis = Redis("tcp://192.168.122.50:6379");
	    // Create a pipeline.
	    sleep(5);
	    int ep = 100;
	while(true){
cout<<"========================"<<ep<<"==================================================\n";

		auto pipe = redis.pipeline(false);
	    for(int i=1; i<=500; i++){
			string s = to_string(i);
			if(i%2 == 1){
				pipe.set(s, s);
			}
			else {
				string st = to_string(i-1);
				pipe.get(st);		
			}
	    }
	    auto pipe_replies = pipe.exec();

	    pipe.discard();
	}
```

Terminal output:
```
secondaryvm@secondaryvm:~/tests$ ./hclient
========================100==================================================
terminate called after throwing an instance of 'sw::redis::TimeoutError'
  what():  Failed to connect to Redis: Connection timed out
Aborted (core dumped)
```

So it is understood that the code is has executed this line: 	    `auto redis = Redis("tcp://192.168.122.50:6379");`
Doesn't it mean that the client has made a connection to the redis-server and now it will only send data over that tcp connection?

I wonder what this `auto pipe = redis.pipeline(false);` statement is actually doing, according to my knowledge it creates a pipeline object with the already established redis conenction, and the parameter false here indicates that it will use only single connection every time it creates a new pipeline object.

But looking at the `tcpdump's` tcp stream , before executing every pipeline call, a `SYN`, `SYN +ACK` , `ACK` packets are interchanged with the server, so how does it reusing the same single connection every time?

**Comment by sewenew** [comment]
> Doesn't it mean that the client has made a connection to the redis-server and now it will only send data over that tcp connection?

NO. redis-plus-plus create connection lazily, i.e. it creates connection when it tries to send the command. In your case, it creates the connection when you calls `Redis::set`.

From the error message, it seems that redis-plus-plus failed to connect to Redis. Can you try to use the official client, i.e. redis-cli, to test if Redis server works?

> I wonder what this auto pipe = redis.pipeline(false); statement is actually doing, according to my knowledge it creates a pipeline object with the already established redis conenction, and the parameter false here indicates that it will use only single connection every time it creates a new pipeline object.

Yes, in your case, it reuses the single connection.

> But looking at the tcpdump's tcp stream , before executing every pipeline call, a SYN, SYN +ACK , ACK packets are interchanged with the server, so how does it reusing the same single connection every time?

From the error message, your code failed to connect to Redis server when it send the first set command, and exit. How can you multiple SYN, SYN +ACK , ACK packets?

Regards

**Comment by ashwani29** [comment]
> > But looking at the tcpdump's tcp stream , before executing every pipeline call, a SYN, SYN +ACK , ACK packets are interchanged with the server, so how does it reusing the same single connection every time?
> 
> From the error message, your code failed to connect to Redis server when it send the first set command, and exit. How can you multiple SYN, SYN +ACK, ACK packets?
> 
> Regards

Yes, this situation is occurring sometimes, I'd seen multiple SYN, SYN + ACK and ACK packets when it was running correctly, sorry for the confusion.  
and yes the redis-cli was also failing to connect, It was very weird to see that I can ping the redis server port and it was open but still client cannot connect.

Is it the same case with standard Redis client too that it also creates multiple connections? can you suggest some alternative where it only creates single connection and exchanges data over that and it should not timeout even in case of a long response delay?

**Comment by sewenew** [comment]
> yes the redis-cli was also failing to connect, It was very weird to see that I can ping the redis server port and it was open but still client cannot connect.

OK, that's beyond the scope of redis-plus-plus, you'd better check the network or Redis server's configurations.

> Is it the same case with standard Redis client too that it also creates multiple connections?

As I mentioned above, in your case, there's only a single connection. However, if the connection is broken, redis-plus-plus will try to reconnect to Redis server automatically. And that's why you see multiple SYN, SYN + ACK and ACK packets.

> can you suggest some alternative where it only creates single connection and exchanges data over that and it should not timeout even in case of a long response delay?

There's no way to guarantee that. Since the connection might be broken for many reasons, e.g. the network might have some problem, and the connection will be closed; Redis server might close idle connections.

Regards

**Comment by ashwani29** [comment]
Thanks for the reply, can you be a little more specific about the server's configurations?

**Comment by sewenew** [comment]
# Close the connection after a client is idle for N seconds (0 to disable)
timeout 0

**Comment by ashwani29** [comment]
Yes, thanks will dig into it further.
