### ISSUE TITLE
Cant compile the app 😞

### ISSUE THREAD

**Issue by dr3adx** [sewenew/redis-plus-plus#142]
I get error: 
```
[100%] Linking CXX executable walter
/bin/ld: CMakeFiles/walter.dir/src/persistence/redis.cpp.o: in function `RedisPers::RedisPers()':
/root/Desktop/tt/new_walter/src/persistence/redis.cpp:34: undefined reference to `sw::redis::Redis::set(std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&, sw::redis::UpdateType)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/walter.dir/build.make:253: walter] Error 1
make[1]: *** [CMakeFiles/Makefile2:575: CMakeFiles/walter.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

I installed redis++ and also hiredis:

```
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libredis++.a
-- Up-to-date: /usr/local/lib/libredis++.so
-- Up-to-date: /usr/local/include/sw/redis++/command.h
-- Up-to-date: /usr/local/include/sw/redis++/command_args.h
-- Up-to-date: /usr/local/include/sw/redis++/command_options
```
I linked it in CMAKE: 
```
add_executable(app ${SOURCES} ${Boost_INCLUDE_DIR} ...)
target_include_directories(app PRIVATE ${Boost_INCLUDE_DIR})


# <------------ add hiredis dependency here --------------->
find_path(HIREDIS_HEADER hiredis)
target_include_directories(app PUBLIC ${HIREDIS_HEADER})

find_library(HIREDIS_LIB hiredis)
target_link_libraries(app PUBLIC ${HIREDIS_LIB})

# <------------ add redis-plus-plus dependency here -------------->
find_path(REDIS_PLUS_PLUS_HEADER sw)      # NOTE: this should be *sw* NOT *redis++*
target_include_directories(app PUBLIC ${REDIS_PLUS_PLUS_HEADER})

find_library(REDIS_PLUS_PLUS_LIB redis++)
target_link_libraries(app PUBLIC ${REDIS_PLUS_PLUS_LIB})

target_link_libraries(app PUBLIC cpprestsdk::cpprest nlohmann_json::nlohmann_json)
```

What the hell am I doing wrong? 😞
I can even include and inspect #include <sw/redis++/redis++.h> and it shows no errors, it even shows function documentation when i hover over sw::redis::Redis::set method, only at compile time it gives that error above **undefined reference to `sw::redis::Redis::set**

**EDIT: After couple of hours of messing around, I found out error is caused because redis-plus-plus was compiled without -DREDIS_PLUS_PLUS_CXX_STANDARD=17 prefix, it defaults to cxx11. Please edit the documentation to clarify this**

**Comment by wingunder** [comment]
Hi @dr3adx,

>EDIT: After couple of hours of messing around, I found out error is caused because redis-plus-plus was compiled without -DREDIS_PLUS_PLUS_CXX_STANDARD=17 prefix, it defaults to cxx11. Please edit the documentation to clarify this

This is in fact documented, starting from line 108 in the top-level README.md:

>From the README.md:
By default, *redis-plus-plus* is built with `-std=c++11` standard. If you want to use the [std::string_view](#stringview) and [std::optional](#optional) features, you can also build *redis-plus-plus* with `-std=c++17` standard by specifying the following cmake flag: `-DREDIS_PLUS_PLUS_CXX_STANDARD=17`.
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/path/to/hiredis -DCMAKE_INSTALL_PREFIX=/path/to/install/redis-plus-plus -DREDIS_PLUS_PLUS_CXX_STANDARD=17 ..
```
From your link error, it hinted that std::basic_string_view was used, which is only around since c++17: 
> undefined reference to `sw::redis::Redis::set(std::basic_string_view<char, ...
 
If the above is not complete enough, could you please suggest what you think should be added to the documentation?
Regards
