### ISSUE TITLE
psubscribe not working

### ISSUE THREAD

**Issue by gnikol** [sewenew/redis-plus-plus#151]
Hi,

I have a simple application:
```auto redis = sw::redis::Redis("tcp://127.0.0.1:6379");
auto subscriber = redis.subscriber();

subscriber.on_meta([](sw::redis::Subscriber::MsgType type, sw::redis::OptionalString channel,
                            long long num) {
	std::cout << "Meta message" << std::endl;
	(void) (type);
    (void) (channel);
    (void) (num);

});

subscriber.on_message([](std::string channel, std::string msg) {
	std::cout << "channel: " <<  channel << " msg: " << msg << std::endl;
});

subscriber.on_pmessage([](std::string pattern, std::string channel, std::string msg) {
      std::cout << "pattern: " << pattern << "channel: " <<  channel << " msg: " << msg << std::endl;
});

std::string pattern = "abc*";
subscriber.psubscribe(pattern);
subscriber.subscribe("channel1");

while (true) {
	try {
        subscriber.consume();
    } catch (const sw::redis::TimeoutError &e) {
    	continue;
    }
}

```

My problem is that while I do see the meta messages as well as the ones that are published with `publish channel1 my_message'` I do not see anything when doing `sadd abc1 def` even though `pubsub numpat` returns 1. Am I doing something wrong?

**Comment by sewenew** [comment]
@gnikol You can publish message to channel *abc1*, e.g. `publish abc1 message`, and your pattern callback will be called. `sadd abc1 def` command won't publish message to any channel, unless you enable keyspace notification. Please check the [doc](https://redis.io/topics/notifications) for detail on how to enable keyspace notification, and what the channel or pattern for the notification is.

Regards

**Comment by gnikol** [comment]
Sorry, I forgot to mention that I have done `config set notify-keyspace-events KEA`. You are correct that `publish abc1 message` works, but I need notifications for set commands for my application. Is there anything more I need to do or something I can check?

**Comment by gnikol** [comment]
Ok, the set notification are prepended with the `__keyspace@0__` (or whatever the appropriate db is) tag so using the pattern `*abc*` works. Thanks for the quick response!
