### ISSUE TITLE
  Compilation error using qtreactor and MinGW

### ISSUE THREAD

**Issue by dearbub** [sewenew/redis-plus-plus#159]
`# hiredis dependency
set(HIREDIS_HEADER "E:/source/redis-plus-plus-compile/tags/1.2.1/hiredis")
set(HIREDIS_LIB "E:/source/redis-plus-plus-compile/tags/1.2.1/hiredis/hiredis/hiredis")

find_path(HIREDIS_HEADER hiredis)
find_library(HIREDIS_LIB hiredis)
`
> Compilation error
mingw32-make.exe[2]: *** No rule to make target 'E:/source/redis-plus-plus-compile/tags/1.2.1/hiredis/hiredis/hiredis', needed by 'libredis++.dll'.  Stop.

> Summary Info
Running D:\CMake\bin\cmake.exe -S E:/source/redis-plus-plus-compile/tags/1.2.1 -B E:/source/redis-plus-plus-compile/tags/build-1.2.1 in E:\source\redis-plus-plus-compile\tags\build-1.2.1.
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The CXX standard is c++11
-- Configuring done
-- Generating done
-- Build files have been written to: E:/source/redis-plus-plus-compile/tags/build-1.2.1
Elapsed time: 00:01.
Running D:\CMake\bin\cmake.exe -S E:/source/redis-plus-plus-compile/tags/1.2.1 -B E:/source/redis-plus-plus-compile/tags/build-1.2.1 in E:\source\redis-plus-plus-compile\tags\build-1.2.1.
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The CXX standard is c++11
-- Configuring done
-- Generating done
-- Build files have been written to: E:/source/redis-plus-plus-compile/tags/build-1.2.1
Elapsed time: 00:01.
Running D:\CMake\bin\cmake.exe -S E:/source/redis-plus-plus-compile/tags/1.2.1 -B E:/source/redis-plus-plus-compile/tags/build-1.2.1 in E:\source\redis-plus-plus-compile\tags\build-1.2.1.
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The CXX standard is c++11
-- Configuring done
-- Generating done
-- Build files have been written to: E:/source/redis-plus-plus-compile/tags/build-1.2.1
Elapsed time: 00:01.

![1](https://user-images.githubusercontent.com/9819222/107114368-3d73fe00-68a0-11eb-9b52-1d95873d688e.png)
![2](https://user-images.githubusercontent.com/9819222/107114372-3fd65800-68a0-11eb-9f73-58274eaa4e98.png)
![3](https://user-images.githubusercontent.com/9819222/107114375-42d14880-68a0-11eb-93c6-3dc6bc8ce8ad.png)

**Comment by sewenew** [comment]
@dearbub It seems that you didn't specify a correct installation path of hiredis header and library. Have you installed hiredis correctly?

Also, if you work on Windows, you can also try to install hiredis and redis-plus-plus with Vcpkg.

Regards

**Comment by dearbub** [comment]
> 
> 
> @dearbub It seems that you didn't specify a correct installation path of hiredis header and library. Have you installed hiredis correctly?
> 
> Also, if you work on Windows, you can also try to install hiredis and redis-plus-plus with Vcpkg.
> 
> Regards

I've tried a few times, HIREDIS_LIB requires an absolute path name and a full file suffix to compile.
`set(HIREDIS_HEADER "PATH/hiredis")`
`set(HIREDIS_LIB "PATH/hiredis/hiredis/libhiredis.a")`
PATH is the hirdis path of my custom copy.Absolute path and . a suffix are indispensable.
Now it's compiled.

**Comment by sewenew** [comment]
Good job!

Regards
