### ISSUE TITLE
How to setup callback subscriber function to read messages ?

### ISSUE THREAD

**Issue by Steeew47** [sewenew/redis-plus-plus#16]
I'm struggle with subscribe feature. I don't know exactly how to set up callback function to (for example) print received messages. The connection settings are correct, because i can easily set value to key.

**Comment by sewenew** [comment]
First of all, you need to create a subscriber object:

```
auto redis = Redis("tcp://127.0.0.1:6379");
auto sub = redis.subscriber();
```

If you want to subscribe to a channel, i.e. [SUBSCRIBE CHANNEL](https://redis.io/commands/subscribe), you can set a callback with the `Subscriber::on_message` interface:

```
sub.on_message([](std::string channel, std::string msg) {
            cout << msg << endl;  // print the message
        });
```

If you want to subscribe to a pattern, i.e. [PSUBSCRIBE PATTERN](https://redis.io/commands/psubscribe), you can set a callback with the `Subscriber::on_pmessage` interface:

```
sub.on_pmessage([](std::string pattern, std::string channel, std::string msg) {
            cout << msg << endl;   // print the message
        });
```

After setting the callbacks, you can consume these messages in a loop:

```
while (true) {
    try {
        sub.consume();
    } catch (const Error &err) {
        // Handle exceptions.
    }
}
```

Also check [the doc](https://github.com/sewenew/redis-plus-plus#examples-1) for other examples.

If you still have problem with this feature, you can show me your code. I'll try to point out your problem of the code.

Regards

**Comment by sewenew** [comment]
The above examples use Lambda as the callback function. If you're not familiar with lambda, you can also set a free function as the callback:

```
void print_message(std::string channel, std::string msg) {
    cout << "received message: " << msg  << " from channel: " << channel << endl;
}

void print_pmessage(std::string pattern, std::string channel, std::string msg) {
    cout << "received message: " << msg << " from channel: " << channel << " of pattern: " << pattern << endl;
}

sub.on_message(print_message);
sub.on_pmessage(print_pmessage);

while (true) {
    try {
        sub.consume();
    } catch (const Error &e) {
        // Handle exception
   }
}
```

**Comment by Steeew47** [comment]
As you guessed i'm not familiar with a Lamba, but your free function as the callback works as intended. I am very grateful for quick response. We can close issue.

**Comment by sewenew** [comment]
I'm glad that the problem is solved. If you have any other problems with redis-plus-plus in the future, always feel free to let me know.

If you like this client, also feel free to star it :)
