### ISSUE TITLE
Make it possible to pass keys and args with iterators to eval function.

### ISSUE THREAD

**Issue by StefanKarlsson321** [sewenew/redis-plus-plus#161]
Hi, I would like to create a PR with an eval function that takes iterators, to see if that is desirable. Is that possible? The current one takes an intializer list, which unnecessarily needs to be created before calling eval.

However, when I try to push a branch to be able to create a PR I get:

```
ERROR: Permission to sewenew/redis-plus-plus.git denied to StefanKarlsson321.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I suppose I would need additional access. The suggested methos has the signature:

```
    template <typename Result, typename Keys, typename Args>
    Result eval(const StringView &script,
                Keys keys_first,
                Keys keys_last,
                Args args_first,
                Args args_last);
```

I have another suggesion as well, to handle timeout in the normal workflow by treating messages that did not result in a reply as stale, but I can specify the details in another issue/PR.

**Comment by sewenew** [comment]
> when I try to push a branch to be able to create a PR I get: ERROR

I put master branch under protection to avoid it being deleted accidentally. It seems that GitHub disallows PR for branches under protection.

Can you create the PR with dev branch? Normally I modify code in dev branch, and merge it to master when the code is fully tested. So that I can ensure the master branch is stable.

> I would like to create a PR with an eval function that takes iterators, to see if that is desirable. Is that possible?

In fact, I considered this overload before. However, It seems that it's not an elegant way when we want to run some scripts that do not have keys or arguments, since we need to pass a pair of iterators for empty ranges. Say, I want to run the following script: `return ARGV[1] + ARGV[2]`, I have to create a temp container to get a pair of key iterators:

```
vector<string> keys;
vector<string> args = {1, 2};
redis.eval<long long>("return ARGV[1] + ARGV[2]", keys.begin(), keys.end(), args.begin(), args.end());
```

Let me know, if you have a better solution. Thanks for your work!

Regards

**Comment by StefanKarlsson321** [comment]
Then I would think adding another overload to cover the case where you lack keys is appropriate. The reason for the change is that you cannot create an std::initializer_list from a std::vector. It is a use case that is not covered, but needed by us at Qlik.

By the way I checked out the dev branch, added my code, and created a new branch eval_range. Then when I try to push I get the read error. Strange, so what you are saying is that I should be able to push a new branch? I have not come the the position to create a PR yet :).

`git push --set-upstream origin eval_range` <-- this one fails

**Comment by wingunder** [comment]
Hi @StefanKarlsson321,
> Strange, so what you are saying is that I should be able to push a new branch?
No, @sewenew said:
> Can you create the PR with dev branch?

The easiest way to share your code, is to first fork the repo, make your changes (on the already existing dev branch) and then submit a pull-request (to the dev branch of this project).
If you want to know how to do this, please refer to the following docs:
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

I hope that this helped.
Regards

**Comment by StefanKarlsson321** [comment]
Thanks! Didn't know that there was a need to fork :). Created PR: https://github.com/sewenew/redis-plus-plus/pull/163.
