### ISSUE TITLE
How to access the database in a callback function?

### ISSUE THREAD

**Issue by rnaves05** [sewenew/redis-plus-plus#164]
Hello everyone,

I have subscribed to pmessage of a given pattern. Now, I would like to access the database inside the callback function that is called when a pmessage is received. Do you know how could I do this? If I understand correctly, the "redis" object cannot be a parameter of my callback function. Do I need to start a new connection to the base every time the callback is called?

Thanks

Raphaël

**Comment by sewenew** [comment]
You can pass the `Redis` object into the callback, e.g. lambda's capture list:

```
auto redis = Redis("tcp://127.0.0.1");
auto sub = redis.subscriber();

// Set callback functions
sub.on_pmessage([&redis](std::string pattern, std::string channel, std::string msg) {
            redis.echo(msg);
        });
```

Regards

**Comment by rnaves05** [comment]
It is exactly what I needed. Thanks a lot. And congratulations for this library, it works very well.

Raphaël
