### ISSUE TITLE
Simple code for Stream does not work

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#169]
Hi, thanks for your help. 
I am having another issue now: the simple code from this web site for Stream does not work, it failed in the first xadd() call:
terminate called after throwing an instance of 'sw::redis::ReplyError'
  what():  WRONGTYPE Operation against a key holding the wrong kind of value
Aborted

Then I changed Attrs to unordered_map,  replaced "*" with another string, still no luck.
Thank you.
---Patrick

**Comment by patrickjchen** [comment]
The Redis server I am using is 5.09, the OS is CENTOS 7

**Comment by sewenew** [comment]
> what(): WRONGTYPE Operation against a key holding the wrong kind of value

The error message shows that the key you tried to call XAAD, is NOT of STREAM type. You should XADD to another key, or remove the key before calling XADD.

Check [this](https://stackoverflow.com/questions/37953019/wrongtype-operation-against-a-key-holding-the-wrong-kind-of-value-php) for reference.

Regards
