### ISSUE TITLE
How to get information about cluster nodes ?

### ISSUE THREAD

**Issue by Steeew47** [sewenew/redis-plus-plus#17]
I'm writing a simple redis client for publish/subscribe massages. I use configured redis cluster with 3 docker-machines where each have in it 2 nodes (master  and slave). It works so far so good. But i have trouble to set starting IP to connect with redis cluster. As You mentioned in documentation you only need to set one master node's host & port, but after one machine failure and reboot masters and slaves have different IP (the slave become master etc.). So after restarting my client i have to set new master IP in connection settings, because it won't connect with a slave IP.

So Is there any option like in hredis-vip to set many IP in connect options ? If not. How am I able to find masters ip  and then setup connection with available master? I tried to read cluster info using command CLUSTER SLOTS, but it didn't work. I followed your instructions about Generic Command Interface, but there always throw an error.

```try{
        RedisCluster cluster2(connection_options[2]);
        //connection_options[2].host = "192.168.99.112";
        //connection_options[2].port = 32768;
        auto r = cluster2.command("cluster","slots");
        assert(r);
        std::vector<OptionalString> result;
        result = reply::parse<std::vector<OptionalString>>(*r);
    }
    catch(const Error &e){
        cout << "Cluster slots error" << endl;

    }
```

Edit 1:
I tried also, but still doesn't work:
```
        std::vector<OptionalString> result;
        auto r = cluster2.command("cluster", "slots");
        assert(r);
        reply::to_array(*r, std::back_inserter(result));
```

Edit 2:
I find commend "ROLE" which would help me. It shows information about node, its role and assigned slots.
```
1) "slave"
2) "192.168.99.113"
3) (integer) 32770
4) "connected"
5) (integer) 33516
```
But i cannot pass Redis::command  with a single parameter.
 `auto r = cluster2.command("ROLE");` doesn't work.

**Comment by sewenew** [comment]
Hi @Steeew47 

> So after restarting my client i have to set new master IP in connection settings, because it won't connect with a slave IP.

In fact, you don't need to restart your client. When the new master and slave comes back, the client will connect to it automatically, no matter whether the ip and port have been changed. However, before the master comes back, when RedisCluster tries to send command to the failed master, it throws exception.

> So Is there any option like in hredis-vip to set many IP in connect options ? I

By now, there's no way to specify multiple IP. I might add this support in the future.

>  I tried to read cluster info using command CLUSTER SLOTS, but it didn't work.

`cluster2.command("cluster", "slots");` this won't work. Because there's no key with this command, so RedisCluster don't know which node it should send the command to. Check [this](https://github.com/sewenew/redis-plus-plus#interfaces) for detail.

You can try the following code:

```
auto r = cluster.redis("any-hash-tag").command("CLUSTER", "SLOTS");
```

The returned reply `r` is of type `std::unique_ptr<redisReply, ReplyDeleter>`. Because the returned reply of "cluster slots" command is too complicated, you have to manually parse it, and cannot simply use the `reply::to_array` to parse it.

Regards

**Comment by sewenew** [comment]
Also, there's another way to send cluster command without keys: you can create a `Redis` object, instead of `RedisCluster` object to send the command.

```
auto redis = Redis("tcp://127.0.0.1:7000");
auto r = redis.command("cluster", "slots");
```

**Comment by Steeew47** [comment]
Thanks for fast response like before :). I tired to simulation situation where one machine is dead and we try connect to redis cluster. We have to set new master ip because the previous one can be slave right now(after cluster reconfiguration) or can be unreachable. I want to do function which can do it for us. I gonna try this command advices for sure. Thank you once again

Ragards

**Comment by sewenew** [comment]
Hi @Steeew47 

I tried to parse the result manually, and you can try the following code. However, it's NOT fully tested.

```
// tuple<ip, port, node-id>
using NodeInfo = tuple<string, long long, string>;

// tuple<slot-begin, slot-end, vector<NodeInfo>>
using SlotInfo = tuple<long long, long long, vector<NodeInfo>>;

SlotInfo parse_element(redisReply &reply) {
        assert(reply.elements >= 3);
        auto slot_begin = reply::parse<long long>(*(reply.element[0]));
        auto slot_end = reply::parse<long long>(*(reply.element[1]));
        vector<NodeInfo> nodes;
        nodes.reserve(reply.elements - 2);
        for (auto idx = 2; idx != reply.elements; ++idx) {
                nodes.push_back(reply::parse<NodeInfo>(*(reply.element[idx])));
        }
        return make_tuple(slot_begin, slot_end, std::move(nodes));
}

int main() {
        RedisCluster cluster("tcp://127.0.0.1:7000");
        auto r = cluster.redis("any-hash-tag").command("CLUSTER", "SLOTS");
        vector<SlotInfo> info;
        info.reserve(r->elements);
        for (auto idx = 0; idx != r->elements; ++idx) {
                auto reply = r->element[idx];
                assert(reply != nullptr);
                info.push_back(parse_element(*reply));

        }
        for (const auto &slot : info) {
                cout << get<0>(slot) << ":" << get<1>(slot) << endl;
                const auto &nodes = get<2>(slot);
                for (const auto &node : nodes) {
                        cout << get<0>(node) << ":" << get<1>(node) << ":" << get<2>(node) << endl;
                }
        }

        return 0;
}
```

Hope this helps :)

Regards

**Comment by Steeew47** [comment]
I'm not able to test this right now, but it looks like what i need. :) I'll let you know tomorrow

**Comment by Steeew47** [comment]
I figured out that in my setup (3 docker-machines with 2 redis nodes on each machine) you don't really need to connect to slave for subscribe channel. It can consume messages easily even if you are connected through slave. But there is some "bug", that doesn't allow to subscribe channel on always one random machine. For example every docker-machine are up, let's name it A, B and C. I can connect through redis-cli with every nodes, i can ping. I can publish some messages and i can also subscribe channel using redis-cli, but i can't do this for one machine e.g A using C++ client and your library. If i restart machine A, it will happen to machine B etc. I connect using Redis Cluster ` RedisCluster cluster("ip");` When i use Redis `auto redis = Redis("<ip>");` it works ok (it can subscribe channel), but i cannot use cluster features.

**Comment by sewenew** [comment]
So you want to subscribe to a channel in a Redis Cluster, and you're wondering whether redis-plus-plus still works well if one of the machine restarts? Correct me if I'm wrong :)

redis-plus-plus can handle the above case by creating a new `Subscriber`:

```
auto cluster = RedisCluster("tcp://127.0.0.1:7000");

while (true) {
    try {
        // Create a new Subscriber by connecting a **RANDOM** master.
        auto sub = cluster.subscriber();

        // Block at here to consume messages.
        subcribe_channel_and_consume_messages(sub);
    } catch (const Error &e) {
        // Something bad happens, e.g. the machine to which the Subscriber connects, restarts.

        // Sleep a while and continue the while loop
        this_thread::sleep_for(chrono::seconds(3));

        // In the next loop, we'll create a new Subscriber by connecting to another **RANDOM** machine.
        continue; 
    }
}
```

The above code always creates a new `Subscriber` by connecting to a **random master**. If machine A restarts, and the old master on it becomes the new slave, and the old slave becomes the new master. `cluster.subscriber()` can always correctly connect to a random master automatically, e.g. it might connect to the master on machine B, and it also might connect to the new master on machine A.

Regards

**Comment by Steeew47** [comment]
It is hard to describe. It is very very strange. In my particular setup there is always one random machine which i cannot consume / subscriber messages using C++ client, but i can still connect with it via redis-cli.

**Comment by Steeew47** [comment]
![export](https://user-images.githubusercontent.com/44441157/62363002-8108e180-b51e-11e9-95b2-b47e55e89125.png)

Everything is working fine, but i cannot connect using C++ client with one machine for example VM1. When i shut it down and restart i cannot connect now with other machine for example VM2. But connecting via redis-cli is working.

**Comment by sewenew** [comment]
Do you mean that you have a `RedisCluster` object running on VM2, and it cannot connect to VM1 once VM1 restart? Also can you show me the complete code?

Another question: after the restart, do NODE 1 and NODE 2 still have the same port number?

Regards

**Comment by Steeew47** [comment]
I'm running code from local machine, out from these virtual machine as i would be a client. After restart nodes have the same ports.

**Comment by sewenew** [comment]
Also, please show me the topology of these masters and slaves, e.g. NODE 2 is a slave of NODE 3.

Say, NODE 2 is NOT the slave of NODE 1, instead NODE 4 is the slave of NODE 1. When VM1 is down, NODE 4 will be promoted as the new master. In that case, `RedisCluster` will NOT connect to NODE 1 and NODE 2 on VM1, since these two nodes are slaves, and, by now, RedisCluster only connects to masters. By contrary, `Redis` can connect to any given node, no mater it's a master or slave. I'm not sure if this is your case.

**Comment by sewenew** [comment]
Although `RedisCluster` doesn't connect to any node in VM1, it can still work well. Because the client only needs to connect to masters to function properly. No matter whether there's a master node on VM1.

**Comment by Steeew47** [comment]
Topology is exactly like at this picture.
![cluster](https://user-images.githubusercontent.com/44441157/62367229-51aba200-b529-11e9-8047-6e227d2836f8.jpg).

**Comment by Steeew47** [comment]
Cluster slots info
ip 172.18.0.1 is 192.168.99.117 because i connect using this ip `redis-cli -h 192.168.99.117`

```1) 1) (integer) 10924
   2) (integer) 16383
   3) 1) "192.168.99.119"
      2) (integer) 6379
      3) "2c481c25618a91002462b197bd0fc9d6b53543bc"
   4) 1) "192.168.99.118"
      2) (integer) 6380
      3) "e4441e4bfc6add22098cd4c1ae0f0483be6e7a6e"
2) 1) (integer) 5462
   2) (integer) 10923
   3) 1) "192.168.99.118"
      2) (integer) 6379
      3) "edf81c011ba9110080fbe937bef958d960d44696"
   4) 1) "172.18.0.1"
      2) (integer) 6380
      3) "09893e4b388b23664847d5470eadfa823d10489a"
3) 1) (integer) 0
   2) (integer) 5461
   3) 1) "172.18.0.1"
      2) (integer) 6379
      3) "f92d7472e3d66d7e2ccd7784b04cf9e53521b523"
   4) 1) "192.168.99.119"
      2) (integer) 6380
      3) "379597403fc4adfb8dbd78903af4ab13e2c1857a"
```

**Comment by Steeew47** [comment]
This my code, I can choose which ip i would like to connect.

```

#include <sw/redis++/redis++.h>
#include <iostream>
#include <chrono>
#include <string>
#include <vector>

#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <iterator>


using namespace sw::redis;
using namespace std;
using namespace std::chrono;

// tuple<ip, port, node-id>
using NodeInfo = tuple<string, long long, string>;

// tuple<slot-begin, slot-end, vector<NodeInfo>>
using SlotInfo = tuple<long long, long long, vector<NodeInfo>>;

//
using MasterInfo = tuple<string, long long>;
vector<MasterInfo> master;

string channel = "test";
int m_receive = 0;
bool initialize = false;
int start = 0;
bool isMaster;
ConnectionOptions connection_options[6];
ConnectionPoolOptions pool_options;




// Parse reply messange form CLUSTER INFO command, and put into a STL container
SlotInfo parse_element(redisReply &reply) {
        assert(reply.elements >= 3);
        auto slot_begin = reply::parse<long long>(*(reply.element[0]));
        auto slot_end = reply::parse<long long>(*(reply.element[1]));
        vector<NodeInfo> nodes;
        nodes.reserve(reply.elements - 2);
        for (auto idx = 2; idx != reply.elements; ++idx) {
            nodes.push_back(reply::parse<NodeInfo>(*(reply.element[idx])));
        }
        return make_tuple(slot_begin, slot_end, std::move(nodes));
}

// Get milliseconds
uint64_t getMs() {
    using namespace std::chrono;
    return duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
}

// Callback for received massages from subscribed channel
void print_message(std::string channel, std::string msg){
    cout << "received message " << m_receive <<" from channel: " << channel;
    long now = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
    long t_start = atol(msg.c_str());
    cout <<" # Latency: "<< now - t_start << " [ms]" << endl;
}

void connection_init(){

    connection_options[0].host = "192.168.99.117";
    connection_options[0].port = 6379; 

    connection_options[1].host = "192.168.99.117";
    connection_options[1].port = 6380;

    connection_options[2].host = "192.168.99.118";
    connection_options[2].port = 6379;

    connection_options[3].host = "192.168.99.118";
    connection_options[3].port = 6380;

    connection_options[4].host = "192.168.99.119";
    connection_options[4].port = 6379;

    connection_options[5].host = "192.168.99.119";
    connection_options[5].port = 6380;

    
}

vector<MasterInfo> connection_check(ConnectionOptions connection){
    try{
        Redis cluster(connection, pool_options);
        //connection_options[2].host = "192.168.99.112";
        //connection_options[2].port = 32768;

        auto r = cluster.command("CLUSTER", "SLOTS");
        vector<SlotInfo> info;
        

        info.reserve(r->elements);

        for (auto idx = 0; idx != r->elements; ++idx) {
            auto reply = r->element[idx];
            assert(reply != nullptr);
            info.push_back(parse_element(*reply));
        }

        for (const auto &slot : info) {
            const auto &nodes = get<2>(slot);
            for (const auto &node : nodes) {
                
                master.push_back(make_tuple(get<0>(node),get<1>(node)));
            }
            
        }
        //get<id>(master[master number])
        // id = 0 - ip
        // id = 1 - port
        
        for(int idx = 0; idx <= master.size() - 1; idx = idx+2){

            if(connection.host == get<0>(master[idx]) && connection.port == get<1>(master[idx])){
                cout << endl << "Connected to master" << endl;
                cout << "----------------------------------";
                isMaster = true;
                //break;                
            }else{
                isMaster = false;
                cout << endl << "Available master" << endl;
                cout << "----------------------------------";                
            }
            cout << endl;
            cout << "host : " <<get<0>(master[idx]) << endl;
            cout << "port : " <<get<1>(master[idx]) << endl;     
        }

        for(int idx = 1; idx <= master.size() - 1; idx = idx+2){

            if(connection.host == get<0>(master[idx]) && connection.port == get<1>(master[idx])){
                cout << endl << "Connected to slave" << endl;
                cout << "----------------------------------";      
            }else{
                isMaster = false;
                cout << endl << "Available slave" << endl;
                cout << "----------------------------------";                
            }
            cout << endl;
            cout << "host : " <<get<0>(master[idx]) << endl;
            cout << "port : " <<get<1>(master[idx]) << endl;     
        }
        return master;
    }
    catch(const Error &e){
        cout << "Trying to get cluster info : failed" << endl;
    }
}

int main(){
    // Set array of possible connection IPs
    
    pool_options.size = 5;
    connection_init();
    connection_check(connection_options[3]);
    cout << endl;


    try{
        int choise;
        cout << "Set connection options : ";
        cin >> choise;
        RedisCluster cluster(connection_options[choise]);
        // TODO:
        auto sub = cluster.subscriber();
        //
        sub.on_message(print_message);
        sub.subscribe("test");

        while (true) {
            try {
                if(!initialize){
                    start = getMs();
                    initialize = true;
                }
                sub.consume();
                m_receive++;

            } catch (const Error &err) {
                cout << "Message consume error";
            }
        }

    }
    catch(const Error &e){
        cout << "Connection lost";
    }
     
    
}
```

**Comment by Steeew47** [comment]
When i choose option 0 or 1 i cannot connect to redis cluster.
```
    connection_options[0].host = "192.168.99.117";
    connection_options[0].port = 6379; 

    connection_options[1].host = "192.168.99.117";
    connection_options[1].port = 6380;
```

**Comment by sewenew** [comment]
Hi @Steeew47 

I tried your code, and cannot reproduce the problem. `RedisCluster` can connect to any of these 6 node.

In your case, when you choose option 0 or 1, does redis-plus-plus throw any error? can you show me the error message?

When you catch the exception, use the following code to print the error message:

```
try {
} catch (const Error &err) {
    cout << err.what() << endl;
}
```

There're 3 `catch` clause in your code,  you can print the error message for all these 3 caught exceptions.

Regards

**Comment by Steeew47** [comment]
I'm so sorry, I've already left home. I'm going to hometown so won't be able to tell you. Don't bother. Have a nice weekend :)

**Comment by sewenew** [comment]
When you back to work, please also show me the "CLUSTER NODES" info.

Have a nice weekend :)
