### ISSUE TITLE
Unrecoverable error from Redis pipeline with connection reuse

### ISSUE THREAD

**Issue by maxmcl** [sewenew/redis-plus-plus#172]
If the Redis instance becomes unreachable after the Redis object was created and before a `Pipeline` object is called, the pipeline will throw and crash the whole program.

Minimal example to reproduce the problem:
```cpp
// main.cpp
#include <iostream>
#include <thread>

#include "sw/redis++/redis++.h"

namespace redis = sw::redis;

int main() {
  try {
    redis::ConnectionOptions connOpts;
    connOpts.host = "127.0.0.1";
    auto redis = redis::Redis(connOpts);
    // Create a connection ahead of time
    redis.ping();
   
   // Stop the Redis service here
    std::cout << "Connected to Redis instance, kill it now" << std::endl;
    std::this_thread::sleep_for(std::chrono::seconds(5));
    
    auto pipe = redis.pipeline(false);
    // This next line will crash
    auto pipe_replies = pipe.set("key", "value").exec();
    
  } catch (const std::exception &e) {
    // Never even gets here
    std::cout << "Some error happened: " << e.what() << std::endl;
  };
}
```

Here's the output of the program:

```
Connected to Redis instance, kill it now
terminate called after throwing an instance of 'sw::redis::IoError'
  what():  Failed to connect to Redis: Connection refused
[1]    287818 abort (core dumped)  ./main
```

It appears the problem has to do with [this](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/queued_redis.hpp#L203).

Commenting out the `_clean_up()` call in `_invalidate()` yields the expected behavior. What would be the proper way to *close* and not *reconnect* the connection?

**Comment by sewenew** [comment]
@maxmcl Sorry, but that's a bug. It incorrectly throws an exception in destructor. I've fixed it. Please try the latest code on master branch.

Sorry again for the inconvenience, and thanks a lot for finding this bug!

Regards

**Comment by maxmcl** [comment]
I'll give it a try soon, but I looked at the change and it makes sense! Thanks for fixing it so quickly
