### ISSUE TITLE
Problem with dynamically add a stream to read

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#177]
Hi, I am using the following code to read data from streams:
 redis.xread(streams.begin(), streams.end(), 1, std::inserter(result, result.end()));
However, I need to add new keys to streams dynamically. Seems it does not work sometimes.
Any idea?

Thanks a lot
---Patrick

**Comment by sewenew** [comment]
What do you mean by *add new keys to streams dynamically*? If I understand correctly, you should use `XADD` to create a new stream. And if you want to read this new stream, you should add it to the `streams` contains, and call `XREAD` again.

**Comment by patrickjchen** [comment]
Thanks. There are some issues with synchronization and it's fixed now.
