### ISSUE TITLE
Cluster Moved not working

### ISSUE THREAD

**Issue by Flavio80** [sewenew/redis-plus-plus#18]
Hello,
i'm trying to use the ClusterRedis class, but it seems not to follow the redirect when needed.

For example I tried an rpush or an expire, but I get a ReplyError, in which the what() says: 8442 10.10.24.66:7002

I also tried to use a transaction, sending the commands in different parts of code, like this:
`
try{
auto tx = cluster.transaction("key"); 
insertPoints("key", tx);
auto replies = tx.exec();
}catch (ReplyError& rep) { cout << rep.what() << endl; }

//////////insertPoints def/////////////////
void insertPoints(string k, Transaction& tx){
tx.rpush(k, value); 
tx.expire(k, seconds); 
}

`

**Comment by sewenew** [comment]
> i'm trying to use the ClusterRedis class, but it seems not to follow the redirect when needed.

Do you mean `RedisCluster` object? Can you show me the code that you create `RedisCluster`?

> For example I tried an rpush or an expire, but I get a ReplyError, in which the what() says: 8442 10.10.24.66:7002

With `RedisCluster` object, I cannot reproduce the problem. However, if you're using a `Redis` object, you'll get this error. Can you show me the complete code?

The following is my testing code:

```
RedisCluster cluster("tcp://127.0.0.1:7000");
try {
    cluster.rpush("key", "val");
    cluster.expire("key", 100);
} catch (const Error &e) {
    cerr << e.what() << endl;
}
```

> I also tried to use a transaction, sending the commands in different parts of code

When you use transaction, if the slot-node mapping is changed between you create the transaction and calls its `exec` method, you'll get the moved error. In other cases, redis-plus-plus will redirect the request automatically.

```
RedisCluster cluster("tcp://127.0.0.1:7000");
// If the slot-node mapping is changed at this moment, you will **NOT** get a MOVED error.
auto tx = cluster.transaction("key");
// If the slot-node mapping is changed at this moment, you'll get a MOVED error.
tx.rpush("key", "val");
// If the slot-node mapping is changed at this moment, you'll get a MOVED error.
tx.expire("key", 100);
// If the slot-node mapping is changed at this moment, you'll get a MOVED error.
auto replies = tx.exec();
```

In this case, you just need to retry the execution of transaction:

```
// Try 3 times
const TRIES = 3;
for (auto idx = 0; idx != 3; ++idx) {
    try {
        auto tx = cluster.transaction("key");
        tx.rpush("key", "val");
        tx.expire("key", 100);
        auto replies = tx.exec();
        // process the replies here ...
       return;
    } catch (const MovedError &e) {
        // retry latter
    } catch (const AskError &e) {
       // retry latter
   }
   this_thread::sleep_for(chrono::seconds(3));
}
```

Hope this helps :)

Regards

**Comment by Flavio80** [comment]
Hi,
thanks for the quick reply.
Yes it was RedisCluster, not ClusterRedis :-)
I noticed the error only with Transaction with  the exact problem you wrote and I thought it was an error in the cluster library. In this first use case I'm not using transactions, but now I'll be more careful. 

Does the cluster.get("key") in the library will get all keys, even if they are spanned between nodes?

**Comment by sewenew** [comment]
> Does the cluster.get("key") in the library will get all keys, even if they are spanned between nodes?

Sorry, but I don't quite understand the question. `cluster.get("key")` only get a single key from Redis. What do you mean ***get all keys***?

redis-plus-plus guarantees that `cluster.get("key")` will return the value, even if the corresponding slot is being migrated to other node.

**Comment by Flavio80** [comment]
Sorry, 
I expressed the question in a bad way. 
You answered my real question with this:

> redis-plus-plus guarantees that cluster.get("key") will return the value, even if the corresponding slot is being migrated to other node.

Thanks a lot.

**Comment by sewenew** [comment]
If you have any other problem with redis-plus-plus in the future, feel free to let me know. If you like it, also feel free to star it :)
