### ISSUE TITLE
"$" does not work in xread?

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#180]
Somehow with "$" specified as the last ID,  xread was not able to read  the new messages written to a stream. Then I changed it to "0-0", now it works.  Not sure if it's Redis or redis-plus-plus.

Thanks
Patrick

**Comment by sewenew** [comment]
redis-plus-plus can handle it correctly. However, '$' is a special id, you can read new message only if there's new message in the stream AFTER you called xread. Check the [doc](https://redis.io/commands/xread#the-special-codecode-id) for detail.

**Comment by sewenew** [comment]
@patrickjchen Since this issue doesn't have any new progress, I'll close it. If you still have problem on it, feel free to reopen it.
