### ISSUE TITLE
[Question] Pipeline in RedisCluster must specify hash_tag?

### ISSUE THREAD

**Issue by Cactusinhand** [sewenew/redis-plus-plus#184]
HI @sewenew 
As title described, does pipeline in RedisCluster must specify hash_tag? When RedisCluster instance created, it already connected to master node with a single connection, then pipeline can easily query data from the connected node. So I don't see why we have to specify a hash_tag.

Thanks!

**Comment by sewenew** [comment]
Yes, you must specify a hash_tag. Because with pipeline, we need to ensure that all keys related to this pipeline must be located in one slot. So when creating pipeline, we use hash_tag to pick the connection to that slot.

Regards

**Comment by Cactusinhand** [comment]
Ok, I understand now.

Thanks
