### ISSUE TITLE
[Question] How to operate Redis cluster pool?

### ISSUE THREAD

**Issue by Cactusinhand** [sewenew/redis-plus-plus#189]
Hi @sewenew
Redis-plus-plus support connection pool feature, and there are some examples in README about how to create a connection pool, but after that, how to operate pool?(especially under Cluster mode)

Thanks!

**Comment by sewenew** [comment]
What do you mean by *operate pool*?

If you create a Redis or RedisCluster object with connection pool options, Redis and RedisCluster will create a connection pool, and fetch connections from the pool automatically. You don't need to fetch connection from the pool manually.

**Comment by Cactusinhand** [comment]
I mean can I directly fetch a one from the pools, and return it to the pools after using it?
I want to maintain a connection pool manually, and I see some methods in there, like `fetch()`, `release()`, `clone()`, so I wander if I can use them directly, and how to use them.

**Comment by sewenew** [comment]
NO, those methods are internally used. You should never use them. Because they might be removed or changed in the future. 

There was a plan to support an interface so that end user can customize the behavior of connection pool. However, that might make lots of changes to code, and a redesign of the connection pool. If there's any progress on it, I'll let you know.

**Comment by Cactusinhand** [comment]
Ok, they are only called inside.
Now if I create a Redis object with connection pool, the pool size is 3, which means there will be 3 connections in it, then how I use one of them?

**Comment by sewenew** [comment]
You don't need to worry about the details, `Redis` will automatically fetch one connection from the pool, when it needs to send command to Redis, and release it back to the pool when it receives the reply. Also if the connection is broken, `Redis` will automatically reconnect it.

In a word, you don't need to know *operate* the connection pool. Everything on the connection pool is implementation details, your application code don't need to operate on the pool.

> According to your comment above, Redis++ can automatically maintain them, am I right?

YES

**Comment by Cactusinhand** [comment]
Closing.
Thanks for your replies.
