### ISSUE TITLE
An xread takes 200 milliseconds?

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#191]
Hi,  I am having problem with the performance of the API:
 Seems even though I specify 1 millisecond for reading,  actually 200 milliseconds was spent here.
Can you help?
Thanks
Patric

using Attrs = std::unordered_map<std::string, std::string>;
using Item = std::pair<std::string, Attrs>;
using ItemStream = std::vector<Item>;
std::unordered_map<std::string, ItemStream> result;
 _redis->xread(_streams.begin(), _streams.end(), std::chrono::milliseconds(1),10, std::inserter(result, result.end()));

**Comment by patrickjchen** [comment]
P.S
I set keep_alive=true

**Comment by sewenew** [comment]
The timeout, i.e. `std::chrono::milliseconds(1)`, you set for the `XREAD` command, is not the timeout of the command. Instead it the timeout for blocking if there's no item in the stream. Check the [doc](https://redis.io/commands/xread) for detail.

You'd better check if your network to redis server suffer from high latency, e.g. ping your Redis server to check the RTT, it might be slow.

**Comment by patrickjchen** [comment]
So the document says the delay is 0.1 seconds or 100 milliseconds,  am I right here? Thanks

**Comment by patrickjchen** [comment]
Will pub/sub interface do much better regarding performance?
Thanks

**Comment by sewenew** [comment]
> So the document says the delay is 0.1 seconds or 100 milliseconds, am I right here? 

It has nothing to do with the delay (If you mean the network latency). According to the doc, most system's time resolution is 0.1 seconds, which means you cannot achieve blocking timeout less than 0.1 seconds. It has nothing to do with network latency.

> Will pub/sub interface do much better regarding performance?

In fact, redis-plus-plus is just a wrapper on hiredis, and it should be very fast. Sorry but I don't have much to do for the optimization. You'd better check if the network is fast or Redis server is heavy loaded.

Regards

**Comment by sewenew** [comment]
@patrickjchen Since this issue doesn't have any new progress, I'll close it. If you still have problem on it, feel free to reopen it.
