### ISSUE TITLE
How to keepalive

### ISSUE THREAD

**Issue by BeyondWUXF** [sewenew/redis-plus-plus#195]
How do I keep a connection in the pool pinging with a service.
Thanks.

**Comment by sewenew** [comment]
In order to enable keepalive, you can set the `ConnectionOptions::keep_alive` to be true.

**Comment by BeyondWUXF** [comment]
This parameter appears to be the TCP layer guarantee in Hiredis。Some servers will close the connection if no command is sent。

**Comment by sewenew** [comment]
In that can, you have to implement this kind of `keep alive` in your application code. So far there's no way to do that with redis-plus-plus.

By the way, if your connection has been idle for a long time, it might not be a bad idea to close it.

**Comment by BeyondWUXF** [comment]
I see. Thank you.

**Comment by BeyondWUXF** [comment]
Thank you for replay.

**Comment by wingunder** [comment]
Hi
Sorry for butting in on this closed issue.

@sewenew: There definitely are use-cases for this. I have apps that subscribe to (slow human-driven) keys, and it can be up to days for some of them to publish. In this case I call `redisEnableKeepAlive(context)` (from hiredis), before subscribing, and this works. I have not tried using `ConnectionOptions::keep_alive`, but I guess it comes to the same.

@BeyondWUXF: Are you sure that there's not a firewall or something that's chopping your idling connections?

Regards

**Comment by BeyondWUXF** [comment]
@wingunder My service is using the Redis product of the cloud vendor. It should be that the cloud vendor handles idle connections.
