### ISSUE TITLE
Redis cluster reconnection problem

### ISSUE THREAD

**Issue by arasatalar** [sewenew/redis-plus-plus#197]
Hi, 

We have a minor problem when we deploy redis cluster in Kubernetes
environment. In tests, we kill multiple shard masters simultaneously
(or maybe all) and then the client loses connection and fails to reconnect. 
We then need to re-instantiate the cluster client (sw::redis::Cluster) using domain 
name, to restore the connection.

In kubernets env, the domain name (given in "_connection_opts") can be translated
into ip address of the newly elected cluster master (after previous one(s) are killed). 
In this case, we expect an auto reconnect by the existing client instead of reconnecting
by instantiating a new sw::redis::RedisCluster.

I propose a change (in shard_pool.cpp) just to explain myself better to start a
discussion. Thanks.

 void ShardsPool::update() {
     // My might send command to a removed node.
\-    // Try at most 3 times.
\-    for (auto idx = 0; idx < 3; ++idx) {
\+    // Try at most 3 times + 1
\+    for (auto idx = 0; idx < 4; ++idx) {
         try {
\-            // Randomly pick a connection.
\-            auto pool = fetch();
\-            assert(pool);
\-            SafeConnection safe_connection(*pool);
\-            auto shards = _cluster_slots(safe_connection.connection());
\+           if (idx < 3) {
\+               // Randomly pick a connection.
\+               auto pool = fetch();
\+               assert(pool);
\+               SafeConnection safe_connection(*pool);
\+               auto shards = _cluster_slots(safe_connection.connection());
\+           } else {
\+               Connection connection(_connection_opts);
\+               auto shards = _cluster_slots(connection);
\+           }

**Comment by sewenew** [comment]
This looks good to me. Feel free to create a PR :)

Regards

**Comment by sewenew** [comment]
@arasatalar Since the code has been merged into master branch, I'll close this issue. If you still have any problem on it, feel free to reopen it.
