### ISSUE TITLE
Store an OpenCV JPEG image to a Redis stream

### ISSUE THREAD

**Issue by RobinLanglois** [sewenew/redis-plus-plus#200]
Hello,
I would like to store an image on my Redis database, which is a result of a cv::imencode with .jpg extension. I saw this StackOverflow post https://stackoverflow.com/questions/42800878/storing-vector-of-chars-in-redis-containing-nul but it does not use a stream, and it's not redis-plus-plus but Hiredis. I didn't manage to do this, according to your piece of code in the Readme about Redis streams. Here is how it looks like :   
```c++
using Attrs = std::unordered_map<std::string, X>;    // what does X should be here ?
/* ... */

void pushImage(string id, vector<uchar>& imageBuffer) {     // imageBuffer is what I got from imencode
    Attrs attrs = { {id, Y}};
    auto id = mRedisServer->xadd(id, "*", attrs.begin(), attrs.end());
}
```

For Y, firstly I tried to put just imageBuffer or imageBuffer.data(), and I'm getting errors like `error: no match for ‘operator<<’ (operand types are ‘sw::redis::CmdArgs’ and ‘std::vector<unsigned char>*’)  :  *this << first->first << first->second; `

Can you help me please ? Thank you in advance, and for your work for this library.

**Comment by sewenew** [comment]
If I understand correctly, you want to push your image into a stream, and for each image you have an id to identify it.

In order to achieve this, you need to convert your `vector<uchar>` to `StringView`,  since redis-plus-puls doesn't support vector<uchar>. You can try the following code (NOTE: the code has not been tested):

```
using Attrs = std::unordered_map<std::string, StringView>;

void pushImage(string id, vector<uchar>& imageBuffer) {     // imageBuffer is what I got from imencode
    auto buf = StringView(reinterpret_cast<const char*>(imageBuffer.data()), imageBuffer.size());
    Attrs attrs = { {id, buf}};
    auto stream_id = mRedisServer->xadd("your-stream-name", "*", attrs.begin(), attrs.end());
}
```

**Comment by RobinLanglois** [comment]
Thank you for answering so quickly ! I'll try this next week.  I kind of confused myself with my IDs while reducing my code to something minimal, but basically you seemed to understand my issue.

**Comment by RobinLanglois** [comment]
It works, thank you ! I'm closing this ;)
