### ISSUE TITLE
Error during linking when using c++14

### ISSUE THREAD

**Issue by VaibhawChandrakar** [sewenew/redis-plus-plus#201]
I followed all steps mentioned at
https://github.com/sewenew/redis-plus-plus#installation

Used -DREDIS_PLUS_PLUS_CXX_STANDARD=**14**

Trying to use the following code in an existing project which uses **-std=c++14** during compilation.

_#include <sw/redis++/redis++.h>
auto re = sw::redis::Redis("tcp://127.0.0.1:6379");
  try{
    re.set("key", "value");
    auto val = re.get("key");
  }
  catch (const sw::redis::Error &err) {
    cout << "here error" << err.what() );
    // error handling
  }_

I keep getting the following error during compilation

_undefined reference to `sw::redis::Redis::Redis(std::string const&)'
undefined reference to `sw::redis::Redis::get(sw::redis::StringView const&)'_

If you notice no undefined reference error came for "set" call, which means there is no error in giving proper library paths during linking.
I even confirmed the library paths are given correctly during linking. (If I remove the library paths, I get undefined reference even for "set" call)

What am I doing incorrect ?

**Comment by sewenew** [comment]
Sorry, but I cannot reproduce your problem. I think you fail to specify static library or fail to specify the linking path, i.e. *-L/path/to/your/installed/lib*, if you compiled it with dynamic library.

Say if you installed hiredis and redis-plus-plus at */home/user/install*,  the header should be located at */home/user/install/include*, and the lib should be located at */home/user/install/lib*. In this case, you should compile your app like this: `g++ -std=c++14 -I/home/user/install/include -o app app.cpp /home/user/install/lib/libhiredis.a /home/user/install/lib/libredis++.a` (use static lib) or `g++ -std=c++14 -I/home/user/install/include -L/home/user/install/lib -o app app.cpp -lhiredis -lredis++` (use dynamic lib).

Regards

**Comment by VaibhawChandrakar** [comment]
I am able to compile and run a standalone code with c++14 compiled redis-plus-plus. But the problem is coming when I am trying to use it in an existing project which has its own Sconstruct. I have cross verified many times the path to library is correct. (checked by running compilation in it's verbose mode). I have even tried using both shared and static library of redis-plus-plus but getting the same error.
I am able to create shared library of the module which is using these redis++ code snippet (which means include path is correct).
Also when I remove static lib path from my project compilation, I get more errors for all the redis++ lib calls, so I guess the lib paths are fine as well

I am guessing the problem is coming due to mismatch in  some compilation config of redis-plus-plus and my project, but not able to find the root cause.
Just want to confirm one thing, do we need to use something extra while compiling hiredis for -std=c++14, like we do for redis++ ?

**Comment by VaibhawChandrakar** [comment]
I figured out the problem. The issue came due to usage of -D_GLIBCXX_USE_CXX11_ABI=0 in projects compilation. Is there any option in cmake to give this option the way we gave for -std=c++14 ?
For Now I modified the 
build/CMakeFiles/redis++_static.dir/flags.make file to include -D_GLIBCXX_USE_CXX11_ABI=0 in CXX_FLAGS.
and built libredis++.a and used that for my existing project.

No linking error came. Though yet to test all the functionality of redis++ after that.

**Comment by sewenew** [comment]
I'm glad to hear that you find the root cause!

You can try the following command to specify _GLIBCXX_USE_CXX11_ABI option when running cmake:

```
cmake -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" ..

make

make install
```

Regards

**Comment by VaibhawChandrakar** [comment]
Great it worked. Thanks
