### ISSUE TITLE
Should we add -std=c++14 to the documentation as well?

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#203]
Hi @sewenew 

I still have several systems with Ubuntu 16.04 installed. These only have gcc with the version:
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```
I can confirm that redis-plus-plus version 1.2.3 works perfectly well with it. However, the documentations seems to only mention the `c++11` and `c++17` standard.  May I make a patch for the top-level README.md, so that it includes `c++14`, or is there a good reason why you only documented `c++11` and `c++17`?

Regards

**Comment by sewenew** [comment]
Yes, it works with C++14 too. Feel free to make the patch, and thanks for your work!
Regards

**Comment by wingunder** [comment]
Linking this issue to PR #207.

**Comment by sewenew** [comment]
@wingunder Thanks for your work! Those two PRs have been merged.

Regards

**Comment by wingunder** [comment]
@sewenew Thanks for merging :)
Closing this issue.
Regards
