### ISSUE TITLE
How to write binary data into Redis++

### ISSUE THREAD

**Issue by fang-da-mao** [sewenew/redis-plus-plus#208]
Hi @sewenew 

I have an array like char str[] = "wjefpo\0lwe\^w\st". When inserting to the Redis, it will replace " \0" with \u0000, and skip the '\' for '\^' and '\s'. 

But there could be anything in binary data right? Could anyone please tell me how can I solve this problem?

Tried to use StringView(str, size), does not work. I am compiling with c++11.

Any help is appreciated, thanks.

**Comment by wingunder** [comment]
Hi @fang-da-mao 

Try this:
``` c++
#include <iostream>
#include <sw/redis++/redis++.h>

// bin2hex adapted from: https://gist.github.com/waveacme/d0b5e8803675be3f10596cb4124b0d88
template <typename T>
std::string bin2hex(const T& input)
{
        std::string res;
        const char hex[] = "0123456789ABCDEF";
        for(auto sc : input) {
                unsigned char c = static_cast<unsigned char>(sc);
                res += hex[c >> 4];
                res += hex[c & 0xf];
                res += " ";
        }
        return res;
}

int main()
{
        sw::redis::ConnectionOptions connOpts;
        connOpts.host = "127.0.0.1";
        connOpts.port = 6379;
        sw::redis::Redis redisInstance(connOpts);

        const char str[] = "wjefpo\0lwe^w\\st";

        std::string strData(str, sizeof(str)-1); // -1, to get rid of the terminating 0.
        std::cout << "in:  " << strData << std::endl;
        std::cout << "in:  " << bin2hex<std::string>(strData) << std::endl;

        const std::string key = "test";
        redisInstance.set(key, strData);
        auto val = redisInstance.get(key);
        if (val) {
                std::cout << "out: " << *val << std::endl;
                std::cout << "out: " << bin2hex<std::string>(*val) << std::endl;
        }
        return 0;
}
```
Output:
```
in:  wjefpolwe^w\st
in:  77 6A 65 66 70 6F 00 6C 77 65 5E 77 5C 73 74
out: wjefpolwe^w\st
out: 77 6A 65 66 70 6F 00 6C 77 65 5E 77 5C 73 74
```
BTW, you were missing a `\` before `\s`.
I hope this helped.
Regards

**Comment by fang-da-mao** [comment]
Hi @wingunder , @sewenew

Thanks for your help! 

What if I want to load the whole binary data array uint8_t rtest[] with content "redis\0test\sfortest\^" . 
After set ("test", rtest) to Redis, when I get("test"), it will show "redis\0test\sfortest\^".

Here is the case, I can't skip '\0' or put one more '\' before '\s' , I need to put the original data in, and get the original data out. Do you think it is possible or is there any possible solution for this?

Thanks

**Comment by sewenew** [comment]
@fang-da-mao redis-plus-plus does not do string escape, and is binary safe. You can simply convert your uint8_t array to a `StringView` object, and pass it to the `Redis::set` method:

```
uint8_t *your_data;
size_t your_data_len;

// set binary data
redis.set("key", StringView(reinterpret_cast<const char *>(your_data), your_data_len));

// get the binary data back
auto val = redis.get("key");
if (val) {
      // copy it to a uint8_t array.
      uint8_t *buf = new uint8_t[val->size()];
      memcpy(buf, val->data(), val->size());        // `buf` should contain the exact data as `your_data`
}
```

Regards

**Comment by fang-da-mao** [comment]
Hi @sewenew ,

Thank you very much! 

Actually I tried to get the binary value back by get("key").value(), cause I notice the return type is OptionalString. Can I use .value()? or copy the val into a new uint8_t array is a safe choice?

Thanks :)

**Comment by sewenew** [comment]
@fang-da-mao It depends on your application code, whether you need to copy or cast it into a uint8_t array. If you want to pass the result to a function that accepts string as parameter, you can pass the dereferenced string result to it. If you want to pass it a function which accepts `uint8_t *` and a length as parameter, you can reinterpret cast the dereferenced string's `data()` pointer to `uint8_t*`.

Regards

**Comment by sewenew** [comment]
@fang-da-mao I'll close this issue. If you still have any problem on it, feel free to reopen it.
