### ISSUE TITLE
Add single key overload method for some command

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#21]
Some commands have single key format, e.g. `BITOP operation destkey key`. However, by now, we only have multiple-key overloads for these commands, and we need to add support for these commands.

**Comment by iamAzeem** [comment]
@sewenew 

Isn't it already resolved by this [commit](https://github.com/sewenew/redis-plus-plus/commit/1caa0603f5ace54c88fa61e98a28cfbe7c403c15)?

**Comment by sewenew** [comment]
Hi @iamAzeem 

NO. There're still a few commands are lack of single key overload, such as `GEOHASH`. I'll close this issue, when I'm done with those commands. Thanks anyway :)

Regards
