### ISSUE TITLE
problems about sending cluster orders

### ISSUE THREAD

**Issue by wuxuecheng** [sewenew/redis-plus-plus#210]
Hi all
I got some problems when I tried to send some cluster orders to redis, like this:

> auto cluster = new RedisCluster(connection_opts, pool_opts, role);

> auto r = cluster->redis("hash_tag", true);

> auto reply = r.command("CLUSTER SLOTS");

Then, I got the error: "ERR unknown command 'CLUSTER SLOTS'" from redis.
If I send this order using 'cluser' like this:

> auto reply = cluster->command("CLUSTER SLOTS", "hash_tag");

I got the same error from redis
the only way to get correct reply, I have to use Connection to send this order:

> auto conx = sw::redis::Connection(connection_opts);

> connection.send("CLUSTER SLOTS");

> auto reply = connection.recv();

at the same time, its weird if I write the code like this:

> auto conx = sw::redis::Connection(connection_opts);

> CmdArgs args;

> args << "CLUSTER SLOTS";

> connection.send(args);

> auto reply = connection.recv();

I got this error again!

Is there anyone who met the same problem like this? or what should I do if I want to send 'CLUSTER SLOTS' using Redis or RedisCluster?

**Comment by sewenew** [comment]
The name of some Redis commands is composed with two strings, e.g. CLIENT SETNAME. In this case, you need to pass these two strings as two arguments for Redis::command.

auto cluster = new RedisCluster(connection_opts, pool_opts, role);
auto r = cluster->redis("hash_tag", true);
auto reply = r.command("CLUSTER”, “SLOTS");

Also [this](https://github.com/sewenew/redis-plus-plus/issues/17) might help.

**Comment by wuxuecheng** [comment]
get it,thx
