### ISSUE TITLE
Build issue: fatal error: 'tls.h' file not found

### ISSUE THREAD

**Issue by ketoo** [sewenew/redis-plus-plus#213]
Hi Sewenew,

I follow the guide and use redis plus plus in my project but meet this issue:

dep/redis-plus-plus/src/sw/redis++/connection.h:31:10: fatal error: 'tls.h' file not found
#include "tls.h"

The steps I have did:

1) 
git clone https://github.com/redis/hiredis.git

cd hiredis

make

make install

2) 
git clone https://github.com/sewenew/redis-plus-plus.git

cd redis-plus-plus

mkdir build

cd build

cmake ..

make

make install

cd ..

3) include redis-plus-plus in my project and try to build

#include <dep/redis-plus-plus/src/sw/redis++/redis_cluster.h>

NoSqlModule::NoSqlModule(IPluginManager* p)
{
    m_bIsExecute = true;
	pPluginManager = p;
}

NoSqlModule::~NoSqlModule()
{

}

bool NoSqlModule::Init()
{
    const std::string& nosqlAddress = pPluginManager->GetParam("nosql_add");
    const std::string& nosqlPort = pPluginManager->GetParam("nosql_port");
    const std::string& nosqlAuth = pPluginManager->GetParam("nosql_auth");

    sw::redis::ConnectionOptions connection_options;
    connection_options.host = nosqlAddress;  // Required.
    connection_options.port = std::stoi(nosqlPort); // Optional. The default port is 6379.
    connection_options.password = nosqlAuth; // Optional. No password by default.

    redisCluster = new  sw::redis::RedisCluster(connection_options);

	return true;
}

Normally it shouldn't include tls.h as I didn't using ssl/tls(-DREDIS_PLUS_PLUS_USE_TLS=ON) when I build redis-plus-plus.

**Comment by sewenew** [comment]
You should not include `dep/redis-plus-plus/src/sw/redis++/redis_cluster.h`. Instead, you should include `sw/redis++/redis++.h`, which is installed by running `make install`.

```
#include <sw/redis++/redis++.h>
```

In your case, since you didn't specify installation path, if you work on Linux, normally, the header should be install at /usr/local/include, i.e. the default installation path.

**Comment by ketoo** [comment]
Thanks, fixed it by using vcpkg.
