### ISSUE TITLE
ask for compiling help

### ISSUE THREAD

**Issue by 15058157346** [sewenew/redis-plus-plus#215]
```
template <typename Input>
void zadd_range(Connection &connection,
                const StringView &key,
                Input first,
                Input last,
                UpdateType type,
                bool changed) {
   ...

    while (first != last) {
        // Swap the <member, score> pair to <score, member> pair.
        args << first->second << first->first;    // 2226
        ++first;    // 2227
    }

    ...
}
```
base operand of ‘->’ has non-pointer type ‘std::__cxx11::basic_string<char>’          2226    src/sw/redis++/command.h
no match for ‘operator++’ (operand type is ‘std::__cxx11::basic_string<char>’)       2227    src/sw/redis++/command.h

**Comment by sewenew** [comment]
Could you please show me your application code that calls `zadd`? It seems that you called `zadd` with incorrect arguments.

Regards

**Comment by 15058157346** [comment]
std::string article = "article:" + article_id;
redis.zadd("time:", std::to_string(now), article);

**Comment by sewenew** [comment]
So you want to add `article` as member, and `now` as score? Also `now` is an integer?

In that case, you should call it like this: `redis.zadd("time:", article, now)`. Please check the function prototype of zadd for detail:

```
long long zadd(const StringView &key,
                    const StringView &member,
                    double score,
                    UpdateType type = UpdateType::ALWAYS,
                    bool changed = false);
```

**Comment by 15058157346** [comment]
Oh, thank you very much
