### ISSUE TITLE
Use hmget by passing a vector as the keys.

### ISSUE THREAD

**Issue by ketoo** [sewenew/redis-plus-plus#217]
Hi,

Redis++ provides interfaces below to access hashmap:
```
template <typename Input, typename Output>
    void hmget(const StringView &key, Input first, Input last, Output output);`

template <typename T, typename Output>
    void hmget(const StringView &key, std::initializer_list<T> il, Output output) {
        hmget(key, il.begin(), il.end(), output);
    }
```

Sometimes people use redis like this:

```
std::vector<sw::redis::OptionalString> activeOrdersRankResult;
std::vector<sw::redis::OptionalString> activeOrdersDataResult;

redisCluster->zrange(KeyForActiveOrdersRank(uuid, std::to_string(coin)), 0, -1, std::back_inserter(activeOrdersRankResult));

redisCluster->hmget(KeyForOrders(uuid, std::to_string(coin)), activeOrdersRankResult, std::back_inserter(activeOrdersDataResult));
```
How can I use hmget by passing a std::vector as the keys?

Kind regards,
James

**Comment by wingunder** [comment]
Hi @ketoo 
There's an example in the tests:
https://github.com/sewenew/redis-plus-plus/blob/b4356ff1011d71ad315290bc8ea928ed8452eaac/test/src/sw/redis%2B%2B/hash_cmds_test.hpp#L115-L121

And if you'd like to use a vector for the keys:
```C++
std::vector<std::string> keys = {"a", "b", "c"};
std::vector<std::string> fields = {"f1", "f2", "f3"};
std::vector<OptionalString> res;
std::for_each(keys.begin(), keys.end(), [&_redis, fields](auto &key){ 
    _redis.hmget(key, fields, std::back_inserter(res));
});
```
Hope this helps.
Regards

**Comment by sewenew** [comment]
> How can I use hmget by passing a std::vector as the keys?

@ketoo Do you mean passing vector as fields? Since hmget doesn't support multiple keys as parameter.

```
vector<string> fields = {"f1", "f2"};
vector<OptionalString> res;
redis.hmget("key", fields.begin(), fields.end(), back_inserter(res));
```

If you want to do this with multiple keys, please see @wingunder 's comment, which is great!

Regards

**Comment by ketoo** [comment]
Thanks Wingunder and Sewenew, got it, I am using vector as the fields.
