### ISSUE TITLE
Does this support snapshotting?

### ISSUE THREAD

**Issue by devspectre** [sewenew/redis-plus-plus#222]
Thanks for the great work.
I need to save data on disk as well.
I am curious to know if redis-plus-plus supports them - SAVE and BGSAVE commands.

**Comment by wingunder** [comment]
Hi @devspectre 

Yes `BGSAVE` is here:
https://github.com/sewenew/redis-plus-plus/blob/b4356ff1011d71ad315290bc8ea928ed8452eaac/src/sw/redis%2B%2B/command.h#L77-L79
and `SAVE` is here:
https://github.com/sewenew/redis-plus-plus/blob/b4356ff1011d71ad315290bc8ea928ed8452eaac/src/sw/redis%2B%2B/command.h#L113-L115

You can just include the following and all commands will be available.
```c++
#include <sw/redis++/redis++.h>
```
Check out: https://github.com/sewenew/redis-plus-plus#getting-started

Hope this helped you.
Regards

**Comment by devspectre** [comment]
Perfect, @wingunder 
By the way, how do I configure things like - automatically dump to disk every 60 seconds if at least 1000keys changed.
redis.save(60, 1000);
Does this work or how can I set those settings?

**Comment by sewenew** [comment]
@devspectre It seems that you want to configure Redis server, not call save or bgsave manually from client side.

In that case, the best way is to configure *redis.conf* on the server side:

```
save 60 1000
```

Although you can call the `config` command to do the setting dynamically (see the code below), however, once you restart your server, these settings will be overwritten.

```
redis.command("config", "set", "save", "60 1000");
```

Regards

**Comment by devspectre** [comment]
Thank you @sewenew .
I have one more question for you.
So we are going to move from MySQL to redis to make it faster.
Is there any library that we can use where we can still use SQL queries and the data is internally mapped to redis data structures.

Best regards

**Comment by sewenew** [comment]
@devspectre sorry, but I’m not familiar with that. You might need to seek help from others.

Regards

**Comment by devspectre** [comment]
@sewenew , I have one more question.
I want to store one row of a SQL table to redis using redis hash.
Not sure how to do that with `redis-plus-plus`
name="John"
age=30
major="javascript"

redis.command("config", "hmset", "name John", "age 30", "major javascript"); ?????
