### ISSUE TITLE
'xdel' explanation

### ISSUE THREAD

**Issue by escherstair** [sewenew/redis-plus-plus#223]
I see [here](https://redis.io/commands/xdel) the documentation on XDEL over streams.
The examples are pretty basics and they show how to delete a single entry.
This matches to what I find in redis-plus-plus README.md line 
```
// Delete an item from the stream.
redis.xdel("key", id);
```
But I don't understand this prototype
https://github.com/sewenew/redis-plus-plus/blob/b4356ff1011d71ad315290bc8ea928ed8452eaac/src/sw/redis%2B%2B/redis.hpp#L1094

Can someone clarify this, please?

**Comment by escherstair** [comment]
It seems that the proper way should be
```
// Delete a list of items from the stream.
std::vector<std::string> id_list{"id1","id2"};
redis.xdel("key", id_list.begin(), id_list.end());
```

Is thsi the supposed way to `xdelete` items?

**Comment by sewenew** [comment]
Yes, `long long Redis::xdel(const StringView &key, Input first, Input last)` is used to delete multiple items from the given stream.

Regards

**Comment by escherstair** [comment]
It seems that a function to delete a single items doesn't exists.
Am I missing something?

**Comment by sewenew** [comment]
What do you mean by "delete a single item*? As yo mentioned in your first comment, there's a `redis.xdel("key", id);` which delete a single item in a stream. If you mean delete a key, which might be of any type, e.g. string, list, hash, you can use `long long del(const StringView &key)` or `long long unlink(const StringView &key);`

Regards

**Comment by escherstair** [comment]
Sorry, my fault.
For some reasons I can't understand, yesterday trying to call `redis.xdel("key", id);` gave compile error (not able to find that overload of `xdel()`).
And so I had to create a `vector` of one item.
Today I wrote again the code and it works.
