### ISSUE TITLE
Undefined reference to set function

### ISSUE THREAD

**Issue by RobinLanglois** [sewenew/redis-plus-plus#224]
Hello,
I have a linking error with a minimal example of the `set` function, coming from the documentation :  
```c++
#include <sw/redis++/redis++.h>
using namespace sw::redis;
...
auto redis = Redis("tcp://127.0.0.1:6379");
redis.set("key", "val");
```

Here's the error I got at compilation :  
`undefined reference to « sw::redis::Redis::set(std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&, sw::redis::UpdateType) »`

Please note that I'm using CMake, and copy pasted the snippet of the README. Moreover, I was already using Redis++ somewhere else in my project, using StringView and xadd, and it worked like a charm, so I really don't understand why it doesn't work when I'm simply adding a `set` (and it's still working when I'm commenting the `set` line).

I'm using Ubuntu 20.04.2, with gcc version 9.3, cmake version 3.16.3, and C++20 standard in my project.

Thank you in advance.

**Comment by sewenew** [comment]
Have you built redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17`?

Regards

**Comment by RobinLanglois** [comment]
No I didn't, I rebuilt it and it works ! Thank you !
