### ISSUE TITLE
Key Expiry is not working properly 

### ISSUE THREAD

**Issue by KedarSadhu** [sewenew/redis-plus-plus#228]
Hi @sewenew ,
I am setting expiry time while setting a key like  **redis_con->set(key, payload, std::chrono::seconds(expiry_time));**
after value is set I check its **ttl** like **redis_con->ttl(key);** it is giving me the ttl time but when I check ttl via redis-cli it is giving me -1 .
I also conformed via aof file there is only plain set command was fired.

It is working for some keys and not working for some.

**Comment by sewenew** [comment]
@KedarSadhu redis-plus-plus works correctly, i.e. both `set` and `ttl`. However, there might be some other client called 'set' command without setting the TTL, and overwritten your setting. TTL returns -1, means there's no TTL set on the key.

Regards
