### ISSUE TITLE
Error compiling with -DREDIS_PLUS_PLUS_BUILD_ASYNC=libuv

### ISSUE THREAD

**Issue by shadow-raven** [sewenew/redis-plus-plus#229]
When the cmake flag:
`-DREDIS_PLUS_PLUS_BUILD_ASYNC=libuv`
is set redis-plus-plus fails to compile with the following warning:
redis-plus-plus/src/sw/redis++/event_loop.h:102:10: error: ‘mutex’ in namespace ‘std’ does not name a type``

This can be fixed by including mutex in event_loop.h
`#include <mutex>`

**Comment by sewenew** [comment]
@shadow-raven Thanks for find the problem. I've fixed it, please try the latest code on master branch. Sorry for the inconvenience.

Regards
