### ISSUE TITLE
Issue with Sentinel support

### ISSUE THREAD

**Issue by kuroyi** [sewenew/redis-plus-plus#23]
Hi, I am using the Sentinel class to connect to a slave and having a problem. Everything is fine until I get an exception from a command and from then on it starts returning data from previous commands instead of the current one. Maybe something is not getting reset properly after the Exception (when reconnecting to Redis?)

It appears to work fine when I connect directly to the slave with the Redis class. (Although my test program hasn't thrown an exception yet to see if it starts getting the correct data after that).

Thanks for any help.

**Comment by sewenew** [comment]
Can you show me the pseudo code, and what exception do you got, e.g. the exception type and error message?

Also, did you use Pipeline or Transaction with the created Redis object? If you're using Pipeline or Transaction, and got an exception, the Pipeline or Transaction object will enter an invalid state, and [you have to recreate one](https://github.com/sewenew/redis-plus-plus#exception-1).

**Comment by kuroyi** [comment]
I did not use Pipeline or Transaction. I'm also not sure which error it's throwing, I will modify my catch statement to try to determine that.  I'm assuming it may be a socket timeout.

    std::shared_ptr<sw::redis::Redis> redis;
    try {
        sw::redis::SentinelOptions sentinel_opts;
        sw::redis::ConnectionOptions connection_opts;
        sw::redis::ConnectionPoolOptions pool_opts;
        sentinel_opts.nodes = {{"orldc-dev-redis01", 26379},
                                {"orldc-dev-redis02", 26379}};
        connection_opts.connect_timeout = std::chrono::milliseconds(200);
        connection_opts.socket_timeout = std::chrono::milliseconds(100);
        auto sentinel = std::make_shared<sw::redis::Sentinel>(sentinel_opts);
        redis = std::make_shared<sw::redis::Redis>(sentinel, "redis-mlat", sw::redis::Role::SLAVE, connection_opts, pool_opts);

                try {
                    auto result = redis->hget("key", value.c_str());
                    if (result) {
                         // use data
                         // it returns a stale result after a previous exception
                    } else {
                        // null result
                    }
                } catch (const sw::redis::Error &e) {
                    // error
                }

**Comment by sewenew** [comment]
Hi @kuroyi 

Thanks for your details. I think I get the problem.

### Problem

In Sentinel mode, we need to configure a `socket_timeout` option, and the connection to Redis might be timed out. In this case, you would catch a `sw::redis::TimeoutError` exception. When this happens, redis-plus-plus clears the error info, in order to support the [pubsub feature](https://github.com/sewenew/redis-plus-plus#publishsubscribe). However, in other scenarios, clear the error info, will make Redis to read the replies of old commands.

### Solution

I'll fix this problem ASAP. However, before that, you can try the following:

1. set a larger timeout with the `ConnectionOptions`.
2. you can try to catch the `TimeoutError`, if you got one, destroy the `Redis` object, and create a new one.

Sorry for the bug... When I fixed it, I'll let you know.

Regards

**Comment by sewenew** [comment]
Hi @kuroyi ,

I've already fixed the problem. Please fetch the latest code from the master branch. Also, I'll release a new version later.

Sorry again for the inconvenience... Also thanks a lot for finding the bug :)

Regards

**Comment by sewenew** [comment]
Also, it seems that your client might timeout when reading the response from Redis. When this happens, redis-plus-plus will reconnect to Redis, and that might be a cost.  So you'd better set a larger timeout, or deploy your client near to the Redis server.

```
try {
    auto val = redis.get("key");
} catch (const TimeoutError &e) {
    // reading from or writing to Redis have been timed out.
} catch (const Error &e) {
    // other errors
}
```

**Comment by sewenew** [comment]
Hi @kuroyi 

Does the latest code fixed your problem? If you still have any problem with redis-plus-plus, feel free to let me know :)

Regards

**Comment by kuroyi** [comment]
Yes, your update did fix the issue, thank you very much.  You are correct that the timeout may be a little low, I will likely increase it.
