### ISSUE TITLE
Lots of Linker errors after following instructions to the letter.

### ISSUE THREAD

**Issue by rick-rheo** [sewenew/redis-plus-plus#231]
Following the setup instructions exactly with no modifications whatsoever.   Using CLion on MacOS (CMake) Trying to build the first example (under Getting Started), with my CMakeLists including an unmodified copy/paste from "Build with Cmake"   There are a bunch of linker errors.

`  "sw::redis::Redis::get(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&)", referenced from:
      testCodebook() in testbed.cpp.o
  "sw::redis::Redis::set(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&, `

There's a lot more.  Any redis command cannot be found by the linker.

But this code compiles and links fine

`		
		auto redis = Redis("tcp://127.0.0.1:6379");
		redis.command("client", "setname", "name");
		auto r = redis.command("client", "getname");
		assert(r);
`

**Comment by sewenew** [comment]
Did you build the code with C++ 17 or later? If you want to build your code with C++ 17, you need to build redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17` when running cmake.

Please check the [installation](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) part for detail. If you still have problems, feel free to let me know.

Regards

**Comment by camgaertner** [comment]
Seeing this too after building from master. 
OS: Windows 10

I've triple checked the C++ standard is 17.

```
1> [CMake] -- redis-plus-plus build with CXX standard: c++17
```

**Comment by sewenew** [comment]
@camgaertner In fact the latest code should work with Windows. It will use REDIS_PLUS_PLUS_CXX_STANDARD to set CXX_STANDARD option.

However, I don't have a Windows box nearby, cannot test with it.

Can you also try to set `CMAKE_CXX_STANDARD` explicitly:

```
cmake -DCMAKE_CXX_STANDARD=17 -DREDIS_PLUS_PLUS_CXX_STANDARD=17 ..
```

Regards

**Comment by camgaertner** [comment]
@sewenew I gave that a try but I still get a linker error when trying to use `Redis::set`

```
error LNK2019: unresolved external symbol "public: bool __cdecl sw::redis::Redis::set(class std::basic_string_view<char,struct std::char_traits<char> > const &,class std::basic_string_view<char,struct std::char_traits<char> > const &,class std::chrono::duration<__int64,struct std::ratio<1,1000> > const &,enum sw::redis::UpdateType)" (?set@Redis@redis@sw@@QEAA_NAEBV?$basic_string_view@DU?$char_traits@D@std@@@std@@0AEBV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@5@W4UpdateType@23@@Z) referenced in function "void __cdecl test(void)" (?test@@YAXXZ)
```

I followed the Windows installation instructions w/ Visual Studio 2019 (CMake 3.20.1).

**Comment by sewenew** [comment]
@camgaertner Can you use Visual Studio to set C++ standard explicitly? The UI of VS2019 should has an option to set C++ standard.

I’ll try to reproduce the problem as soon as I get a Windows box.

Regards

**Comment by sewenew** [comment]
Hi all,

The latest code is built with C++17 standard by default. And these problem should be fixed. I'll close this issue. If you still have problem with it, feel free to let me know.

Regards
