### ISSUE TITLE
ConnectionOptions.db not working with AsyncRedis

### ISSUE THREAD

**Issue by shadow-raven** [sewenew/redis-plus-plus#232]
I tried to set the db to a value other than the default, but it isn't working. If i explicitly run command with select it works, but this solution won't work if im using a connection pool. I have tried with tcp and unix socket, with uri and with ConnectionOptions. I have also tried without a connection pool with the same result. I have attached a code snippet below to show what i am doing.

```c++
sw::redis::ConnectionOptions connectionOptions;
connectionOptions.host = "127.0.0.1";
connectionOptions.port = 6379;
connectionOptions.db = 5;
sw::redis::ConnectionPoolOptions connectionPoolOptions;
connectionPoolOptions.size = 2;
sw::redis::AsyncRedis client = sw::redis::AsyncRedis(connectionOptions, connectionPoolOptions);.

sw::redis::Future<sw::redis::OptionalString> user = client.hget("key_name", "hash_key");
sw::redis::OptionalString u = user.get();
if (!u) {
	std::cout << "no record" << std::endl;
	return false;
}
std::cout << *u << std::endl;
return true;
```
this outputs `no record`

Whereas if i explicitly call select it works. (no connection pool here to ensure both calls are done on the same connection)
```c++
sw::redis::ConnectionOptions connectionOptions;
connectionOptions.host = "127.0.0.1";
connectionOptions.port = 6379;
sw::redis::AsyncRedis client = sw::redis::AsyncRedis(connectionOptions);
client.command<void>("select", "5").wait();

sw::redis::Future<sw::redis::OptionalString> user = client.hget("key_name", "hash_key");
sw::redis::OptionalString u = user.get();
if (!u) {
	std::cout << "no record" << std::endl;
	return false;
}
std::cout << *u << std::endl;
return true;
```
this outputs `value`

If the problem is with my implementation i would really appreciate some help, otherwise if you need any additional info from me i will gladly help.

Thank You

**Comment by sewenew** [comment]
@shadow-raven That's a bug. I'll fix it ASAP. Sorry for the inconvenience.

Regards

**Comment by sewenew** [comment]
@shadow-raven The code has been fixed. Please try the latest code on master branch. If you still have problem with it, feel free to let me know :)

Regards
