### ISSUE TITLE
asyncRedis with "select db" cmd will throw exception

### ISSUE THREAD

**Issue by wolf289184291** [sewenew/redis-plus-plus#237]
sw::redis::ConnectionOptions ops;
...
ops.db = 1; //not use default

sw::redis::AsyncRedis* pRedis = new sw::redis::AsyncRedis(ops, poolOps);

auto future = pRedis->ping();
future.wait();
future.get(); //this will thow exception since your cmd is "select %lld", but your type of ConnectionOptions.db is int, 
the actual param after parse is  "select -321331232312", it will reply an error by redis,
just let cmd to be "select %d" will work, or let ConnectionOptions.db to be int64

**Comment by sewenew** [comment]
Yes, that's a bug! The behavior is undefined, although my compiler doesn't complain about it.

Thanks a lot for pointing it out! I've fixed the problem. Please try the latest code on master branch. Sorry for the inconvenience.

Regards
