### ISSUE TITLE
Store an OpenCV cv::Mat

### ISSUE THREAD

**Issue by RobinLanglois** [sewenew/redis-plus-plus#239]
Hello,
Sorry for bothering you again. Thank you for always answering so quickly.
I'm facing a problem quite similar to those I had in #200, but this time, I would like to store a cv::Mat in Redis, instead of a vector<uchar>. Do you know how I could achieve this, **without copying the frame** ?
Thank you in advance.

**Comment by sewenew** [comment]
@RobinLanglois You can serialize cv::Mat into a std::string, and then you can use the string object as parameters to redis-plus-plus' interface. However, I know little about OpenCV, and cannot help. You can google how to do the serialization work. For example: https://stackoverflow.com/questions/15200570/convert-cvmat-to-string-of-bytes-in-opencv

Regards

**Comment by RobinLanglois** [comment]
This copies the frame, doesn't it ?

**Comment by sewenew** [comment]
Yes, since you need to convert the object to string, you have to copy it.

**Comment by RobinLanglois** [comment]
So there's nothing we can do with a StringView ?

**Comment by sewenew** [comment]
If you can find an interface of cv::Mat, which uses a const char pointer and a length to represent the underlying data, you can construct a StringView with the pointer and length. Otherwise, you have to do a copy.

**Comment by RobinLanglois** [comment]
I'll try. Thank you !

**Comment by RobinLanglois** [comment]
This seems to be working : 
```c++
using Attrs = std::unordered_map<double, StringView>;
Mat frame;
...
StringView buffer ((char*)frame.ptr(), frame.total() * frame.channels());
Attrs attrs = { {timestamp, buffer}};
string id = mRedisServer->xadd(cameraId, "*", attrs.begin(), attrs.end());
```

What you said put me on the right track. Thank you !
Regards
