### ISSUE TITLE
About the async interface.

### ISSUE THREAD

**Issue by portsip** [sewenew/redis-plus-plus#242]
I see the new version support async with std::future implementation, how can I have the lambada callback mode for the async interface?  Once the async call is completed, the lambada callback will be called automatically with the result?

For example:

```
redis->eval(script,
keys,
args,
[p1, p2](std::string & reply)
{
   // In callback thread
   std::cout << "Received reply: " << std::endl;
});

```
Thanks

**Comment by sewenew** [comment]
So far, there's no support for callback.

In fact, std::future should have a `then` method, which works like the callback (check [this](https://en.cppreference.com/w/cpp/experimental/future/then) for reference). However, the C++ committee doesn't include this feature in the latest standard. There's a plan to support other implementation of `future`, e.g. boost::future, folly::Future, so that the library user can use the `then` method, i.e. continuation.

`future` is better than callback, since it avoids the *callback hell* problem. However, since the continuation feature might not ready even in C++23, I might add a callback interface. But, I still need to do some research on how to report error in this case, and the priority is low. The interface might be something like this:

```
redis.command<OptionalString>("get", "key", [](OptionalString val, std::exception_ptr err) {
                                                                                   if (err) { process_error(); } else { process_val(); }
                                                                               });
```

If I have progress on it, I'll let you know.

Regards

**Comment by pengweichu** [comment]
Thanks a lot for your reply.

Since we can create a thread pool to handle the callbacks that's why I prefer that - in our current redis client (cpp-redis) is works this way, but the cpp-redis is no longer maintained, so we would like to replace it.

The future way is modern and graceful, but if provided the thread pool for it will be great. As my research, we can use the std::async to launch a thread to take results that don't block the current thread to wait for the "future", but the std::async maybe not implement with thread pool it will cause the application to create massive threads.

BR

**Comment by portsip** [comment]
> So far, there's no support for callback.
> 
> In fact, std::future should have a `then` method, which works like the callback (check [this](https://en.cppreference.com/w/cpp/experimental/future/then) for reference). However, the C++ committee doesn't include this feature in the latest standard. There's a plan to support other implementation of `future`, e.g. boost::future, folly::Future, so that the library user can use the `then` method, i.e. continuation.
> 
> `future` is better than callback, since it avoids the _callback hell_ problem. However, since the continuation feature might not ready even in C++23, I might add a callback interface. But, I still need to do some research on how to report error in this case, and the priority is low. The interface might be something like this:
> 
> ```
> redis.command<OptionalString>("get", "key", [](OptionalString val, std::exception_ptr err) {
>                                                                                    if (err) { process_error(); } else { process_val(); }
>                                                                                });
> ```
> 
> If I have progress on it, I'll let you know.
> 
> Regards

Thanks a lot for your reply.

Since we can create a thread pool to handle the callbacks that's why I prefer that - in our current redis client (cpp-redis) is works this way, but the cpp-redis is no longer maintained, so we would like to replace it.

The future way is modern and graceful, but if provided the thread pool for it will be great. As my research, we can use the std::async to launch a thread to take results that don't block the current thread to wait for the "future", but the std::async maybe not implement with thread pool it will cause the application to create massive threads.

BR

**Comment by sewenew** [comment]
In fact, an elegant implementation of future should give an option to run the callback in thread pool. Take boost for example, you can set a thread pool when you call the `then` method.

If you can use boost, you can try the following:

1. replace *src/sw/redis++/async_utils.h* with the following code:
2. 
```
#ifndef SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
#define SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H

//#include <future>

#define BOOST_THREAD_PROVIDES_FUTURE
#define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION
#define BOOST_THREAD_PROVIDES_EXECUTORS
#include <boost/thread/future.hpp>

namespace sw {

namespace redis {

template <typename T>
using Future = boost::future<T>;
//using Future = std::future<T>;

template <typename T>
using Promise = boost::promise<T>;
//using Promise = std::promise<T>;

}

}

#endif
```

2. build and install redis-plus-plus.
3. use it as the following example:

```
#include <sw/redis++/async_redis++.h>
#include <boost/thread/executors/basic_thread_pool.hpp>

boost::executors::basic_thread_pool pool(3);

ConnectionOptions opts;
opts.host = "127.0.01";
opts.port = 6379;

auto async_redis = AsyncRedis(opts);
async_redis.get("key").then(pool, [](Future<OptionalString> f) {
    auto val = f.get();
    if (val) cout << *val << endl;
});
```

There's a plan to support boost and other popular future libs, and will have a cmake option to let user choose between these libs.

Regards

**Comment by portsip** [comment]
> In fact, an elegant implementation of future should give an option to run the callback in thread pool. Take boost for example, you can set a thread pool when you call the `then` method.
> 
> If you can use boost, you can try the following:
> 
> 1. replace _src/sw/redis++/async_utils.h_ with the following code:
> 
> ```
> #ifndef SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> #define SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> 
> //#include <future>
> 
> #define BOOST_THREAD_PROVIDES_FUTURE
> #define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION
> #define BOOST_THREAD_PROVIDES_EXECUTORS
> #include <boost/thread/future.hpp>
> 
> namespace sw {
> 
> namespace redis {
> 
> template <typename T>
> using Future = boost::future<T>;
> //using Future = std::future<T>;
> 
> template <typename T>
> using Promise = boost::promise<T>;
> //using Promise = std::promise<T>;
> 
> }
> 
> }
> 
> #endif
> ```
> 
> 1. build and install redis-plus-plus.
> 2. use it as the following example:
> 
> ```
> #include <sw/redis++/async_redis++.h>
> #include <boost/thread/executors/basic_thread_pool.hpp>
> 
> boost::executors::basic_thread_pool pool(3);
> 
> ConnectionOptions opts;
> opts.host = "127.0.01";
> opts.port = 6379;
> 
> auto async_redis = AsyncRedis(opts);
> async_redis.get("key").then(pool, [](Future<OptionalString> f) {
>     auto val = f.get();
>     if (val) cout << *val << endl;
> });
> ```
> 
> There's a plan to support boost and other popular future libs, and will have a cmake option to let user choose between these libs.
> 
> Regards

Appreciates your reply, yes, this makes sense, we will try with boost.

One more thing, about the pub/sub, we must have a thread to call the consume in the loop, maybe built-in a thread in the subscriber to always call the consume in that thread loop will more easy to use? 

Our application is for real-time communications, it's performance sensitive, so I just focus on the async :)

**Comment by sewenew** [comment]
In fact, so far the async interface doesn't have built-in support for pub/sub. Because I still looking for a better API design. C++ language doesn't have built-in support for async stream like Dart, and I'm trying to figure out a better way to make it easy to use. IMHO, it might not be a good idea to have a built-in thread for the subscriber. Since I would like to let the end user to decide whether s/he wants to run the callback in the main thread or a new thread or even a thread pool (like the `then` method with a thread pool, mentioned above). If I have any progress, I'll let you know.

For the sync interface, I leave the end user to call `consume` in a loop. Because that will be much more flexible. The end user can decide what to do when the connection is timed out or some error happens. You can wrap the loop in a lambda, and pass the lambda to `std::async`, which can start a new thread to do the work.

Regards

**Comment by wingunder** [comment]
Just my 2 cents:

> ...might not be a good idea to have a built-in thread for the subscriber.

I second that. I think it's already easy enough as it is now and as @sewenew  said, the user has full control. Hiding some stuff in a thread is problematic, as you'll need to get the data out of the thread, back into the user scope.

Regards

**Comment by portsip** [comment]
> In fact, so far the async interface doesn't have built-in support for pub/sub. Because I still looking for a better API design. C++ language doesn't have built-in support for async stream like Dart, and I'm trying to figure out a better way to make it easy to use. IMHO, it might not be a good idea to have a built-in thread for the subscriber. Since I would like to let the end user to decide whether s/he wants to run the callback in the main thread or a new thread or even a thread pool (like the `then` method with a thread pool, mentioned above). If I have any progress, I'll let you know.
> 
> For the sync interface, I leave the end user to call `consume` in a loop. Because that will be much more flexible. The end user can decide what to do when the connection is timed out or some error happens. You can wrap the loop in a lambda, and pass the lambda to `std::async`, which can start a new thread to do the work.
> 
> Regards

Thanks, it makes sense.

BR

**Comment by portsip** [comment]
> In fact, an elegant implementation of future should give an option to run the callback in thread pool. Take boost for example, you can set a thread pool when you call the `then` method.
> 
> If you can use boost, you can try the following:
> 
> 1. replace _src/sw/redis++/async_utils.h_ with the following code:
> 
> ```
> #ifndef SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> #define SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> 
> //#include <future>
> 
> #define BOOST_THREAD_PROVIDES_FUTURE
> #define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION
> #define BOOST_THREAD_PROVIDES_EXECUTORS
> #include <boost/thread/future.hpp>
> 
> namespace sw {
> 
> namespace redis {
> 
> template <typename T>
> using Future = boost::future<T>;
> //using Future = std::future<T>;
> 
> template <typename T>
> using Promise = boost::promise<T>;
> //using Promise = std::promise<T>;
> 
> }
> 
> }
> 
> #endif
> ```
> 
> 1. build and install redis-plus-plus.
> 2. use it as the following example:
> 
> ```
> #include <sw/redis++/async_redis++.h>
> #include <boost/thread/executors/basic_thread_pool.hpp>
> 
> boost::executors::basic_thread_pool pool(3);
> 
> ConnectionOptions opts;
> opts.host = "127.0.01";
> opts.port = 6379;
> 
> auto async_redis = AsyncRedis(opts);
> async_redis.get("key").then(pool, [](Future<OptionalString> f) {
>     auto val = f.get();
>     if (val) cout << *val << endl;
> });
> ```
> 
> There's a plan to support boost and other popular future libs, and will have a cmake option to let user choose between these libs.
> 
> Regards

Please consider supporting Facebook folly future.
Thanks

**Comment by sewenew** [comment]
@portsip `folly::Future` doesn't support `folly::Future<void>`, instead it has a `folly::Future<folly::Unit>`. So you have to do some tricky thing, i.e. make a proxy for`folly::Future`. You can replace `src/sw/redis++/async_utils.h` with the following code:

```
#ifndef SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
#define SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H

#include <folly/futures/Future.h>

namespace sw {

namespace redis {
template <typename T>
struct Future {
	explicit Future(folly::Future<T> fut) : future(std::move(fut)) {}
	folly::Future<T> future;
};

template <>
struct Future<void> {
	explicit Future(folly::Future<folly::Unit> fut) : future(std::move(fut)) {}

	folly::Future<folly::Unit> future;
};

template <typename T>
struct Promise {
	Future<T> get_future() {
		return Future<T>(promise.getFuture());
	}

	void set_value(T &&val) {
		promise.setValue(std::move(val));
	}

	void set_exception(std::exception_ptr err) {
		promise.setException(folly::exception_wrapper::from_exception_ptr(err));
	}

	folly::Promise<T> promise;
};

template <>
struct Promise<void> {
	Future<void> get_future() {
		return Future<void>(promise.getFuture());
	}

	void set_value() {
		promise.setValue();
	}

	void set_exception(std::exception_ptr err) {
		promise.setException(folly::exception_wrapper::from_exception_ptr(err));
	}

	folly::Promise<folly::Unit> promise;
};

}

}

#endif // end SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
```

NOTE: you need to build the redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17`, i.e. build the code with c++17 standard.

*folly* depends on lots of other libs, so you need to link your application with those libs. For example:

```
c++ -std=c++17 -o app app.cpp -lredis++ -lhiredis -pthread -lfolly -lglog -lgflags -pthread -ldl -levent -ldouble-conversion -lboost_context -liberty -lfmt -luv
```

Regards

**Comment by portsip** [comment]
> @portsip `folly::Future` doesn't support `folly::Future<void>`, instead it has a `folly::Future<folly::Unit>`. So you have to do some tricky thing, i.e. make a proxy for`folly::Future`. You can replace `src/sw/redis++/async_utils.h` with the following code:
> 
> ```
> #ifndef SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> #define SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> 
> #include <folly/futures/Future.h>
> 
> namespace sw {
> 
> namespace redis {
> template <typename T>
> struct Future {
> 	explicit Future(folly::Future<T> fut) : future(std::move(fut)) {}
> 	folly::Future<T> future;
> };
> 
> template <>
> struct Future<void> {
> 	explicit Future(folly::Future<folly::Unit> fut) : future(std::move(fut)) {}
> 
> 	folly::Future<folly::Unit> future;
> };
> 
> template <typename T>
> struct Promise {
> 	Future<T> get_future() {
> 		return Future<T>(promise.getFuture());
> 	}
> 
> 	void set_value(T &&val) {
> 		promise.setValue(std::move(val));
> 	}
> 
> 	void set_exception(std::exception_ptr err) {
> 		promise.setException(folly::exception_wrapper::from_exception_ptr(err));
> 	}
> 
> 	folly::Promise<T> promise;
> };
> 
> template <>
> struct Promise<void> {
> 	Future<void> get_future() {
> 		return Future<void>(promise.getFuture());
> 	}
> 
> 	void set_value() {
> 		promise.setValue();
> 	}
> 
> 	void set_exception(std::exception_ptr err) {
> 		promise.setException(folly::exception_wrapper::from_exception_ptr(err));
> 	}
> 
> 	folly::Promise<folly::Unit> promise;
> };
> 
> }
> 
> }
> 
> #endif // end SEWENEW_REDISPLUSPLUS_ASYNC_UTILS_H
> ```
> 
> NOTE: you need to build the redis-plus-plus with `-DREDIS_PLUS_PLUS_CXX_STANDARD=17`, i.e. build the code with c++17 standard.
> 
> _folly_ depends on lots of other libs, so you need to link your application with those libs. For example:
> 
> ```
> c++ -std=c++17 -o app app.cpp -lredis++ -lhiredis -pthread -lfolly -lglog -lgflags -pthread -ldl -levent -ldouble-conversion -lboost_context -liberty -lfmt -luv
> ```
> 
> Regards

Git it, thanks a lot.

**Comment by sewenew** [comment]
Hi all,

Async support has been release with redis-plus-plus 1.3.0.

Regards
