### ISSUE TITLE
MOVED error (exception)

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#243]
Hi in my code, I received MOVED error (exception). The document says that both MOVE/ASK are handled. Not sure why I received the error. Shall I reset my Redis Cluster connection to use the new port and send the request again? Or call some other methods? 

Thank you!

**Comment by patrickjchen** [comment]
The exception was thrown when xread() was called.

**Comment by patrickjchen** [comment]
My Redis cluster is simply using ports 7001---7006, with the first 3 as primary nodes, the last 3 as backup

**Comment by sewenew** [comment]
Can you show me your code and version or branch of redis-plus-plus and hiredis?

Regards

**Comment by patrickjchen** [comment]
Hi, thanks for the quick reply.
My code is simply:
using Attrs = std::unordered_map<std::string, std::string>;
using Item = std::pair<std::string, Attrs>;
using ItemStream = std::vector<Item>;

std::unordered_map<std::string, std::string> _streams;  //this is populated in contructor

The main loop:
std::unordered_map<std::string, ItemStream> result;
 _redis->xread(_streams.begin(), _streams.end(), 10, std::inserter(result, result.end()));

Then I changed to:
for (auto iter=_streams.begin(); iter != _streams.end(); ++iter) {
    _redis->xread(iter, std::next(iter), 10, std::inserter(result, result.end()));
}
Both have the same problem.

I am not sure how to get the versions of redis++ and hiredis.
The compiler I am using is gcc 8.1, with c++17 turned on

**Comment by patrickjchen** [comment]
The version for hiredis
/usr/local/lib/libhiredis.so.1.0.1-dev

**Comment by sewenew** [comment]
Sorry, but I cannot reproduce your problem. Did you use a `Redis` object or `Redis Cluster` object?

If you want to send commands to Redis Cluster, you should use `RedisCluster` instead of `Redis`

Regards

**Comment by patrickjchen** [comment]
Sorry Redis object was used instead of RedisCluster object, due to a bug in the CMake build file.
Thanks a lot!
