### ISSUE TITLE
Does redis-plus-plus have http support？

### ISSUE THREAD

**Issue by WanZixin** [sewenew/redis-plus-plus#244]
I want to use **http request** to connect redis through redis-plus-plus. But I only find `auto redis = Redis("tcp://127.0.0.1:6379");`. I also want to add http header, use http post request. Where can the solution be found?

**Comment by sewenew** [comment]
Sorry, but redis-plus-plus doesn't have http support. Not sure if [webdis](https://github.com/nicolasff/webdis) is what you are looking for.

Regards

**Comment by WanZixin** [comment]
Sorry, I’m a newbee about&nbsp;redis. I have known about more information about redis and I supposed redis uses http. Thanks for your advice.
Regards



发自我的iPhone


------------------ Original ------------------
From: sewenew ***@***.***&gt;
Date: Wed,Jun 16,2021 9:51 PM
To: sewenew/redis-plus-plus ***@***.***&gt;
Cc: WanZixin ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [sewenew/redis-plus-plus] Does redis-plus-plus have http support？ (#244)

**Comment by sewenew** [comment]
No, it doesn't use HTTP protocol. Instead it has its own protocol. If you're coding with C++, you can use redis-plus-plus as your client.

Regards

**Comment by WanZixin** [comment]
Thanks for answering my qustions. I'm using redis-plus-plus.
Regards
