### ISSUE TITLE
Storing bigger data (more than 512 MBs) using set command

### ISSUE THREAD

**Issue by VaibhawChandrakar** [sewenew/redis-plus-plus#246]
Hi,
I am trying to use Redis.set to store key value pair in Redis. The value is just some binary data.
Though it is working fine, but when the size of "value" is more than 512 MBs the command fails and I get following error in my catch
_Failed to get reply: Connection reset by peer_
I went through Redis documentation at https://redis.io/topics/data-types-intro  and found out this
**_Values can be strings (including binary data) of every kind, for instance you can store a jpeg image inside a value. A value can't be bigger than 512 MB._**

Is there any way in Redis-plus-plus library to store bigger than 512 MBs values ?
Alternatively I am thinking of creating a wrapper write/read api which breaks and store in multiple key,value pair and similarly read and join them back.

Vaibhaw

**Comment by sewenew** [comment]
No, there's no way to store value bigger than 512MB with redis-plus-plus' API. You can split your data into serval parts, and save them into a List or Hash with redis-plus-plus' API.

However, IMHO, it's not a good idea to read / write a large value into Redis. Since Redis is single-threaded, it might block for a long time, if the value is too large.

Regards

**Comment by VaibhawChandrakar** [comment]
Hi,
Thanks for the reply.
>>>>>>Since Redis is single-threaded, it might block for a long time, if the value is too large.
Just want to understand little more on this. 
1. I did a pstack on redis-server process id and see it has 5 threads running on it. So when you say single-threaded, you mean only one thread to save/read from Redis server ?
2. When we use ConnectionPoolOptions to create more than one connection to Redis server what are they used for ?
3. If we are having more than one Redis Clients at the same time, with all of them doing save/read to Redis Server at the same time, does Redis serves the requests from them only one at a time ?
4. Will RedisCluster help if want to save bigger data (is it multithreaded) ?

Thanks in advance for your reply.

Regards

**Comment by sewenew** [comment]
> 1. I did a pstack on redis-server process id and see it has 5 threads running on it. So when you say single-threaded, you mean only one thread to save/read from Redis server ?

Only a single thread to process the request.

> 2. When we use ConnectionPoolOptions to create more than one connection to Redis server what are they used for ?

Used for connection pool.

> 3. If we are having more than one Redis Clients at the same time, with all of them doing save/read to Redis Server at the same time, does Redis serves the requests from them only one at a time ?

YES

> 4. Will RedisCluster help if want to save bigger data (is it multithreaded) ?

If you mean `sw::redis::RedisCluster`, it doesn't work with Redis server. Instead, you need to have a Redis Cluster. Check its doc for detail. NOTE: For each instance in the cluster, it's still single-threaded.

Regards
