### ISSUE TITLE
no matching function for call

### ISSUE THREAD

**Issue by tscdemo2020** [sewenew/redis-plus-plus#247]
Greetings!!

I am developing a simple C++ application to asynchronously process elements in a Redis database.

I declared the following in a header file:
Redis redis;
Subscriber subscribe;
When I attempt to compile the code using g++ (version: 9.3.0-17) on an ubuntu (20.04), I get the following errors:
error: no matching function for call to ‘sw::redis::Redis::Redis()’

It seems like I can't declare those objects without initializing. Please advise how i can do that. Thank you!!

**Comment by sewenew** [comment]
There's no default constructor for `Redis`, you need to specify a `ConnectionOptions` or URI for it. Check [the doc](https://github.com/sewenew/redis-plus-plus#connection) for detail.

Regards
