### ISSUE TITLE
C++17 with msvc

### ISSUE THREAD

**Issue by paceholder** [sewenew/redis-plus-plus#250]
https://github.com/sewenew/redis-plus-plus/blob/eff34aa7783d38940a9ad51263e1595fcd71ec01/CMakeLists.txt#L132

CMake docs state:

`set_property(TARGET tgt PROPERTY CXX_STANDARD 11)`
with a compiler which does not support -std=gnu++11 or an equivalent flag will not result in an error or warning, but will instead add the -std=gnu++98 flag if supported.

So, this line has no effect, for instance, for `msvc` compiler.

Possible solution: 
Usin CMake function available starting from the version 3.8.2
`target_compile_features(${SHARED_LIB} PUBLIC cxx_std_${REDIS_PLUS_PLUS_CXX_STANDARD})`

**Comment by sewenew** [comment]
@paceholder

Thanks for pointing it out! I'll do some research on it, and fix the problem ASAP.

Regards

**Comment by paceholder** [comment]
No problem, thanks for the library!

The problem is quite subtle, the lines with `__has_include(string_view)` seemed to work correctly (because the files are there) but the compiler has refused to use the c++17 featues. So, the replacing library's StringView and Optional classes kicked in.

**Comment by sewenew** [comment]
@paceholder The latest code has fixed this problem by explicitly specifying */std:c++17* when compiling on Windows. I've tested the code with Visual Studio 2019, and you can have a try.

Regards
