### ISSUE TITLE
Smart routing in Redis cluster

### ISSUE THREAD

**Issue by 0ersted** [sewenew/redis-plus-plus#251]
Hello,

First of all, thanks for the nice-written client @sewenew !

I am using Redis stream function on a Redis cluster. And I want to write messages to many streams distributed among the cluster in a short time window. It requires low latency.

As you mentioned in the doc, `RedisCluster` has a slot-node mapping, and sends command directly to the right node. So in my understanding, if I have enough connection pool size `ConnectionPoolOptions.size`, say greater than the number of nodes in the cluster, the speed should be as fast as if I am working on a single Redis. However, it just does not happen in my case and it is slow.

And I also write some code with many `RedisCluster`s that each one connects to a  stream with pool size 1 (single connection). Under this setting, I reach almost the same speed in the benchmark by Redis. Therefore, your implementation should be good enough for the single connection case. I guess that in the connection pool case, the client has spent some time to handle redirection.

I can't find any reason as I even look at the source code on `ShardsPool`. Is it possible to achieve what I want for the connection pool? Thanks!

**Comment by sewenew** [comment]
Can you show me the code that you used for a single `RedisCluster`, and code for multiple `RedisCluster`s? Did you work in multiple threads? If you do, do these threads share a single `RedisCluster` object? Or each thread owns a different `RedisCluster`?

Sorry for the late reply. I was working for the latest release.

Regards

**Comment by 0ersted** [comment]
Thanks for the reply. I use single thread for a single `RedisCluster` and multi threads for `RedisCluster`s. Both of them receive tens of thousands messages. Each message is of the size 1K. And in the multi-thread setting, each thread has its own `RedisCluster`. The number of threads is the number of streams. However, the difference of the speed is not proportional to the number of threads. I only used several threads up to 10 and the multi-thread `RedisCluster`s implementation is faster than 100 times.

Code sketch for a single `RedisCluster`
```c++
ConnectionOptions conn_options;   
// my conn_options configuration
ConnectionPoolOptions conn_pool_options;
conn_pool_options.size = 12;
auto redis = RedisCluster(conn_options, conn_pool_options);

using Attrs = std::vector<std::pair<std::string, std::string>>;
using Item = std::pair<std::string, Attrs>;
using ItemStream = std::vector<Item>;

auto start = std::chrono::system_clock::now();
for (int i = 0; i < msg_cnt; i++) {
    std::unordered_map<std::string, ItemStream> result;
    const int stream_idx = i % num_stream;

    redis.xreadgroup(group_name, consumer, stream_names[stream_idx], ">",
        std::chrono::milliseconds(2 * 1000), 1, false, std::inserter(result, result.end()));

    auto time_str = timestamp();
    if (result.empty()) {
          // error handling
    } else {
            // record the time 
    }
}
```

Code sketch for `RedisCluster`s:
```c++
for (int stream_idx = 0; stream_idx < num_stream; stream_idx++) {
    threads.emplace_back([&fout, &conn_options, &pool, num_stream, msg_cnt, stream_idx]
      (std::string stream_name, std::string group_name, std::string consumer) {
          try {
              auto redis = RedisCluster(conn_options);

              using Attrs = std::vector<std::pair<std::string, std::string>>;
              using Item = std::pair<std::string, Attrs>;
              using ItemStream = std::vector<Item>;

              for (int i = 0; i < msg_cnt; i++) {
                  if (i % num_stream != stream_idx) {
                      continue;
                  }

                  std::unordered_map<std::string, ItemStream> result;
                  redis.xreadgroup(group_name, consumer, stream_name, ">",
                          std::chrono::milliseconds(2 * 1000),  1, false, std::inserter(result, result.end()));

                  auto time_str = timestamp();
                  if (result.empty()) {
                           // error handling
                  } else {
                           // record the time
                  }
              }
          } catch (const Error &e) {
              // Error handling.
              std::cout << "get error: " << e.what() << std::endl;
          }
    }, stream_names[stream_idx], group_name, consumer);
}
```

I believe the code above demonstrates well of my case. Thanks!

**Comment by sewenew** [comment]
The multiple `RedisCluster`s version is faster, because you runs the code in multiple threads, and it has nothing to do with the *smart routing*. Since the operation is blocking, multiple threads will be much faster than single thread.

`RedisCluster` is thread-safe, so you can share a single `RedisCluster` in multiple threads, and each thread `xreadgroup` a dedicated stream. It should has almost the same performance as the multiple `RedisCluster`s version (the `RedisCluster` is protected with a lock), and be much faster than the original single `RedisCluster` version.

```
ConnectionOptions conn_options;   
// my conn_options configuration
ConnectionPoolOptions conn_pool_options;
conn_pool_options.size = 12;
auto redis = RedisCluster(conn_options, conn_pool_options);

for (int stream_idx = 0; stream_idx < num_stream; stream_idx++) {
    threads.emplace_back([&redis, &fout, &conn_options, &pool, num_stream, msg_cnt, stream_idx]    /// <---- capture RedisCluster
      (std::string stream_name, std::string group_name, std::string consumer) {
          try {
              //auto redis = RedisCluster(conn_options);    // <----     no need to create RedisCluster for each thread.

             // other code

            redis.xreadgroup(group_name, consumer, stream_name, ">",
                          std::chrono::milliseconds(2 * 1000),  1, false, std::inserter(result, result.end()));       // <---- share the RedisCluster, which is thread safe.

            // other code
}
```

Regards

**Comment by 0ersted** [comment]
Thanks for the reply. It works! I tried single `RedisCluster` in multi threads before I found the connection pool size parameter. So I did not think of this way. Anyway, thank you again and I will close the issue.
