### ISSUE TITLE
Subscriber support for async interface

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#252]

**Comment by thofaict** [comment]
Hi Sewenew

Thanks for providing your Redis C++ client. It's very helpful and clean.
I have, however, a question with regard to the `Subscriber` support for async interface. As indicated in your documentation, a `Subscriber` object is created, after which callback functions and subscriptions to specific channels can be added. Finally, a _consume_ loop can be started, which actively polls for messages. I noticed that once this consume loop has started, it's no longer possible change subscriptions or callbacks. For example: adding a new channel to subscribe to. I.e. the `Subscriber` object does not respond to changes made in another thread. There is a statement with regard to thread safety of `Subscriber` in your documentation, but I'm not sure if this use case is inconvenient behaviour.
What I was wondering: will the async interface solve this problem? After having started the `Subscriber` consume loop, will it be possible to change subscriptions, callbacks etc.?

Thanks for your answer!
Thomas

**Comment by sewenew** [comment]
> it's no longer possible change subscriptions or callbacks. 

In fact, you can change the subscription and callbacks after consuming the message. Normally we do these changes based on the messages we received. Take the following code as an example:

```
auto sub = redis.subscriber();
sub.on_message([&sub](std::string channel, std::string msg) {
                cout << "set on_message before consuming, channel: " << channel << ", msg: " << msg << endl;
                if (msg == "on_message") {
                    sub.on_message([](std::string channel, std::string msg) {
                            cout << "set on_message after consuming" << endl;
                    });
                } else if (msg == "channel") {
                    sub.subscribe("second-channel");
                }
            });
sub.subscribe("first-channel");
```

If you want to do the change in another thread and the change has nothing to do with the received message, you can do the change in the consume loop, and need to do the thread synchronization manually. Also don't forget to set a `socket_timeout` for the `Subscriber`. Take the following as an example:

```
atomic<bool> should_change_subscription{false};
atomic<bool> should_change_channel{false};

void do_change_if_needed(Subscriber &sub) {
    if (should_change_subscription) {   
        sub.on_message(new_callback);
    }
    if (should_change_channel) {
        sub.subscribe("new-channel");
    }
}

// in one thread.
ConnectionOptions opts;
opts.host = "127.0.0.1";
opts.port = 6379;
opts.socket_timeout = chrono::milliseconds(100);

auto redis = Redis(opts);
auto sub = redis.subscriber();
sub.on_message(old_callback);

sub.subscribe("old_channel");

while (true) {
    try {
        sub.consume();
        do_change_if_needed(sub);       // <------ check if we need to do the change after a successful consume.
    } catch (const TimeoutError &e) {
        do_change_if_needed(sub);      // <------ check if we need to do the change when timeout.
    } catch (const Error &e) {
        // handle error
    }
}

// in another thread
should_change_subscription = true;
should_change_channel = true;
```

Regards

**Comment by sewenew** [comment]
Async support for pubsub is done with [this commit](https://github.com/sewenew/redis-plus-plus/commit/68d5db92fb731539a5e323c417227413d002fdcc)

Regards
