### ISSUE TITLE
Pipeline is invalid when command throws ReplyError

### ISSUE THREAD

**Issue by awilner** [sewenew/redis-plus-plus#254]
The documentation states:

> "If any of Pipeline's method throws an exception other than ReplyError, the Pipeline object enters an invalid state. You CANNOT use it any more, but only destroy the object, and create a new one."

Actually, since PipelineImpl::exec() does not handle any ReplyError exception thrown by
```c++
if (reply::is_error(*reply)) {
    throw_error(*reply);
}
```
inside Connection::recv(), the exception is caught in QueuedRedis\<Impl\>::exec(), and as a consequence the replies cannot be retrieved anymore, and the pipeline is invalidated.

I believe the easiest way to fix this is by changing PipelineImpl::exec to something like:
```c++
std::vector<ReplyUPtr> replies;
while (cmd_num > 0) {
    try
    {
        replies.push_back(connection.recv());
    }
    catch (ReplyError& e)
    {
        redisReply* reply = new redisReply();
        memset(reply, 0, sizeof(reply));
        reply->type = REDIS_REPLY_ERROR;
        reply->len = strlen(e.what());
        reply->str = new char[reply->len + 1];
        strcpy(reply->str, e.what());
        replies.push_back(ReplyUPtr(reply));
    }
    --cmd_num;
}

return replies;
```
I'm not sure if the code above would generate any memory leaks, so adjust accordingly to correctly free all memory.

**Comment by sewenew** [comment]
Yes, that's bug. Your solution has a problem: the redisReply::str is allocated by `new`, but will be released with `free` (by hiredis). The behavior is undefined.

I've fixed the problem, and throw ReplyError when user tries to call `QueuedReply::get`. Please check the latest code on dev branch to have a try.

Not sure if throwing exception when calling `QueuedReply::get` is the best solution. If you have better suggestion, feel free to let me know.

Regards

**Comment by sewenew** [comment]
The code has been merged into master. I'll close this issue.

Regards
