### ISSUE TITLE
TLS compile error 

### ISSUE THREAD

**Issue by copycd** [sewenew/redis-plus-plus#257]
It is not happened.
auto redis1 = sw::redis::Redis(url);

but that code is happened error below.
sw::redis::Redis* redis1 = new sw::redis::Redis(url);

1>  CmRedisManager.obj : error LNK2019: unresolved external symbol redisFreeSSLContext referenced in function "public: void __cdecl sw::redis::tls::TlsContextDeleter::operator()(struct redisSSLContext *)const " (??RTlsContextDeleter@tls@redis@sw@@QEBAXPEAUredisSSLContext@@@Z)
1>  bin\x86_64\Debug\cm.xatlas_uvmesh.exe : fatal error LNK1120: 1 unresolved externals

I wish to control redis variable as member variable of my class for reusing.
please help me~~

**Comment by copycd** [comment]
> It is not happened.
> auto redis1 = sw::redis::Redis(url);
> 
> but that code is happened error below.
> sw::redis::Redis* redis1 = new sw::redis::Redis(url);
> 
> 1> CmRedisManager.obj : error LNK2019: unresolved external symbol redisFreeSSLContext referenced in function "public: void __cdecl sw::redis::tls::TlsContextDeleter::operator()(struct redisSSLContext *)const " (??RTlsContextDeleter@tls@redis@sw@@QEBAXPEAUredisSSLContext@@@z)
> 1> bin\x86_64\Debug\cm.xatlas_uvmesh.exe : fatal error LNK1120: 1 unresolved externals
> 
> I wish to control redis variable as member variable of my class for reusing.
> please help me~~


I have resolved.
I am including that file.
..\..\lib\redis\include\sw\redis++\tls   ->  ..\..\lib\redis\include\sw\redis++\no_tls

good~~

**Comment by sewenew** [comment]
The install command should copy the correct TLS related headers to the installation path. Anyway, I'm glad that you solved it!

Regards

**Comment by JaservTECH** [comment]
Got problem to on windows have anything clue? 
![image](https://github.com/sewenew/redis-plus-plus/assets/18694628/c670e68b-0c3b-458f-aace-4123b2dd7eff)

**Comment by sewenew** [comment]
@JaservTECH Looks like you didn't link hiredis and redis-plus-plus correctly.

Regards
