### ISSUE TITLE
AsyncRedisCluster: update slot mapping when the connection is down

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#262]
When connection is down, we also need to update the slot mapping. Because the corresponding master might been replace with a new one.

**Comment by zhangjie0125** [comment]
@sewenew 

I meet a similiar issue.
My redis cluster servers need to be upgraded OS (CentOS7 -> Redhat8)

redis cluster server upgrade OS steps:
1. stop one master node redis processes (in this step, role change should happen, there is a new redis master node at once)
2. upgrade that master node OS
3. run redis services and change it back to master node

But my client always get "Connection refused" exception, seems redis-plus-plus always try to reconnect to old master node

Environment:

* OS: CentOS7
* Compiler: g++4.8
* hiredis version: v1.2.0
* redis-plus-plus version: 1.3.11

So when will you add this feature?

**Comment by sewenew** [comment]
@zhangjie0125 With #595 fix, redis-plus-plus updates the slot-node mapping every `ClusterOptions::slot_map_refresh_interval` (by default, it updates every 10 seconds). Your problem should be solved with the latest code on master branch.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue. If you still have problem with it, feel free to reopen it.

Regards
