### ISSUE TITLE
pub sub not all published messages are handled by subscription

### ISSUE THREAD

**Issue by orennitzan** [sewenew/redis-plus-plus#263]
Regular code... 
Publish many consumed in on_message much less. and every time different number.
 have no cue from where to start debugging that.
checked channels, published a simple message.
Any idea?

**Comment by sewenew** [comment]
Can you show me your code that can reproduce the problem? Both consumer and publisher. Also include connection options you set.

What’s the version of redis++ and hiredis?

Regards

**Comment by sewenew** [comment]
Since there's no update on this issue. I'll close it. If you still have problems, feel free to reopen it.

Regards
