### ISSUE TITLE
Add QueuedReplies default constructor

### ISSUE THREAD

**Issue by EricGustin** [sewenew/redis-plus-plus#264]
I want to call `Pipeline::exec` inside of a try/catch block but need the returned `QueuedReplies` object to persist after the execution of the try/catch block. This desired persistence of the `QueuedReplies` object could be achieved by declaring a default constructor for `QueuedReplies`.

For example, the desired functionality would allow for the following scenario:

```c++
QueuedReplies replies; // use default constructor outside of try/catch block so that it persists
try {
    replies = my_pipeline.exec();
} catch (...) {
    throw;
}
// do stuff with replies
// ...
```

I look forward to hearing how you intended for this object to be used within a try/catch block. Also, I am willing to put up the PR for this as it is a simple addition.

Best.

**Comment by sewenew** [comment]
In your example, since you just catch the exception, and throw it, you don’t need to put the exec in a try-catch block.

```
auto replies = pipe.exec();  // it might throw

// if it does not throw do stuff with reply here
```

Not sure if I understand correctly?

Regards

**Comment by EricGustin** [comment]
The example provided above was just the simplest example of something that cannot be compiled. In general, the project that I am working on needs to be able to do more complicated things inside of the catch block. Hopefully that helps clear things up. Thanks.

**Comment by EricGustin** [comment]
The example provided above was just the simplest example of something that cannot be compiled. In general, the project that I am working on needs to be able to do more complicated things inside of the catch block. Hopefully that helps clear things up. Thanks.

**Comment by sewenew** [comment]
Normally, the problem can be solved by anther layer of indirection.

However, I have to admit that in some situation, you might not be able to use exception, e.g. Google's coding style, and that might be a problem.

Anyway, I've added a default constructor for `QueuedReplies`. You can try the latest code on mater branch.

Regards

**Comment by EricGustin** [comment]
Thanks so much @sewenew
