### ISSUE TITLE
AsyncRedisCluster::rank or AsyncRedisCluster::zrank

### ISSUE THREAD

**Issue by Hanshanhu** [sewenew/redis-plus-plus#267]
Hi，it seems that there's a mistake about "zrank" command in the async redis cluster version, where we get the "rank" interface and    the wrong "RANK" command sent to the redis server.

**Comment by sewenew** [comment]
Yes, that's a stupid bug... It should be `zrank`. Sorry for the inconvenience. I've fixed the code. Please try the latest code on master branch.

Regards
