### ISSUE TITLE
how to send a bgrewriteaof command to redis server using redis-plus-plus client?

### ISSUE THREAD

**Issue by vvvvjvvvv** [sewenew/redis-plus-plus#270]

**Comment by sewenew** [comment]
You can use the [generic interface](https://github.com/sewenew/redis-plus-plus/#generic-command-interface) to send these commands:

```
try {
    auto status = redis.command<std::string>("BGREWRITEAOF");
} catch (const ReplyError &e) {
    // error handle
}
```

Note: `BGREWRITEAOF` might return status reply or error reply. So you need to try to convert the reply to string (`Redis::command<std::string>`), and catch possible error reply (`ReplyError` exception).

Regards
