### ISSUE TITLE
Can not compile with REDIS_PLUS_PLUS_ASYNC_FUTURE

### ISSUE THREAD

**Issue by JindrichD** [sewenew/redis-plus-plus#272]
hi, i wanted to use async with boost::future, so i used REDIS_PLUS_PLUS_ASYNC_FUTURE (i am using boost 1.74) and got following compile errors
```
In file included from /home/jdolezal/src/redis-plus-plus-1.3.1/src/sw/redis++/future/boost/async_utils.h:24,
                 from /home/jdolezal/src/redis-plus-plus-1.3.1/src/sw/redis++/async_connection.h:30,
                 from /home/jdolezal/src/redis-plus-plus-1.3.1/src/sw/redis++/async_connection.cpp:18:
/data/workspace/boost_1_74_0/boost/thread/future.hpp:123:24: error: ‘executor’ was not declared in this scope
     typedef shared_ptr<executor> executor_ptr_type;
```
but when i tried to include future.hpp into some test program, it worked ok.
it turned out that above error is because of the definition of `BOOST_THREAD_PROVIDES_EXECUTORS`
without it i was finally able to compile the rest-plus-plus lib
so i am wondering which boost version you were compiling with so that you did not have any compile errors

**Comment by JindrichD** [comment]
UPDATE:
i was able to compile the code as is with boost 1.62
so my question is what is the BOOST_THREAD_PROVIDES_EXECUTORS for? what it does and would the library work fine if i would not define it?
thanks

**Comment by JindrichD** [comment]
i managed to compile the code by adding `#define BOOST_THREAD_USES_MOVE` in `sw/redis++/future/boost/async_utils.h`
i.e.
```
#define BOOST_THREAD_PROVIDES_FUTURE
#define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION
#define BOOST_THREAD_PROVIDES_EXECUTORS
#define BOOST_THREAD_USES_MOVE
#include <boost/thread/future.hpp>
```
just hoping all will work as expected

**Comment by sewenew** [comment]
Thanks for the info!

> what is the BOOST_THREAD_PROVIDES_EXECUTORS for?

`BOOST_THREAD_PROVIDES_EXECUTORS` is used for running the continuation, i.e. `then` clause, in a thread pool:

```
#include <sw/redis++/async_redis++.h>
#include <boost/thread/executors/basic_thread_pool.hpp>

boost::executors::basic_thread_pool pool(3);
auto fut = redis.get("key").then(pool,
        [](sw::redis::Future<sw::redis::Optional<std::string>> fut) {
            auto val = fut.get();
            if (val) cout << *val << endl;
        });

// Do other things

fut.get();
```

> what it does and would the library work fine if i would not define it?

If you don't define it, and you don't need to use thread pool with continuation, it won't be a problem.

However, it seems that the boost 1.74 doesn't behave like older version. I'll do some research, and might remove this definition from async_utils.h.

Thanks again!

Regards

**Comment by sewenew** [comment]
@JindrichD I've remove the BOOST_THREAD_PROVIDES_EXECUTORS definition from async_utils.h. You can try the latest code on master branch.

If you want to use boost's thread pool, you need to define BOOST_THREAD_PROVIDES_EXECUTORS manually.

Regards.

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue. If you still have problems, feel free to reopen it :)

Regards
