### ISSUE TITLE
cxx_utils.h:32:25: error: 'string_view' in namespace 'std' does not name a type  using StringView = std::string_view;

### ISSUE THREAD

**Issue by cjpurackal** [sewenew/redis-plus-plus#273]
I've successfully built and installed redis-plus-plus. However when i include the header
`#include <sw/redis++/redis++.h>`
in my program, i'm encountering multiple errors like this when making my project:
`/usr/local/include/sw/redis++/cxx_utils.h:32:25: error: 'string_view' in namespace 'std' does not name a type
 using StringView = std::string_view;
                         ^~~~~~~~~~~
/usr/local/include/sw/redis++/cxx_utils.h:35:23: error: 'optional' in namespace 'std' does not name a template type
 using Optional = std::optional<T>;
                       ^~~~~~~~
/usr/local/include/sw/redis++/cxx_utils.h:38:22: error: 'variant' in namespace 'std' does not name a template type
 using Variant = std::variant<Args...>;
                      ^~~~~~~
/usr/local/include/sw/redis++/cxx_utils.h:40:24: error: 'monostate' in namespace 'std' does not name a type
 using Monostate = std::monostate;
                        ^~~~~~~~~
In file included from /usr/local/include/sw/redis++/reply.h:28:0,
                 from /usr/local/include/sw/redis++/connection.h:29,
                 from /usr/local/include/sw/redis++/connection_pool.h:26,
                 from /usr/local/include/sw/redis++/redis.h:25,
                 from /usr/local/include/sw/redis++/redis++.h:20,
                 from /home/developer/legocv/node_pool/klg_reader/main.cpp:2:
/usr/local/include/sw/redis++/utils.h:29:24: error: 'Optional' does not name a type; did you mean 'optind'?
 using OptionalString = Optional<std::string>;
                        ^~~~~~~~
                        optind
/usr/local/include/sw/redis++/utils.h:31:26: error: 'Optional' does not name a type; did you mean 'optind'?
 using OptionalLongLong = Optional<long long>;
                          ^~~~~~~~
                          optind
/usr/local/include/sw/redis++/utils.h:33:24: error: 'Optional' does not name a type; did you mean 'optind'?
 using OptionalDouble = Optional<double>;
                        ^~~~~~~~
                        optind
/usr/local/include/sw/redis++/utils.h:35:28: error: 'Optional' does not name a type; did you mean 'optind'?
 using OptionalStringPair = Optional<std::pair<std::string, std::string>>;
                            ^~~~~~~~
                            optind
/usr/local/include/sw/redis++/utils.h:79:71: error: 'StringView' was not declared in this scope
             : std::integral_constant<bool, !std::is_convertible<Iter, StringView>::value> {};
`
 
GCC version : 7.4
ubuntu 18.04 (docker)

**Comment by sewenew** [comment]
By default, redis-plus-plus is built with c++17. However, it seems that you built your application with c++11. In order to solve the problem, you can add -std=c++17 flag when you build your application code.

Regards
