### ISSUE TITLE
 The undefined symbol error is emitted for both  `set(..)`  and `get(..)` on redis object.

### ISSUE THREAD

**Issue by meghadriG** [sewenew/redis-plus-plus#274]
This might be related. Haven't been able to solve it yet.  
Compiler: clang 12, 
build platform Win10, 
cmake v3.21.0, vcpkg toolchain used.

**Error:** 
`lld-link: error: undefined symbol: public: bool __cdecl sw::redis::Redis::set(class std::basic_string_view<char, struct std::char_traits<char>> const &, class std::basic_string_view<char, struct std::char_traits<char>> const &, class std::chrono::duration<__int64, struct std::ratio<1, 1000>> const &, enum sw::redis::UpdateType)`

**Relevant Lines from CMakeLists.txt:**
`find_package(hiredis CONFIG REQUIRED)`
`find_package(redis++ CONFIG REQUIRED)`
`....`
`target_link_libraries(${PROJECT_NAME} PRIVATE hiredis::hiredis redis++::redis++)`

**Code**
The basic sample in redis++

`#include <sw/redis++/redis++.h>`
`...`
`sw::redis::Redis r("tcp://127.0.01:6379");`
`r.set("foo", "val");`
`auto v = r.get("foo"); `

The undefined symbol error is emitted for both  `set(..)`  and `get(..)`

**Comment by sewenew** [comment]
This might be a duplicate issue with #273 

Please ensure that redis-plus-plus and your application code are built with the same C++ standard.

Regards

**Comment by meghadriG** [comment]
CMAKE_CXX_STANDARD is set to 17 in the cmake.

Declaring a string_view variable in my test code does not result in a compilation error.

**Comment by sewenew** [comment]
@meghadriG It seems that vcpkg haven't update the code to the latest release. So the code installed by vcpkg still build the redis-plus-plus with C++ 11 by default. In order to fix this problem, you should rebuild redis-plus-plus with C++17 standard (not sure if there's an option for Vcpkg to choose C++ standard, also I recommend you to build the latest code) or build your application code with c++ 11 standard.

Regards

**Comment by meghadriG** [comment]
That does not seem to be the cause - I installed the cxx17 variant. Additionally using the VS compiler kit (in VSCode) and C++17 does not result in the link error. For now I'll go with this due to some deadlines. Will investigate further when time permits and post any useful information that may result. Thanks.
