### ISSUE TITLE
How can I send binary data to a stream by xadd?

### ISSUE THREAD

**Issue by ZhouZhaoJi** [sewenew/redis-plus-plus#275]

**Comment by wingunder** [comment]
Hi @ZhouZhaoJi,

@sewenew covered a similar case for `SET` in the following issue:
https://github.com/sewenew/redis-plus-plus/issues/208#issuecomment-821276609

In the top-level [README.md](https://github.com/sewenew/redis-plus-plus/#readme)
You'll find the following example:

``` c++
using Attrs = std::vector<std::pair<std::string, std::string>>;
Attrs attrs = { {"f1", "v1"}, {"f2", "v2"} };

// Add an item into the stream. This method returns the auto generated id.
auto id = redis.xadd("key", "*", attrs.begin(), attrs.end());
```
Combining the above, you should get to something like:
``` c++
uint8_t *your_data;
size_t your_data_len;

const std::string bin_data= "bin_data";
using Attrs = std::vector<std::pair<std::string, std::string>>;
Attrs attrs = { {bin_data, std::string(reinterpret_cast<const char *>(your_data), your_data_len)} };
const std::string key = "stream";
// xadd binary data
auto id = redis.xadd(key, "*", attrs.begin(), attrs.end());
```
Alternatively, you could also look at the [code for the stream test cases](https://github.com/sewenew/redis-plus-plus/blob/master/test/src/sw/redis%2B%2B/stream_cmds_test.hpp).

Regards

**Comment by ZhouZhaoJi** [comment]
I get it. Thank you for your answer.

**Comment by KOOKDONGHUN** [comment]
then how to read stream?

**Comment by sewenew** [comment]
@KOOKDONGHUN You can use `xread` or `xreadgroup`. Take a look at the [doc](https://redis.io/commands/xread/) for detail.

Regards

**Comment by KOOKDONGHUN** [comment]
> @KOOKDONGHUN You can use `xread` or `xreadgroup`. Take a look at the [doc](https://redis.io/commands/xread/) for detail.
> 
> Regards

Thx!
