### ISSUE TITLE
Attach method to disconnection 

### ISSUE THREAD

**Issue by picanumber** [sewenew/redis-plus-plus#276]
Is there a concise way to attach a method to disconnection events?

I want to react to disconnection events, since I have subscribers that may lose messages when the server is down. Is there an easy way to do this? If not, does the `consume` method of a subscriber create a specialized exception for such cases?

**Comment by wingunder** [comment]
Hi @picanumber,

The following code could be the clue that you're looking for:
https://github.com/sewenew/redis-plus-plus/blob/e29c63db54653a660d7a0f556f670b7a6fce0a78/src/sw/redis%2B%2B/subscriber.cpp#L76-L85

and

https://github.com/sewenew/redis-plus-plus/blob/e29c63db54653a660d7a0f556f670b7a6fce0a78/src/sw/redis%2B%2B/subscriber.cpp#L130-L134

You can also just periodically `ping` a Redis server in a different thread. This is crude, but will work.
Would it not be better to use Redis Streams if you are concerned of losing messages?

Regards

**Comment by picanumber** [comment]
Ok so it's clear that `consume` will throw a dedicated error. I can verify from my tests cases as well. I'm closing the issue, will take a look at streams too.
