### ISSUE TITLE
Why is script_load(), script_exists(), script_flush() and script_kill() not available in RedisCluster?

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#28]
Given a Redis cluster, one could load a script into a Redis cluster node, using:

`$ redis-cli -c -h 127.0.0.1 -p 7000 SCRIPT LOAD "return redis.call(\"PING\")"`
`"dc9acaa27306c368e1f1eb390e9b0dc9ec7314ee"`

`$ redis-cli -c -h 127.0.0.1 -p 7000 SCRIPT EXISTS dc9acaa27306c368e1f1eb390e9b0dc9ec7314ee`
`1) (integer) 1`

This command loads the script _only_ into the  127.0.0.1:7000 node and unless explicitly loaded into all other cluster nodes, none of the rest of the cluster nodes will have this script. So, if one connects to the 127.0.0.1:7001 node, in the same cluster, the loaded script won't exist, as it wasn't loaded to that node yet:

`$ redis-cli -c -h 127.0.0.1 -p 7001 SCRIPT EXISTS dc9acaa27306c368e1f1eb390e9b0dc9ec7314ee`
`1) (integer) 0`

All of this seems to be expected/designed redis-cli behavior and it seems to be the user's problem to get the script over to the other cluster nodes, if needed. Obviously the user might be in trouble if the client loaded a script onto the connected node and reconnects, possibly to another node. In this case, the script will not be in the Redis cache. With redis-cli, the user is expected to work around this  problem at the moment.

The script_exists(), script_flush() and script_kill() functions also _only_ operate on the connected node, when using redis-cli.

Would you agree that, at the moment, there is no reason not to allow script_load(), script_exists(), script_flush() and script_kill() to be available in RedisCluster, as long as we mimic the behavior of redis-cli?

To implement the above is probably straight forward.

One could of course also go the long, slow and complicated way and ensure that RedisCluster::script_load(), RedisCluster::script_exists(), RedisCluster::script_flush() and RedisCluster::script_kill() operate on all cluster nodes.

Eg: RedisCluster::script_load() could load a script into _all_ cluster nodes like this:
   1. Use the `CLUSTER SLOTS` command in order to get all the cluster nodes, as was originally posted by @sewenew in https://github.com/sewenew/redis-plus-plus/issues/17#issuecomment-516441521.
   2. For each cluster node:
      1. establish a connection, using the Redis class constructor (_not_ RedisCluster).
      2. load the script, using Redis::script_load()

I am not in favor of the last method, as operating on a script on all nodes will be impossible if some nodes are down. It will be better to simply just operate on scripts of the current connected node and let it up to the user to worry about the script calls on other cluster nodes.

**Comment by sewenew** [comment]
Hi @wingunder ,

In fact, there's a better way to send `script_xxx` command to Redis Cluster. You can create a `Redis` object with the `Redis RedisCluster::redis(const StringView &hash_tag)` method. And send these `script_xxx` command with this `Redis` object.

There's no need to get all cluster nodes. Instead, with the `hash_tag` parameter, you can specify to which node the command should be sent. If you want to send the command to a random node, just give some random string as the `hash_tag` parameter. You can check the [doc](https://github.com/sewenew/redis-plus-plus#interfaces) for detail.

Normally, this method should solve most problems. However, If you still have some special case, feel free to let me know :)

Regards

**Comment by wingunder** [comment]
Hi @sewenew,
Excellent, thanks for your help. I'm sure your suggested solution will work for me.
Regards

**Comment by wingunder** [comment]
Hi @sewenew,
Thanks your suggestion works for me. 
I'm closing this issue.
Regards
