### ISSUE TITLE
XINFO GROUPS will crash

### ISSUE THREAD

**Issue by Sola1Go** [sewenew/redis-plus-plus#287]
**Unable to parse XINFO**
XINFO method is not supported yet, and some difficulties have been encountered in parsing it for me.
```c++
auto res = redis->command<std::vector<std::vector<OptionalStringPair>>>("xinfo", "groups", "group_name");
```
I got: terminate called after throwing an instance of 'sw::redis::ProtoError'
  `what():  Expect ARRAY reply`
```c++
auto res = redis->command<std::vector<std::vector<OptionalString>>>("xinfo", "groups", "group_name");
```
I got: terminate called after throwing an instance of 'sw::redis::ProtoError'
 ` what():  Expect STRING reply`
And `Expect STRING reply` means that the type indicated in `redis.command<>` is expected a `string` instead of the correct return is expected to be `string`?

**Environment:**
 - OS: NixOS
 - Compiler: clang 11.1.0
 - hiredis version: 1.0.0 master
 - redis-plus-plus version: 1.3.1 master

**By the way**
Is there a better way to judge whether a group/consumer exists?
Regards

**Comment by Sola1Go** [comment]
Starting with Redis version 7.0.0, returns of the command `XINFO GROUPS` have been enhanced with entries `entries-read` and `lag`.
These two keys are certain to be present in returns, but their values might be `NULL`.

```
// code:
using XInfoRes = std::vector<std::unordered_map<std::string, std::variant<long long, std::string>>>;

auto res = redis->command<XInfoRes>("xinfo", "groups", "group_name");

// crash:
// terminate called after throwing an instance of 'sw::redis::ParseError'
// what():  expect STRING or STATUS or VERB or BIGNUM reply, but got NULL reply
```

**Comment by sewenew** [comment]
If the value of `entries-read` and `lag` might be null, you can add `optional<long long>` to the `std::variant` definition:

```
using XInfoRes = std::vector<std::unordered_map<std::string, std::variant<long long, std::string, std::optional<long long>>>>;
```

You can try the above code, and if you still get problem, feel free to let me know.

Regards

**Comment by Sola1Go** [comment]
thx again ~
Regards
