### ISSUE TITLE
subscriber::consume and web server in main thread.

### ISSUE THREAD

**Issue by BFamzz** [sewenew/redis-plus-plus#289]
How can I manage a web server and subscriber::consume on the same thread?

The web server typically blocks the main thread and listens for connections until the server is stopped. However, the application need to subscribe to Redis channel(s) to receive and disperse messages accordingly.

How can this be achieved?

Will subscriber::consume method be called in another thread? Because using a while (true) loops blocks the main thread too.

Please help.

Thanks.

**Comment by sewenew** [comment]
Yes, you need to run the consume loop in another thread.

Regards

**Comment by BFamzz** [comment]
Thanks for your swift response @sewenew

A quick follow up question. Is calling the consume loop in another thread thread-safe?

Thanks.

**Comment by sewenew** [comment]
The `Subscriber` class is not thread safe. So you need to ensure that there's only one thread calling `Subscriber::consume` in the loop. In your case, the main thread should not call any method on the `Subscriber`.

Regards

**Comment by BFamzz** [comment]
Hello @sewenew 

I encountered a small problem. I setup the webserver and subscriber as described in a multi-threaded fashion. However, the subscriber does not fire the on_message callback for the first published message to the channel but subsequent messages are consumed and the on_message callback is fired.

I have created a docker image for the application [bfamz/redis-sw](https://hub.docker.com/repository/docker/bfamz/redis-sw) and a github repo [redis-sw](https://github.com/BFamzz/redis-sw) for the code, dockerfile and docker-compose files.

Thanks.

**Comment by sewenew** [comment]
> Can the message callback functions be attached to the Subscriber object (since this is done only once) before spawning the worker thread to call Subscriber::consume?

Yes

> I encountered a small problem.

Your code is not thread safe. Since you do not protect the `Subscriber::consume` with the lock, while the main thread might call `Subscriber::subscribe` method in parallel.

You need to do thread synchronization between these two threads.
Regards
