### ISSUE TITLE
*** stack smashing detected ***

### ISSUE THREAD

**Issue by TannedCung** [sewenew/redis-plus-plus#290]
**Describe the bug**
I made a simple script to connect to Redis but it showed
```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
``` 
The Script is as simple as below:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>
#include <vector>

using namespace sw::redis;

int main (){
    try {
        auto redis = Redis("tcp://127.0.0.1:6379");
        std::cout << "Redis connected \n";
        auto res = redis.hset("atest", std::make_pair("field", "val"));
        std::cout << "hset: pass\n" ;

        std::unordered_map<std::string, std::string> items;
        redis.hgetall("atest", std::inserter(items, items.end()));

        for(auto & u: items){
            std::cout << u.first << " - " << u.second << std::endl; 
        }
   } catch (const Error &e) {
        std::cout << "caught an err: " << e.what() << std::endl;
        // Error handling.
    }
    return 1;
}
```
The weird thing is that i print a line to notice that if `hset()` was successfully operated, it does print out in case i comment `hgetall()`, but does not otherwise. RDM shows new set hash only when `hset()` without `hgetall()`.

**To Reproduce**
I ​used this command to  compile:  `g++ std=c++14 -o app test_redis.cpp -lredis++ -lhiredis -pthread`
while installing redis++,  `test_redis++` shows `Pass all tests`

*Expected behavior**

**Environment:** ​
- OS: ubuntu
- Compiler: g++ 7.5.0
- hiredis version: master
​- redis-plus-plus version: 1.3.0

**Additional context**
Add any other context about the problem here

Thank you for your help!!!

**Comment by sewenew** [comment]
@TannedCung The code looks good to me, and I cannot reproduce the problem.

Please check if you installed multiple version of hiredis, e.g. your system might already install hiredis by `apt-get`. If that's your case, you might get some wired problem, and you need to uninstall unused versions of hiredis. Ensure there's only 1 version of hiredis installed.

Regards

**Comment by TannedCung** [comment]
You are right, the problem could be from `hiredis`, as what  found, my environment has installed only 1 `hiredis` version, so i start again with a new docker, using `hiredis` from `apt-get`, things work. However, i need to use `SSL` support which is not available from `apt-get` (adding `-DREDIS_PLUS_PLUS_USE_TLS=ON` makes cmake return `CMake Error: The following variables are used in this project, but they are set to NOTFOUND`). Could you explain me how to build `hiredis` from source. i have tried some workarounds (both using Makefile as explained in your README and Cmake), but `redis++` just pass `test_redis++` but failed with my script.
Thank you!!!

**Comment by sewenew** [comment]
You can start with a new docker image without installing hiredis with apt-get. Then follow [the instruction](https://github.com/sewenew/redis-plus-plus/#enable-tlsssl-support) to enable SSL support for hiredis (`USE_SSL=1`) and redis-plus-plus (`-DREDIS_PLUS_PLUS_USE_TLS=ON`).

NOTE: you might also need to specify `-DCMAKE_PREFIX_PATH=/path/to/hiredis`. Check the [doc](https://github.com/sewenew/redis-plus-plus/#install-redis-plus-plus) for detail. 

Regards

**Comment by TannedCung** [comment]
Thank you @sewenew. You're right, after starting with a brand new docker, everything works. I think the above weird behavior happened because i did not delete Symbolic link when removing previous `hiredis`. Deleling `hiredis` installed file along with its  `Symbolic link` did the trick.
