### ISSUE TITLE
How build redis plus plus for 32bit Application?

### ISSUE THREAD

**Issue by guedesolavio** [sewenew/redis-plus-plus#291]
Hi, i need redis plus plus work on my 32 bit c++ Aplication. How to build to archive that?
I'm not to familiar with cmake, etc.

**Environment:**
 - OS: Ubuntu 20.04(WSL first)
 - Compiler: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - hiredis version: [master] 32 bit build.
 - redis-plus-plus version:1.3.2
Thanks in advance!

**Comment by sewenew** [comment]
First of all, you need to install gcc-multilib and g++-multilib: `sudo apt-get install gcci-multilib g++-multilib`. Then you need to install hiredis in 32bit mode, i.e. `make 32bit`

I created a `32bit` branch, and updated the CMakelists.txt files to make it compile in 32bit mode. You can try it.

Regards

**Comment by guedesolavio** [comment]
Thanks, Works great! Great Job!
