### ISSUE TITLE
async_redis 

### ISSUE THREAD

**Issue by SunnyChenkang** [sewenew/redis-plus-plus#292]
A function for the integral operation is desired

**Comment by sewenew** [comment]
Sorry, but I don't quite understand your problem. What do you mean by *integral operation*? Can you give some detail on the problem that you need to solve?

Regards

**Comment by SunnyChenkang** [comment]
I need to asynchronize on the leaderboard but the interface provided asynchronously is not that comprehensive

**Comment by sewenew** [comment]
Can you give a detailed example of your scenario? Or what do you want the interface look like?

Regards

**Comment by SunnyChenkang** [comment]
![897ec089-31ba-4bc1-86b7-874cb6e899ca](https://user-images.githubusercontent.com/25769651/142114544-299ab6a8-a960-497f-ae16-f4b01879e4f7.png)


The data returned using the zrevrange interface is incorrect       The result of using synchronous or asynchronous is the same

**Comment by SunnyChenkang** [comment]
Please use the data I provided to test

**Comment by wingunder** [comment]
Hi @SunnyChenkang,

I think you need to supply some C++ code. Redis-plus-plus is a C++ library and we can help you by fixing bugs in redis-plus-plus or by adding new functionality and/or interfaces to redis-plus-plus. I don't think that it's the goal of this project to help people implement a specification. The application implementation and integration with redis-plus-plus should be done by you. If you have specific interfacing problems with redis-plus-plus and you can supply a small dedicated piece of C++ code, demonstrating a problem or a need, related to redis-plus-plus, we can consider helping you. I hope you understand.

Regards

**Comment by SunnyChenkang** [comment]
sw::redis::ConnectionOptions opts;
	opts.host = "127.0.0.1";
	opts.port = 6379;
	opts.db = 1;

	sw::redis::ConnectionPoolOptions pool_opts;
	pool_opts.size = 3;
	sw::redis::Redis redis( opts, pool_opts );

	redis.zadd( "rank", "11077", 170 );
	redis.zadd( "rank", "11060", 125 );
	redis.zadd( "rank", "11078", 50 );
	redis.zadd( "rank", "11005", 50 );
	redis.zadd( "rank", "11076", 25 );

	std::unordered_map<std::string, double> zrevrange_result;
	redis.zrevrange("rank", 0, -1, std::inserter( zrevrange_result, zrevrange_result.end() ) );
	for ( auto& elem : zrevrange_result )
	{
		nlwarning( " first : %s second : %f ", elem.first.c_str(), elem.second );
	}

	/*
	Synchronous Asynchronous
	Print result:

	WRN  d14 social_contact_service.cpp   54 CSocialContactService::init:  first : 11060 second : 125.000000
	WRN  d14 social_contact_service.cpp   54 CSocialContactService::init:  first : 11077 second : 170.000000
	WRN  d14 social_contact_service.cpp   54 CSocialContactService::init:  first : 11078 second : 50.000000
	WRN  d14 social_contact_service.cpp   54 CSocialContactService::init:  first : 11005 second : 50.000000
	WRN  d14 social_contact_service.cpp   54 CSocialContactService::init:  first : 11076 second : 25.000000
	*/

**Comment by sewenew** [comment]
@SunnyChenkang The problem is that you saved the results into an `unordered_map` which is unordered. So the returned result lost its original order. The README and code example are misleading, I'll change it. Sorry for the inconvenience!

In order to get the right order, you should save the results into a  vector of (string, double) pair:

```
std::vector<std::pair<std::string, double>> zrevrange_result;
redis.zrevrange("rank", 0, -1, std::back_inserter(zrevrange_result));
```

Also, the async interface does not implement `zrevrange` command, I'll add it this weekend.

Regards

**Comment by SunnyChenkang** [comment]
Thank you

**Comment by sewenew** [comment]
@SunnyChenkang The README and code examples have been fixed.

Regards
