### ISSUE TITLE
Can it use hiredis in a custom directory

### ISSUE THREAD

**Issue by nqf** [sewenew/redis-plus-plus#293]
For some reasons, the old version of hiredis is used in the system directory， But I want to use its asynchronous interface，But the asynchronous interface requires a new hiredis ， 
I hope it can link my own compiled hiredis when compiling， cmake does not seem to provide parameters

**Comment by nqf** [comment]
```
 can it Support this form?
 cmake .. -D REDIS_PLUS_PLUS_BUILD_ASYNC=libuv -DHIREDIS_HEAD_PATH=/xxxxxx/include, -DHIREDIS_LIB_PATH=/xxxx/lib/
```

**Comment by sewenew** [comment]
You can use CMAKE_PREFIX_PATH to specify hiredis installation path:

`cmake -DCMAKE_PREFIX_PATH=/installation/path/to/hiredis -DREDIS_PLUS_PLUS_BUILD_ASYNC=libuv ..`

However, you'd better uninstall the old version of hiredis. There're many users met some wired problems when they installed multiple versions of hiredis. If you cannot uninstall the old version, you'd better statically link to both hiredis and redis-plus-plus. Ensure your application not link to the older version of hiredis.

Regards

**Comment by wingunder** [comment]
Hi @nqf

@sewenew is right. It's really better to have just one lib installation. If you really need a different version of a lib, then link the binaries, that use the other lib version, statically.

There is however a way (at least in most UNIX derivatives), to use a specific lib, if you have more than one installation.

NOTE (WARNING): Don't use the following unless you fully understand what you're doing. It is not the goal to nurse users of redis-plus-plus through the process, and sometimes even agony, of mixing multiple versions of lib installations.

You can set the `LD_LIBRARY_PATH` environment variable, before running your binary:

``` console
$ LD_LIBRARY_PATH=/opt/my_libs_v_001/lib ./my_app
```

``` console
$ LD_LIBRARY_PATH=/opt/my_libs_v_002/lib ./my_app
```

Another trick (at least in most UNIX derivatives) would be to use `ldd` to find out which libs your app will use to run:

``` console
$ export LD_LIBRARY_PATH=/opt/my_libs_v_001/lib
$ ldd ./my_app
```

``` console
$ export LD_LIBRARY_PATH=/opt/my_libs_v_002/lib
$ ldd ./my_app
```

I am not going any deeper into the use of `LD_LIBRARY_PATH` and `ldd`, as there is more than enough material on the web, explaining this. I also have no idea how this works under Windows. The examples above, was for UNIX derivatives like Linux, Solaris, etc. It should also work, when using Cygwin.

Hope this helps.
Regards
