### ISSUE TITLE
g++.exe: error: /std:c++11: No such file or directory

### ISSUE THREAD

**Issue by xkungfu** [sewenew/redis-plus-plus#295]
**Describe the problem**
cmake build error:

```
I:\CXXlibs\REDISPLUSPLUS\redis-plus-plus-20211118\build>cmake .. -G "MinGW Makefiles"


-- redis-plus-plus version: 1.3.2
-- The CXX compiler identification is GNU 8.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: I:/CXXTools/MinGW64/mingw64-810_gcc810/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- redis-plus-plus build type: Release
-- redis-plus-plus build with CXX standard: c++11
CXX_UTILS_DIR: src/sw/redis++/cxx11
-- redis-plus-plus TLS support: OFF
-- redis-plus-plus build static library: ON
-- redis-plus-plus build static library with position independent code: ON
-- redis-plus-plus build shared library: ON
-- redis-plus-plus build test: OFF
-- Debian package name: .deb
-- Configuring done
-- Generating done
-- Build files have been written to: I:/CXXlibs/REDISPLUSPLUS/redis-plus-plus-20211118/build
```

```
I:\CXXlibs\REDISPLUSPLUS\redis-plus-plus-20211118\build>cmake --build .


[  3%] Building CXX object CMakeFiles/redis++_static.dir/src/sw/redis++/command.cpp.obj
g++.exe: error: /std:c++11: No such file or directory
mingw32-make.exe[2]: *** [CMakeFiles\redis++_static.dir\build.make:76: CMakeFiles/redis++_static.dir/src/sw/redis++/command.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:84: CMakeFiles/redis++_static.dir/all] Error 2
mingw32-make.exe: *** [Makefile:155: all] Error 2
```

**Environment:**
 - OS: Windows 10
 - Compiler: mingw64  x86_64-8.1.0-release-win32-seh-rt_v6-rev0
 - hiredis version:  v1.0.2 
 - redis-plus-plus version: redis-plus-plus 1.3.2

**Additional context**

build steps:
1  cd I:\CXXlibs\REDISPLUSPLUS\redis-plus-plus-20211118\build
2  cmake .. -G "MinGW Makefiles"
3  cmake --build .

error occurred at step 3.

and same error on set(REDIS_PLUS_PLUS_DEFAULT_CXX_STANDARD 17) and set(REDIS_PLUS_PLUS_DEFAULT_CXX_STANDARD 14)

how can I do? thanks!

**Comment by sewenew** [comment]
It seems that CMake takes Mingw as Win32, and use `/std:c++11` to specify the C++ standard. I created a new branch, i.e. *mingw*, and fixed the problem. Can you check out the *mingw* branch, and test if it works?

Thanks a lot!

Regards

**Comment by xkungfu** [comment]
thank you very much!
I will try it soon and report!

**Comment by xkungfu** [comment]
I have tried the redis++'s MINGW branch.
since error about std::mutex, I also change MinGW64 to "x86_64-8.1.0-release-posix-seh-rt_v6-rev0".
and at last the rebuild success!

now I am testing some code to let it run. 

thank you for the great work!

**Comment by sewenew** [comment]
@xkungfu, the change has been merged master, you can try the master branch now.

By the way, what's *error about std::mutex*? If that's a problem, I'll fix it.

Regards
