### ISSUE TITLE
[QUESTION] how to share a global connection?

### ISSUE THREAD

**Issue by xkungfu** [sewenew/redis-plus-plus#296]
sorry for the naive question.

how to share connection from different cpp files?

I have tried to set redis as global variable in the global class  but got error:

`default constructor of 'Global' is implicitly deleted because field 'redis' has no default constructor`

(the global class was copied from stackoverflow, and I don't understand it clearly...)

I put redis connection in "main", but I don't know how to use it in another file.

so, 
how to share one connection as a session for many cpp files? define in one file like below：

`auto redis = Redis("tcp://127.0.0.1:6379");`

and keep alive and used by anywhere。

thanks.

**Comment by xkungfu** [comment]
I finally create a class to resole it.
I am not it is right way, but it works!
```

RedisPP::RedisPP() {
   std::cout << "RedisPP Object is being created" << std::endl;
   m_redis = new Redis("tcp://127.0.0.1:6379");
}
RedisPP::~RedisPP() {
   std::cout << "RedisPP Object is being deleted" << std::endl;
}
void RedisPP::setFoovar( double foo ) {
   foovar = foo;
}
double RedisPP::getFoovar( void ) {
   return foovar;
}

void RedisPP::setKV(std::string key, std::string value) {
   m_redis->set("onekey", "hello world!");
}
std::string RedisPP::getKV(std::string key) {
   auto val = m_redis->get("onekey");    // val is of type OptionalString. See 'API Reference' section for details.
   std::string xxx = *val;
   return xxx;
}
```

**Comment by sewenew** [comment]
`Redis` is not copiable, but movable. Also it doesn't have a default constructor.

If you want to have global variable, you can define a `std::shared_ptr<Redis>` object, and initialize it in one cpp file, and use it in other ones.

```
std::shared_ptr<Redis> instance;

void init(const std::string &uri) {
    instance = std::make_shared<Redis>(uri);
}

void set(const std::string &key, const std::string &val) {
    instance->set(key, val);
}
```

Regards

**Comment by xkungfu** [comment]
@sewenew thank you. For I am a newbie to c++, I don't know what is std::shared_ptr now, and I will try to do some search about it .

and can I use my code above temporarily? I don't know it is good or bad but it work well.

**Comment by sewenew** [comment]
The above code has several problems:
1. you did not delete the Redis object, so it has a memory leak.
2. you did not catch possible exceptions throw by redis-plus-plus
3. you did not define a proper copy and move constructors, so you'd better do not copy or move your `RedisPP` object.

In order to solve these problems, you'd better take a look at `std::shared_ptr` :)

Regards

**Comment by xkungfu** [comment]
@sewenew  thank you very much.
I will change to sahred_ptr soon!
