### ISSUE TITLE
[QUESTION] Using redis-plus-plus with cmake

### ISSUE THREAD

**Issue by shreyasrTAMU** [sewenew/redis-plus-plus#297]
Hello, I am trying to use redis-plus-plus with a codebase that uses cmake and make files. I have modified the CMakeLists.txt file with the lines mentioned in the README, however it messes up compiling the project with make.
The CMakeLists file is found at: https://github.com/srsran/srsRAN/blob/master/CMakeLists.txt
and I have added the lines 

```
set(SOURCE_FILES srsenb/src/stack/mac/scheduler_metric.cc)
add_executable(app ${SOURCE_FILES})

find_path(HIREDIS_HEADER hiredis)
target_include_directories(app PUBLIC ${HIREDIS_HEADER})

find_library(HIREDIS_LIB hiredis)
target_link_libraries(app ${HIREDIS_LIB})

find_path(REDIS_PLUS_PLUS_HEADER sw)      # NOTE: this should be *sw* NOT *redis++*
target_include_directories(app PUBLIC ${REDIS_PLUS_PLUS_HEADER})

find_library(REDIS_PLUS_PLUS_LIB redis++)
target_link_libraries(app ${REDIS_PLUS_PLUS_LIB})
```

The scheduler_metric.cc file is where I'd like to use redis. However, after I add these lines it changes the root directory(?) and the header files are not getting included properly when I make compile the project.

Any help or insight would be appreciated! Thanks

**Comment by sewenew** [comment]
These lines should not change the root directory. If you installed hiredis and redis-plus-plus at some non-default location, you need to use `-DCMAKE_PREFIX_PATH` option to specify the installation path, when you run cmake command.

Sorry, but I'm not an expert of CMake. If the above comment does not work, you'd better seek help from stackoverflow with [cmake] tag.

Regards
