### ISSUE TITLE
[QUESTION]batch kv object fetch lattency over 5ms

### ISSUE THREAD

**Issue by hudengjunai** [sewenew/redis-plus-plus#299]
**Describe the problem**
Hi, thank you for excellent work.  I have using this client in my online serving for half years. And I have a problem.
 When I use async_cluster_client to fetch 100 hash object. the wait tail latency above 7ms. the code is like this.
```
auto time_start = chrono_nano_time();
std::vector<string> hash_keys = {"xx1","xx2"....,"xx99"};
std::vector<Future<xxx>> waited_futures;
waited_futures.reserver(100)
for(auto &key : hash_keys){
   auto future = async_cluster_client.hgetall<unordered_map<string, string>>(key);
  waited_future.emplace_back(future); 
}
for(auto& fut : waited_future){
  unordered_map<string, string> sample = fut.get();  //the sample.size() is about 40.
}
auto time_end = chrono_nano_time();
auto duration = time_end - time_start;
```
the duration is not stable.  sometimes  the *duration* would go above 7ms（but mean time is about 2-3ms). so is there any solution to solve this problem? (batch hgetall in redis-cluster mode). Or can you give me more example snippet code to use this client library?

I have test the RedisClusterClient with slot shard and pipeline. but the time also above 5ms. 
My redis-cluster and the client is in same computer-cluster physically.(the network overhead is small).

**Environment:**
 - OS: [e.g. Ubuntu/Centos]
 - Compiler: [e.g. gcc 9.xx]
 - hiredis version: [e.g. v1.0.2#1 master]      cxx17 support  
 - redis-plus-plus [-cxx17 ] version: [e.g. 1.3.0, master, commit b0a42e] //installed by vcpkg, with libuv support.

**Additional context**

**Comment by sewenew** [comment]
The code looks good to me. There might be many possible reasons that cause the high latency. Take the following as example:

- Is your Redis Cluster overloaded? If there're many request to Redis Cluster, especially if there're some slow command running, you might get a higher latency.
- Is the hash very large? If you have many fields or the value size is very large, Redis might become slower, when you try to get all elements in the large hash.
- Did you set `ConnectionPoolOptions::connection_lifetime` or `ConnectionPoolOptions::connection_idle_time`? If you set these options, when the connection has been opened more than connection_lifetime or has been idled more than connection_idle_time, the connection will be closed, and reconnected. In that case, when it reconnect, it might cause higher latency.
- Also I'm not sure if the for loop to get/wait for all pending futures is a problem. Say, if the first request is delayed, other requests won't be processed until the first request is ready. You might need to seek help from a C++ expert to see if this is a possible problem.

Regards

**Comment by hudengjunai** [comment]
> 

Thanks for your reply.  I will check those four conditions that you mentioned above.
