### ISSUE TITLE
Connection reset by peer for Redis Cloud

### ISSUE THREAD

**Issue by shivalikac** [sewenew/redis-plus-plus#300]
Hello,

I am trying to send messages using the redis cloud broker using the redis-plus-plus API. 
I am able to establish the connection, but when i publish messages, i get the error:

terminate called after throwing an instance of 'sw::redis::IoError'
  what():  Failed to get reply: Connection reset by peer

This issue is only on my Redhat machine. I tried connecting via stunnel following [this article](https://datanextsolutions.com/blog/how-to-fix-redis-cli-error-connection-reset-by-peer/). But i am still facing the issue

Can anyone help me understand what the issue is?

Thanks
Shivalika

**Comment by sewenew** [comment]
It seems that Redis server closed the connection. You'd better seek help from redis cloud to see if there's some configuration problem.

Regards
