### ISSUE TITLE
[BUG]AsyncRedisCluster with Role::SLAVE hang forever

### ISSUE THREAD

**Issue by yyweii** [sewenew/redis-plus-plus#301]
**Describe the bug**
I use AsyncRedisCluster  with Role::SLAVE to execute get command. The Future::wait hang forever. But AsyncRedisCluster  with Role::Master and RedisCluster are ok.

**To Reproduce**
`
  try {
    auto fu = slave.get("test-key");
    fu.wait();
    auto val = fu.get();
    if (val) {
      cout << *val << endl;
    } else {
      cout << "not found" << endl;
    }
  } catch (sw::redis::Error &e) {
    cout << e.what() << endl;
  }
`

**Expected behavior**

**Environment:**
 - OS: [ubuntu]
 - Compiler: [g++ 7.5  c++14]
 - hiredis version: [v1.0.2]
 - redis-plus-plus version: [1.3.2]

**Additional context**
weiyy@ubuntu:/mnt/work$ redis-cli  -c -p 7004
127.0.0.1:7004> CLUSTER SLOTS
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 7000
      3) "b59546dfe52d7e25a6ba3ce86832761749d29f55"
   4) 1) "127.0.0.1"
      2) (integer) 7004
      3) "04a3b0b21ef124158a69e68eaeedfab09fe71b99"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 7001
      3) "35b995b03698bb303cb213590914956a2400d208"
   4) 1) "127.0.0.1"
      2) (integer) 7005
      3) "81aac83c6a6a03424b018089517960baef2a01ff"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 7002
      3) "8d93a09ceb936345e728ad933f5cf1ecf9a2cee8"
   4) 1) "127.0.0.1"
      2) (integer) 7003
      3) "22c4d265e918a76edf1a11213200eca3e9a9069e"
127.0.0.1:7004>

**Comment by sewenew** [comment]
That's a bug. AsyncRedisCluster failed to send READONLY command to Redis. I'll fix this problem ASAP.

Thanks for pointing it out! And sorry for the inconvenience...

Regards

**Comment by sewenew** [comment]
@yyweii The bug has been fixed. Please check out the latest code on master branch to have a test.

Thanks again!

Regards
