### ISSUE TITLE
Failover with sentinel

### ISSUE THREAD

**Issue by jinj** [sewenew/redis-plus-plus#304]
I created a basic setup on 3 boxes: A, B, C. On box A, I run redis master and sentinel 1, Box B runs replica and sentinel 2. Box C has sentinel 3. Then I created a redis connection using 3 sentinels. The connection works. However, if I shutdown Box A on which both master and sentinel 1 are running, the connection will fail with message:  'Failed to create connection with sentinel'. Here is the relevant code, which is basically a copy from this wiki page:
```
SentinelOptions      sentinel_opts;
    const unsigned short default_port = 26379;
    sentinel_opts.nodes               = {{redis_sentinel1, default_port},
                           {redis_sentinel2, default_port},
                           {redis_sentinel3, default_port}};
    sentinel_opts.connect_timeout = std::chrono::milliseconds(100);
    sentinel_opts.socket_timeout = std::chrono::milliseconds(100);
    auto sentinel = std::make_shared<Sentinel>(sentinel_opts);
    ConnectionOptions connection_opts;
    connection_opts.connect_timeout = std::chrono::milliseconds(100);
    connection_opts.socket_timeout  = std::chrono::milliseconds(100);
    connection_opts.db              = index;
    ConnectionPoolOptions pool_opts;
    pool_opts.size = 1;

    auto redis = Redis(sentinel, master_name, Role::MASTER, connection_opts, pool_opts);
```
How can I get connection working after a whole box is down (a redis server and a sentinel)?

**Comment by sewenew** [comment]
If you configure sentinels properly (check the [doc](https://redis.io/topics/sentinel#configuring-sentinel) for details, especially the quorum option), when box A is down, sentinel 2 and sentinel 3 will start a failover, and elect a replica as the new master. That might take some time, depend on your settings.

When the election is done, `Redis` object will automatically connect to the new master, and you can send commands to master. However, before the failover is done, if you continue sending commands with `Redis` object, you'll get the failed message as you posted.

So if you get the exception, you can retry the command latter. When the failover is done, everything will recover to normal automatically.

Regards
