### ISSUE TITLE
[QUESTION]How to build this into a conan package

### ISSUE THREAD

**Issue by UlfbertHuynh** [sewenew/redis-plus-plus#308]
Hi, my question is stated in the header. How to build this into a conan package?

**Comment by sewenew** [comment]
Sorry, but I'm not familiar with Conan.

However, someone has already published a redis-plus-plus package on Conan.io. You can try it: [redis-plus-plus](https://conan.io/center/redis-plus-plus)

Regards

**Comment by COM8** [comment]
If you need an example, I have done it here: https://github.com/UWPX/UWPX-Push-Server/blob/master/CMakeLists.txt

https://github.com/UWPX/UWPX-Push-Server/blob/efb7331c9878ea6369d74ded4a6fdc3b59ca77dd/CMakeLists.txt#L92

https://github.com/UWPX/UWPX-Push-Server/blob/efb7331c9878ea6369d74ded4a6fdc3b59ca77dd/CMakeLists.txt#L101-L105

https://github.com/UWPX/UWPX-Push-Server/blob/efb7331c9878ea6369d74ded4a6fdc3b59ca77dd/CMakeLists.txt#L110

And then linking against it here:
https://github.com/UWPX/UWPX-Push-Server/blob/efb7331c9878ea6369d74ded4a6fdc3b59ca77dd/src/storage/redis/CMakeLists.txt#L7

**Comment by UlfbertHuynh** [comment]
ah ok thank for your help.
