### ISSUE TITLE
Support C++17

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#31]
Many modern compilers already have good support for C++ 17, and redis-plus-plus uses `StringView` and `Optional<T>` as replacements for `std::string_view` and `std::optional<T>`. In fact, if user already has a compiler supporting C++ 17, we should make redis-plus-plus use `std::string_view` and `std::optional<T>`, instead of those replacements.

I think we can do some compiler check to decide whether we should compile redis-plus-plus with C++11  or C++ 17.

**Comment by iamAzeem** [comment]
@sewenew :

And, please take into account the C++17 compliance to [dynamic exception specs](https://en.cppreference.com/w/cpp/language/except_spec) also.

At the moment, it generates the following error with `-std=c++1z` with GCC 7.4.0 on Ubuntu 18.04 machine:
```
/usr/include/pqxx/tuple.hxx:95:33: error: ISO C++1z does not allow dynamic exception specifications
   reference at(size_type) const throw (pqxx::range_error);   //[t11]
```

**Comment by sewenew** [comment]
Hi @iamAzeem 

In fact, I didn't use *dynamic exception specification* in redis-plus-plus.

I tried to build redis-plus-plus with `-std=c++1z` and *gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)*, and there's no such errors.

I specify `-std=c++1z` flag by modifying the *CMakeLists.txt* file: 

```
set(CMAKE_CXX_FLAGS "-std=c++1z -Wall -W -Werror -fPIC")
```

I don't know how you specified this flag. But you can try this solution.

Also, from your error message, it's the *pqxx* lib throws the error. You might need to check if *pqxx* can build with C++ 17.

Hope this helps :)

Regards

**Comment by iamAzeem** [comment]
Hi @sewenew,

Thank you for the quick response!

Actually, I installed it using the following command:
```
$ sudo apt install libpqxx-dev
```
The library I'm trying it to link with is using `-std=c++1z` and there I got that error.
Then, I switched to C++14 and it's working fine now.

I'll try to build it with C++17 and update later.

Thanks a lot!

**Comment by sewenew** [comment]
Hi @iamAzeem 

So you got the error message when linking *libpqxx-dev*? If so, I think you should create an issue on *libpqxx*. And this is an issue on *REDIS-PLUS-PLUS* :-)

Regards

**Comment by iamAzeem** [comment]
@sewenew 

Sorry about that. My bad. ;-(
Actually, I realized that after my second comment.

You can delete the comments.

**Comment by wingunder** [comment]
Hi,

For your information, I just managed to compile the entire redis++ lib and test binary, without _any_ errors, on an ancient Ubuntu 16.01.6 LTS system, using C++17, with the following patch:
````patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index fb160b5..a3b8722 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,7 +6,7 @@ else()
     cmake_minimum_required(VERSION 2.8.0)
 endif()

-set(CMAKE_CXX_FLAGS "-std=c++11 -Wall -W -Werror -fPIC")
+set(CMAKE_CXX_FLAGS "-std=c++1z -Wall -W -Werror -fPIC")

 set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
````
Here's the environment:
````sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
````
Regards

**Comment by sewenew** [comment]
Hi @wingunder 

Thanks for your good work!

Regards

**Comment by wingunder** [comment]
Hi @sewenew,

>Thanks for your good work!

You're welcome.

I also did the `-std=c++1z` compile on my Debian system with an up-to-date `testing`/`Bullseye` installed, and it all compiled without errors. So I think it should be safe to close this issue.

Regards

**Comment by iamAzeem** [comment]
@wingunder 

Actually, the issue is about to check the compiler support for C++17 and then compile with standard library support for [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view) and [`std::optional`](https://en.cppreference.com/w/cpp/utility/optional). At the moment, the `redis-plus-plus` is using its own version of those facilities i.e. [`StringView`](https://github.com/sewenew/redis-plus-plus/blob/ce75d3e9892e6c332b7de9522062bdca8690914b/src/sw/redis%2B%2B/utils.h#L30) and [`Optional`](https://github.com/sewenew/redis-plus-plus/blob/ce75d3e9892e6c332b7de9522062bdca8690914b/src/sw/redis%2B%2B/utils.h#L58).

So, the whole idea is about that switchable configuration at compile time.

**PS**:
I wrongly commented on this open issue window in my browser. I was using this project and some others at the time to build some code. It was a mistake. This project is perfectly compiling with `-std=c++1z` with GCC 7.4.0 on my machine as well.

Thanks!

**Comment by sewenew** [comment]
Hi @iamAzeem @wingunder ,

I've added support for `std::string_view` and `std::optional`.

By default, redis-plus-plus is built with C++ 11. However, if you want to build redis-plus-plus with C++ 17, and use these two features, you can add `-DREDIS_PLUS_PLUS_CXX_STANDARD=17` parameter to the cmake command line:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/path/to/hiredis -DCMAKE_INSTALL_PREFIX=/path/to/install/redis-plus-plus -DREDIS_PLUS_PLUS_CXX_STANDARD=17 ..
```

Then redis-plus-plus will be compiled with `-std=c++17` option.

You can try it, and if you have any problem on building it with C++ 17, feel free to let me know.

Regards

**Comment by iamAzeem** [comment]
Hi @sewenew,

The commit looks good!

Though, I have a few points/questions:

Shouldn't C++17 or latest be the default one if it's available?
And, this could be determined from the CMake instead of using a flag.

If the flag is for compiling with a specific C++ standard, then it should be there with the highest priority.

For example:
1. Check the flag, if defined, use that.
2. If the flag is not defined, determine the latest C++ standard, use that.
3. The C++ standard check shall be from latest to oldest i.e. `C++20` > `C++17` > `C++11`.

And, from the continuous integration standpoint, I'd suggest to output on the console as well for the selected C++ standard for the build.

Another point is that if one builds with the C++17 flag and the compiler is not C++17 compliant then the build system is passing the flag silently over to the compiler.
Shouldn't it be checked and reported by the build system itself instead of propagating it to the compiler i.e. the Fail Fast Principle?

Thanks and regards!

**Comment by sewenew** [comment]
Hi @iamAzeem 

Thanks for your comments! I'll try to answer your concerns.

> Shouldn't C++17 or latest be the default one if it's available?

NO. Because, by now,  it seems that not all compilers have full support for C++17, although you can still specify the `-std=c++17` standard. For example, although GCC 5 has partial support for C++ 17 feature, we usually don't specify the `-std=c++17` option to compile the code with GCC 5.

> And, this could be determined from the CMake instead of using a flag.

Yes, we can use [CMAKE_CXX_STANDARD to specify the c++ standard version](https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/). However, in order to support C++ 17, the minimum version of CMAKE is `3.8`.  Unfortunately, some of my working environments have old CMAKE, and I cannot upgrade these systems. So, as a compromise, I use flag to specify the C++ standard. I might use the CMAKE to determine the C++ standard, when I can get ride of those old systems.

> And, from the continuous integration standpoint, I'd suggest to output on the console as well for the selected C++ standard for the build.

Good idea! I'll add the following message to the CMAKE output: `-- The CXX standard is c++17`

> Shouldn't it be checked and reported by the build system itself instead of propagating it to the compiler i.e. the Fail Fast Principle?

Yes, it's a good idea. It seems `set(CMAKE_CXX_STANDARD_REQUIRED ON)` can achieve the goal. However, it needs a new version of CMAKE. I'll try it in the future.

Thanks again for your reply :)

Regards

**Comment by sewenew** [comment]
Hi @iamAzeem 

I've added c++ standard info in the cmake output. And I'll close the issue. If you still have any problem with the C++ 17 support, feel free to comment it or  reopen it :)

Regards

**Comment by vakker** [comment]
@sewenew 

I tried building an example with C++17 and it fails during linking.
Base on #5 I modified `app.cpp` to:
```c++
#include <iostream>

#include <sw/redis++/redis++.h>

using namespace sw::redis;

int main()
{
        auto redis = Redis("tcp://127.0.0.1:6379");
        redis.set("key", "val");
        auto val = redis.get("key");
        if (val) 
                std::cout << *val << std::endl;
        return 0;
}
```

and with the `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.0.0)

project(app)

set(CMAKE_CXX_FLAGS "-std=c++11 -Wall -W -Werror -fPIC")

set(SOURCE_FILES app.cpp)
add_executable(app ${SOURCE_FILES})

# <------------ add hiredis dependency here --------------->
find_path(HIREDIS_HEADER hiredis)
target_include_directories(app PUBLIC ${HIREDIS_HEADER})

find_library(HIREDIS_LIB hiredis)
target_link_libraries(app ${HIREDIS_LIB})

# <------------ add redis-plus-plus dependency here -------------->
find_path(REDIS_PLUS_PLUS_HEADER sw)      # NOTE: this should be *sw* NOT *redis++*
target_include_directories(app PUBLIC ${REDIS_PLUS_PLUS_HEADER})

find_library(REDIS_PLUS_PLUS_LIB redis++)
target_link_libraries(app ${REDIS_PLUS_PLUS_LIB})
```
it does build, but using:
```cmake
set(CMAKE_CXX_FLAGS "-std=c++17 -Wall -W -Werror -fPIC")
```
fails with:
```
[ 50%] Building CXX object CMakeFiles/app.dir/app.cpp.o
[100%] Linking CXX executable app
CMakeFiles/app.dir/app.cpp.o: In function `main':
app.cpp:(.text+0x19a): undefined reference to `sw::redis::Redis::set(std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&, sw::redis::UpdateType)'
app.cpp:(.text+0x1d0): undefined reference to `sw::redis::Redis::get[abi:cxx11](std::basic_string_view<char, std::char_traits<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:85: recipe for target 'app' failed
make[2]: *** [app] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sewenew** [comment]
@vakker 

Take it easy :) If you still have any problem with redis-plus-plus, feel free to let me know.

Regards

**Comment by 0fa7** [comment]
Just for anyone else running into link issues in regards to:
sw::redis::Redis::publish and friends
sw::redis::Subscriber::subscribe and friends
rebuilding redis-plus-plus with -DREDIS_PLUS_PLUS_CXX_STANDARD=17 worked for me as well.

Would it be worth it setting the default behavior to pick the latest standard if available?

**Comment by sewenew** [comment]
@0fa7 Sorry, but I cannot set it be the latest standard. First of all, it might break the old application building with C++ 11. Also the latest standard might not be stable, say, for some compiler, the latest standard is C++ 20, which might be still not stable.

Regards

**Comment by 0fa7** [comment]
No worries, and thank you for the response.
