### ISSUE TITLE
Issue with creating a Redis object in Visual Studio 2022 on Windows 10.

### ISSUE THREAD

**Issue by Michczu** [sewenew/redis-plus-plus#310]
After installing both redis-plus-plus and hiredis using vcpkg , I tried to build a very simple code by just creating a Redis object:
```
-(just some inconsequential warnings from sds.h that I removed)
1>RedisTest.obj : error LNK2019: unresolved external symbol "public: __cdecl sw::redis::Redis::Redis(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Redis@redis@sw@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "void __cdecl Main(void)" (?Main@@YAXXZ)
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>E:\Tests\RedisTest\x64\Debug\RedisTest.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "RedisTest.vcxproj" -- FAILED.
```
Previously I tried building both hiredis and redis-plus-plus using cmake, but encountered the same issue.

**Comment by sewenew** [comment]
Looks like redis-plus-plus has not been linked correctly. You might need to set the installed redis-plus-plus lib path when you building your application code.

Regards

**Comment by Michczu** [comment]
Alright, I checked and made sure that all the include files and libraries were linked. Turns out I forgot about the libraries, but it still doesn't work even after linking them.
```
Build started...
1>------ Build started: Project: RedisTest, Configuration: Debug x64 ------
1>RedisTest.obj : error LNK2019: unresolved external symbol "public: __cdecl sw::redis::Redis::Redis(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Redis@redis@sw@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "void __cdecl Main(void)" (?Main@@YAXXZ)
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\micha\vcpkg\installed\x86-windows\lib\redis++.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>C:\Users\micha\vcpkg\installed\x86-windows\lib\hiredis.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>E:\Tests\RedisTest\x64\Debug\RedisTest.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "RedisTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
I really appreciate your help.

**Comment by sewenew** [comment]
Looks like that you set different target platform for redis-plus-plus and your application code, i.e. one the x86, while the other is x64. You need to set them with the same target platform. Also they should have the same Configuration, e.g. either both be Debug, or both be Release.

Check [this](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms) and [this](https://docs.microsoft.com/en-us/cpp/build/how-to-configure-visual-cpp-projects-to-target-64-bit-platforms) for reference.

Regards

**Comment by Michczu** [comment]
It works! Thank you so much for taking the time out of your day to help me @sewenew !
There were a few problems: 
1. First was actually including the packages correctly and vcpkg actually is quite convinient in that regard, you just have to go to:  ```Configuration Properties -> vcpkg -> General -> Installed Directory -> vcpkg installation directory/vcpkg/installed
2. Vcpkg, by default installed packages for a 32 bit (x86) system. Changed it to 64 bit (x64) by creating an environmental variable ```VCPKG_DEFAULT_TRIPLET=x64-windows```
3. The last one was that I created a console aplication project in VS, but it was more of a background problem.
