### ISSUE TITLE
[mem leakage]Does wrapping the mget inside try ... catch cause memory leakage?

### ISSUE THREAD

**Issue by UlfbertHuynh** [sewenew/redis-plus-plus#311]
```
RedisCacheDataLoader<V, Formatter>::mget(const std::vector<std::string>& keys) {
   ...
    std::vector<sw::redis::OptionalString> values;
    try{
        redis->mget(keys.begin(), keys.end(), std::back_inserter(values));
    } catch (sw::redis::Error error) {
        LOG(ERROR) << "Error getting data from redis: " << error.what();
        return out;
    }
...
```
Given the above code will this cause any memory leakage ?
I'm worrying inside mget() may Error is thrown before some cleaning up operation.

**Comment by wingunder** [comment]
Hi @UlfbertHuynh,

It should not leak, but you can easily test it by using [Valgrind](https://valgrind.org/).
There are many on-line tutorials to find out how to use Valgrind, just in case you're not familiar with it.

Regards

**Comment by sewenew** [comment]
NO, `mget` doesn't leak memory. The code looks good to me.

Regards
