### ISSUE TITLE
[QUESTION]  can RedisCluster class connect to single redis server?

### ISSUE THREAD

**Issue by HHcamel** [sewenew/redis-plus-plus#315]
Hi ,@sewenew,
I  have a simple question,  can RedisCluster class connect to single redis server? 

 Thanks for your answer and help.

**Comment by wingunder** [comment]
Hi @HHcamel,

If you want to just have a `sw::redis::Redis` reference from an existing `sw::redis::RedisCluster` object, then the answer is in the top-level [README.md](https://github.com/sewenew/redis-plus-plus/blob/master/README.md):

From the [RedisCluster section](https://github.com/sewenew/redis-plus-plus#redis-cluster):

>you can also call Redis RedisCluster::redis(const StringView &hash_tag) to create a Redis object with a hash-tag specifying the node. In this case, the returned Redis object creates a new connection to Redis server. NOTE: the returned Redis object, IS NOT THREAD SAFE!. Also, when using the returned Redis object, if it throws exception, you need to destroy it, and create a new one with the RedisCluster::redis method.

And a snippet of an example, a bit further down, in the same file:
```C++
#include <sw/redis++/redis++.h>

using namespace sw::redis;

auto redis_cluster = RedisCluster("tcp://127.0.0.1:7000");

// Create a Redis object with hash-tag.
// It connects to the Redis instance that holds the given key, i.e. hash-tag.
auto r = redis_cluster.redis("hash-tag");

// And send command without key parameter to the server.
r.command("client", "setname", "connection-name");
```

I hope that this helped you.
Regards

**Comment by HHcamel** [comment]
First， thank you for your answer！
Actually , I want to use the `RedisCluster  `class of connecting to Redis in single-node deployment . can I ? in other words , the `RedisCluster `class can replace the `Redis` class ?

**Comment by sewenew** [comment]
@HHcamel If I understand correctly, *single-node deployment* means standalone Redis instance, i.e. **cluster-enabled no**. In that case, NO, you cannot use `RedisCluster` to connect to it. Because `RedisCluster` will send cluster-related commands to the node to get slot-mapping info, however, the standalone Redis instance will reply with error, and `RedisCluster` will fail to do connection.

Instead, you should use `Redis` to connect to standalone instance. If you want to connect to a single node of Redis Cluster, @wingunder 's comment is very nice!

B.T.W Why do you want to achieve that? 

Regards

**Comment by wingunder** [comment]
Hi @HHcamel,

Like @sewenew, I'm also interested to find out about your use-case.

I personally have a use-case and a solution for it, that I have used successfully a few times. I had software that used to run on a single Redis instance, but it had to get migrated to a Redis Cluster. For this, redis-plus-plus is just excellent, as you can achieve this pretty easily by using C++ templates. Consider the following code, that will run on either a single Redis instance or a Redis Cluster.

``` C++
#include <sw/redis++/redis++.h>

using namespace sw::redis;

template <typename RedisInstance>
int run(const sw::redis::ConnectionOptions& connectionOptions)
{
    auto redisInstance = RedisInstance(connectionOptions);

    // App code follows:
    redisInstance.set("some_key_name", 123);

    return 0;
}

int main()
{
    sw::redis::ConnectionOptions connectionOptions;
    connectionOptions.host = "127.0.0.1";

    // The following bool is hard-coded, but can be set from the application arguments or environment.
    bool useCluster = true; // Set to false for non-RedisCluster operation.

    // The following 'if' can be removed once the migration is done.
    if (useCluster) {
        connectionOptions.port = 7000;
        return run<sw::redis::RedisCluster>(connectionOptions);
    }
    else  {
        connectionOptions.port = 6379;
        return run<sw::redis::Redis>(connectionOptions);
    }
}
```

BTW, if you look at the [redis-plus-plus test dir](https://github.com/sewenew/redis-plus-plus/tree/master/test/src/sw/redis%2B%2B), you'll see that the tests can also be run on clustered and non-clustered Redis, depending on which switches you set on the command line.

Final note: Not all Redis members are implemented for RedisCluster. There are really good reasons for this and you should make sure that you're only using members that are implemented in the Redis class _as well as in the_ RedisCluster class. Examples of exceptions are: 'auth', 'echo', 'ping', etc. For more information on this, please refer to #309.

Hope this helped.
Regards

**Comment by HHcamel** [comment]
HI @sewenew, @wingunder , Thank you for your answer, especially the example code, benefited a lot.
By the way,What I really want to know is whether there is a class that can connect to both standalone Redis and Redis luster,No additional configuration or parameters are required;
Please forgive me for my limited English.

Thank you again for your helps!

**Comment by wingunder** [comment]
Hi @HHcamel,

You're welcome.

Using `RedisCluster` and then the `RedisCluster::redis()` method, as described in the first example, is the closest that you might get. As far as I know, redis-plus-plus does not directly supply what you want. I would seriously suggest to try out something like what I demonstrated in the second example. The template solution is limitless as far as mixing cluster and non-cluster code. If understood, and used correctly, it will most probably also cover your use case.

Regards

**Comment by HHcamel** [comment]
Hi, @wingunder ,
I have learned.
Thank you again for your answer and help, very much!
