### ISSUE TITLE
[QUESTION] Regarding "onConnect" / "onDisconnect" callbacks

### ISSUE THREAD

**Issue by picanumber** [sewenew/redis-plus-plus#321]
I see no API for users of `Redis.h` to specify an `onConnection` / `onDisconnection` callback. I'd like to verify that I'm not missing something from the documentation and possibly what are the architectural choices for not including this. My assumption would be: 

* The fact that connection is lazy, so having an `onConnect` skews the fact that a connection is lazily created. 
* We should rely on failed requests to deduce the state of the connection. 
* The connection pool is self-healing so one should design their system to always assume a connection, and if that goes away be certain that the system tries to recover it.
* This is consistent with not having an `isConnected` member in `Redis`, since we should inspect for example the result of a `ping` call to deduce whether we are online or not. 

Thanks in advance for your answers.

**Comment by sewenew** [comment]
Yes, there's no `onConnection`/`onDisconnection` callbacks, and your assumptions are reasonable.

Normally, we reconnect to server in `onDisconnection` callback. However, if the connection is broken, redis-plus-plus will automatically reconnect to it. So you don't need to manually do that in such a callback. If it fails to do connect to server, redis-plus-plus throws exception, and the application code can retry the command.

Regards

**Comment by picanumber** [comment]
Thanks for clarifying.
