### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michaeldain** [sewenew/redis-plus-plus#324]
**Describe the bug**
READ.md say "If ConnectionOptions::socket_timeout is 0ms, Subscriber::consume blocks until it receives a message." in the Publish/Subscribe.but if i set ConnectionOptions::socket_timeout to 0, connection will failed in the sentinel model;  error msg:what():  With sentinel, connection timeout and socket timeout cannot be 0

**To Reproduce**
    SentinelOptions sentinel_opts;
    sentinel_opts.nodes = {{"10.96.208.59", 26379}}; // Required. List of Redis Sentinel nodes.
    // Optional. Timeout before we successfully connect to Redis Sentinel.
    // By default, the timeout is 100ms.
    sentinel_opts.connect_timeout = std::chrono::milliseconds(200);

    // Optional. Timeout before we successfully send request to or receive response from Redis Sentinel.
    // By default, the timeout is 100ms.
    sentinel_opts.socket_timeout = std::chrono::milliseconds(200);

    auto sentinel = std::make_shared<Sentinel>(sentinel_opts);

    ConnectionOptions connection_opts;
    connection_opts.connect_timeout = std::chrono::milliseconds(100); // Required.
    connection_opts.socket_timeout = std::chrono::milliseconds(0);  // Required.

    ConnectionPoolOptions pool_opts;
    pool_opts.size = 3; // Optional. The default size is 1.

    // mymaster不能修改
    auto redis = Redis(sentinel, "mymaster", Role::MASTER, connection_opts, pool_opts);
    auto sub = redis.subscriber();

    auto msgs = {"msg1", "msg2"};
    auto channel1 = "test:c1";
    sub.on_message([&msgs, &channel1](std::string channel, std::string msg)
                   {
                        static std::size_t idx = 0;
                        std::cout << "channel:" << channel << " msg:" << msg << endl;
                        
                        ++idx; });

    sub.subscribe(channel1);

    printf("subscribe success.\n");
    while (true)
    {
        try
        {
            // Consume the UNSUBSCRIBE message.
            sub.consume();
            printf("consume success.\n");
        }
        catch (const TimeoutError &e)
        {
            // Try again.
            std::cerr << e.what() << " func:" << __FUNCTION__  << " line:" << __LINE__<< '\n';
            continue;
        }
        catch (const ReplyError &e)
        {
            // Try again.
            std::cerr << e.what() << " func:" << __FUNCTION__ << '\n';
            continue;
        } 
        catch (const Error &e)
        {
            std::cerr << e.what() << __FUNCTION__ << " line:" << __LINE__<< '\n';
            sub = redis.subscriber();

            auto msgs = {"msg1", "msg2"};
            auto channel1 = "test:c1";
            sub.on_message([&msgs, &channel1](std::string channel, std::string msg)
                           {
                        static std::size_t idx = 0;
                        std::cout << "channel:" << channel << " msg:" << msg << endl;
                        
                        ++idx; });

            sub.subscribe(channel1);
        }
    }

**Expected behavior**

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.3.1, clang 3.9.1]
 - hiredis version: [e.g. v1.0.0, master]
 - redis-plus-plus version: [e.g. 1.3.2, master, commit b0a42e]

**Additional context**

**Comment by sewenew** [comment]
If you use Sentinel, you cannot set `socket_timeout` or `connect_timeout` to 0. Because redis-plus-plus will use this connection option to communicate with sentinel, and if the timeout is 0, it might block for a long time.

In your case, you can set `socket_timeout` to a non-zero value. If you catch a TimeoutError exception, retry it, i.e. continue the loop.

Regards

**Comment by michaeldain** [comment]
First of all, thank you for your answer
I find SentinelOptions and ConnectionOptions all have **socket_timeout**. Can the **socket_timeout** of connectionoptions be set to 0. so client can block forever read data?

**Comment by wingunder** [comment]
Hi @michaeldain,

>Can the socket_timeout of connectionoptions be set to 0. so client can block forever read data?

Please see: https://github.com/sewenew/redis-plus-plus/issues/325#issuecomment-1047504739

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
