### ISSUE TITLE
reconnect timeout and how many time it will try to reconnect?

### ISSUE THREAD

**Issue by pranaysai27** [sewenew/redis-plus-plus#328]
If the connection is broken, how many times the redis object will try to reconnect? and what is the reconnect timeout?

**Comment by wingunder** [comment]
Hi @pranaysai27 ,

Please read the [Connection](https://github.com/sewenew/redis-plus-plus#connection) chapter in the top-level [README.md](https://github.com/sewenew/redis-plus-plus#readme).

I hope this helped.
Regards
