### ISSUE TITLE
RedisClusterUPtr 

### ISSUE THREAD

**Issue by pranaysai27** [sewenew/redis-plus-plus#329]
Does this have a RedisClusterUPtr similar to transaction and reply pointers, if yes can we copy the pointers without std::move ?

**Comment by sewenew** [comment]
@pranaysai27  What do you mean by `RedisClusterUPtr`? Do you mean `std::unique_ptr<RedisCluster>`?

Transaction and reply are not copyable. Even if you wrap them into a unique_ptr, you still cannot copy them.

Regards

**Comment by pranaysai27** [comment]
Thanks for the response.
I asked about handling the RedisCluster with pointers. Please help me where to find the examples or documentation for using the std::unique_ptr<RedisCluster>.
Regards

**Comment by sewenew** [comment]
That's a C++ 11 question. You can simply call `make_unique` to create a `unique_ptr<RedisCluster>`. Also You cannot copy the unique_ptr.

Regards

**Comment by sewenew** [comment]
The code cannot work. You must specify a type parameter for `std::unique_ptr`, and your code are not compilable.

You can cast a `RedisCluster *` to `void *`, but you cannot cast `std::unique_ptr<RedisCluster>` to `void *`, or `std::unique_ptr<void>` (in fact, `std::unique_ptr<void>` is ill-formed).

Regards

**Comment by sewenew** [comment]
Since there's no update. I'll close it.

Regards
