### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by harkhuang** [sewenew/redis-plus-plus#330]
**Before Asking A Question**
The [README.md file](https://github.com/sewenew/redis-plus-plus/blob/master/README.md) has a detailed introduction with examples on how to use redis-plus-plus, and [redis.h](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h) has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis), and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

**Describe the problem**
A clear and concise description of the problem, with minimal code to reproduce the problem.

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.3.1, clang 3.9.1]
 - hiredis version: [e.g. v1.0.0, master]
 - redis-plus-plus version: [e.g. 1.3.2, master, commit b0a42e]

**Additional context**

**Comment by sewenew** [comment]
@harkhuang  It seems that you did not post your question here :)

Regards
