### ISSUE TITLE
[QUESTION] Where is initializer_list file?

### ISSUE THREAD

**Issue by NamSeungwoo** [sewenew/redis-plus-plus#331]
**Before Asking A Question**
The [README.md file](https://github.com/sewenew/redis-plus-plus/blob/master/README.md) has a detailed introduction with examples on how to use redis-plus-plus, and [redis.h](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h) has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis), and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

**Describe the problem**
Hi, I tried to some cmake process.
1) hiredis build procedure from CMake gui.
2) redis-plus-plus build procedure from CMake gui.
   - set value(example)
      . CMAKE_INSTALL_PREFIX : C:/Users/Kevin/temp/redis_plus_plus
      . HIREDIS_HEADER : C:/Users/Kevin/temp/hiredis/include
      . HIREDIS_LIB : C:/Users/Kevin/temp/hiredis/lib/hiredis.lib
      . TEST_HIREDIS_LIB : C:/Users/Kevin/temp/hiredis-master/Build/Debug/hiredis_staticd.lib
      .hiredis_DIR : hiredis_DIR-NOTFOUND // cannot change path

3) I added some path parameter(e.g. include, library) to visual studio project properties

But, a problem occurred when I built project.
in .../includes/sw/redis++/redis.h(23): fatal error C1083: 'initializer_list': No such file or directory.

How can I fix it?

**Environment:**
 - OS: Window 10
 - Compiler: Visual Studio 2012(c++11)
 - hiredis version: download zip latest
 - redis-plus-plus version: download zip latest

**Additional context**

**Comment by Mephalich** [comment]
Hello. 
As far as I know VS12 doesn't support initializer_list...

->https://stackoverflow.com/questions/12928931/initializer-list-in-visual-studio-2012
&&
->https://social.msdn.microsoft.com/Forums/vstudio/en-US/8da5dd69-67d3-4c80-b3a3-71e455bc746d/include-ltinitializerlistgt-broken?forum=vcgeneral

You might wanna upgrade your compiler... Use the links above for more details.
Best regards

**Comment by sewenew** [comment]
@NamSeungwoo VS2012 is an old compiler, please upgrade it.

Regards
