### ISSUE TITLE
[QUESTION]: Continuously listen to Redis stream using xreadgroup 

### ISSUE THREAD

**Issue by sukhiwrring** [sewenew/redis-plus-plus#339]
I am trying write a code for a consumergroup to continuously listen to the server and reads whenever a new message is added to the stream. The BLOCK parameter would block only until message is unavailable. It is required to send XREADGROUP command again in order to listen to the last added message or a new message. How can consumergroup be made online/active all the time and make the program to not end and keep listening to the stream?

**Comment by krishna116** [comment]
I think any operation can block forever if you like, for example:
```
while(ping(redis server is not dead))
{
    //your_block_operation();
    //sleep(some time);
}
```
thanks.

**Comment by sukhiwrring** [comment]
> 

The purpose here is to keep listening for the added messages over the streams. Whenever a message comes in, XREADGROUP should process that message and then instead of exit, it should wait for the next message and this goes on.
