### ISSUE TITLE
Will `Redis& RedisCluster::redis(const StringView &hash_tag);` be possible?

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#34]
Would it be possible to have the following member function in `RedisCluster`'s public interface?

```c++
Redis& RedisCluster::redis(const StringView &hash_tag);
```
It will be very useful for something like this:
```c++
template <typename T>
class RedisMaster
{
public:
        RedisMaster(T& instance);

        Redis& getInstance();

private:
        T& _instance;
};

template<>
Redis& RedisMaster<Redis>::getInstance() {
        return _instance;
}

template<>
Redis& RedisMaster<RedisCluster>::getInstance() {
        return _instance.redis("");
}
```
At the moment I cannot get the above to work, as `_instance.redis("")` returns `Redis` and not `Redis&`.

Alternatively, is there another way to do the above?

Thanks & regards

**Comment by sewenew** [comment]
There's no way to return a reference from `RedisCluster::redis`. Because this method creates a new connection to Redis server. So it has to return a `Redis` object.

In fact, you don't need to make `RedisMaster` be a template. You can try the following:

```
class RedisMaster {
public:
    explicit RedisMaster(Redis redis) : _redis(std::move(redis)) {}
    explicit RedisMaster(RedisCluster &cluster) : _redis(cluster.redis("")) {}

private:
    Redis _redis;
};
```

**Comment by wingunder** [comment]
Hi @sewenew,
Thanks a lot for the detailed explanation. I'll try it.
Regards

**Comment by wingunder** [comment]
Hi @sewenew,
It  turns out that I need to move the 'RedisInstance' back to where it was moved from, in my case.
I have to do this in the destructor, but only for the `RedisInstance==Redis` case, as the move at construction time was only done in the `RedisInstance==Redis` case. So my implementation now looks as follows. Does this look plausible to you? 
 
```c++
template <typename RedisInstance>
class RedisMaster {
public:
    explicit RedisMaster(RedisInstance &instance, const std::string& key);

    ~RedisMaster() {}

    Redis& getInstance() { return _instance; }

private:
    RedisInstance& _orgInstance;
    Redis _instance;
};

template <>
RedisMaster<Redis>::RedisMaster(Redis &instance, const std::string&)
    : _orgInstance(instance), _instance(std::move(instance))
{}

template <>
RedisMaster<RedisCluster>::RedisMaster(RedisCluster &instance, const std::string& key)
    : _orgInstance(instance), _instance(instance.redis(key))
{}

template <>
RedisMaster<Redis>::~RedisMaster() {
    _orgInstance = std::move(_instance);
}
```

**Comment by sewenew** [comment]
Hi @wingunder 

Why do you need to move it back? Normally, since C++ 11, when we pass a variable by value, it means we release the ownership of the object to others.

Your solution is not so good. One of the C++ philosophy is ***pay only for what you use***. However, your solution uses two variables, but in fact, `_orgInstance` is not used in case of `RedisCluster`. That's an extra pay. Also if the original instance has been destroyed, and your destructor tries to move a `Redis` object to a destroyed reference, the code will core.

If you do need to move it back, you can add a `release` method for `RedisMaster`, which release the ownership of the underlying `Redis` object. Please try the following code:

```
class RedisMaster {
public:
    explicit RedisMaster(Redis redis) : _redis(std::move(redis)) {}
    explicit RedisMaster(RedisCluster &cluster) : _redis(cluster.redis("")) {}

    Redis release() {
        return std::move(_redis);
    }

private:
    Redis _redis;
};

auto redis = Redis("tcp://127.0.0.1");
auto master = RedisMaster(std::move(redis));
// redis is no longer valid
// ...
// other code with master
// ...

// move it back
redis = master.release();
// master is no longer valid
```

Regards

**Comment by wingunder** [comment]
Hi @sewenew,
Thanks, your input helped me.
Closing this issue.
Regards
