### ISSUE TITLE
[cmake fail with hiredis anredis-plus-plus compile together;

### ISSUE THREAD

**Issue by achilsh** [sewenew/redis-plus-plus#340]
**Before Asking A Question**
The [README.md file](https://github.com/sewenew/redis-plus-plus/blob/master/README.md) has a detailed introduction with examples on how to use redis-plus-plus, and [redis.h](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h) has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis), and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

**### **Describe the problem****
my CMakeList.txt file written like this:
`execute_process(COMMAND cmake -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/redis/install/hiredis
                COMMAND make  COMMAND make install
                 WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/redis/hiredis 
                RESULT_VARIABLE cmake_hiredis_ret_val)

if (NOT  cmake_hiredis_ret_val EQUAL "0" ) 
    message(FATAL_ERROR "build and install hiredis fail")
else()
    message(STATUS "..................install hiredis succ")
endif()

message("...................... begin to build redis_plus_plus")
execute_process(COMMAND mkdir -p  build 
                WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/redis/redis-plus-plus  
                RESULT_VARIABLE cmake_redis_plusplus_ret)

execute_process(COMMAND cmake  -DCMAKE_PREFIX_PATH=${CMAKE_CURRENT_SOURCE_DIR}/redis/install/hiredis 
                                -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/redis/install/redis_plusplus
                                -DREDIS_PLUS_PLUS_CXX_STANDARD=17  .. 
                WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/redis/redis-plus-plus/build
                RESULT_VARIABLE cmake_redis_plusplus_ret)
        
if (NOT cmake_redis_plusplus_ret EQUAL "0") 
    message(FATAL_ERROR "...................... cmake redis_plusplus fail")
else()
    message(STATUS  "............................cmake redis_plusplus succ")
endif()

message("...................... begin to make redis_plus_plus")
execute_process(COMMAND   make    COMMAND make install 
                         WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/redis/redis-plus-plus/build
                         RESULT_VARIABLE cmake_redis_plusplus_ret)
if (NOT cmake_redis_plusplus_ret EQUAL "0") 
    message(FATAL_ERROR "................... make redis_plusplus fail")
else()
    message(STATUS  ".........................make redis_plusplus succc")
endif()

message("...................... begin to install redis_plus_plus")
execute_process(COMMAND  make  install
                         WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/redis/redis-plus-plus/build
                         RESULT_VARIABLE cmake_redis_plusplus_ret)
if (NOT cmake_redis_plusplus_ret EQUAL "0") 
    message(FATAL_ERROR "................... install redis_plusplus fail")
else()
    message(STATUS  ".........................install redis_plusplus succc")
endif()
`

### **run cmd:**
when run cmake .. in build dir,  its parent dir is same with cmakelists.txt file..
`
└── redis
    ├── hiredis
    ├── install
    └── redis-plus-plus
├── build
├── CMakeLists.txt

### **err like this**:
`  2%] Building CXX object CMakeFiles/redis++.dir/src/sw/redis++/command.cpp.o
In file included from /home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/command.h:24:0,
                 from /home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/command.cpp:17:
/home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/connection.h:27:10: fatal error: hiredis/hiredis.h: No such file or directory
 #include <hiredis/hiredis.h>
          ^~~~~~~~~~~~~~~~~~~
In file included from /home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/command.h:24:0,
                 from /home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/command.cpp:17:
/home/user/prj_dict/works/src/pxing/third_party/redis/redis-plus-plus/src/sw/redis++/connection.h:27:10: fatal error: hiredis/hiredis.h: No such file or directory
 #include <hiredis/hiredis.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
CMakeFiles/redis++.dir/build.make:62: recipe for target 'CMakeFiles/redis++.dir/src/sw/redis++/command.cpp.o' failed
make[2]: *** [CMakeFiles/redis++.dir/src/sw/redis++/command.cpp.o] Error 1
make[2]: *** [CMakeFiles/redis++.dir/src/sw/redis++/command.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/redis++.dir/all' failed
make[1]: *** [CMakeFiles/redis++.dir/all] Error 2
make[1]: *** [CMakeFiles/redis++.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
make: *** [all] Error 2
CMake Error at third_party/CMakeLists.txt:46 (message):
`

`

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.3.1, clang 3.9.1]
 - hiredis version: [e.g. v1.0.0, master]
 - redis-plus-plus version: [e.g. 1.3.2, master, commit b0a42e]

**Additional context**

**Comment by sewenew** [comment]
It seem that hiredis does not installed properly, or the installation path has not been properly specified when building redis-plus-pus.

Sorry, but I'm not quite familiar with cmake either. You might need to seek help from a cmake expert for help.

Regards

**Comment by h28dev** [comment]
Hi ! I was having the same problem. In my case, you get that error if you compile with:

`cmake -DCMAKE_PREFIX_PATH=/some_path/hiredis ...`

The solution that worked for me was:

`cmake -DHIREDIS_LIB=/some_path/hiredis/lib/libhiredis.so -DHIREDIS_HEADER=/some_path/hiredis/include ...`

I think the documentation says that you have to use `-DCMAKE_PREFIX_PATH`, `-DHIREDIS_LIB` and `-DHIREDIS_HEADER` (the three of them), but it's possible that only the last two of them are neccesary. Maybe I didn't understood correctly, or maybe the documentation or the provided cmake need to be adjusted.

I hope it helps. :)

**Comment by sewenew** [comment]
@h28dev `HIREDIS_LIB` and `HIREDIS_HEADER` are internal variables. If cmake finds the installation path of hiredis successfully, it will assign these two variables automatically. In your case, it looks like cmake does not find the location of hiredis.

B.T.W. If you compiling it on Windows, you need to set these two variables, so far. I'm not familiar with Visual Studio, not sure if the cmake integrated in Visual Studio works the same as Linux or macOS.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
