### ISSUE TITLE
[QUESTION] wrapper function for xreadgroup

### ISSUE THREAD

**Issue by sukhiwrring** [sewenew/redis-plus-plus#343]
I am trying to build a wrapper for redis.xreadgroup(group, consumer, key, id, count, noack,)   similar to following example for redis.scan:
```
    std::vector<std::string> RedisImpl::scan(std::string_view pattern, int count)
    {
        std::vector<std::string> keys;
        auto cursor = 0LL;
        do
        {
            cursor = redis->scan(cursor, pattern, count, std::back_inserter(keys));
        } while (cursor != 0);

        return keys;
    }
```
I am getting errors:
```
no type named 'type' in 'struct sw::redis::IsKvPairIter<std::back_insert_iterator<int> >'
  detail::to_array(typename IsKvPairIter<Output>::type(), reply, output);
```

I need to understand as how can I define the type of variable Output/result in redis.xreadgroup same as keys in redis.scan?
Are these completely different?

**Comment by sewenew** [comment]
Yes, they are quite different. One is map, and the other is not. You can check the code examples in README for how to use `xreadgroup`: [example](https://github.com/sewenew/redis-plus-plus#examples-4)

Regards

**Comment by sukhiwrring** [comment]
From this example it is clear that result field is unordered map.

using Attrs = std::vector<std::pair<std::string, std::string>>;
using Item = std::pair<std::string, Optional<Attrs>>;
using ItemStream = std::vector<Item>; 
std::unordered_map<std::string, ItemStream> result;

Now if it's type has to be defined when calling the xreadgroup function like 
redis.xreadgroup(std::string_view group, std::string_view consumer, std::string_view key, std::string_view id, long long count, bool noack, **OUTPUT** output). 
How can OUTPUT type be defined?
 
Here OUTPUT 's type is unordered map which can contain further nested lists inside. 
I was taking the example of scan as it also has this OUTPUT parameter when function is called. 

If I put a wrapper function like:

void RedisImpl:: xreadgroup(std::string_view group, std::string_view consumer, std::string_view key, std::string_view id, long long count, bool noack, sw::redis::Output output) {return redis->xreadgroup(group, consumer, key, id, count, noack, std::back_inserter(result)); }

This will generate an error due to incorrect  type in the call. 
I have also tried replacing "sw::redis::Output" with unordered map definition. It didn't work either.

**Comment by sewenew** [comment]
`Output` is a template parameter, not a specific type. If you want to make your wrapper works as `scan`, you need to make it a template. Check the prototype of `Redis::xreadgroup` for example. You might also need to ask help from a C++ expert for more info on template programming.

Regards
