### ISSUE TITLE
[QUESTION] How to retrieve results from HGETALL with pipeline? 

### ISSUE THREAD

**Issue by jangitje** [sewenew/redis-plus-plus#346]
[QUESTION] I'm trying to use pipeline in combination with hgetall. Without pipeline the result can be easily inserted into a vector. But has does it work with a pipeline? I want to use pipeline because I need to speed up the lookups. Working with Redis Cluster. #346

**Comment by sewenew** [comment]
You can check the [test code](https://github.com/sewenew/redis-plus-plus/blob/463f34109ecbb8956e8b376e7f2bb39407082194/test/src/sw/redis%2B%2B/pipeline_transaction_test.hpp#L180) for an example.

Regards

**Comment by jangitje** [comment]
Thanks, it's now clear
