### ISSUE TITLE
Additional ConnectionOptions constructor request.

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#35]
Would it make sense to add the following `ConnectionOptions` constructor?

````c++
explicit ConnectionOptions(
    const ConnectionType &type = ConnectionType::TCP,
    const std::string &password = "",
    int db = 0,
    const std::string &host = "localhost",
    int port = 6379,
    bool keep_alive = true,
    const std::chrono::milliseconds &connect_timeout = std::chrono::milliseconds(0),
    const std::chrono::milliseconds &socket_timeout = std::chrono::milliseconds(0));
````
Currently, only the following constructor is available:
https://github.com/sewenew/redis-plus-plus/blob/3ba84a812ec57b35567646072fd5a628d1d0ce2a/src/sw/redis%2B%2B/connection.h#L44-L45

The keep_alive is suggested to be true, due to issue https://github.com/sewenew/redis-plus-plus/issues/30.

**Comment by sewenew** [comment]
Sorry, I don't think we need such a constructor.

First of all, there would be too many parameters, that's a code smell. Secondly, normally, user only needs to set part of the options. However, with such a constructor, even if the user only want to set a non-default port, s/he has to set too many other options, and that would be inconvenience.

Lastly, about the default value of `keep_alive`. I did some tests several days ago, and it comes out that sometimes `keep_alive = true` is slower than `keep_alive = false`. So I still haven't changed the default value. I'll do some further tests in the future to decide whether I should make the change.

Regards

**Comment by wingunder** [comment]
Hi @sewenew,
Ok, no problem.
Thanks for your quick reply.
Regards
