### ISSUE TITLE
[BUG] When the "-static" option is used get a Segmentation fault (Core dumped) [Resolved]

### ISSUE THREAD

**Issue by sirlordt** [sewenew/redis-plus-plus#356]
**Describe the bug**
When the "-static" option is used get a Segmentation fault (Core dumped)

**To Reproduce**
I create two git repos

Using conan

```
git clone https://github.com/sirlordt/redis_integration_test01
cd redis_integration_test01
redis_integration_tes01$ ./run_build_debug.sh make
```
Using git to clone from the redis++ repo.

```
git clone https://github.com/sirlordt/redis_integration_test02
cd redis_integration_test02
redis_integration_tes02$ ./run_build_debug.sh make
```

**Expected behavior**
I expected don't get a "Segmentation fault (Core dumped)"

**Environment:**
 - OS: Linux Mint 20.3
 - Compiler: gcc-11
 - hiredis version: master and conan 1.3.3
 - redis-plus-plus version:  master, conan 1.3.3

**Additional context**
![image](https://user-images.githubusercontent.com/4441192/166563896-20e5f44f-8af6-43aa-9d0c-d6ac0b63cd83.png)

**Comment by sewenew** [comment]
According to the warning message you given, hiredis calls `getaddrinfo`, while `getaddrinfo` cannot be linked with `-static` option, in multiple env. Check the following links for detail:

https://sourceware.org/bugzilla/show_bug.cgi?id=10652

https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo

https://bugzilla.redhat.com/show_bug.cgi?id=523694

Regards

**Comment by sirlordt** [comment]
Hello again...

I have a project in this repo:

`https://github.com/sirlordt/soci_integration_test01.git`

Is full linked static and the linker generate a lot of warnings included the same of `getaddrinfo` and work perfect fine.

By analogy if the problem `"is not possible full static link when getaddrinfo is used"` then 

**Why this program is working fine?. By logic must fail of same way.**

I mean the program connect to mysql. it use the network api from os with no problems.

I think is something more darkness!!! And suspect the problem come from libhiredis, some kind obsolete libc api used by hiredis.

Screenshots

![image](https://user-images.githubusercontent.com/4441192/166740539-76ab4848-feff-425a-92c4-456c8628e52c.png)

**Comment by sirlordt** [comment]
Hello again again.

The problem is with **redis_plus_plus** library. **hiredis** library work perfect with full static link executable.

I create a repo to show you 

[https://github.com/sirlordt/redis_integration_test04](https://github.com/sirlordt/redis_integration_test04)

Screenshot
![image](https://user-images.githubusercontent.com/4441192/166812367-2a8d2881-3ce0-4ae9-8b1e-78a705d8479f.png)

**Comment by sewenew** [comment]
After some hard research, I found the problem has nothing to do with redis-plus-plus. Instead it's a problem with the gcc and pthread lib. Check [this](https://stackoverflow.com/questions/9002264/starting-a-stdthread-with-static-linking-causes-segmentation-fault) for detail.

You can reproduce the problem with the following code:

```
// app.cpp
#include <condition_variable>

int main() {
        std::condition_variable var;
        return 0;
}
```

If you link the code with `-static` option, you'll get segmentation fault when running it:

```
g++ -std=c++17 -static -o app app.cpp -pthread
```

The solution is use `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive` instead of `-pthread`.

```
g++ -std=c++17 -static -o app app.cpp -Wl,--whole-archive -lpthread -Wl,--no-whole-archive
```

You can add `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive` when you linking your application with redis-plus-plus, and the problem should be gone.

Regards

**Comment by sirlordt** [comment]
it work!!!

Thanks. Be appreciated!!!

You are the best!!!.

**Comment by sewenew** [comment]
No problem :)

If you have any problem with redis-plus-plus, feel free to let me know. If you like it, feel free to star it and spread it :)

Regards

**Comment by sirlordt** [comment]
Sure!!! thank!!!

Your library is great!!!.

I added a star to you project.
