### ISSUE TITLE
[FEATURE] Supporting KEEPTTL in SET

### ISSUE THREAD

**Issue by FedericoHeichou** [sewenew/redis-plus-plus#366]
**Is your feature request related to a problem? Please describe.**
Actually I can't update a variable keeping its TTL without manually get and set it

**Additional context**
In your code there is a:  
// TODO: Support KEEPTTL option for Redis 6.0

Is planned adding it soon? Checking out the code seems not hard adding this feature, but I prefer wait you

**Comment by sewenew** [comment]
I've add this feature to dev branch. You can take a try. If everything is OK, I'll merge it into master.

```
bool Redis::set(const StringView &key, const StringView &value, bool keepttl, UpdateType type = UpdateType::ALWAYS);
```

Usage:

```
// set with ttl
redis.set("key", "val", std::chrono::seconds(100));

// remove ttl by default
redis.set("key", "value");

// set with keepttl
redis.set("key", "val", true);
```

Regards

**Comment by FedericoHeichou** [comment]
Great! I will check and try your code next week, thank you! I really appreciate

**Comment by FedericoHeichou** [comment]
For me is ok, I checked and tried the code and works as expected. Thank you very much for your work.

Will you tag this commit?

**Comment by FedericoHeichou** [comment]
Ok, thank you!
