### ISSUE TITLE
[FEATURE] AsyncRedisCluster client seems no append function? has incr function

### ISSUE THREAD

**Issue by maris205** [sewenew/redis-plus-plus#367]
**Is your feature request related to a problem? Please describe.**
 AsyncRedisCluster client seems no append function

**Describe the solution you'd like**
need this function

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by sewenew** [comment]
The `append` command has been added to master branch.

Regards

**Comment by sewenew** [comment]
Since the code has been merged to master branch, I'll close this issue. If you still have any problem on redis-plus-plus, feel free to let me know. If it's helpful, also feel free to star it and spread it :)

Regards
