### ISSUE TITLE
[QUESTION] Using it on Windows

### ISSUE THREAD

**Issue by bigdaronlee163** [sewenew/redis-plus-plus#368]
**Describe the problem**
when I using redis++ on windows, I got right result on get ,rpush, hset hadd  command ,but the set command always occurs error . Although an error was encountered, the set command did succeed ， I think the reply got error 。

**Environment:**
OS: [Windows 10 x64]
Compiler: [VS2022 using ISO C++17]
hiredis version: [master]
redis-plus-plus version: [master]

**Additional context**

**Comment by bigdaronlee163** [comment]
this is my project ：
![image](https://user-images.githubusercontent.com/49524138/176105328-8b44bc9d-c1ef-4780-afa0-6d6df0b30228.png)
and the error occurs when run to line 368 
![image](https://user-images.githubusercontent.com/49524138/176105449-d36f52e3-f52f-4bf9-814b-3b5cc1acb1ed.png)

when stepping into the reply::rewrite_set_reply(*reply); I found error too 
![image](https://user-images.githubusercontent.com/49524138/176105675-817379c0-ea1f-459d-97be-81a90a4983b7.png)

**Comment by bigdaronlee163** [comment]
in the end ， I got 
![image](https://user-images.githubusercontent.com/49524138/176105793-0933b0ea-7bec-44d9-900b-3a20a6c2369e.png)

The information is as follows：
线程 0x1bc8 已退出，返回值为 0 (0x0)。
HEAP[ldx_redis_clion_2.exe]: Invalid address specified to RtlValidateHeap( 000001A3E5CC0000, 000001A3E5CC5E10 )
已在 ldx_redis_clion_2.exe 中执行断点指令(__debugbreak()语句或类似调用)。

Debug Assertion Failed!

Program: ...l\ldx_redis_clion_2\out\build\x64-Debug\ldx_redis_clion_2.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 904

Expression: _CrtIsValidHeapPointer(block)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Comment by sewenew** [comment]
First of all, please check if you installed multiple hiredis. If you do, uninstall them, and only keep one hiredis.

Secondly, please ensure that you build both redis-plus-plus and hiredis with the same configuration, i.e. x64-Debug.

Regards

**Comment by sewenew** [comment]
@bigdaronlee163 After some research, I modified some code, that might cause your problem. The modified code has been committed on dev branch. Please checkout the latest code on dev branch to take a try.

Regards

**Comment by sewenew** [comment]
The code has been merged into master branch.

Since there's no update, I'll close this issue.

Regards
