### ISSUE TITLE
[BUG] Cannot find hiredis built in debug mode

### ISSUE THREAD

**Issue by Aposhian** [sewenew/redis-plus-plus#369]
**Describe the bug**
When `hiredis` is built in debug mode, its libraries are suffixed with `d` via
https://github.com/redis/hiredis/blob/95a0c1283a7277f684388edcbdf5b73d0d76104f/CMakeLists.txt#L28

This makes `redis-plus-plus` unable to find the `hiredis` library when built in debug mode. It would be nice to have a cmake option to point to a different name.

**To Reproduce**
```
git clone https://github.com/redis/hiredis.git
cd hiredis
cmake -DCMAKE_BUILD_TYPE=Debug .
make
make install
cd ..
git clone https://github.com/sewenew/redis-plus-plus.git
cd redis-plus-plus
cmake .
```
produces
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TEST_HIREDIS_LIB
    linked by target "test_redis++" in directory /opt/redis-plus-plus/test

-- Configuring incomplete, errors occurred!
```

**Expected behavior**
redis-plus-plus to find my library of hidredis built from source in debug mode.

**Environment:**
 - OS: Ubuntu
 - Compiler: gcc 9.4.0
 - hiredis version: master
 - redis-plus-plus version: master

**Additional context**
I ran across this while building both packages with [colcon](https://colcon.readthedocs.io/en/released/)

**Comment by sewenew** [comment]
Thanks for reporting this! And sorry for the late reply!

How about making the test code's CMakeLists.txt search for hiredis library's suffix version automatically? It tries to find hiredis library without suffix. If it fails, it searches for the suffix version.

Regards

**Comment by Aposhian** [comment]
Yeah that seems like a reasonable solution.

**Comment by sewenew** [comment]
The problem has been fixed. You can try it with the latest code on master branch.

So sorry for the late reply. Too busy these days...

Thanks again for reporting the bug :)

Regards
