### ISSUE TITLE
why did't support full uri  scheme

### ISSUE THREAD

**Issue by KHaxen** [sewenew/redis-plus-plus#37]
for example "redis://[dev]:my_password@127.0.0.1:6379",  it will simplify out config, because auth is mandatory  now

**Comment by sewenew** [comment]
Hi @KHaxen 

Do you mean "redis://[**db_num**]:my_password@127.0.0.1:6379"?

In fact, I was trying to support specifying db number and password in the URI. However, I heard that Redis 6 will have strong ACL support. So I decided to defer the support until I know how Redis ACL works.

When Redis 6 officially releases the ACL support, I'll add the support in URI. Thanks for this issue! I'll keep it open, and if I have any progress, I'll let you know.

Also, AFAIK, auth is **NOT** mandatory, unless you enable protected mode, and try to access Redis from another host.

By now, Redis' auth support is very weak, while Redis is very fast. So  hackers can guess the password quickly, and you need to take special care, if you have to expose Redis to external hosts.

Regards

**Comment by KHaxen** [comment]
Hi, 
thank u response.
redis 6 ACL has some document, see https://redis.io/topics/acl,  and i think the URI should be like redis://username:password@127.0.0.1:6379/db",  where username, password, db are all optional,  what do u think?

**Comment by sewenew** [comment]
Hi @KHaxen 

Thanks for your info!

Your proposal sounds good to me, except that we need to distinguish TCP connection and UNIX socket connection. So it should be something like the following:

```
tcp://[[username]:password@]host[:port][/db]

unix://[[username]:password@]host[:port][/db]
```

I'll create a commit to support this full scheme ASAP.

Sorry for the late reply, too busy these days...

Regards

**Comment by wingunder** [comment]
For parsing the URI, the following function in the redis source code could work, with some minor adaptions: 
https://github.com/antirez/redis/blob/a1b654819cc0031ba30910afa1d68174d4f926ae/src/redis-cli.c#L369-L419

**Comment by sewenew** [comment]
Hi @KHaxen and @wingunder ,

Now redis-plus-plus supports full URI scheme. You can get the latest code from the dev branch. I'll do some more tests before merging the code into master branch.

Hope this helps :)

Regards

**Comment by sewenew** [comment]
Hi @KHaxen and @wingunder 

The code has been tested, and merged into the master branch. I'll close the issue, and if you still have any problem, feel free to reopen it.

Regards
