### ISSUE TITLE
[FEATURE] More infos on raw command errors

### ISSUE THREAD

**Issue by immerhart** [sewenew/redis-plus-plus#378]
I'm working with the RedisJSON module (I'm using raw commands for that), which documentation is not the best and the redis responses seem to vary.
It would be really helpful to get more info than:
`Expected STRING reply`
Would it be possible to output smth like
`Expected STRING reply, got ARRAY<OptionalString>`
or similar.
It's quite hard to understand what the issue is (I also tried to use smth like reply::is_array, but got lost on e.g. the array-item type).
I really like this lib and the documentation is very helpful! Thanks for the effort!

**Comment by sewenew** [comment]
Good suggestion! I'll make it on the TODO list. Thanks!

Regards

**Comment by sewenew** [comment]
@immerhart I've updated the code on dev branch to add more info on parse error. You can have a try, and I'll do some test on it in the near future. When everything is done, I'll merge it into master branch.

I'm on vacation, and might reply lately. Sorry for that...

Regards

**Comment by immerhart** [comment]
> @immerhart I've updated the code on dev branch to add more info on parse error. You can have a try, and I'll do some test on it in the near future. When everything is done, I'll merge it into master branch.
> 
> I'm on vacation, and might reply lately. Sorry for that...
> 
> Regards

Awesome! Looks all correct to me.
Could you give me any hint on how to check the type of ARRAY reply elements? It's also not really clear to me if all elements of an array reply have the same type, or if they could differ...
Thank you so much.

**Comment by sewenew** [comment]
> if all elements of an array reply have the same type, or if they could differ...

Yes, it could differ.

If you're using C++ 17, you can convert these kinds of replies, i.e. array replies with different element types,  to vector<variant<Args...>>. Check the doc for detail.

Regards

**Comment by sewenew** [comment]
@immerhart The code has been merged to master. Sorry for the late reply.

Regards
