### ISSUE TITLE
VC2017 build on windows

### ISSUE THREAD

**Issue by RameshKandukuriB** [sewenew/redis-plus-plus#38]
Can't build on windows. Issues with find_path(HIREDIS_HEADER hiredis), find_library(HIREDIS_LIB hiredis) when the hiredis on different folder. What are the expectations with the dependent hiredis lib. I have hiredis in different folder here the folder structure, what should be the values for HIREDIS_HEADER & HIREDIS_LIB. tried with the these paths still report errors.

"C:\xxxx\redis\redis-plus-plus"
"C:\xxxx\redis\hiredis_lib"
- "C:\xxxx\redis\hiredis_lib\install\include\hiredis\read.h"
- "C:\xxxx\redis\hiredis_lib\install\include\hiredis\sds.h"
- "C:\xxxx\redis\hiredis_lib\install\include\hiredis\async.h"
- "C:\xxxx\redis\hiredis_lib\install\include\hiredis\hiredis.h"
- "C:\xxxx\redis\hiredis_lib\install\lib\hiredis.dll"

Errors
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/xxxx/redis/redis-plus-plus/HIREDIS_HEADER
   used as include directory in directory C:/xxxx/redis/redis-plus-plus
   used as include directory in directory C:/xxxx/redis/redis-plus-plus
C:/xxxx/redis/redis-plus-plus/test/HIREDIS_HEADER
   used as include directory in directory C:/xxxx/redis/redis-plus-plus/test
HIREDIS_LIB
    linked by target "shared" in directory C:/xxxx/redis/redis-plus-plus
HIREDIS_STATIC_LIB
    linked by target "test_redis++" in directory C:/xxxx/redis/redis-plus-plus/test				
Error		CMake Error at C:\xxxx\redis\redis-plus-plus\CMakeLists.txt:44 (install):
  install Library TARGETS given no DESTINATION!	redis	C:\xxxx\redis\redis-plus-plus\CMakeLists.txt	44

**Comment by sewenew** [comment]
Hi @RameshKandukuriB 

It seems that you haven't set `CMAKE_PREFIX_PATH`, so `find_path(HIREDIS_HEADER hiredis)` and `find_library(HIREDIS_LIB hiredis)`  cannot find hiredis dependency.

In your case, you should set `CMAKE_PREFIX_PATH` to be *"C:\xxxx\redis\hiredis_lib\install"*. If you build redis-plus-plus with cmake command line, you can try the following:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:\xxxx\redis\hiredis_lib\install" directory\where\CMakeLists.txt\located
```

Then the compiler will set `HIREDIS_HEADER` to be *"C:\xxxx\redis\hiredis_lib\install\include"*, and set `HIREDIS_LIB` to be *"C:\xxxx\redis\hiredis_lib\install\lib"*.

If you're using cmake gui, [this](https://vtk.org/Wiki/VTK/Configure_and_Build#On_Windows_4) and [this](https://vtk.org/Wiki/File:Cmake-add-cache-entry-arrow.png) might help you to set `CMAKE_PREFIX_PATH` variable.

Regards

**Comment by RameshKandukuriB** [comment]
hiredis didn't generate lib file on windows, however it generated dll. I am thinking of using the dll instead. Still has error making, is  hiredis lib must? can it use dll?

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HIREDIS_LIB
    linked by target "shared" in directory C:/xxxx/redis/redis-plus-plus
HIREDIS_STATIC_LIB
    linked by target "test_redis++" in directory C:/xxxx/redis/redis-plus-plus/test

**Comment by sewenew** [comment]
So after specifying `CMAKE_PREFIX_PATH`, the compiler can find `HIREDIS_HEADER` now?

> is hiredis lib must? can it use dll?

It should work with dll. You can try this: in CMakeLists.txt, add the following before the `find_library(HIREDIS_LIB hiredis)` command:

```
SET(CMAKE_FIND_LIBRARY_PREFIXES "")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll")

find_library(HIREDIS_LIB hiredis)
```

I'm not a cmake expert.  Hope it works :)

Regards

**Comment by RameshKandukuriB** [comment]
Thanks, that worked however the same didn't work for /test. I am new to CMake.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HIREDIS_STATIC_LIB
    linked by target "test_redis++" in directory C:/xxxx/redis/redis-plus-plus/test

**Comment by RameshKandukuriB** [comment]
changed to find_library(HIREDIS_STATIC_LIB hiredis) in /test now cmake done. However i don't see the dll or lib file for redis-plus-plus.

C:\xxxx\redis\redis-plus-plus>cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="C:\xxxx\redis\hiredis_lib\install" "C:\xxxx\redis\redis-plus-plus"
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xxxx/redis/redis-plus-plus

**Comment by sewenew** [comment]
You can comment the following to disable building test:

```
#add_subdirectory(test)
```

If you want to build the test, try to use the following to replace the *test/CMakeLists.txt* file:

```
project(test_redis++)

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    cmake_minimum_required(VERSION 3.0.0)
else()
    cmake_minimum_required(VERSION 2.8.0)
endif()

set(PROJECT_SOURCE_DIR ${PROJECT_SOURCE_DIR}/src/sw/redis++)

file(GLOB PROJECT_SOURCE_FILES "${PROJECT_SOURCE_DIR}/*.cpp")

add_executable(${PROJECT_NAME} ${PROJECT_SOURCE_FILES})

# hiredis dependency
find_path(HIREDIS_HEADER hiredis)
target_include_directories(${PROJECT_NAME} PUBLIC ${HIREDIS_HEADER})

SET(CMAKE_FIND_LIBRARY_PREFIXES "")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll")

find_library(HIREDIS_STATIC_LIB libhiredis.lib)
target_link_libraries(${PROJECT_NAME} ${HIREDIS_STATIC_LIB})

# redis++ dependency
target_include_directories(${PROJECT_NAME} PUBLIC ../src)
set(REDIS_PLUS_PLUS_LIB ${CMAKE_CURRENT_BINARY_DIR}/../lib/libredis++.lib)

## solaris socket dependency
IF (CMAKE_SYSTEM_NAME MATCHES "(Solaris|SunOS)" )
    target_link_libraries(${PROJECT_NAME} -lsocket)
ENDIF(CMAKE_SYSTEM_NAME MATCHES "(Solaris|SunOS)" )

find_package(Threads REQUIRED)

target_link_libraries(${PROJECT_NAME} ${REDIS_PLUS_PLUS_LIB} ${CMAKE_THREAD_LIBS_INIT})
```

Regards

**Comment by sewenew** [comment]
Hi @RameshKandukuriB 

After the cmake command, you should also run `make` and `make install` to build the library and install it. Check [this](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus) for detail.

Also, with Windows, it might be `nmake`, not quite sure.

Regards

**Comment by lygstate** [comment]
Yeap, redis plus plus doesn't working on Windows

**Comment by sewenew** [comment]
HI @lygstate 

On Windows, you can build redis-plus-plus with mingw-w64. [Some one has tried that successfully](https://github.com/sewenew/redis-plus-plus/issues/50).

When I get a Windows box, I'll try to build it with Visual Studio to see if it works.

Regards

**Comment by lygstate** [comment]
build with small fixes with vc2015

**Comment by phuongtran7** [comment]
I was able to build the DLL without building tests with VS2019 with some modification to the `CMakeLists.txt`. I just want a shared library for now so I delete all reference to the static library. However, all this should be the same if you want to build a static lib.

1. Remove the `-Wall -W -Werror -fPIC` as they for the GCC compiler not MSVC. We can use `/W4 /permissive-` for that if needed.
2.  Add `set_target_properties(${SHARED_LIB} PROPERTIES CXX_STANDARD 17 CXX_EXTENSIONS OFF)` to make the project to use C++17.
3. Add:
```
#define NOMINMAX
#include <windows.h>
```
to the `connection.h` to fix the `timeval` struct error. However I don't know whether this is the right way to fix that.

After these, build `hiredis` and link it like mentioned in the README. VS should be able to build `redis++.dll`. I've not test the library yet as I just discovered this project today.

**Comment by sewenew** [comment]
@phuongtran7 Great work!

I'll try hard to find a Windows box to test your solution and merge it into the code base.

About the 3rd point, it seems hiredis has a solution for that, and you can check [this](https://github.com/redis/hiredis/blob/master/win32.h#L5) for detail.

Regards

**Comment by phuongtran7** [comment]
Hi @sewenew 

Thank you so much for the info on hiredis solution. I was able to replace the big `windows.h` header file with the header from hiredis and Redis-plus-plus compiled just fine too. The change I made for the `connection.h` in Redis-plus-plus so that it can be compiled on Windows is this:

```cpp
#ifdef _WIN32
#define NOMINMAX
#include <hiredis/win32.h>
#else
```

Unfortunately, it seems that the rule for installing hiredis is not complete or something. The `include` folder in install location of hiredis doesn't have `win32.h` header file. I had to manually copy it from the source folder to the install location. Other than that, everything works fine.

Also, this is my current `CMakeLists.txt` file for compiling the project on Windows 10 and VS2019. Should be just like the original, beside removing the GCC specific compiler flag and building static library. I also made the project to use C++17 by using `set_target_properties` as MSVC doesn't seem to understand the `-std=c++17` compiler flag. That's why I also remove the `set(CMAKE_CXX_FLAGS)` line.

I think it'd be great if we can add a flag in CMake to choose between building static and dynamic library.

```
project(redis++)

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    cmake_minimum_required(VERSION 3.0.0)
else()
    cmake_minimum_required(VERSION 2.8.0)
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++${REDIS_PLUS_PLUS_CXX_STANDARD}")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

set(PROJECT_SOURCE_DIR ${PROJECT_SOURCE_DIR}/src/sw/redis++)

file(GLOB PROJECT_SOURCE_FILES "${PROJECT_SOURCE_DIR}/*.cpp")

set(SHARED_LIB shared)

add_library(${SHARED_LIB} ${PROJECT_SOURCE_FILES})

# Set the project to use C++17
set_target_properties(${SHARED_LIB} PROPERTIES
            CXX_STANDARD 17
            CXX_EXTENSIONS OFF
            )

# hiredis dependency
find_path(HIREDIS_HEADER hiredis)
target_include_directories(${SHARED_LIB} PUBLIC ${HIREDIS_HEADER})

find_library(HIREDIS_LIB hiredis)
target_link_libraries(${SHARED_LIB} ${HIREDIS_LIB})

set_target_properties(${SHARED_LIB} PROPERTIES OUTPUT_NAME ${PROJECT_NAME})

set_target_properties(${SHARED_LIB} PROPERTIES CLEAN_DIRECT_OUTPUT 1)

option(REDIS_PLUS_PLUS_BUILD_TEST "Build tests for redis++" ON)

if(REDIS_PLUS_PLUS_BUILD_TEST)
    add_subdirectory(test)
endif()

# Install shared lib.
install(TARGETS ${SHARED_LIB}
        LIBRARY DESTINATION lib)

#Install headers.
set(HEADER_PATH "sw/redis++")
file(GLOB HEADERS "${PROJECT_SOURCE_DIR}/*.h*")
install(FILES ${HEADERS} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/${HEADER_PATH})
```

**Comment by sewenew** [comment]
@phuongtran7 

> Unfortunately, it seems that the rule for installing hiredis is not complete or something. The include folder in install location of hiredis doesn't have win32.h header file. I had to manually copy it from the source folder to the install location. Other than that, everything works fine.

win32.h is used internally for hiredis, so it's not installed. Instead, you can just implement this solution by your own, without including hiredis/win32.h:

```
#ifdef _MSC_VER

#include <winsock2.h> /* for struct timeval */

#endif
```

> Also, this is my current CMakeLists.txt file for compiling the project on Windows 10 and VS2019. 

Thanks for your work! I'll try it once I got a Window box.

> I think it'd be great if we can add a flag in CMake to choose between building static and dynamic library.

I'll add a flag for that after merging the dev branch into master.

Thanks again for your work!

Regards

**Comment by sewenew** [comment]
@phuongtran7  I've added cmake flags to disable building static or shared library. Check [this](https://github.com/sewenew/redis-plus-plus/issues/84) for detail.

Regards

**Comment by phuongtran7** [comment]
Hi @sewenew,

Thank you so much for the update. The switch to turn off static build works great for me. I was able to do a clean pull both hiredis and redis++ and build them without much of a problem. I've not test this new build yet but I assume there is no breaking change so everything should be working as before.

**Comment by sewenew** [comment]
Hi guys, finally I get a Windows box, and made redis-plus-plus support Visual Studio 2017 and later.

You can check out the latest code on master branch and follow the [building instructions](https://github.com/sewenew/redis-plus-plus#windows-support) to have a try. If you have any problem with it, feel free to let me know.

Thanks a lot for @phuongtran7 and @lygstate 's work!

Regards
