### ISSUE TITLE
[QUESTION]How to run the test example?

### ISSUE THREAD

**Issue by Fido1999** [sewenew/redis-plus-plus#381]
**Describe the problem**
I transplant redis plus plus to a new system and i compile this tool successfuly.I run the test example with command ./(the name of 
executable file of redis plus plus test example) -h 127.0.0.1 -p 6379 . Redis has been deploy on the same mahcine with default configuration and test example reply as below:

Testing Redis...
Test failed: A null status reply

Why it reply as this ? Dose it caused by wrong command parameter ？

**Comment by sewenew** [comment]
Cannot reproduce the problem. If you still have the problem, feel free to reopen it.

Regards
