### ISSUE TITLE
it not worke when the password contain the special character '@'

### ISSUE THREAD

**Issue by aengusjiang** [sewenew/redis-plus-plus#383]
use URL create Redis
tcp://[[username:]password@]host[:port][/db]
redis://[[username:]password@]host[:port][/db]
unix://[[username:]password@]path-to-unix-domain-socket[/db]

How about deal with the password contain the character `@'

the current version it does not worke such as:
Redis redis3("tcp://pass@127.0.0.1");

**Comment by sewenew** [comment]
That's a known issue. Please check [this](https://github.com/sewenew/redis-plus-plus/issues/144) for a solution, i.e. use another constructor.

Regards
