### ISSUE TITLE
can support async cluster pipeline

### ISSUE THREAD

**Issue by dandyhuang** [sewenew/redis-plus-plus#389]
like [this ](https://github.com/sewenew/redis-plus-plus/issues/350)， I found this doesn't seem to be supported。Although it is possible to use AsyncRedisCluster futures。 but I don't want to increase redis io pressure。

**Comment by sewenew** [comment]
If I understand correctly, you can use AsyncRedisCluster with the [callback interface](https://github.com/sewenew/redis-plus-plus#getting-started-1). In this way you don't need to worry about blocking wait for futures.

B.T.W. what do you mean by *increase redis io pressure*? Redis IO has nothing to do with pipeline. AFAIK, Pipeline is used to reduce RTT in sync mode.

Regards

**Comment by dandyhuang** [comment]
pipeline It's not just a matter of RTT，if you don't use it。  for each request, the server needs to read and write io multiple times。 You can see that the redis official website [pipline](https://redis.io/docs/manual/pipelining/), and did a test to verify the data。 pipeline+[callback interface](https://github.com/sewenew/redis-plus-plus#getting-started-1)  This is the best solution。  [go-redis](https://github.com/go-redis/redis)  is support this way

**Comment by sewenew** [comment]
With redis-plus-plus' async interface, you don't need to explicitly specify a pipeline. All commands will be sent to the underlying socket ASAP, i.e. piped to Redis. When Redis try to read from the socket, if there're multiple commands already in the socket, it will reads them all at once.

Regards

**Comment by dandyhuang** [comment]
thinks
