### ISSUE TITLE
use Redis class connect redis servr with Standalone or cluster mode

### ISSUE THREAD

**Issue by geiliwanghaichao** [sewenew/redis-plus-plus#394]
**Describe the problem**
I‘m not sure a question after reading README.md
I will use publish/Subscribe mode, I want to user Redis class to implement function。
I am not sure using Redis class to connect redis server with standalone or cluster mode 

**Environment:**
  OS: [e.g. ubuntu]
 -Compiler: 
 - hiredis version: hiredis-1.0.2
 - redis-plus-plus version: redis-plus-plus-1.3.5

#include <iostream>
#include <sw/redis++/redis++.h>

using namespace sw::redis;
using namespace std;

int main()
{
    //six node：10.10.43.1:6371 10.10.43.2:6371 10.10.43.3:6371 10.10.43.2:6372  10.10.43.3:6372  10.10.43.1:6372
    ConnectionOptions connection_options;
    connection_options.host = "10.10.43.1"; 
    connection_options.port = 6371;
    connection_options.password = "legend2022";

    connection_options.socket_timeout = std::chrono::milliseconds(200);
    
    //Redis redis1(connection_options);
    ConnectionPoolOptions pool_options;
    pool_options.size = 3;
    
    pool_options.wait_timeout = std::chrono::milliseconds(100);
    
    pool_options.connection_lifetime = std::chrono::minutes(10);
    
    Redis redis2(connection_options, pool_options);

    auto sub = redis2.subscriber();

    sub.on_message([](std::string channel, std::string msg) {
            cout<<"channel:"<<channel<<", msg:"<<msg<<endl;
        });
        
    sub.subscribe("drsuuu1");

    while (true) {
        try {
            sub.consume();
        } catch (const Error &err) {
            // Handle exceptions.
        }
    }

    return 0;
}

**Comment by sewenew** [comment]
> I am not sure using Redis class to connect redis server with standalone or cluster mode

It depends on you. If you have a standalone Redis server, and publish messages to it, you should create a subscriber with `Redis` object. If you have a redis cluster, and publish messages to the cluster, you should create a subscriber with `RedisCluster` object.

Regards

**Comment by geiliwanghaichao** [comment]
@sewenew thanks for your replay，but i mean : no matter what redis server is standalone mode or cluster mode, my appliation only use Redis Class to connect it.this way is ok? thanks

**Comment by geiliwanghaichao** [comment]
this information from README.md ：
Since there's no key parameter, RedisCluster has no idea on to which node these commands should be sent. However there're 2 workarounds for this problem:

If you want to send these commands to a specific node, you can create a Redis object with that node's host and port, and use the Redis object to do the work.
Instead of host and port, you can also call Redis RedisCluster::redis(const StringView &hash_tag) to create a Redis object with a hash-tag specifying the node. In this case, the returned Redis object creates a new connection to Redis server. NOTE: the returned Redis object, IS NOT THREAD SAFE!. Also, when using the returned Redis object, if it throws exception, you need to destroy it, and create a new one with the RedisCluster::redis method.
i know the answer ， thanks
