### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by lilelife** [sewenew/redis-plus-plus#396]
I'd like to use "hget" command.

I wrote the following code:

.... 

                OptionalString res;
                res = RedisClient::instance().get()->hget(NGINX_IP_REDIS_KEY, INTERFACE_IP_HTTP + "_" + nginxIpType);
                LOG_WARN("GetNginxIp nginxIpType HTTP_" << nginxIpType);
                if (res != std::nullopt) {
                    LOG_WARN("get redis get nginx httpIp res = " << res.value());
                    nginxIpAddr = res.value();
                    return nginxIpAddr;
                } 
            

**Describe the problem**
when i use hget ,  terminate called after throwing an instance of 'sw::redis::Error'
  what():  Failed to send command with key: nginxIp

stack like:
redis++/lib/libredis++.so.1(_ZN2sw5redis12RedisCluster8_commandIPFvRNS0_10ConnectionERKSt17basic_string_viewIcSt11char_traitsIcEESA_EJSA_SA_EEESt10unique_ptrI10redisReplyNS0_12ReplyDeleterEET_SA_DpOT0_+0x392) [0x7fb1f0f15572]

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.3.0, ]
 - hiredis version: [e.g. v1.0.0, master]
 - redis-plus-plus version: [e.g. 1.3.2, master]

**Additional context**

Please let me know how i should do.

Thank you.

**Comment by sewenew** [comment]
First of all, you always need to try-catch code using redis-plus-plus, since it might throw exception. Otherwise, you code will be terminated.

Look like you are using `RedisCluster`. What's exactly the implementation of `RedisClient::instance().get()`? Does it return a `RedisCluster` object or `Redis` object?

> Failed to send command with key: nginxIp

This means it failed to send command to RedisCluster. Normally, this means your cluster's states is unstable, e.g. a slot is moving from source node to destination node, however, source node has already run 'CLUSTER SETSLOT xxx NODE xxx', while the destination node has NOT run it. In this case, you can retry latter, if it still has the problem, you should check if your Redis cluster is stable.

Regards

**Comment by lilelife** [comment]
> First of all, you always need to try-catch code using redis-plus-plus, since it might throw exception. Otherwise, you code will be terminated.
> 
> Look like you are using `RedisCluster`. What's exactly the implementation of `RedisClient::instance().get()`? Does it return a `RedisCluster` object or `Redis` object?
> 
> > Failed to send command with key: nginxIp
> 
> This means it failed to send command to RedisCluster. Normally, this means your cluster's states is unstable, e.g. a slot is moving from source node to destination node, however, source node has already run 'CLUSTER SETSLOT xxx NODE xxx', while the destination node has NOT run it. In this case, you can retry latter, if it still has the problem, you should check if your Redis cluster is stable.
> 
> Regards
RedisClient::instance().get()  will return a  RedisCluster * .  you mean   cluster's states is unstable ，  When is it going to happen a slot is moving from source node to destination node ， then i should use new node? destination node

**Comment by sewenew** [comment]
> you mean cluster's states is unstable

Yes. Some node in cluster might be down.

> When is it going to happen a slot is moving from source node to destination node

Your database admin might resharding the cluster, i.e. moving some slots from one node to another

> then i should use new node?

No. You only need to retry the operation later. When the cluster become stable, RedisCluster will automatically recover.

Regards

**Comment by lilelife** [comment]
ok, think you very much
