### ISSUE TITLE
[FEATURE] support dragonfly

### ISSUE THREAD

**Issue by inaryart** [sewenew/redis-plus-plus#399]
[dragonflydb/dragonfly](https://github.com/dragonflydb/dragonfly) supports all redis equal commands, so can `redis-plus-plus` also support it as a client

**Comment by wingunder** [comment]
On https://dragonflydb.io/, they display the following example, that shows the usage of `redis-cli` with `dragonfly`.
If `redis-cli` works with `dragonfly`, I see no reason why a `redis-plus-plus` client won't work with it.

From https://dragonflydb.io/:
```shell 
# Dragonfly self managed is free and takes 10 seconds to setup.
# Get Dragonfly running
docker run --network=host --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly

# Test with redis-cli
redis-cli PING
```

NOTE: It seems that only a part of the `Redis API` is implemented in `dragonfly`, so if your `redis-plus-plus` app uses something that's not implemented in `dragonfly` yet, it'll obviously not work. An example would probably be `Redis Cluster commands`, as dragonfly has no cluster support yet.

The best would be to test your `redis-plus-plus` app on dragonfly yourself ;)

Regards

**Comment by sewenew** [comment]
The underlying protocol should be the same. You can have a try, if it has problem, feel free to let me know

Regards
