### ISSUE TITLE
[QUESTION]Got compilation error when trying to use zscore with c++11

### ISSUE THREAD

**Issue by ReturnHttp418** [sewenew/redis-plus-plus#401]
**Describe the problem**
Hi, I was trying to use zscore and check if its returned value is equal to zero, however, I get error
```
 error: no match for ‘operator!=’ (operand types are ‘sw::redis::Optional<double>’ and ‘int’)
   45 |   if (result != 0) {
      |       ~~~~~~ ^~ ~
      |       |         |
      |       |         int
      |       sw::redis::Optional<double>
```
I'm using c++11 to compile the redis plus plus and also set it in my project's cmake file,
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
build command `cmake -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local -DREDIS_PLUS_PLUS_CXX_STANDARD=11 -DREDIS_PLUS_PLUS_BUILD_ASYNC=libuv ..`
If I use optional's function I will also get error
```
 error: request for member ‘value’ in ‘* result.sw::redis::Optional<double>::operator->()’, which is of non-class type ‘double’
   38 |   if (result->value() != 0) {
      |               ^~~~~
```
It seems c++11 does not support std::optional and in the header file `zscore` only returns optional<double> 
```
    /// @brief Get the score of the given member.
    /// @param key Key where the sorted set is stored.
    /// @param member Member.
    /// @return The score of the member.
    /// @note If member does not exist, `zscore` returns `OptionalDouble{}` (`std::nullopt`).
    /// @see https://redis.io/commands/zscore
    OptionalDouble zscore(const StringView &key, const StringView &member);
```
Is this an known issue or is there anything wrong with my settings/compilations?

**Environment:**
 - OS: WSL2-ubuntu
 - Compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
 - hiredis version: v1.0.2, master
 - redis-plus-plus version: master

**Comment by sewenew** [comment]
You need to use `operator *` to get the double value:

```
if (*result ! =0) {
}
```

Also it might not make sense to compare a double with 0.

Regards

**Comment by ReturnHttp418** [comment]
What's the correct way to check if the returned result is empty/null when there's no such member in the sorted set? Is it `if(*result != NULL)` ?

**Comment by sewenew** [comment]
If member does not exist, it returns a null Optional<double>, which can be tested with the if statement:

```
double score = 0.0;
if (result) {
    score = *result;
} else {
    // member does not exist.
}
```

Regards

**Comment by ReturnHttp418** [comment]
Thanks! What if I'm using async interface, how can I set the returned data type of future?
```
redis_cluster->zscore(key, value, [](std::future<double>&& fut) {
			try {
				auto result = fut.get();
				if (result)
					return true;
				else
					return false;
			}
			catch (const Error& err) {
				// handle error
			}
			});
```
doesn't seem to be right for the compiler.
Cheers,

**Comment by sewenew** [comment]
`zscore` returns `Optional<double>`, not `double`. So your lambda should be something like the following:

```
[](Future<Optional<double>> &&fut) {
  try {
    auto result = fut.get();
    if (result) {
    } else {
   }
  } catch (...) {
  }
}
```

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close the issue.

Regards
