### ISSUE TITLE
[BUG] 编译错误

### ISSUE THREAD

**Issue by 15910897938** [sewenew/redis-plus-plus#403]
hiredis - 1.0.0
libuv-1.x  https://github.com/libuv/libuv#documentation 
master test_redis 异步接口 编译出错
![Uploading 766ad25a6a79ca2ab6972f6824dab65.jpg…]()

**Comment by 15910897938** [comment]
E:\code\redis-plus-plus\test\src\sw\redis++\test_main.cpp(122): message : 查看对正在编译的 类 模板 实例化“sw::redis::test::AsyncTest<sw::redis::AsyncRedis>”的引用
2>E:\code\redis-plus-plus\src\sw\redis++\async_connection.h(610,69): error C2664: “sw::redis::CallbackClusterEvent<Result,ResultParser,Callback>::CallbackClusterEvent(const std::shared_ptr<sw::redis::AsyncShardsPool> &,const sw::redis::StringView &,sw::redis::FormattedCommand,sw::redis::CommandEvent<Result,ResultParser>::Callback &&)”: 无法将参数 4 从“_Ty”转换为“sw::redis::CommandEvent<Result,ResultParser>::Callback &&”
2>        with
2>        [
2>            Result=bool,
2>            ResultParser=sw::redis::fmt::SetResultParser,
2>            Callback=sw::redis::test::AsyncTest<sw::redis::AsyncRedisCluster>::_test_str::SetReady
2>        ]
2>        and
2>        [
2>            _Ty=sw::redis::test::AsyncTest<sw::redis::AsyncRedisCluster>::_test_str::SetReady
2>        ]
2>        and
2>        [
2>            Result=bool,
2>            ResultParser=sw::redis::fmt::SetResultParser
2>        ]
2>E:\code\redis-plus-plus\src\sw\redis++\async_connection.h(611,1): message : 原因如下: 无法从“_Ty”转换为“sw::redis::CommandEvent<Result,ResultParser>::Callback”
2>        with
2>        [
2>            _Ty=sw::redis::test::AsyncTest<sw::redis::AsyncRedisCluster>::_test_str::SetReady
2>        ]
2>        and
2>        [
2>            Result=bool,
2>            ResultParser=sw::redis::fmt::SetResultParser
2>        ]
2>E:\code\redis-plus-plus\src\sw\redis++\async_connection.h(611,55): message : 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
2>E:\code\redis-plus-plus\src\sw\redis++\async_connection.h(536,5): message : 参见“sw::redis::CallbackClusterEvent<Result,ResultParser,Callback>::CallbackClusterEvent”的声明
2>        with
2>        [
2>            Result=bool,
2>            ResultParser=sw::redis::fmt::SetResultParser,
2>            Callback=sw::redis::test::AsyncTest<sw::redis::AsyncRedisCluster>::_test_str::SetReady
2>        ]
2>E:\code\redis-plus-plus\src\sw\redis++\async_redis_cluster.h(1146): message : 查看对正在编译的函数 模板 实例化“void sw::redis::AsyncConnection::send<Result,ResultParser,Callback>(const std::shared_ptr<sw::redis::AsyncShardsPool> &,const sw::redis::StringView &,sw::redis::FormattedCommand,Callback &&)”的引用
2>        with
2>        [
2>            Result=bool,
2>            ResultParser=sw::redis::fmt::SetResultParser,
2>            Callback=sw::redis::test::AsyncTest<sw::redis::AsyncRedisCluster>::_test_str::SetReady
2>        ]

**Comment by 15910897938** [comment]
如果我把代码修改下就能编译过
---------------------------------------
template <typename Result, typename ResultParser, typename Callback>
class CallbackEvent : public CommandEvent<Result, ResultParser> {
public:
    // add  解决编译问题
	CallbackEvent( FormattedCommand cmd ) :
		CommandEvent<Result, ResultParser>( std::move( cmd ) ) {}

    CallbackEvent(FormattedCommand cmd, Callback &&cb) :
        CommandEvent<Result, ResultParser>(std::move(cmd)), _cb(std::forward<Callback>(cb)) {}

    virtual void set_exception(std::exception_ptr err) override {
        CommandEvent<Result, ResultParser>::set_exception(err);
        _run_callback();
    }

    virtual void set_value(redisReply &reply) override {
        CommandEvent<Result, ResultParser>::set_value(reply);
        _run_callback();
    }

private:
    void _run_callback() {
        assert(_cb);

        try {
            _cb(CommandEvent<Result, ResultParser>::get_future());
        } catch (...) {
            // Catch all possible exceptions thrown by user defined callbacks.
        }
    }

// add  解决编译问题
public:
    std::function<void (Future<Result> &&)> _cb;
};

--------------------------------------
template <typename Result, typename ResultParser, typename Callback>
void AsyncConnection::send(FormattedCommand cmd, Callback &&cb) {
    //auto event = CallbackEventUPtr<Result, ResultParser, Callback>(
    //        new CallbackEvent<Result, ResultParser, Callback>(std::move(cmd),
	//            std::forward<Callback>(cb))); 编译问题

	auto callback = new CallbackEvent<Result, ResultParser, Callback>( std::move( cmd ) );
	callback->_cb = std::forward<Callback>( cb );
	auto event = CallbackEventUPtr<Result, ResultParser, Callback>( callback );

    send(std::move(event));
}


改这两处 就能编译成功 ， 不知道是怎么回事

**Comment by sewenew** [comment]
你的编译器版本是什么？VS2019？还是别的？感觉是编译器的问题，这段代码在GCC和CLANG下是正常的。可以试试换一个高版本的编译器试试。

**Comment by sewenew** [comment]
Finally, I got a Windows box, and reproduced the problem. The problem has been fixed with [this commit](https://github.com/sewenew/redis-plus-plus/commit/764d7f535110694fc6ddbee4c150bab9f44dd299).

Regards
