### ISSUE TITLE
[FEATURE] support XTRIM MINID

### ISSUE THREAD

**Issue by steve-numeus** [sewenew/redis-plus-plus#405]
**Is your feature request related to a problem? Please describe.**
Currently only `XTRIM MAXLEN` is supported by redis-plus-plus; however [redis also supports `XTRIM MINID`](https://redis.io/commands/xtrim)

> MINID: Evicts entries with IDs lower than threshold, where threshold is a stream ID.

**Describe the solution you'd like**
Add `MINID` overload to `xtrim`

**Comment by sewenew** [comment]
Thanks for the proposal! I'll add an overload for it.

Before that, you can use [the generic interface](https://github.com/sewenew/redis-plus-plus#generic-command-interface) to send XTRIM command with MINID:

```
redis.command<long long>("XTRIM", key, "MINID", id, "LIMIT", count);
```

Regards

**Comment by steve-numeus** [comment]
Great, thanks!

**Comment by sewenew** [comment]
@steve-numeus This feature is done. Please take the latest code to have a try.

Regards

**Comment by sewenew** [comment]
Take it easy. If you like the project, feel free to spread it and star it :)

Regards
