### ISSUE TITLE
[QUESTION] async command perfect forwarding issue.

### ISSUE THREAD

**Issue by dkd1111** [sewenew/redis-plus-plus#411]
**Environment:**
 - OS: windows 11
 - Compiler: msvc 14.2, c++17
 - hiredis version: 1.0.2
 - redis-plus-plus version: 1.3.5

```

...
  sw::redis::AsyncRedis redis{connection_options, pool_options};
  std::unique_ptr<std::string> up{new std::string{"test_code"}};
  redis.command<std::vector<std::string>>(
      "time", [m = std::move(up)](
          sw::redis::Future<std::vector<std::string>> &&f) mutable {
    try {
      auto v = f.get();
    } catch(const sw::redis::Error &e) {
      std::cerr << e.what() << std::endl;
    }
  });

```
complie error:  "attempting to reference a deleted function"

In the code above, I used std::move because there is no copy operation of unique-ptr .
Perfect forwarding lambda is no problem, but just complie error.
copy constructor is only needed during build time.

How can I solve it?

**Comment by sewenew** [comment]
Thanks for reporting the problem! I'll do some research on it.

Regards

**Comment by dkd1111** [comment]
Thanks for comments.

https://stackoverflow.com/questions/25421346/how-to-create-an-stdfunction-from-a-move-capturing-lambda-expression

Compiler needs copy constructor of unique-ptr because lambda is assigned to std::function variable.
CallbackEvent class(in async_connection.h) has "std::function<void (Future<Result> &&)> _cb".

If type of "_cb" is changed(std::function<void (Future<Result> &&)> -> Callback), I can solve the build error.
However, I don't know if this is a good way to solve it.

**Comment by sewenew** [comment]
@dkd1111 Thanks for your info! The change looks good to me, and I've fixed the problem. Please check the latest code on master branch for testing.

Regards
