### ISSUE TITLE
CoRedisCluster Constructor increment EventLoopSPtr

### ISSUE THREAD

**Issue by nqf** [sewenew/redis-plus-plus#416]
```
    CoRedisCluster(const ConnectionOptions &opts,
            const ConnectionPoolOptions &pool_opts = {}) : _async_redis(opts, pool_opts) {}


    AsyncRedisCluster(const ConnectionOptions &opts,
            const ConnectionPoolOptions &pool_opts = {},
            Role role = Role::MASTER,
            const EventLoopSPtr &loop = nullptr);
```

**Comment by sewenew** [comment]
So far, `CoRedisCluster`'s implementation is based on `AsyncRedisCluster`. However, that might be changed in the future, so `EventLoopSPtr` is not a parameter of `CoRedisCluster`'s constructor.

Regards

**Comment by nqf** [comment]
> So far, `CoRedisCluster`'s implementation is based on `AsyncRedisCluster`. However, that might be changed in the future, so `EventLoopSPtr` is not a parameter of `CoRedisCluster`'s constructor.
> 
> Regards

but， If EventLoopSPtr cannot be passed externally， The coroutine will run in the default EventLoopSPtr，This is very inflexible

**Comment by nqf** [comment]
> > The coroutine will run in the default EventLoopSPtr
> 
> If I understand correctly, coroutine still runs in main thread, and the underlying socket operations, e.g. recv, send, run in event loop's thread.
> 
> > This is very inflexible
> 
> What do you mean by _inflexible_? Do you want to share the event loop between multiple `CoRedis` object? However, as I mentioned, the event loop stuff is implementation details, and should not be exposed to end user.
> 
> Regards

```
        void await_suspend(std::coroutine_handle<> handle) {
            _async_redis->co_command_with_parser<void, DefaultResultParser<void>>(_key, std::move(_cmd),
                    [this, handle](Future<void> &&fut) mutable {
                        _result = std::move(fut);

                        handle.resume();  // The coroutine will be resume in the event  loop thread
                    });
        }
```

**Comment by sewenew** [comment]
Sorry, but I did not get the point (I'm not an expert on coroutine)? What's exactly the problem?

Regards

**Comment by nqf** [comment]
I only hope that CoRedisCluster can pass my own event loop during construction，In this way, during coroutine resume, it will run in my own event loop thread，There is another point， AsyncRedisCluster Support the transmission of custom event loops， So I think CoRedisCluster should also support it

**Comment by nqf** [comment]
> There're 3 parts when running coroutine with CoRedisCluster:
> 
> 1. start a coroutine with `co_await co_redis.command()`
> 2. Redis related stuff runs in the background, until data is ready, and resume the coroutine, i.e. async callback is called.
> 3. co_await returns
> 
> The step 1 and 3 run in main thread, only step 2 runs in the event loop thread. So you want step 2 runs in your own event loop thread?
> 
> > AsyncRedisCluster Support the transmission of custom event loops， So I think CoRedisCluster should also support it
> 
> As I mentioned before, CoRedisCluster might not be implemented with AsyncRedisCluster in the future, and the event loop might not be part of the implementation. That's why it's not included. Even with AsyncRedisCluster, the event loop parameter is experimental.
> 
> I can add the event loop as a parameter of CoRedisCluster, however, you need to be careful that the interface is experimental, and might be removed in the future.
> 
> Regards

I think you have some misunderstanding， When 3 is executed, it is already in the everloop thread， It will not return to the main thread

**Comment by nqf** [comment]
```
1. main thread
2. co_await co_redis.command()  // Suspend
3.  event loop thread

```

**Comment by sewenew** [comment]
I did some tests, and yes, you're right, i.e. step 3 runs in the event loop thread. Thanks for the important info!

So, the original design of CoRedis has a big flaw, once the coroutine returns, all logic runs in the event loop thread, and the loop might be blocked, and cannot send command to or receive response from Redis. For example, two threads shared a CoRedis objects, and both threads use coroutine to send messages to Redis. If one of the thread block, e.g. sleep for a long time, once it returns from co_await, the other thread can never be resumed from the coroutine.

I'm wondering if CoRedis has an event loop as parameter of constructor, how can you avoid this problem? It seems that we need to redesign the underlying implementation to solve the problem. Say, have a thread pool for the coroutine.

Do you have any good idea on it?

Regards

**Comment by nqf** [comment]
I don't think we need to solve this problem，  The user should control it, But we should be able to set the  resume  thread of the coroutine

**Comment by sewenew** [comment]
I have to say that I still don't have a good idea on the coroutine interface. Neither the current interface, or interface with event loop is the best solution.

Anyway, I created a *coro* branch, and added event loop as parameter for `CoRedisCluster`'s constructor. You can have a try. And I'll try to find a better solution.

Regards
