### ISSUE TITLE
[BUG] Cluster class does not work with generic time command

### ISSUE THREAD

**Issue by bigsamich** [sewenew/redis-plus-plus#418]
**Describe the bug**
Issuing a generic time command with a redis cluster object fails to compile
It compiles and works with a redis object.

**To Reproduce**

RedisCluster _redisCluster("tcp://127.0.0.1:30001");
vector<string> result;
_redisCluster.command("time", std::back_inserter(result));

**Expected behavior**
I expect the RedisCluster object to behave the same as a Redis Object

**Environment:**
 - OS: ubuntu
 - Compiler: gcc 11.3.0
 - hiredis version: master
 - redis-plus-plus version: master

**Comment by sewenew** [comment]
The `time` command does not have a key, so you need to create a `Redis` object with `RedisCluster::redis`, and send the command with it:

```
_redisCluster.redis("hash-tag", false).command("time", std::back_inserter(result));
```

Check the [doc](https://github.com/sewenew/redis-plus-plus#interfaces) for detail.

Regards

**Comment by bigsamich** [comment]
Sorry for the late response. Thank you for the help.

**Comment by sewenew** [comment]
Take it easy. If you find redis-plus-plus helpful, feel free to star it :)

Regards
