### ISSUE TITLE
how select db number form redis Sentinel

### ISSUE THREAD

**Issue by zkdada** [sewenew/redis-plus-plus#42]
ConnectionOptions connection_opts;
    //connection_opts.password = "auth";  // Optional. No password by default.
    connection_opts.connect_timeout = std::chrono::milliseconds(200);   // Required.
    connection_opts.socket_timeout = std::chrono::milliseconds(200);    // Required.
    connection_opts.db = 1;

    ConnectionPoolOptions pool_opts;
    //pool_opts.size = 3; // Optional. The default size is 1.

    _redis = new Redis(sentinel, "mymaster", Role::MASTER, connection_opts, pool_opts);

I want to change the number of db，how？

**Comment by sewenew** [comment]
Hi @zkdada 

If you want to select a DB number, you can set the `connection_opts.db` parameter, and create a `Redis` object with this option. However, you cannot dynamically change this db number. Instead, you need to create another `Redis` object with `connection_opts.db` setting to another number.

Regards

**Comment by zkdada** [comment]
@sewenew 
thanks a lot!
