### ISSUE TITLE
Sentinel always throws exception "Failed to create connection with sentinel"

### ISSUE THREAD

**Issue by oledahle** [sewenew/redis-plus-plus#426]
I have a Redis master and replica, monitored by three sentinels, all as docker instances. All seem fine with redis-cli and using redis-plus-plus to connect directly to the master. But when I try to use the Sentinel object, I always get the exception "Failed to create connection with sentinel". Code  very close to Readme example:

        sw::redis::SentinelOptions sentinel_opts;
        std::vector<std::pair<std::string, int>> nodes;
        sentinel_opts.nodes = { { "172.18.0.4", 5000 } }; // Required. List of Redis Sentinel nodes.
        sentinel_opts.password = "dummy";

        // Optional. Timeout before we successfully connect to Redis Sentinel.
        // By default, the timeout is 100ms.
        sentinel_opts.connect_timeout = std::chrono::milliseconds(500);

        // Optional. Timeout before we successfully send request to or receive response from Redis Sentinel.
        // By default, the timeout is 100ms.
        sentinel_opts.socket_timeout = std::chrono::milliseconds(200);
        m_sentinel = std::make_shared<sw::redis::Sentinel>(sentinel_opts);

        sw::redis::ConnectionOptions connection_opts;
        connection_opts.user = "default";
        connection_opts.password = "";
        connection_opts.connect_timeout = std::chrono::milliseconds(200); // Required.
        connection_opts.socket_timeout = std::chrono::milliseconds(100);  // Required.
        connection_opts.db = 0; // Always select dabase 0

        sw::redis::ConnectionPoolOptions pool_opts;
        pool_opts.size = 3; // Optional. The default size is 1.

        // Get the master named "novamaster" from the Sentinel
        m_redis_master = std::make_unique<sw::redis::Redis>(
            m_sentinel, "novamaster", sw::redis::Role::MASTER, connection_opts, pool_opts);
        std::string pingResponse = m_redis_master->ping();
---
The exeption happens when I call m_redis_master->ping(). In the debugger, it seems like the sentinel node is in the list m_broken_sentinels inside the sentinel object, can that be a clue?

**Environment:**
 - OS: Fedora 36
 - Compiler: GCC 12.2.1
 -  Redis: 6.2.7
 - hiredis version: 1.0.2-2
 - redis-plus-plus version: 1.3.6

**Comment by sewenew** [comment]
> it seems like the sentinel node is in the list m_broken_sentinels inside the sentinel object

It means that the client cannot connect to sentinel with the given options.

You can test these options with redis-cli to see if it can connect to sentinel and get the monitored master successfully: `redis-cli -h 172.18.0.4 -p 5000 -a dummy SENTINEL get-master-addr-by-name novamaster`.

Regards

**Comment by oledahle** [comment]
Thank you, it was the password option that should be removed for this case. (Almost duplicate of [Issue 100](https://github.com/sewenew/redis-plus-plus/issues/100), sorry.)

For reference, I was confused by the differences of -a and --pass options for redis-cli. --pass worked, wheras -a gave an error:

```
$ redis-cli -h 172.18.0.4 -p 5000 --user default --pass dummy SENTINEL get-master-addr-by-name novamaster
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "172.18.0.2"
2) "6379"
$ redis-cli -h 172.18.0.4 -p 5000 -a dummy SENTINEL get-master-addr-by-name novamaster
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
$
```
