### ISSUE TITLE
[Question]RedisCluster master node down，the redis will be unavailable.

### ISSUE THREAD

**Issue by jo2osaka** [sewenew/redis-plus-plus#428]
When using rediscluster, when the connected node is the master node, if the master node goes down or disconnects, then redis will be unavailable. If the connected node is a slave node, it can be used normally even if the node is disconnected.

**Comment by jo2osaka** [comment]
ConnectionOptions opts;
	opts.host = config->host;
	opts.port = config->port;

	// Optional. Max time to wait for a connection. 0ms by default, which means wait forever.
	// Say, the pool size is 3, while 4 threds try to fetch the connection, one of them will be blocked.
	opts.socket_timeout = std::chrono::milliseconds(3000);

	ConnectionPoolOptions pool_opts;
	pool_opts.size = config->poolsize;
	// Optional. Max lifetime of a connection. 0ms by default, which means never expire the connection.
	// If the connection has been created for a long time, i.e. more than `connection_lifetime`,
	// it will be expired and reconnected.
	pool_opts.connection_lifetime = std::chrono::minutes(10);
       auto redisCluster = AsyncRedisCluster(opts, pool_opts);

**Comment by sewenew** [comment]
Fixed with [this commit](https://github.com/sewenew/redis-plus-plus/pull/429/commits/d34a0a4526e022c9447ccd76cc84f19da02606ab).

Sorry for the inconvenience...

Regards

**Comment by sewenew** [comment]
`publish` is different than other commands, e.g. `get`, `set`. Redis Cluster does not redirect `publish` command based on key. So if you only send `publish` to Redis, it will connect to the node you specified in constructor, and redis-plus-plus cannot update the node-slot mapping. With [this change](https://github.com/sewenew/redis-plus-plus/commit/2d7d83aaf2f297bd88450e5ae26e82b442574e19), redis-plus-plus will asynchronously update the mapping when initializing AsyncRedisCluster, and repeat trying to update the mapping if fails.

The latest code should fix your problem. Please take a try.

Regards

**Comment by jo2osaka** [comment]
Test ok! Thks!

**Comment by zhangyafeikimi** [comment]
@sewenew hi, would you like to make it new release containing this patch?

**Comment by sewenew** [comment]
@zhangyafeikimi Yes, I'll make a new release this week with some other changes.

Regards
