### ISSUE TITLE
shards_pool.h:90:36: error: expected ‘)’ before ‘min’ 

### ISSUE THREAD

**Issue by tingtan1015** [sewenew/redis-plus-plus#434]
I want to use redis-plus-plus in an existing project.
I only did is to put #include <sw/redis++/redis++.h> in a hpp file.
When I compile it:
![截屏2022-12-19 15 49 21](https://user-images.githubusercontent.com/65152528/208374800-04e3e2f1-07ff-45da-adaa-0df8ad91e3c6.jpeg)
I wonder why this happen?

**Comment by sewenew** [comment]
A possible reason is that your other code defined a Marco, named `min`.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
