### ISSUE TITLE
connection pool 并不能保证  几乎同时发送的两个请求 并行

### ISSUE THREAD

**Issue by teddy-hoo** [sewenew/redis-plus-plus#437]
**Describe the bug**
https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/async_redis_cluster.h#L1014-L1017

这里  在  函数return之后   GuardedAsyncConnection被析构   

实际的connection又会被放回到pool里
但是此时实际的connection并未真正被使用  假设此时的请求是A  

此时如果用户再发送一个请求B 就会复用这个connection  这样就会导致   A 和  B 在同一个 连接里 被串行执行

**Comment by sewenew** [comment]
connection pool不是用来保证请求并行的，而是为了复用链接，减少不必要的创建链接工作。因此，两个请求完全有可能在同一个链接中处理。

祝好！

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
