### ISSUE TITLE
Getting CMake Error for HIREDIS_TLS_LIB

### ISSUE THREAD

**Issue by narendra-hn-by** [sewenew/redis-plus-plus#440]
**Describe the problem**

Getting the following error while trying to build using CMake:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HIREDIS_TLS_LIB
    linked by target "redis++" in directory /redis-plus-plus-1.3.7
TEST_HIREDIS_TLS_LIB
    linked by target "test_redis++" in directory /redis-plus-plus-1.3.7/test

**Environment:**
 - OS: ubuntu
 - hiredis version:  v1.1.0, 
 - redis-plus-plus version: 1.3.7

How to fix this?

**Comment by narendra-hn-by** [comment]
had to use USE_SSL=1 during make install.

**Comment by mankouzhuya** [comment]
I got the same trouble

**Comment by sewenew** [comment]
@mankouzhuya You need to enable TLS support for hiredis installation, then build redis-plus-plus with TLS support. Check the [doc](https://github.com/sewenew/redis-plus-plus/#tlsssl-support) for detail.

Regards
