### ISSUE TITLE
Support READONLY connections and commands

### ISSUE THREAD

**Issue by prat0088** [sewenew/redis-plus-plus#45]
https://redis.io/commands/readonly

To help support scale out scenarios by distributing read-only workloads across replicas.

I think we would need to create two pools, one for readwrite and one for readonly, then add an optional flag to command().

**Comment by sewenew** [comment]
Hi @prat0088 

Can you describe your scenario in more detail?

If you are running a Redis master with a slave, you can create 2 `Redis` instances, one for the master, and the other for slave. Then you can write with the first instance, and read with the second one. If you are running Redis Sentinel, you can also use the [sentinel interface](https://github.com/sewenew/redis-plus-plus#redis-sentinel) to create these 2 `Redis` instances.

Normally, Redis slave is configured to be [readonly](https://github.com/antirez/redis/blob/unstable/redis.conf#L404). So if you are trying to send write command to slave, you'll get an error reply.

If you are running Redis Cluster, by now, there's no way to create connection to slave node. And there's an [issue](https://github.com/sewenew/redis-plus-plus/issues/20) to track it. I'll fix it in the future.

Sorry for the late reply...

Regards

**Comment by prat0088** [comment]
I'm prototyping Redis for our application.  I plan to have a cluster with slaves / replicas.  It looks like the existing issue you link to is relevant. 

I've seen this behavior implemented by StackExchange.Redis for C# by passing an optional flag to the commands to specify they are read-only commands, and then the library may pick a read-only connection from the connection pool.

**Comment by sewenew** [comment]
@prat0088 Now redis-plus-plus supports reading from slave nodes in Redis Cluster. Instead of passing a flag for each command, you can create a `RedisCluster` object with `Role::SLAVE` as the third parameter. The created `RedisCluster` object will connect to slave nodes, and send READONLY command automatically. So that you can read from slaves to scale read.

```
ConnectionOptions connection_options;
connection_options.host = "127.0.0.1";
connection_options.port = 7000;

ConnectionPoolOptions pool_options;
pool_options.size = 3;

RedisCluster cluster(connection_options, pool_options, Role::SLAVE);
auto val = cluster.get("key");
```

Please check the [doc](https://github.com/sewenew/redis-plus-plus#read-from-replica) for detail.

Regards
