### ISSUE TITLE
[BUG] Error using redis-plus-plus & log4cpp

### ISSUE THREAD

**Issue by valendovsky** [sewenew/redis-plus-plus#451]
**Describe the bug**
I use redis++ and log4cpp libraries in my project. I installed them using the 'vcpkg'. If 'include redis++'  are added after 'include log4cpp', then the compiler outputs more than 100 errors inside the redis-plus-plus library. Even if you add them to a simple 'HelloWorld' project, we will still get errors.
If you use 'include redis++' first, then the problem disappears. Because of this, you have to dance with a tambourine so that includes are located in the right sequence.

**To Reproduce**
For example:
#include <log4cpp/Appender.hh>
#include <log4cpp/FileAppender.hh>
#include <log4cpp/OstreamAppender.hh>
#include <log4cpp/Layout.hh>
#include <log4cpp/BasicLayout.hh>
#include <log4cpp/Category.hh>
#include <log4cpp/Priority.hh>
#include <sw/redis++/redis++.h>

**Environment:**
 - OS: Windows 10
 - Compiler: VS Community 2019
 - hiredis version: 1.0.2#4 (from vcpkg)
 - redis-plus-plus version: 1.3.2#1 (from vcpkg)

Thanks.

**Comment by sewenew** [comment]
Can you give some examples of the error messages you got?

Also since the version (1.3.2) you used is too old, can you try the latest version of redis-plus-plus?

Regards

**Comment by valendovsky** [comment]
I tried the latest version of redis-plus-plus from the GitHub repository. And the errors disappeared. Now the project has been compiled and works without problems. I launched a project for Windows and Linux.
Thanks
