### ISSUE TITLE
Binary packages for ARM64 debian for redis-plus-plus and hiredis, cross compile for ARM64

### ISSUE THREAD

**Issue by sknagappan** [sewenew/redis-plus-plus#457]
like to run redis-plus-plus in ARM64 debian linux

Is there binary packages available, which i can use directly?

like most packages, i dont see configure script like 
./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu
so what's the easiest way to cross compile?

**Comment by sewenew** [comment]
> Is there binary packages available, which i can use directly?

Sorry, but there's no binary package available. I'm not sure if [vcpkg](https://vcpkg.io/en/index.html) or [Conan](https://conan.io/center/redis-plus-plus) works for you. You can have a try.

> i dont see configure script like ./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu

redis-plus-plus does not support building with `configure`, instead, you can use cmake to build it or use third party package management tool like vcpkg or Conan to compile.

> what's the easiest way to cross compile?

Sorry, I'm not familiar with cross compile. You might need to ask help from some cross compiling expert. So sorry for that.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
