### ISSUE TITLE
Are there any use cases?

### ISSUE THREAD

**Issue by dylanzjy** [sewenew/redis-plus-plus#46]
We are finding a c++ redis client that supports cluster mode and password. Are there any online use cases of redis-plus-plus?

**Comment by sewenew** [comment]
Hi @dylanzjy 

Yes, it has been used in production environment, and [fully tested](https://github.com/sewenew/redis-plus-plus/#run-tests-optional). If you have any problem on *redis-plus-plus*, feel free to [let me know](https://github.com/sewenew/redis-plus-plus/issues), and I'll response it ASAP.

If you like it, also feel free to star it :)

Regards
