### ISSUE TITLE
[Question] exception on plain redis command

### ISSUE THREAD

**Issue by Avalanchecoder** [sewenew/redis-plus-plus#465]
I'm sending following command to redis
auto val = redis.command<OptionalString>("ZADD",keys,"1","one");
    if (val) {
    std::cout << *val << std::endl;
}
which returns an integer but library is throwing following error.
what():  expect STRING or STATUS or VERB or BIGNUM reply, but got INTEGER reply.
Please let me know if there is any discussion channel which is active other than this so i can post my question there.

**Comment by sewenew** [comment]
You should specify template parameter for `Redis::command` method, otherwise, it returns a `ReplyUPtr` object:

```
// since this command returns integer reply, you can specify `long long` as the template parameter.
auto val = redis.command<long long>("ZADD", keys, "1", "one");
cout << val << endl;
```

> Please let me know if there is any discussion channel which is active other than this so i can post my question there.

You can post your question on stackoverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis). That's also the recommended way :)

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue. If you still have problem with it, feel free to reopen it.

Regards
