### ISSUE TITLE
Question: is Redis Object is thread-safe

### ISSUE THREAD

**Issue by felixyao** [sewenew/redis-plus-plus#47]
Hi

When Redis with a single connection. The connection seems like shared in multi-threads without any protection.  So as the underlying redisContext  object.
redisContext  itself is not thread safe. Does that means the Redis object in this case is also thread unsafe?

**Comment by sewenew** [comment]
Hi @felixyao 

**`Redis` object is thread-safe**.

Yes, the connection is shared in multi-threads, but it's **protected** with mutex.

In fact, although there's only one connection, the underlying implementation creates a connection pool of size 1. When you call member functions of `Redis`, it will fetch the connection from the connection pool, send command with the connection, and release the connection back to the pool. The connection pool is protected with a mutex. So it's safe to call `Redis`' member functions with multiple threads.

Most part of *redis-plus-plus* is thread-safe, and the thread-unsafe parts have been documented in the README.md file. For example, `Transaction`, `Pipeline`, and `Subscriber` are NOT thread-safe.

If you still have any problem on thread-safety, feel free to let me know :)

Regards

**Comment by felixyao** [comment]
Hi se

**Comment by felixyao** [comment]
Hi sewenew

Thank you for the response. I figured it out how connections are protected. It is way better then I expected. Thank you again
