### ISSUE TITLE
MinGW suseconds_t compile problem

### ISSUE THREAD

**Issue by dellorogiulio** [sewenew/redis-plus-plus#48]
Hi, I'm currently building redis-plus-plus with MinGW64. 
I found an error while trying to compile _connection.cpp_, in particular the `Connection::Connector::_to_timeval(const std::chrono::milliseconds &dur)` function.
I had an undefined symbol to  suseconds_t in `static_cast<suseconds_t>(msec.count())`. This is correct since I'm under windows and the winsock timeval is defined as:
```
typedef struct timeval {
long tv_sec;
long tv_usec;
} TIMEVAL, *PTIMEVAL, *LPTIMEVAL;
```
Is it possibile that you relate on the hideris timeval definition? Because, looking to the hiredis defines, I see guards for _MSC_VER which are probably not meet for MinGW.
Hover, I was able to fix this error by using WIN32 guards:

```
#ifdef WIN32

timeval Connection::Connector::_to_timeval(const std::chrono::milliseconds &dur) const {
    auto sec = std::chrono::duration_cast<std::chrono::seconds>(dur);
    auto msec = std::chrono::duration_cast<std::chrono::microseconds>(dur - sec);
    return {
        static_cast<long>(sec.count()),
        static_cast<long>(msec.count())
    };
}

#else

timeval Connection::Connector::_to_timeval(const std::chrono::milliseconds &dur) const {
    auto sec = std::chrono::duration_cast<std::chrono::seconds>(dur);
    auto msec = std::chrono::duration_cast<std::chrono::microseconds>(dur - sec);

    return {
            static_cast<std::time_t>(sec.count()),
            static_cast<suseconds_t>(msec.count())
    };
}

#endif
```
Is this change acceptable to you?
Thanks in advance

**Comment by sewenew** [comment]
Hi @dellorogiulio 

I fixed this problem by implicit converting `msec.count()` to `suseconds_t` or `long`:

```
timeval Connection::Connector::_to_timeval(const std::chrono::milliseconds &dur) const {
    auto sec = std::chrono::duration_cast<std::chrono::seconds>(dur);
    auto msec = std::chrono::duration_cast<std::chrono::microseconds>(dur - sec);

    timeval t;
    t.tv_sec = sec.count();
    t.tv_usec = msec.count();
    return t;
}
```

I don't have MinGW64 environment, please try it with MinGW64, and give me some feedback.

Thanks a lot for finding the bug!

Regards

**Comment by dellorogiulio** [comment]
All seems good now!
Thanks!
