### ISSUE TITLE
Support of Redis modules[QUESTION]

### ISSUE THREAD

**Issue by georgasa** [sewenew/redis-plus-plus#481]
Hi!

Do you support Redis modules (custom commands)? Is it covered by the generic command interface?
https://github.com/sewenew/redis-plus-plus#generic-command-interface

Thank you!

**Comment by sewenew** [comment]
Yes, you can use generic command interface to send custom commands for Redis Modules. Also there's a redis-plus-plus-modules lib for Redis modules. Check [this](https://github.com/sewenew/redis-plus-plus/#redis-modules) for detail.

Regards
