### ISSUE TITLE
[QUESTION] How can I user hset() with multiple fields together?

### ISSUE THREAD

**Issue by mlanzuisi** [sewenew/redis-plus-plus#483]
I'm using the hset() function as described in the readme file examples.
Is it possible to use it to match the 

HSET key field value [field value ...]

syntax (with multiple fields/values)?

**Comment by sewenew** [comment]
You can try the following code:

```
std::unordered_map<std::string, std::string> m = {{"f1", "v1"}, {"f2", "v2"}};
redis.hset("hash", m.begin(), m.end());

redis.hset("hash", {std::make_pair("f1", "v1"), std::make_pair("f2", "v2")});
```

Also check redis.h for more info.

Regrads

**Comment by mlanzuisi** [comment]
Thank you for the support, I will check better redis.h in the future
