### ISSUE TITLE
Support of binary data

### ISSUE THREAD

**Issue by ZiroDiv** [sewenew/redis-plus-plus#494]
Currently the redis-plus-plus functions mainly supports Strings
It will be nice add support of binary data so no base64 conversion is needed when we need to use binary data (like images, wavs etc)
this applies to many features like set/get, pub/sub commands etc

**Comment by sewenew** [comment]
redis-plus-plus DOES support binary data. Most interfaces take `StringView` as parameter. You can create a `StringView` object with binary data's pointer and length.

```
char *buf; // your binary data's start pointer
size_t len; // length of your binary data.

redis.set("key", StringView(but, len));
```

Regards
