### ISSUE TITLE
[TEST][MinGW][Win10] Redis-plus-plus Test under MinGW

### ISSUE THREAD

**Issue by dellorogiulio** [sewenew/redis-plus-plus#50]
Hi @sewenew,
I open an "issue" to keep track of tests under MinGw. Maybe someone is interested in them,
### Preface
I'm running redis 4.0 under Windows 10 natively (NO WSL), so I could not test some redis 5.x functionalities. Sorry about that but I was not able to find a Win10-native redis 5.0 distribution.
For this reason, I need to comment out:
- `_test_zpop()` (_zset_cmds_test.hpp_)
- `_test_bzpop()` (_zset_cmds_test.hpp_)
- `_test_stream_cmds()` (_stream_cmds_test.hpp_)
- `_test_group_cmds()` (_stream_cmds_test.hpp_)

Currently I'm not setting up a RedisClaster, I should update this topic once I can test Cluster too. 
Trying to run `_test_multithreads` with `pool_opts.size = 10`  bring my virtual machine to never ends test.. I tried to leave it runs for about 4 hours but nothing goes further. 
Even reducing  `pool_opts.size = 2` I was not able to terminate thread test.s 

### TESTS
```
Testing Redis...
Pass sanity tests
Pass connection commands tests
Pass keys commands tests
Pass string commands tests
Pass list commands tests
Pass hash commands tests
Pass set commands tests
Pass zset commands tests
Pass hyperloglog commands tests
Pass geo commands tests
Pass script commands tests
Pass pubsub tests
Pass pipeline and transaction tests
```

**Comment by sewenew** [comment]
Thanks @dellorogiulio ! Great job!

Could you please also share how to build and install redis-plus-plus on  MinGW? I'm not sure if the [building steps](https://github.com/sewenew/redis-plus-plus#installation) I mentioned in README.md also works on MinGW.

Thanks again!

Regards

**Comment by dellorogiulio** [comment]
Hi @sewenew ,
Under MinGw I generally re-build everything from source. 
So I clone the hiredis repo, add it as CMake submodule and link it against redis-plus-plus!

**Comment by sewenew** [comment]
Good! So the install instruction in README works under MinGW. Thanks a lot!

Regards
