### ISSUE TITLE
Pub/Sub questions

### ISSUE THREAD

**Issue by pasta737** [sewenew/redis-plus-plus#502]
Hi 
I have a couple of questions related to Pub/Sub thread safety and invalidation of the subscriber due to throwing an exception. I hope that you can help. 

The Wiki states that the **Subscriber** methods are not thread safe. I was planning to run a **Subscriber->consume()** loop with required exception handling in its own separate thread. Other client threads will call **Subscriber->subscribe()/unsubscribe()** from within a mutex lock. As it would seem that **consume()** cannot be locked using the same mutex, will this be thread safe? Otherwise, how can **subscribe->consume()** calls be interrupted? 

When a **Subscriber->subscribe()/unsubscribe()** methods throws an exception (not _ReplyError_ or _TimeoutError_), I understand that the **Subscriber** object is invalidated and must be recreated. What happen to the blocking (with timeout) call to **Subscriber->consume()**? Will this also return with a similar exception? 

Thanks in advance

**Comment by sewenew** [comment]
> will this be thread safe?

NO. It's NOT thread-safe.

> how can subscribe->consume() calls be interrupted?

Set socket_timeout, and handle the TimeoutError exception, or publish a STOP message. Check [this](https://github.com/sewenew/redis-plus-plus/issues/338) and [this](https://github.com/sewenew/redis-plus-plus/issues/171) of example.

Regards
