### ISSUE TITLE
[QUESTION] Conan package for latest version?

### ISSUE THREAD

**Issue by JStatnekov** [sewenew/redis-plus-plus#504]
I use Conan as my package management system and would like to use it to retrieve the latest version of Redis++ but the [Conan repo](https://conan.io/center/redis-plus-plus) hasn't been updated since 1.3.7. Would it be possible for you to push the latest version to Conan?

**Comment by sewenew** [comment]
Sorry, but I'm not familiar with Conan, and not the maintainer of this Conan repo. However, it seems that someone has already updated redis-plus-plus to the latest version, i.e. 1.3.10. Check [this](https://github.com/conan-io/conan-center-index/pull/18509) for detail. I don't know why Conan repo does not show it on the website.

Regards

**Comment by JStatnekov** [comment]
Oh awesome, that'll hopefully get merged soon and it'll be available in [conan center](https://conan.io/center/redis-plus-plus).

It's worth checking out Conan, it's a super convenient way of managing the 3rd party libraries you might use in a project.

**Comment by sewenew** [comment]
Thanks for your info! I'll try it :)

Regards
