### ISSUE TITLE
[QUESTION] Is there any way to increase the resources used for the async event loop?

### ISSUE THREAD

**Issue by mrichmon** [sewenew/redis-plus-plus#508]
**Describe the problem**
My workload is issuing around 7K redis mget operations per second. I am using redis++ async cluster routines to perform these calls. Using the same code paths with low numbers (< ~20) operations per second I see the query round trip time around 1 millisecond or less to my 40 node redis cluster (after the connections have warmed up).

When performing thousands of queries per second I see the round-trip redis mget time increase to as much as 45 milliseconds.

I suspect that I may be saturating the event loop threads. Do you have a recommended way for users of redis++ to increase the thread pool used by the redis++ event loop? My workload will require closer to 20K redis operations per second when fully scaled up.

Any other recommendations for tuning redis++ to process 20K+ redis operations per second?

**Environment:**
 - OS: CentOS 7.5
 - Compiler: clang version 5.0.1 x86_64
 - hiredis version: v1.1.0
 - redis-plus-plus version: v1.3.10

**Comment by sewenew** [comment]
Please give me the code you used, so that I can do some search.

> Do you have a recommended way for users of redis++ to increase the thread pool used by the redis++ event loop? 

The event loop does not own a thread pool.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close it.

Regards
