### ISSUE TITLE
Create Redis object using ConnectionOptions in classes

### ISSUE THREAD

**Issue by dellorogiulio** [sewenew/redis-plus-plus#51]
Hi @sewenew ,
I would like to initialize a `sw::redis::Redis` obj in a class with a` sw::redis::ConnectionOptions` object.
Consider the following example:

```
using namespace sw:redis;

class MyClass
{
   public:
	MyClass() :
	   connection_options_(),
	   redis_(connection_options_)
	{}


   private:
	ConnectionOptions connection_options_;
	Redis redis_;

};
```
I would like to set `connection_options_.socket_timeout` and then pass the correct `connection_options_` to `redis_`. Currently I'm not able to do that since `ConnectionOption `does not have a constructor which accepts this parameter. Moreover, it is not possibile to initialize  `ConnectionOption ` with an initialization list (something like `{ConnectionType::TCP, "12.0.0.1", 6379, etc}`). In addition, no default constructor for `redis_` is define, so the only option I see here is to create a `Redis*` and manually allocate it. Something like:
```

using namespace sw:redis;

class MyClass
{
   public:
	MyClass() :
		connection_options_(),
		redis_(connection_options_)
		{
                        connection_options_.host = "127.0.0.1";
	                connection_options_.port = 6379;
			connection_options_.socket_timeout = std::chrono::seconds(1);
			redis_ = new Redis(connection_options_);
		}


   private:
	ConnectionOptions connection_options_;
	Redis* redis_;

};

```

Am I missing something?

Thanks in advance

**Comment by sewenew** [comment]
Hi @dellorogiulio 

You can have a small function that builds a `ConnectionOptions`, and then pass it to the constructor of `Redis`.

Try the following code: 

```
class MyClass {
public:
    MyClass() : 
        connection_options_(_build_options()),
        redis_(connection_options_) {}

private:
    ConnectionOptions _build_options() {
         ConnectionOptions opts;
         opts.socket_timeout = std::chrono::seconds(1);
        // set other options
        return opts;
    }

    ConnectionOptions connection_options_;

    // NOTE: MUST define `redis_` AFTER `connection_options_`
    Redis redis_;
};
```

Also if you really need a pointer to Redis, try `std::unique_ptr<Redis>` or `std::shared_ptr<Redis>`. It's not a good idea to use raw pointer.

Regards

**Comment by dellorogiulio** [comment]
I agree with the function, but it's not a clean solution. Why not provide a more friendly constructor for ConnectionOptions? For example with an intialization list?

**Comment by sewenew** [comment]
Because there're too many options. If we have a constructor, it won't be helpful, since user has to specify too many parameters.

For example: you only want to modify the `socket_timeout` option, and keep other options use the default value, but you have to write something like:
```
ConnectionOptions(ConnectionType::TCP,
                                  "127.0.0.1", 6379,
                                  "", 
                                  "default",
                                  "",
                                  0,
                                  false,
                                  std::chrono::milliseconds{},
                                  std::chrono::milliseconds(1))
```

That's really annoying.

**Comment by dellorogiulio** [comment]
I agree with you which could be annoying, but such a constructor is clear in all options and we can  directly see all connection settings.
Of course this is just an opinion!

**Comment by sewenew** [comment]
Hi @dellorogiulio 

IMHO, when there're too many options, a simple struct is good enough, and flexible. Some other C++ libraries also take this solution, e.g. RocksDB's [DBOptions](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L357).

In fact, you can also use an URI to initialize Redis: *tcp://[[username:]password@]host[:port][/db]*. For example:

```
auto redis = Redis("tcp://password@127.0.0.1:6379/1");
```

By now, these's no way to specify `socket_timeout` with URI. However, there's a plan to support all options by URI parameter, something like this:

```
tcp://127.0.0.1:6379/1?socket_timeout=3000&keep_alive=true
```

Regards

**Comment by dellorogiulio** [comment]
The URI idea is awesome!
I could try to write a possible solution and present it to you!
We stay in touch.

**Comment by dellorogiulio** [comment]
Hi @sewenew ,
I've tested your dev branch about the URI parsing: all seems good to me. 
I already close the pull request I made,
thanks

**Comment by sewenew** [comment]
Hi @dellorogiulio 

After fixing 2 missing headers, this feature has been fully tested, and merged into master branch.

Thanks again for your work :)

Regards

**Comment by yitian108** [comment]
hi @sewenew , thank you for finding the original issue. Actually, I have a question why the initialize redis must in initial list in constructor? As you known, initilize the redis must pass the host, or other parameters, if we can only initilize in constructor, how can we pass the configuration parameters of redis?

**Comment by sewenew** [comment]
@yitian108 

> I have a question why the initialize redis must in initial list in constructor?

Because `Redis` doesn't have a default constructor.

> if we can only initilize in constructor, how can we pass the configuration parameters of redis?

The above comments mentioned 3 solutions. Please check them for detail.

Regards

**Comment by yitian108** [comment]
@sewenew Yes, I do review the 3 solutions, however, they seems to initialize the parameters as literal value, for example, the host="133.33.23.2", if we need read the value of host from a configuration file, how can we do that?


Regards

**Comment by sewenew** [comment]
@yitian108 You can pass these parameters with your customized class, e.g. `A`'s constructor, and then pass them to `Redis`, or pass the configuration file name to `_build_options` mentioned above.

Regards

**Comment by yitian108** [comment]
@sewenew , maybe it is not easy to deal with, class A should be a singleton class, since redis object could not be constructed each call, so when we pass a parameter as A's constructor, like A(Config conf), we should initialize Redis object in every constructor, that's a bit strange, and for each A::Instance().xxx call will need to add the parameter 'conf', right?
And if pass file name to the function _build_options, while the function seems only to be run in constructor, other similar like set configuration function will be later to run, it does not  seems to work as well.
If I understand the solution incorrectly, pls correct me, thanks

**Comment by sewenew** [comment]
@yitian108 Normally these 3 solutions should solve most problems. Sorry, but I'm not a C++ expert. If your scenario is really complicated, you'd better seek help from stackoverflow on how to initialize a data member which doesn't have a default constructor, but movable, in such a scenario.

Regards

**Comment by paxifaer** [comment]
Hello, my project is relatively simple, the whole project only needs to connect a redis address, so I plan to initialize redis-plus-plus with singleton mode. But when I was coding, I found that redis-plus-plus does not seem to support this kind of writing. I'm using lazy mode.
I have carried out a secondary encapsulation for my project, the code is below.
`
.h  file
#ifndef _REDIS_H_
#define _REDIS_H_

#include <sw/redis++/redis++.h>
#include <iostream>
#include <unordered_set>
#include <list>
#include <vector>
using namespace sw::redis;
class Red
{
public:

    static Red* getInstance();
    void CacheRules(const std::string &key,const std::string &rules);
    std::string SearchRules(const std::string &str);
    void CacheData(const std::string &key,const std::string &str,int time);
    void CacheData(const std::string &key,const std::string &str);
    void DelKey(const std::string &key);
    void DelKey(const std::vector<std::string> &key);
    std::unordered_set<std::string> GetSetFromRedis(const std::string & set);
    void REMForSet(const std::string &set_name,const std::unordered_set<std::string> &values);
    void InsertSet(const std::string &set_name,const std::unordered_set<std::string> &values);
    std::vector<std::string> GetListFromRedis(const std::string & list);
    void LREMForList(const std::string &list_name,const std::vector<std::string> &values);
    void Rpush(const std::string &list_name,const std::vector<std::string> &values);
private:
    Redis redis;
    static Red* instance;
    Red(){};
    Red(const Red &) {};
    Red &operator=(const Red &) {};
    ~Red();
    void RedisConnect();

};
Red* Red::getInstance()
{
    static Red  instance;
    return &instance;
}

`
