### ISSUE TITLE
[QUESTION] LPOS command

### ISSUE THREAD

**Issue by FaerHack** [sewenew/redis-plus-plus#516]
Are there plans to implement LPOS command?

**Comment by sewenew** [comment]
I'll try to add it in the future, but the priority is low. However, before that, you can use the [generic interface](https://github.com/sewenew/redis-plus-plus/#generic-command-interface) to to send LPOS command:

```
auto r = Redis("tcp://127.0.0.1");
auto pos = r.command<Optional<long long>>("LPOS", "key", "element");  // When there's no COUNT option, it might return a nil reply, and we need specify the type as `Optional`.

auto result = r.command<std::vector<long long>>("LPOS", "key", "element", "count",3);
```

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
