### ISSUE TITLE
Getting invalid URI: no scheme

### ISSUE THREAD

**Issue by ksohan** [sewenew/redis-plus-plus#521]
**Describe the problem**
All the details are written in this stackoverflow question. Please have a look and suggest how can I solve it. 
[Issue](https://stackoverflow.com/questions/77177858/getting-no-scheme-error-in-redis-plus-plus)

**Environment:**
 - OS: Windows
 - Compiler: MVSC
 - hiredis version: 1.2.0 from VCPKG
 - redis-plus-plus version: 1.3.10 from VCPKG

**Comment by ksohan** [comment]
Any specific version of C++ needed? Or any special flags?

**Comment by sewenew** [comment]
redis-plus-plus works with C++11 or later. No special flag should be specified. Also you can run the [test program](https://github.com/sewenew/redis-plus-plus#run-tests-optional), which tests the URI case.

**Comment by sewenew** [comment]
Since there's no update, I'll close it.

Regards
