### ISSUE TITLE
Async interface with boost::asio

### ISSUE THREAD

**Issue by iasna** [sewenew/redis-plus-plus#528]
Can I use async interface, if my application works with boost::asio ?

**Comment by sewenew** [comment]
Of course, you can use it. The async interfaces are all non-blocking. It should work well with boost::asio. Although the underlying network layer is libuv, not boost::asio. 

Regards

**Comment by iasna** [comment]
It means the  communication with redis will be done by this library using libuv, and rest of my async operations that are being handled by boost asio will work with out any issues. correct me if understood anything wrong.

**Comment by sewenew** [comment]
I don’t think there will be any problems.


________________________________
发件人: ai ***@***.***>
发送时间: Wednesday, November 15, 2023 2:57:31 AM
收件人: sewenew/redis-plus-plus ***@***.***>
抄送: sewenew ***@***.***>; Comment ***@***.***>
主题: Re: [sewenew/redis-plus-plus] Async interface with boost::asio (Issue #528)


It means the communication with redis will be done by this library using libuv, and rest of my async operations that are being handled by boost asio will work with out any issues. correct me if understood anything wrong.

―

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
