### ISSUE TITLE
[QUESTION] Role change is not handled correctly

### ISSUE THREAD

**Issue by mike1821** [sewenew/redis-plus-plus#537]
Hello,

I am implementing a Redis client using an AsyncRedisCluster object and establish a connection towards one of the master nodes (i.e server 0) of my cluster using the following options. 

```
sw::redis::ConnectionOptions props;
sw::redis::AsyncRedisCluster client;

props.host = xx.xxx.xxx.189;
props.port = 6379;
client = sw::redis::AsyncRedisCluster(props);
```

The cluster map is as follows:

service/server-0          ClusterIP   **xx.xxx.xxx.189**   <none>        6379/TCP,16379/TCP   3h39m
service/server-1          ClusterIP   xx.xxx.xxx.196   <none>        6379/TCP,16379/TCP   3h39m
service/server-2          ClusterIP   xx.xxx.xxx.217    <none>        6379/TCP,16379/TCP   3h39m
service/server-3          ClusterIP   xx.xxx.xxx.80    <none>        6379/TCP,16379/TCP   3h39m
service/server-4          ClusterIP   xx.xxx.xxx.213   <none>        6379/TCP,16379/TCP   3h39m
service/server-5          ClusterIP   xx.xxx.xxx.173   <none>        6379/TCP,16379/TCP   3h39m

pod/server-0                        3/3     Running   0          23m     master                            
pod/server-1                        3/3     Running   0          3h15m   master                          
pod/server-2                        3/3     Running   0          3h15m   master                          
pod/server-3                        3/3     Running   0          9m9s    slave           xx.xxx.xxx.189
pod/server-4                        3/3     Running   0          3h15m   slave          xx.xxx.xxx.217
pod/server-5                        3/3     Running   0          3h15m   slave          xx.xxx.xxx.196

I successfully create keys towards the database using the following logic:

``` 
auto a_client = client .redis(KEY, false);
a_client.command<OptionalLongLong>(cmd.begin(), cmd.end() , [this] (std::future<OptionalLongLong> &&fut) {
     try {
           auto ret = fut.get();
           std::cout << "ok" << std::endl;
     } catch (const Error &ex) {
           std::cout << ex.what() << std::endl;
     }
});
```

The hashing is correct and the keys are distribute in all master database pods. 

My problem is that when for some reason I restart one of the master pods, I persistently receive MOVED errors when trying to create a key.
**MOVED 1449 xx.xxx.xxx.80:6379**

On my understanding the library should automatically identify the cluster shard and send the request towards the new master pod (i.e server-3). 
Could you please help me identify what might be wrong in this case?

P.S Searching in the discussions tab I noticed the [issue#523](https://github.com/sewenew/redis-plus-plus/issues/523). In my case I am working behind a redis-module and use the generic command interface to send commands and not any plain Redis commands (i.e GET). Could this be related?

Environment:
OS: Rocky Linux
Compiler: g++ 8.5.0
hiredis version: v1.0.2, master
redis-plus-plus version: 1.3.10, master

**Comment by sewenew** [comment]
I did some research, and this is indeed a similar problem with the issue you mentioned. If you only call `AsyncRedisCluster::redis` to create an `AsyncRedis` object, and send command with this object, redis-plus-plus does not update the underlying node-slot mapping, and always send command to the old master.

Thanks for reporting the bug, and I'll try to fix it ASAP.

Before that, you can work around it by calling `AsyncRedisCluster::get` with the key you used, once you get an exception. This way, the underlying node-slot mapping will be updated, and redis-plus-plus will follow the MOVED indication.

Regards

**Comment by georgasa** [comment]
Hi @sewenew , I'm facing the same issue, so please a quick correction would be more than welcome!

**Comment by sewenew** [comment]
I fixed the problem, please try the latest code on **dev** branch. After some more tests, I'll merge the code into master branch.

You can use the following code to do a test:

```
auto cluster = RedisCluster("redis://127.0.0.1:7000");
while (true) {
    try {
        auto r = cluster.redis(key, false);
        cout << r.command<string>("ping") << endl;
    } catch (const Error &e) {
        cout << e.what() << endl;
    }
```

At the beginning, the test program prints "PONG". When the master that *key* located, is down, the program prints error message. When a new master is elected, the program prints "PONG" again.

You can try the latest fix. If you still has problem with it, feel free to let me know.

Sorry for the late fix. Too busy these days.

Regards

**Comment by sewenew** [comment]
Code has been merged into master branch. If you still have problem with it, feel free to reopen it.

Regards

**Comment by georgasa** [comment]
Thanks a lot for the fix, could you please create a new release that includes the fix so as to incorporate it in our project?

**Comment by sewenew** [comment]
I’ll create a release this weekend with some other features and fixes.

Regards

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Apostolos Georgas ***@***.***>
发送时间: Thursday, December 28, 2023 6:24:27 AM
收件人: sewenew/redis-plus-plus ***@***.***>
抄送: sewenew ***@***.***>; State change ***@***.***>
主题: Re: [sewenew/redis-plus-plus] [QUESTION] Role change is not handled correctly (Issue #537)


Thanks a lot for the fix, could you please create a new release that includes the fix so as to incorporate it in our project?

―

**Comment by sewenew** [comment]
New release has been created. Enjoy it!

Regards
