### ISSUE TITLE
version info at compile

### ISSUE THREAD

**Issue by phdpsx** [sewenew/redis-plus-plus#547]
Is there a way to get redis++ version at the compile time (define)? Didn't find anything in headers...

**Comment by sewenew** [comment]
You can get the version information from CMakeLists.txt.

Regards

**Comment by phdpsx** [comment]
I did notice it in CMake files.
I'm interested in compile/run time version, after library install when I only have lib(s) and headers. I need it to track versions between different binaries we make.

**Comment by sewenew** [comment]
I'll add a version file in the next release. Thanks for your suggestion!

Regards

**Comment by sewenew** [comment]
Version info has been added to `src/sw/redis++/version.h` file.

Regards
