### ISSUE TITLE
more example for script

### ISSUE THREAD

**Issue by vanehu** [sewenew/redis-plus-plus#55]
thank you for this great job
can you provide some more lua script reply parse example? 
ex: script return  0 "1" [1,2,3]  (number string ,array(int/string))

**Comment by vanehu** [comment]
and some tuple parse example, or user define reply parse?

**Comment by sewenew** [comment]
Hi @vanehu 

If you want to return a tuple of <number, string, int array>, you can try the following code:

```
using Result = std::tuple<long long, std::string, std::vector<long long>>;
std::string script = R"(return {0, "1", {1, 2, 3}})";
auto res = redis.eval<Result>(script, {}, {});
cout << std::get<0>(res) << endl;
cout << std::get<1>(res) << endl;
for (auto ele : std::get<2>(res)) {
    cout << ele << endl;
}
```

By now, redis-plus-plus doesn't support parsing user defined reply type. However, it can parse any kind of tuples. So you can define an `std::tuple` as your user defined reply type. The type of the tuple element can be `long long`, `double`, `string`, STL containers (e.g. `vector`, `unordered_map`, `list`, `set` and so on), or `tuple` (nested tuples). In a word, it's very flexible. For example, given the following script: 

```
std::string script = R"(return {0, "1", {{"a", 1}, {"b", 1}}})";
```
You can parse the reply as `std::tuple<long long, std::string, std::vector<std::pair<std::string, long long>>>`, `std::tuple<long long, std::string, std::unordered_map<std::string, long long>>`, or some other user defined types that match the return value.

If you still have any problem on redis-plus-plus, feel free to let me know. If you like it, also feel free to start it :)

Regards

**Comment by vanehu** [comment]
thanks
