### ISSUE TITLE
how to deal vector or list keys/args

### ISSUE THREAD

**Issue by vanehu** [sewenew/redis-plus-plus#56]
now can use    
std::initializer_list<sw::redis::StringView> keys = { "uid:10136387:record","uid:10136387:all","uid:10136387:empty" };
    std::initializer_list<sw::redis::StringView > args = { "0","-20","0" };

but sometimes we need this 
std::vector<std::string> keys;
keys.push_back("uid:10136387:record");
keys.push_back(....);

so it cannt complie how to do for this

**Comment by sewenew** [comment]
Hi @vanehu 

I'll add an overload for `eval` to support this case in the future.

By now, you can solve the problem with the **dark corner** of [generic command interface](https://github.com/sewenew/redis-plus-plus#generic-command-interface):

```
template <typename Cmd, typename ...Args>
auto command(Cmd cmd, Args &&...args)
    -> typename std::enable_if<!std::is_convertible<Cmd, StringView>::value, ReplyUPtr>::type;
```

In you case, you can try the following code:

```
using Result = std::tuple<long long, std::string, std::string>;
std::string script = R"(return {0, KEYS[1], ARGV[1]})";
std::vector<std::string> keys = {"a"};
std::vector<std::string> args = {"b"};
auto eval = [](sw::redis::Connection &connection, const std::string &script, const std::vector<std::string> &keys, const std::vector<std::string> &args) {
    sw::redis::CmdArgs cmd_args;
    cmd_args << "EVAL" << script << keys.size() << std::make_pair(keys.begin(), keys.end()) << std::make_pair(args.begin(), args.end());

    return connection.send(cmd_args);
};
auto r = redis.command(eval, script, keys, args);
auto res = sw::redis::reply::parse<Result>(*r);
cout << std::get<0>(res) << endl;
cout << std::get<1>(res) << endl;
cout << std::get<2>(res) << endl;
```

Regards

**Comment by vanehu** [comment]
thanks
