### ISSUE TITLE
[FEATURE] Support for LMOVE / BLMOVE

### ISSUE THREAD

**Issue by craigsoules** [sewenew/redis-plus-plus#560]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be support for LMOVE or BLMOVE.  They are new in Redis 6.2.

**Describe the solution you'd like**
Support for those functions.

**Describe alternatives you've considered**
Currently using BRPOPLPUSH, but it's more limiting in it's capabilities.

**Additional context**
Thank you for your consideration!

**Comment by sewenew** [comment]
Before the feature is supported, you can use the generic command to send these commands.

Regards

**Comment by craigsoules** [comment]
Thank you for the tip!  Really appreciate your work on this library.

**Comment by sewenew** [comment]
#599 implements this feature.

Regards

**Comment by craigsoules** [comment]
Thank you so much for implementing this!  Do you have a sense of when this will get bundled into a release?

**Comment by sewenew** [comment]
Release 1.3.13 is out, which contains this fix. Enjoy it :)
