### ISSUE TITLE
[QUESTION]在redis设置了超时断开连接的情况下，本库是推荐自动重连还是推荐定时ping的方式保持连接

### ISSUE THREAD

**Issue by feihongmeilian** [sewenew/redis-plus-plus#568]
hi！
 
redis-plus-plus下在执行命令的时候实现了自动重连机制；同时，我发现最新版本的RedisCluster提供了for_each，并在for_each上面的使用案例显示的事使用ping函数。

如果在redis里设置了一段时间不执行命令就断开连接，那么，使用redis-plus-plus是推荐基于自动重连机制，还是推荐基于for_each定时ping从而实现保活呢？

谢谢！

**Comment by sewenew** [comment]
基于重连就可以了
________________________________
发件人: feihongmeilian ***@***.***>
发送时间: Wednesday, June 5, 2024 9:05:59 PM
收件人: sewenew/redis-plus-plus ***@***.***>
抄送: Subscribed ***@***.***>
主题: [sewenew/redis-plus-plus] [QUESTION]在redis设置了超时断开连接的情况下，本库是推荐自动重连还是推荐定时ping的方式保存连接 (Issue #568)


hi！

redis-plus-plus下在执行命令的时候实现了自动重连机制；同时，我发现最新版本的RedisCluster提供了for_each，并在for_each上面的使用案例显示的事使用ping函数。

如果在redis里设置了一段时间不执行命令就断开连接，那么，使用redis-plus-plus是推荐基于自动重连机制，还是推荐基于for_each定时ping从而实现保活呢？

谢谢！

―
