### ISSUE TITLE
[QUESTION] CentOS 8 build error

### ISSUE THREAD

**Issue by Purushoth24051999** [sewenew/redis-plus-plus#574]
I have followed the installation procedure for Hiredis and it got installed but when i proceeded to install redis++ when i run make command ith throws bellow error
![Screenshot from 2024-06-21 21-38-09](https://github.com/sewenew/redis-plus-plus/assets/169040787/f6981cf1-6194-480a-9bbf-c990f006d875)

**Comment by sewenew** [comment]
Looks like this is a compiler bug? Can you try another compiler?

Regards

**Comment by Purushoth24051999** [comment]
> Looks like this is a compiler bug? Can you try another compiler?
> 
> Regards

This issue has been solved by upgrading my c++ compiler to latest version. It works fine now. Thanks for your response
