### ISSUE TITLE
[QUESTION] xadd and xread via async interface 

### ISSUE THREAD

**Issue by FScHalm** [sewenew/redis-plus-plus#580]
Hi.

I just started using redis-plus-plus and wonder how to use xadd and xread async. 
For non async (sw::redis::Redis) there are interfaces, but can not find them for sw::redis::AsyncRedis.

Thanks

**Comment by sewenew** [comment]
You can use the generic interface for `AsyncRedis`, i.e. the `AsyncRedis::command` method, to do the work. Check the [Getting Started section](https://github.com/sewenew/redis-plus-plus?tab=readme-ov-file#getting-started-1) for example.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
