### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by selcukaltinay** [sewenew/redis-plus-plus#582]
I am setting up a redis cluster with 6 containers(Redis 7.2.5). After scanning with the scan command along with various test cases, I delete the keys I obtained. I'm using RedisPlusPlus. But suddenly the redis instances are shutting down. I don't know how a client can cause a server to shut down.

my cluster.conf is
```

cluster-enabled yes
cluster-config-file nodes.conf
databases 16
timeout 300
tcp-keepalive 60
maxmemory 2gb
maxmemory-policy allkeys-lru
cluster-node-timeout 15000
cluster-require-full-coverage yes
protected-mode no
dbfilename dump-rdb
dir /data
save 10 1
loglevel debug
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
```
When I examine the logs, I saw the interesting log below: I/O error reading from node link: connection closed I/O error reading from node link: connection closed Connection with Node ... at ... failed: Connection refused.

Those are the latest logs.

I'm working on a virtual machine. I could not find the cause of the problem.

 - OS: RHEL 8.5
 - Compiler: gcc 8.5
 - hiredis version: 1.2.0
 - redis-plus-plus version: 1.3.11(Written in cmakelists.txt)

**Comment by sewenew** [comment]
> I don't know how a client can cause a server to shut down.

It should not be down by a client, unless client sends the `shutdown` command. If you only send scan commands to Redis, and Redis server is down, that is a Redis bug. I suggest you do a bug report for Redis server.

Regards

**Comment by selcukaltinay** [comment]
When I connect to redis with cli to see monitor command output, I saw this messages, Error: Server closed the connection.
At dmesg command output, I saw the listed messages;
Code: Unable to access opcode bytes at RIP 0xfffffffffffffd6
app[4130076]: seg fault at 0 ip 00000000000000 sp 0007ff... error 14 in app

I have opened this issue so the client application is giving error above

Regards

**Comment by sewenew** [comment]
This seems not be a problem with redis-plus-plus. I'll close this issue.

Regards
