### ISSUE TITLE
[QUESTION] Support for Valkey

### ISSUE THREAD

**Issue by mlanzuisi** [sewenew/redis-plus-plus#594]
Does redis-plus-plus support open-source Redis fork named Valkey?

**Comment by sewenew** [comment]
Since Valley is compatible with Redis, they use the same protocol. So, yes, redis-plus-plus support Valkey.

Regards

**Comment by sewenew** [comment]
I'll close this issue. If you have any specific problem on connecting Valkey with redis-plus-plus, feel free to create issues.
