### ISSUE TITLE
[QUESTION] When the next release from the master will be available?

### ISSUE THREAD

**Issue by mroland91** [sewenew/redis-plus-plus#596]
Hi @sewenew, Last release is from January. When do you plan to have a new official release? Many thanks.

**Comment by georgasa** [comment]
Hi, do you have a draft estimation about when this gonna happen? A new release is needed so as to build correctly our application with your new library.

Thanks

**Comment by sewenew** [comment]
Release 1.3.13 is out. Enjoy it :)

**Comment by georgasa** [comment]
Thanks a lot!
