### ISSUE TITLE
add is_valid to Redis transaction

### ISSUE THREAD

**Issue by molar-pl** [sewenew/redis-plus-plus#60]
Consider the following scenario. I have got a pool of Redis transactions, in the pool I store thin wrappers around sw::redis::transaction and upon destruction of the wrapper I put sw::redis::transaction back to the pool assuming the transaction is still valid. What I do now is (pseudo code):
```
Wraper::~Wrapper()
{
if (!std::uncaught_exception())
{
  pool.push_back(transaction);
}
}
```
That is not a perfect solution since the exception can be not related to Redis at all. Also what I would like to do is discard transaction before putting in back to the pool, in case somebody left unexecuted commands in the transaction. So I would like to have something like that:
```
Wraper::~Wrapper()
{
if (transaction->is_valid())
{
  if (transaction->in_transaction())
  {
    transaction->discard();
  }
  pool.push_back(transaction);
}
}
```
My proposal to make it work would be adding the following functions:
```
bool QueuedRedis::is_valid() { return _valid; }
bool QueuedRedis::is_in_transaction() { return _impl.is_in_transaction(); }
bool TransactionImpl::is_in_transaction() { return _in_transaction; }
bool PipelineImpl::is_in_transaction() { return false; }
```
Would that make sense? Is there any other way to achieve that behaviour?

**Comment by sewenew** [comment]
Hi @molar-pl 

A better solution is to use `std::unique_ptr<Transaction>`, and if the transaction is invalid, i.e. some error throws, release the unique_ptr. You can try the following code.

**NOTE**: the following code is NOT tested and NOT thread-safe!!!

```
using TransactionUPtr = std::unique_ptr<Transaction>;

class TransPool {
public:
    TransPool(Redis &redis, size_t num) : _redis(redis) {
        for (auto idx = 0; idx != num; ++idx) {
            // use move constructor to construct a Transaction
            auto trans = TransactionUPtr(new Transaction(redis.transaction()));
            _pool.push_back(std::move(trans));
        }
    }

    TransactionUPtr fetch() {
        if (_pool.empty()) {
            return nullptr;
        }

        auto trans = std::move(_pool.front());
        _pool.pop_front();

        if (!trans) {
            // this Transaction is invalid, create a new one
            return TransactionUPtr(new Transaction(_redis.transaction()));
        } else {
            return trans;
        }
    }

    void release(TransactionUPtr trans) {
        _pool.push_back(std::move(trans));
    }

private:
    using Pool = std::deque<TransactionUPtr>;
    Pool _pool;
    Redis &_redis;
};

// guard to ensure that transaction will be returned to pool
struct Guard {
    Guard(TransPool &pool, TransactionUPtr &trans) : _pool(pool), _trans(trans) {}

    ~Guard() {
        _pool.release(std::move(_trans));
    }

    TransPool &_pool;
    TransactionUPtr &_trans;
};

int main() {
    try {
        auto redis = Redis("tcp://127.0.0.1");
        TransPool pool(redis, 3);
        auto trans = pool.fetch();
        if (!trans) {
            cerr << "no trans in pool" << endl;
            return -1;
        }

        Guard guard(pool, trans);

        try {
            // use trans.
            trans->set("a", "b");
            trans->set("b", "c");
            trans->exec();
        } catch (const Error &e) {
            // something bad happened.
            // no need to call discard, just release/close the connection
            trans.release();
        }
    } catch (const Error &e) {
        // handle error
    }
}
```

Regards

**Comment by molar-pl** [comment]
Hi @sewenew,
thank you for the quick response and for the example. I have got very similar implementation to the one you posted, but I see a disadvantage here, namely every single piece of code, which uses transaction must be wrapped in try-catch block. So I was looking for some way to avoid this boiler-plate code and I came up with an idea to let the transaction decide upon destruction if it want to go back to the pool or not. Anyway, I think pool of transactions (#57) would do exactly want I need (assuming there is some built-in mechanism preventing from using invalid transaction/connection). So for now I guess I am going to wait for this feature. Thanks again for help.

**Comment by sewenew** [comment]
Hi @molar-pl 

This feature has been implemented on the dev branch, and passed all tests. However, since this is a big change, I still need to do more tests before merging it to master. If you are interested, you can fetch the dev branch, and have a try. If you get any problem, feel free to let me know :)

The following is an example to create a `Transaction` object with the underlying connection pool:

```
auto redis = Redis("tcp://127.0.0.1");

// By default, create a Transcation object with a new connection.
auto tx1 = redis.transaction();

// Create a Transaction object with the underlying connection pool (the second parameter).
// And commands in the transaction won't be sent in a pipeline (the first parameter)
auto tx2 = redis.transaction(false, false);
```

Sorry for the big delay to implement this feature. Too busy these days...

Regards

**Comment by sewenew** [comment]
@molar-pl I've fixed some problem, and merge the dev branch into master. Please read the related [doc1](https://github.com/sewenew/redis-plus-plus#create-transaction-without-creating-new-connection) and [doc2](https://github.com/sewenew/redis-plus-plus#very-important-notes) carefully before using it. Sorry for a big delay.

Regards
