### ISSUE TITLE
[BUG] Generated file appears as git untracked file when redis++ submoduled under another project

### ISSUE THREAD

**Issue by d4vebr4cey** [sewenew/redis-plus-plus#602]
When redis++ is submoduled under another project and compiled, the generated file:

`src/sw/redis++/hiredis_features.h`

is detected by git as a new untracked file.

Can this be added to the .gitignore for redis++ please?  It seems it must be added at the redis++ .gitignore level (adding it to higher level .gitignore does not fix it).

**Comment by sewenew** [comment]
It seems that you're using an old version (older than 1.3.8) of redis-plus-plus. The latest version generates hiredis_features.h in compile directory not the source code directory. You can upgrade to the latest version, and the problem should be solved.

Regards

**Comment by d4vebr4cey** [comment]
Confirm latest version does not have this issue
