### ISSUE TITLE
[QUESTION]How can I determine whether the connection to Redis is successful?

### ISSUE THREAD

**Issue by daizhichao** [sewenew/redis-plus-plus#607]
Is it necessary to use the ping() function to determine whether the connection is successful? As shown in the figure, an exception indicating a connection failure will be thrown only after using the ping() function.

**Comment by daizhichao** [comment]
![QQ20241111-162325](https://github.com/user-attachments/assets/9cfe25be-a509-4923-8468-f7e63952ec79)

**Comment by sewenew** [comment]
The connection is lazily created, i.e. when you send command to Redis server, redis++ creates a connection to it.

If you want to check if the given <host, port> pair works, you can manually send a ping command.

Regards

**Comment by sewenew** [comment]
Close this issue, since there's no update.
