### ISSUE TITLE
[QUESTION]new version  build and use problem

### ISSUE THREAD

**Issue by fjccc** [sewenew/redis-plus-plus#608]
I compiled a Redis++ static library using the following method:

cmake -DCMAKE_PREFIX_PATH=/home/hiredisInstall -DCMAKE_INSTALL_PREFIX=/home/install/redis-plus-plus -DREDIS_PLUS_PLUS_CXX_STANDARD=11 ..

Subsequently, when I tried to use this static library to compile an executable, I encountered the following error:

libredis++.a(shards_pool.cpp.o):(.data.rel.ro+0x10): undefined reference to `typeinfo for std::thread::_State'

**Environment:**
 - OS: [centos7]
 - Compiler: [gcc 4.8.5]
 - hiredis version: [ v1.1.0]
 - redis-plus-plus version: [ 1.3.13,]

Has anyone encountered this issue before?

**Comment by sewenew** [comment]
If you work on Linux env, you might need to add `-pthread` to make your application link with pthread lib. If you work on Windows, you can ask some Windows experts how to link the an alternative threading lib.

Regards

**Comment by fjccc** [comment]
-pthread  has already added, but still build failed! build command like below
g++ -g -o ut_msgmgr  ut_msgmgr_common.o ut_msgmgr_redis.o ut_msgmgr_old.o ut_msgmgr_mock_api.o ut_msgmgr.o -L/home/zxin10/lib -lmsgmgros -lmsgmgr -lvssfunc -lzxinfunc -lzxcommon -lcjson -lcjson_ext -lstdc++ -lchFunc -levent   -L/home/zxin10/lib -lexpat -lzookeeper_mt -lz -lm -lssl -lcrypto -ldl -lredis++ /home/zxin10/lib/libhiredis.a -pthread /home/zxin10/lib/libemock.a -lgcov -lgtest -lgtest_main
/home/zxin10/lib/libmsgmgr.so: undefined reference to `typeinfo for std::thread::_State'
/home/zxin10/lib/libmsgmgr.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
/home/zxin10/lib/libmsgmgr.so: undefined reference to `std::thread::_State::~_State()'
collect2: error: ld returned 1 exit status
make[3]: *** [ut_msgmgr] Error 1

**Comment by fjccc** [comment]
g++ -shared -o libmsgmgr.so  msgmgr_http.o msgmgr_entry.o msgmgr.o msgmgr_common.o msgmgr_kafka_consumer.o msgmgr_restartalarm.o msgmgr_redis.o msgmgr_config.o -L/home/zxin10/lib -lz -lm -lssl -lcrypto -ldl -lvssfunc -lredis++ /home/zxin10/lib/libhiredis.a -pthread -lgcov -lgtest -lgtest_main

**Comment by sewenew** [comment]
Follow [this thread](https://gcc.gnu.org/legacy-ml/gcc-help/2018-05/msg00133.html), you can try to put `-pthread` at the end of your compiler options, or upgrade your compiler.

Regards

**Comment by sewenew** [comment]
Close the issue, since there's no update.
