### ISSUE TITLE
[QUESTION] Why does RedisCluster::pipeline require asynchronous updating of slot information?

### ISSUE THREAD

**Issue by caijillx** [sewenew/redis-plus-plus#610]
**Describe the problem**
I would like to know if calling async_update() is necessary when obtaining a pipeline object, and if the asynchronous slot update process is mandatory?
**Environment:**
 - OS: [Linux 4.19.91]
 - Compiler: [gcc 9.2.1]
 - hiredis version: [v1.1.0, master]
 - redis-plus-plus version: [1.3.12]

**Additional context**
In src/sw/redis++/redis_cluster.cpp
```
Pipeline RedisCluster::pipeline(const StringView &hash_tag, bool new_connection) {
    assert(_pool);

    _pool->async_update();

    auto pool = _pool->fetch(hash_tag);
    if (new_connection) {
        // Create a new pool
        pool = std::make_shared<ConnectionPool>(pool->clone());
    }

    return Pipeline(pool, new_connection);
}
```
I have noticed a lot of CLUSTER SLOTS commands in the slow logs of my Redis cluster, and upon tracing, I found that it originates from this part of my application. In fact, the shards remain constant most of the time. For better performance, what would be the impact if we remove the async_update function call here?

**Comment by sewenew** [comment]
This is a known issue (#593), and has been solved. You can update your code to the latest version.

Regards

**Comment by caijillx** [comment]
Thanks for your reply.
