### ISSUE TITLE
[QUESTION]抱歉纯程序新手，没弄明白，程序总会在与redis数据库连接断开后崩溃，而不是自动重连

### ISSUE THREAD

**Issue by djhdj1** [sewenew/redis-plus-plus#612]
**Before Asking A Question**
The [README.md file](https://github.com/sewenew/redis-plus-plus/blob/master/README.md) has a detailed introduction with examples on how to use redis-plus-plus, and [redis.h](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h) has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis), and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

**Describe the problem**
A clear and concise description of the problem, with minimal code to reproduce the problem.

**Environment:**
 - OS: [windows]
 - Compiler: [visual studio 2022]
 - hiredis version: [1.2.0]
 - redis-plus-plus version: [1.3.13]

**Additional context**
我连接数据库之后，只要数据库断开，程序就会崩溃，崩溃点在connection_pool文件的第108行，请问我应该怎么做才能在没有连接到redis数据库的时候自动重连，而不是直接崩溃？
`    if (_need_reconnect(connection, connection_lifetime, connection_idle_time)) {
        try {
            connection.reconnect();
        } catch (const Error &) {
            // Failed to reconnect, return it to the pool, and retry latter.
            release(std::move(connection));
            throw;
        }
    }`
以下是我测试用的程序，当ping的时候就会发生以上崩溃
`    ConnectionOptions connection_options;
    connection_options.keep_alive=true;
    connection_options.host = "127.0.0.1";  // Required.
    connection_options.port = 6379; // Optional. The default port is 6379.

    connection_options.socket_timeout = std::chrono::milliseconds(200);
    connection_options.connect_timeout= std::chrono::milliseconds(200);

    auto redis = Redis(connection_options);
    redis.ping();`
感谢大佬的付出

**Comment by sewenew** [comment]
代码有捕获异常吗？这里重连如果失败了（例如redis当前不稳定，连不上），是会抛异常的，如果没有捕获异常，程序就会崩溃

Regards

**Comment by djhdj1** [comment]
> 这里重连如果失败了

`    if (_need_reconnect(connection, connection_lifetime, connection_idle_time)) {
        try {
            connection.reconnect();
        } catch (const Error &) {
            // Failed to reconnect, return it to the pool, and retry latter.
            release(std::move(connection));
            throw;
        }
    }`
就是崩溃在connection.reconnect();这句上，这算捕获异常吗...

**Comment by fjccc** [comment]
2024-12-05 17:16:18:898] [msgdis:0] [redisAgent.cpp:716]
[ERROR] [tid:init] init redisAsyncThread failed, err=[WRONGPASS invalid username^M
[2024-12-05 17:16:18:898] [msgdis:0] [redisAgent.cpp:585]
我这边也有类似的报错，然后上述报错内容 在代码中搜索不到
![202412051733200252180000140279FD](https://github.com/user-attachments/assets/448054b7-1d2a-4ad5-b400-56b840c2a49a)

**Comment by sewenew** [comment]
> > 这里重连如果失败了
> 
> ` if (_need_reconnect(connection, connection_lifetime, connection_idle_time)) {
> 
> ```
>     try {
> 
>         connection.reconnect();
> 
>     } catch (const Error &) {
> 
>         // Failed to reconnect, return it to the pool, and retry latter.
>         release(std::move(connection));
> 
>         throw;
> 
>     }
> 
> }`
> ```
> 
> 就是崩溃在connection.reconnect();这句上，这算捕获异常吗...

你贴的代码是redis-plus-plus内部的catch，捕获之后会重新抛出的，`throw`语句。你需要在你的应用程序里捕获异常

> invalid username

你的这个错误是redis server返回的，你指定的密码错了，所以创建链接失败，抛的异常

**Comment by djhdj1** [comment]
> > > 这里重连如果失败了
> > 
> > 
> > ` if (_need_reconnect(connection, connection_lifetime, connection_idle_time)) {
> > ```
> >     try {
> > 
> >         connection.reconnect();
> > 
> >     } catch (const Error &) {
> > 
> >         // Failed to reconnect, return it to the pool, and retry latter.
> >         release(std::move(connection));
> > 
> >         throw;
> > 
> >     }
> > 
> > }`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就是崩溃在connection.reconnect();这句上，这算捕获异常吗...
> 
> 你贴的代码是redis-plus-plus内部的catch，捕获之后会重新抛出的，`throw`语句。你需要在你的应用程序里捕获异常
> 
> > invalid username
> 
> 你的这个错误是redis server返回的，你指定的密码错了，所以创建链接失败，抛的异常

感谢大佬，会用了，问题关闭
