### ISSUE TITLE
vs2019 cmake compile error：“redis-plus-plus\out\build\x64-Debug\cl : command line error D8004: “/W

### ISSUE THREAD

**Issue by chris-shenzhen-china** [sewenew/redis-plus-plus#62]
redis-plus-plus\out\build\x64-Debug\cl : 命令行 error D8004: “/W”需要参数

**Comment by sewenew** [comment]
Hi @chris-shenzhen-china 

Sorry, but I don't have a VS2019 box, and not sure if redis-plus-plus can be compiled with VS2019. However, you can try to compile redis-plus-plus with MinGWin64, and it should work. You can check [this issue](https://github.com/sewenew/redis-plus-plus/issues/50) for reference.

Regards

**Comment by sewenew** [comment]
Hi @chris-shenzhen-china 

You closed [issue 63](https://github.com/sewenew/redis-plus-plus/issues/63), so it seems your problem has been solved? And can I close this issue now?

Regards
