### ISSUE TITLE
don't overwrite CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by paulohefagundes** [sewenew/redis-plus-plus#67]
please don't overwrite CMAKE_CXX_FLAGS in the CMakeLists.txt

do instead append to it. Some systems depend on some flags in `CMAKE_CXX_FLAGS` and if you overwrite it, then we can't build

Example below for a patch that I had to do locally for v1.1.1

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index fb160b5..035ecfe 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,7 +6,7 @@ else()
     cmake_minimum_required(VERSION 2.8.0)
 endif()
 
-set(CMAKE_CXX_FLAGS "-std=c++11 -Wall -W -Werror -fPIC")
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -W -Werror -fPIC")
 
 set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
```

**Comment by sewenew** [comment]
Hi @paulohefagundes 

Thanks for your pull request! I've merged it into master.

Regards

**Comment by paulohefagundes** [comment]
awesome, thanks! :+1:
