### ISSUE TITLE
ERROR parsing URI into Redis()

### ISSUE THREAD

**Issue by abhi3700** [sewenew/redis-plus-plus#69]
Hello,
* I created a Heroku Redis database & trying to parse URI using C++ code.
* __Error:__
```console
$ ./a.out
invalid URI: invalid type
```

* __Code:__
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;


const string redis_uri = "redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";
// const string redis_uri = "tcp://[[username:]password@]host[:port][/db]";
// const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_uri = "tcp://ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_url = "redis-16818.c61.us-east-1-3.ec2.cloud.redislabs.com:16818";

int main() {

	try {
		auto redis = Redis(redis_url);
		redis.set("name", "abhijit roy");

		auto val = redis.get("name");
		// std::cout << val << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```

Could anyone please solve this error??
Thank you,

**Comment by sewenew** [comment]
Hi @abhi3700 

You need to use **tcp** instead of **redis** when specifying uri.

I'm not familiar with Heroku. However, if your Redis instance's user name is *h*, password is * pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a*, host is *ec2-54-209-85-193.compute-1.amazonaws.com*, and port is *11989*, then you can use the following uri to connect to Redis:

```
const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";
```

Regards

**Comment by abhi3700** [comment]
Hi @sewenew,
Now, I am getting this error:
```console
$ g++ -std=c++17 test.cpp -lredis++ -lhiredis -pthread
$ ./a.out
ERR wrong number of arguments for 'auth' command
```

**Comment by sewenew** [comment]
Hi @abhi3700 

Please show me your code of test.cpp. And which version of Redis are you using? Redis 6.0.x or other version?

Regards

**Comment by abhi3700** [comment]
* Redis version: current stable one i.e. 6
* Code:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;


const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";
// const string redis_uri = "tcp://[[username:]password@]host[:port][/db]";
// const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_uri = "tcp://ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_url = "redis-16818.c61.us-east-1-3.ec2.cloud.redislabs.com:16818";
// const string redis_uri = "tcp://redis-16818.c61.us-east-1-3.ec2.cloud.redislabs.com:16818/1";

int main() {

	try {
		auto redis = Redis(redis_uri);
		redis.set("name", "abhijit roy");

		auto val = redis.get("name");
		// std::cout << val << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```

**Comment by abhi3700** [comment]
* In order to check if the database is working fine, I tried running with Python using this code:
```py
import redis
# import sys

REDIS_URL = "redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989"

# define Redis database
r = redis.from_url(REDIS_URL)

print("\n============Single key:value pair DB=============")
# 
r.set("name1","abhijit")
r.set("birthyear1", "1993")
# r.delete
print(r.get("name1"))    # in bytes
print(r.get("name1").decode('utf-8'))    # in string
r.delete("name1")
print(r.get("name1"))    # returns `None`
print(r.get("birthyear1"))
r.delete("birthyear1")
print(r.keys())
```
* Output:
```console
============Single key:value pair DB=============
b'abhijit'
abhijit
None
b'1993'
[]
[Finished in 3.5s]
```
* So, the redis database is working absolutely fine!!

**Comment by sewenew** [comment]
Hi @abhi3700 

Does your username is *h*, and password is *pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a*?

The latest redis-plus-plus on master branch should work with Redis 6.0's ACL correctly. And I did some tests:

```
// set Redis ACL: create a user 'alice' with password 'pass' on all keys
ACL setuser alice on >pass ~* +@all
```

```
// connect to Redis with username and password:
auto redis = Redis("tcp://alice:pass@127.0.0.1:6379");
cout << redis.ping() << endl;
```

This works fine.

Can you use `redis-cli` to test if your username and password work?

```
127.0.0.1:6379> auth h pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a
```

If the username and password matches, Redis should returns **OK** reply. Otherwise, returns some error message.

Regards

**Comment by sewenew** [comment]
Hi @abhi3700 

Are you using the latest release of redis-plus-plus, i.e. 1.1.1? If you do, you cannot use it to connect to Redis 6.0 with username and password. Sorry for the inconvenience...

Instead, please use the latest code on master branch, which is stable, and supports Redis ACL. I'll publish a new release these days to include the recent updates of redis-plus-plus in the near future.

Regards

**Comment by abhi3700** [comment]
> Hi @abhi3700
> 
> Does your username is _h_, and password is _pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a_?
> 
> The latest redis-plus-plus on master branch should work with Redis 6.0's ACL correctly. And I did some tests:
> 
> ```
> // set Redis ACL: create a user 'alice' with password 'pass' on all keys
> ACL setuser alice on >pass ~* +@all
> ```
> 
> ```
> // connect to Redis with username and password:
> auto redis = Redis("tcp://alice:pass@127.0.0.1:6379");
> cout << redis.ping() << endl;
> ```
> 
> This works fine.
> 
> Can you use `redis-cli` to test if your username and password work?
> 
> ```
> 127.0.0.1:6379> auth h pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a
> ```
> 
> If the username and password matches, Redis should returns **OK** reply. Otherwise, returns some error message.
> 
> Regards


Yes!! my 

* username: `h`
* password: `pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a`
* host: `ec2-54-209-85-193.compute-1.amazonaws.com`
* port: `11989`

* I tried this for my redis server, but didn't work:
> ```
> // connect to Redis with username and password:
> auto redis = Redis("tcp://alice:pass@127.0.0.1:6379");
> cout << redis.ping() << endl;
> ```

Code:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;


const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";
// const string redis_uri = "tcp://[[username:]password@]host[:port][/db]";
// const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_uri = "tcp://ec2-54-209-85-193.compute-1.amazonaws.com:11989/0";
// const string redis_url = "redis-16818.c61.us-east-1-3.ec2.cloud.redislabs.com:16818";
// const string redis_uri = "tcp://redis-16818.c61.us-east-1-3.ec2.cloud.redislabs.com:16818/1";

int main() {

	try {
		auto redis = Redis(redis_uri);
		// redis.set("name", "abhijit roy");

		// auto val = redis.get("name");
		// std::cout << val << "\n";
		std::cout << redis.ping() << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```
* Error:
```console
ERR wrong number of arguments for 'auth' command
```

**Comment by abhi3700** [comment]
> Hi @abhi3700
> 
> Are you using the latest release of redis-plus-plus, i.e. 1.1.1? If you do, you cannot use it to connect to Redis 6.0 with username and password. Sorry for the inconvenience...
> 
> Instead, please use **the latest code on master branch**, which is stable, and supports Redis ACL. I'll publish a new release these days to include the recent updates of redis-plus-plus in the near future.
> 
> Regards

I am using v `1.1.1` of `redis-plus-plus`

**Comment by abhi3700** [comment]
Moreover, I checked by running python `redis` lib on the generated Heroku database.
But I think there is some prob. related to `redis-plus-plus` lib in C++ which is not able to communicate with this database.

**Comment by abhi3700** [comment]
Hi @sewenew,
My generated Heroku redis server is running fine! in CLI:
```console
$ redis-cli -u redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989 ping
PONG
```

**Comment by sewenew** [comment]
> I am using v `1.1.1` of `redis-plus-plus`

Hi @abhi3700 

As I mentioned in my comment, you should use the latest code on master branch. v `1.1.1` does not support Redis ACL yet.

Please try the latest code, and it should work.

Regards

**Comment by abhi3700** [comment]
Okay how to do that?

**Comment by sewenew** [comment]
Just clone the latest code: `git clone https://github.com/sewenew/redis-plus-plus.git`, or download the zip file: `https://github.com/sewenew/redis-plus-plus/archive/master.zip` and then build it with the [instruction](https://github.com/sewenew/redis-plus-plus#install-redis-plus-plus)

If you still have problem, feel free to let me know:)

Regards

**Comment by abhi3700** [comment]
I did exactly this...& Updated the library...
It's saying 
"Up-to-date"

**Comment by abhi3700** [comment]
The same error is still coming.

**Comment by sewenew** [comment]
> I did exactly this...& Updated the library...
> It's saying
> "Up-to-date"

Does `git` says update-to-date? What does `git branch` says? You need to checkout the *master* branch, and remove the * compile* directory mentioned in the instruction. And redo the instruction to build.

Or you can remove redis-plus-plus (including the installed header files and library) from your local disk, and re-fetch it from git. And redo the whole building instruction.

**Comment by abhi3700** [comment]
Hi @sewenew ,
* I completely cleaned the repo, & then cloned the repo. using `git clone https://github.com/sewenew/redis-plus-plus.git`.
* I followed this to install:
```
$ cd redis-plus-plus/
$ mkdir compile && cd compile
$ cmake -DCMAKE_BUILD_TYPE=Release -DREDIS_PLUS_PLUS_CXX_STANDARD=17 ..
$ make
$ sudo make install
```
* Then, I just re-compiled & re-run the code.
* Case-1:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;

const string redis_uri = "tcp://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";

int main() {

	try {
		auto redis = Redis(redis_uri);
		// redis.set("name", "abhijit roy");

		// auto val = redis.get("name");
		// std::cout << val << "\n";
		std::cout << redis.ping() << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```
* The output of Case-1:
```console
$ g++ -std=c++17 test.cpp -lredis++ -lhiredis -pthread
$ ./a.out
ERR wrong number of arguments for 'auth' command
```
* Case-2:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;


const string redis_uri = "redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";

int main() {

	try {
		auto redis = Redis(redis_uri);
		// redis.set("name", "abhijit roy");

		// auto val = redis.get("name");
		// std::cout << val << "\n";
		std::cout << redis.ping() << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```
* The output of Case-2:
```console
$ g++ -std=c++17 test.cpp -lredis++ -lhiredis -pthread
$ ./a.out
invalid URI: invalid type
```

**Comment by abhi3700** [comment]
Hi @sewenew ,
Finally, I got the issue resolved.
The original URI which is provided to us via Heroku database is
```
redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989
```
But, the URL to be parsed into the `Redis()` function is:
```
tcp://pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989
```
- Here, the username `h` is dropped & `redis` is replaced with `tcp`
- So, the final code is:
```cpp
#include <sw/redis++/redis++.h>
#include <iostream>

using namespace sw::redis;
using std::string;


// const string redis_uri = "redis://h:pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";
const string redis_uri = "tcp://pd4ecec34154bbca551fdeafb94421d0ec41147dab602a6a878e6509ae49f638a@ec2-54-209-85-193.compute-1.amazonaws.com:11989";

int main() {

	try {
		auto redis = Redis(redis_uri);
		// redis.set("name", "abhijit roy");

		// auto val = redis.get("name");
		// std::cout << val << "\n";
		std::cout << redis.ping() << "\n";
	}
	catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	}

	return 0;
}
```
- Output:
```console
$ g++ -std=c++17 test.cpp -lredis++ -lhiredis -pthread
$ ./a.out
PONG
```
