### ISSUE TITLE
 sentinel is fully supported? 

### ISSUE THREAD

**Issue by lixiaochun** [sewenew/redis-plus-plus#7]
hi i want to know if sentinel is fully supported? thank you:)

**Comment by lixiaochun** [comment]
thank you for your information and support,  and I already found another easy way to connect sentinel cluster  using single redis intance driver instead of sentinel pool,  and read and write could be also fully seperated. the main idea is shown as below. this is temp way haha and could be working properly,  and i 
 will still use  redis-plus-plus  to connect sentinel using single redis intance driver , and once  redis-plus-plus supports sentinel senario,  i will remove consul and dns related components to make redis setup  as easy as possible:) 
![image](https://user-images.githubusercontent.com/9587277/51594584-b7dabb00-1f2f-11e9-9df3-991e192c5b6e.png)

**Comment by sewenew** [comment]
Hi @lixiaochun 

Now sentinel is supported by redis-plus-plus. You can try the latest code of master branch.

With this feature, `Redis` can get master or slave address from Redis Sentinel. Even if a failover occurs, it can automatically get the address of the new master.

```
SentinelOptions sentinel_opts;
sentinel_opts.nodes = {{"127.0.0.1", 9000},
                        {"127.0.0.1", 9001},
                        {"127.0.0.1", 9002}};
auto sentinel = std::make_shared<Sentinel>(sentinel_opts);
ConnectionOptions connection_opts;
connection_opts.connect_timeout = std::chrono::milliseconds(100);   // Required.
connection_opts.socket_timeout = std::chrono::milliseconds(100);     // Required.
auto master = Redis(sentinel, "master_name", Role::MASTER, connection_opts);
auto slave = Redis(sentinel, "master_name", Role::SLAVE, connection_opts);
master.set("key", "value");
slave.get("key");
```

Please see the [doc](https://github.com/sewenew/redis-plus-plus#redis-sentinel) for detail. If you have any problem, feel free to let me know.

Regards

**Comment by lixiaochun** [comment]
perfect, thank you very much for your information, I will try it ASAP:)

**Comment by lixiaochun** [comment]
sentinel fully supported ,  good work:)

**Comment by sewenew** [comment]
Hi @lixiaochun ,

Recently, I find a bug which might make the Redis object created with Sentinel, not work properly. Please update your code to the latest master branch.

Sorry for the inconvenience...

Regards
