### ISSUE TITLE
How do free a cluster redis?

### ISSUE THREAD

**Issue by dairuiqiang** [sewenew/redis-plus-plus#72]
I want to use redis interface in cluster hash-tag mode, but the connection cannot be released after use, and I also don't want to release the cluster pointer. Is there any way to release the redis connection after use?

		auto redisCluster = new RedisCluster(connection_options, pool_opts);
		auto redis = redisCluster->redis(hasttag);
		auto tx = redis.transaction(true);
                tx.set(key1, data);
                tx.del(key2);
                tx.exec();

**Comment by sewenew** [comment]
Hi @dairuiqiang 

So far, `RedisCluster::redis(const StringView &hashtag)` creates a `Redis` object with a new connection to server. When the created `Redis` object is destroyed, the underlying connection will be closed. So you can put your code into a block scope:

```
auto redisCluster = new RedisCluster(connection_options, pool_opts);
{
    auto redis = redisCluster->redis(hasttag);
    auto tx = redis.transaction(true);
            tx.set(key1, data);
            tx.del(key2);
            tx.exec();
}    // When `redis` is destroyed, the connection will be closed.
```

**NOTE**: This behavior will be changed in the near future: instead of creating a new connection, this method will fetch a connection from the underlying connection pool of the `RedisCluster` object. Then you don't need to worry about the new connection. However, the code is still on the dev branch. If you're interest, you can check out the dev branch, and have a try.

Regards

**Comment by ruiqiangdai** [comment]
Thank a lot for replying. But when I use it:
auto redisCluster = new RedisCluster(connection_options, pool_opts);
{
    auto redis = redisCluster->redis(hasttag);  //I can't return the connection information here, so they all fail.   
    auto tx = redis.transaction(true);
            tx.set(key1, data);
            tx.del(key2);
            tx.exec();
}
Errmsg is Failed to connect to Redis: Name or service not known.

**Comment by dairuiqiang** [comment]
Thank a lot for replying. But when I use it:
auto redisCluster = new RedisCluster(connection_options, pool_opts);
{
     auto redis = redisCluster->redis(hasttag); //I can't return the connection information here, so they all fail.
     auto tx = redis.transaction(true);
     tx.set(key1, data);
     tx.del(key2);
     tx.exec();
}
Errmsg is Failed to connect to Redis: Name or service not known.

**Comment by sewenew** [comment]
Hi @dairuiqiang 

What do you mean: *I can't return the connection information here, so they all fail*?

The error message means the host you specified in `connection_option` cannot be reached. I guess it's `new RedisCluster(connection_options, pool_opts);` throws exception not `redisCluster->redis(hasttag);`, right? If you're not sure, you can try the following code:

```
try {
    auto redisCluster = new RedisCluster(connection_options, pool_opts);

    try {
        auto redis = redisCluster->redis(hashtag);
    } catch (const Error &e) {
        cout << "redis throws: " << e.what() << endl;
    }
} catch (const Error &e) {
    cout << "RedisCluster throws: " << e.what() << end;
}
```

If it's print *RedisCluster throws*, you can check if the host you specified in connection_option is reachable.

Regards

**Comment by dairuiqiang** [comment]
Hi @sewenew Thank a lot for replying
I am coded according to redisCluster->redis(hashtag), and always return an error when calling redis.transaction When using gdb, I find that the connection cannot be returned correctly when calling RedisCluster::redis.

**Comment by sewenew** [comment]
Hi @dairuiqiang 

My BAD!!! I gave you an incorrect answer.

In fact, the `Redis` object returned by `RedisCluster::redis` method cannot be used to create `Transaction` object. Instead, you should use the `RedisCluster::transaction` method to create one.

```
auto tx = redisCluster->transaction(hashtag, true);
tx.set(key1, data);
tx.del(key2);
tx.exec();
```

When you try to create a `Transaction` object from a `Redis` object obtained with `RedisCluster::redis` method, it should throw an exception. I'll fix this soon.

Thanks a lot for find this problem.

If you still have any problem on it, feel free to let me know:)

Regards

**Comment by dairuiqiang** [comment]
Hi @sewenew

I see. Thank again for your answer.

Regards
