### ISSUE TITLE
How to store vector of float in redis by 'hmset' ?

### ISSUE THREAD

**Issue by woodenwatcher** [sewenew/redis-plus-plus#73]
will the follow code work?

std::unordered_map<std::string, std::vector<float>> floats_map = {{"f1", {0.6,0.8,0.7}}, {"f2", {0.5,0.4,0.3}}, {"f3", "0.9,0.1,0.2"}};
redis.hmset("hash", floats_map.begin(), floats_map.end());

**Comment by sewenew** [comment]
Hi @woodenwatcher 

Your code won't work, since the value of HASH can only be STRING. If you insist on saving a vector of float as the HASH value, you have to serialize it into a string, e.g. converting float to string and concat these strings with some delimiter.

Take the following code as an example:

```
unordered_map<string, vector<float>> m = {{"f1", {0.6,0.8,0.7}}, {"f2", {0.5,0.4,0.3}}, {"f3", "0.9,0.1,0.2"}};
unordered_map<string, string> kv;
for (const auto &ele : m) {
    const auto &key = ele.first;
    const auto &value =ele.second;
    string val;
    for (auto iter = value.begin(); iter != value.end(); ++iter) {
        if (iter != value.begin()) {
            val += ",";
        }
        val += to_string(*iter);
    }
    kv.emplace(key, val);
}
redis.hmset("hash", kv.begin(), kv.end());
```

Regards

**Comment by woodenwatcher** [comment]
Can I serialize these float numbers to a bytes buffer for saving memory? I think the value of HASH can be a binary data

**Comment by sewenew** [comment]
YES, you can. HASH value is binary safe.

Regards

**Comment by woodenwatcher** [comment]
but how can i pass the 'bytes buffer' argument to 'hmset' ? use stringView?

**Comment by sewenew** [comment]
There're two methods:

- If your bytes buffer is a char array, you can construct a `StringView` with a pointer and length: `StringView(const char*buf, size_t len)`

- If your bytes buffer is a `std::string`, it can be converted to `StringView` implicitly: `StringView(const std::string &buf)`

Regards
