### ISSUE TITLE
Is pub/sub supported in cluster mode?

### ISSUE THREAD

**Issue by sbluemin** [sewenew/redis-plus-plus#8]
Hi, i want pub/sub with cluster mode.

Is it supported?

Your project is very useful!

Thank you!

**Comment by sewenew** [comment]
Yes, `RedisCluster` supports pub/sub, it has the same interface as `Redis`. You can use `RedisCluster::publish` method to publish messages, and use `RedisCluster::subscriber` to create a subscriber, and consume messages with the subscriber. Check the [doc](https://github.com/sewenew/redis-plus-plus#publishsubscribe) for details. It also have an example on how to subscribe.

P.S. I'm glad that you like *redis-plus-plus*. If you have any problem, feel free to let me know.

Regards
