### ISSUE TITLE
Unexpected ReplyError

### ISSUE THREAD

**Issue by terry8yu** [sewenew/redis-plus-plus#81]
If I run another shell command after some operations, the try-catch will thrown ReplyError exception, message like:
ERR unknown command `before`, with args beginning with: `exec`, `bash:ls`, `-l`,
Here is my code:

        try
        {
            if (g_pRedis)
            {
                std::string strKey("FATRI:WEB-UPDATER:INDEX");
                if (!g_pRedis->exists(strKey))
                {
                    usleep(50 * 1000);
                    continue;
                }
                auto        item = g_pRedis->zpopmax(strKey);
                g_Log.LogMessage(12, "[Tip:%s] Found web-updater command [id : %s][score : %.6lf].", __func__, item->first.c_str(), item->second);
                strKey.assign("FATRI:WEB-UPDATER:").append(item->first);
                if (g_pRedis->exists(strKey))
                {
                    std::vector<OptionalString> res;
                    g_pRedis->hmget(strKey, {"WebId", "WebPath", "WebBackPath", "FileLinkUrl"}, std::back_inserter(res));
                    g_Log.LogMessage(12, "[Tip:%s] Command fields [WebId : %s][WebPath : %s][WebBackPath : %s][FileLinkUrl : %s].", __func__,
                        res[0] ? res[0]->c_str() : "", res[1] ? res[1]->c_str() : "", res[2] ? res[2]->c_str() : "", res[3] ? res[3]->c_str() : "");
                    if (res[3])
                    {
                        std::string strRet = ExecShellCommand(std::string(res[3]->c_str())); // Here I exec shell command ls -l /work
                        g_Log.LogMessage(12, "[Tip:%s] Exec : %s Output: \r\n%s", __func__, res[3]->c_str(), strRet.c_str());
                    }
                }                
            }
            else
            {
                usleep(1000 * 1000);
            }
        }
        catch (const ReplyError& err)
        {
            // WRONGTYPE Operation against a key holding the wrong kind of value
            g_Log.LogMessage(0, "[Error:%s] Redis ReplyError exception thrown [%s].", __func__, err.what());
        }

ExecShellCommand code:
std::string ExecShellCommand(std::string strCmd)
{
    char        szBuf[1024];
    FILE*       fp;
    std::string strRes;
    // system call
    std::cout << "before exec bash:" << strCmd << std::endl;
    const char* sysCommand = strCmd.data();
    if ((fp = popen(sysCommand, "r")) == NULL)
    {
        strRes.assign("error");
        std::cout << "error" << std::endl;
        return strRes;
    }
    while (!::feof(fp))
    {
        size_t iCnt = ::fread(szBuf, 1, sizeof(szBuf), fp);
        if (iCnt > 0)
        {
            strRes.append(szBuf, szBuf + iCnt);
        }
        usleep(500 * 1000);
    }
    pclose(fp);

    return strRes;
}

**Comment by sewenew** [comment]
@terry8yu It seems string outputted to stdout has been sent to Redis:

```
std::cout << "before exec bash:" << strCmd << std::endl;   // strCmd = "ls -l /work";
```

It's really strange, but I cannot reproduce it. Can you give me a runnable example? So that I can debug it.

Regards

**Comment by sewenew** [comment]
Also, is there anywhere that your code read a string from stdout, and calls `Redis::command` to send the string to Redis?

**Comment by terry8yu** [comment]
There is no other operation to do the calls like Redis::command, I just embedded ExecShellCommand in the try-catch after the redis ralated calls, here is my whole code (https://file.fatri.cn:8443/pot/down/266265d0f331a67a4ba46d7a37e284f0.zip) you can comments g_Log related code to compile and run. Thank you any way for your reply & support !

**Comment by sewenew** [comment]
@terry8yu I run your code, and it works fine. I cannot reproduce your problem.

Also when you try to free the resource of Redis object, you should call `delete g_pRedis;`, instead of `free(g_pRedis);`

Regards

**Comment by terry8yu** [comment]
Thank you for your advices, here is my bin files, you can put fatri.cn, fatri1.0, libLogBird.so.2.0 in /fatri directory, and create /fatri/log/console to store log files, change parameters in the fatri.cn to yours, then run the fatri1.0, you can get log message like that appeared in 2020-08-17.000.log.

**Comment by sewenew** [comment]
@terry8yu Can you create a docker file with your code? So that I can debug it.

The following is an example of a docker file that installs redis, hiredis, and redis-plus-plus. You can add your stuff into it (download your code and dependencies). Thanks.

```
From alpine:3.12
RUN apk add --no-cache make g++ curl cmake unzip redis hiredis-dev
RUN mkdir /data;\
        cd /data;\
        curl -L -k 'https://github.com/sewenew/redis-plus-plus/archive/1.1.2.zip' -o redis-plus-plus.zip;\
        unzip redis-plus-plus.zip;\
        cd redis-plus-plus-1.1.2;\
        mkdir compile;\
        cd compile;\
        cmake ..;\
        make -j2;\
        make install;\
```

**Comment by terry8yu** [comment]
OK, use your Dockfile to create the image named: alpine-redispp:1.0.0, below is my Dockfile:
`FROM alpine-redispp:1.0.0
RUN  mkdir /fatri; \
     cd /fatri;\
     curl -L -k 'https://file.fatri.cn:8443/pot/down/55eaf3b04f06618339a027be1db939b0.zip' -o redispp-test.zip;\
     unzip redispp-test.zip;\
     cp libLogBird.so.2.0 /lib/;\
     chmod 755 build-fatri.sh;\
     ./build-fatri.sh;\
     mkdir log;\`

**Comment by sewenew** [comment]
@terry8yu I tried your Dockerfile with some modification, and it works fine. You can try the following Dockerfile, and see if you still have any problem?

```
From alpine:3.12
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache make g++ curl cmake unzip redis hiredis-dev
RUN mkdir /data;\
        cd /data;\
        curl -L -k 'https://github.com/sewenew/redis-plus-plus/archive/1.1.2.zip' -o redis-plus-plus.zip;\
        unzip redis-plus-plus.zip;\
        cd redis-plus-plus-1.1.2;\
        mkdir compile;\
        cd compile;\
        cmake ..;\
        make -j2;\
        make install;
RUN mkdir /fatri;\
        cd /fatri;\
        curl -L -k 'https://file.fatri.cn:8443/pot/down/55eaf3b04f06618339a027be1db939b0.zip' -o redispp-test.zip;\
        unzip redispp-test.zip;\
        cp libLogBird.so.2.0 /lib/;\
        chmod 755 build-fatri.sh;\
        ./build-fatri.sh;\
        mkdir log;
```

You can cd to the directory containing the Dockerfile, and run the following command to build it:

```
docker build --tag fatri .
```

When it successfully built, you can log on the docker container to do the test:

```
docker run -it fatri sh
```

You need to cd to modify `/fatri/fatri.cnf`, and set `svr_ip=127.0.0.1`. Run `redis-server &` to start Redis, then you can do your test.

**Comment by terry8yu** [comment]
Yes, you are right. I think the problem is about the function InitDaemon:
'
void    InitDaemon()
{
    pid_t pid;
    if ((pid = fork()) < 0)
    {
        exit(1);
    }
    else if (pid > 0)
    {
        exit(0);
    }

    setsid();

    if ((pid = fork()) < 0)
    {
        exit(1);
    }
    else if (pid > 0)
    {
        exit(0);
    }

    close(STDIN_FILENO);
    close(STDOUT_FILENO);
    close(STDERR_FILENO);
    chdir("/tmp");
    umask(0);
}
'
I want to run it in deamon mode, maybe the last few close(XXX) affect the result, the last code I send to you I commented the function and it worked fine. 
BTW, what's the minimal package list for container to run such application, maybe I just apk add c++ runtime, hiredis and compiled redis++, is it?

**Comment by sewenew** [comment]
@terry8yu I think you are right, since redis-plus-plus only depends on hiredis.
