### ISSUE TITLE
Does redis-plus-plus support async mehtod?

### ISSUE THREAD

**Issue by portsip** [sewenew/redis-plus-plus#82]
I want to use it to replace the https://github.com/cpp-redis/cpp_redis in my project.

**Comment by sewenew** [comment]
@portsip I'm so sorry, but there's no async method for redis-plus-plus. There's a TODO for async support. If I have any progress I'll let you know.

Regards

**Comment by sewenew** [comment]
Duplicate of #13

**Comment by sewenew** [comment]
Async support is out! Although, so far, Redis Cluster, Redis Sentinel, Transaction and Subscriber support are still on the way.

Please check the [doc](https://github.com/sewenew/redis-plus-plus#async-interface) for detail.

Regards

**Comment by c5h11oh** [comment]
Hi @sewenew ,

Thank you for the hard work! I am also trying to replace cpp_redis with redis_plus_plus.

Does AsyncRedis supports SSL connections as well? While I can connect to a Redis server with SSL enabled using synchronized "Redis" objects, I failed to do so using "AsyncRedis" using the same ConnectionOptions.

**Comment by sewenew** [comment]
@c5h11oh

I just added TLS support for async interface. Please check the latest code on dev branch. I'll do some more tests and merge the code into master.

Regards

**Comment by c5h11oh** [comment]
@sewenew 
I tried it today, and it works! Thank you for such a fast response! :)

**Comment by sewenew** [comment]
Hi all,

Async support has been release with redis-plus-plus 1.3.0.

Regards
