### ISSUE TITLE
Always return false when calling method from worker thread.

### ISSUE THREAD

**Issue by sbluemin** [sewenew/redis-plus-plus#9]
Hi, I using Redis Cluster client.

In all methods, worker threads are prevented from performing normal operations.

1. RedisClusterClient object (main thread)
2. hset is working ok. (main thread)
3. hset is alway not working. (worker thread)

My dev environment.
- c++14
- cpprestsdk (pplx)

PS. I'm not native speaker. sry.

**Comment by sewenew** [comment]
I think you might misunderstand the return value of `HSET` command. When it returns `false` it doesn't mean that the operation is failed, instead, it means that the field that you want to set, already exists, and the value is updated.

Please check [HSET manual](https://redis.io/commands/hset) and redis++'s doc for [boolean return value](https://github.com/sewenew/redis-plus-plus#boolean-return-value) for details.

Regards

**Comment by sbluemin** [comment]
Oh my mistake. thank you for your answer :)
