### ISSUE TITLE
Failed to refresh cluster slots topology

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#94]
@sewenew thanks for info about the merge. Could you please point me to information what sort of connection management changes were there on master?
Was about to create an issue here anyway about a similar topic. Some time ago I ran a test, where one of the cluster's node was restarted to see if redis-plus-plus would refresh the topology. Unfortunately it didn't go ok.
Code failed at https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis++/redis_cluster.hpp#L1332 - the problem was that it wasn't even able to send the CLUSTER SLOTS command.

Scenario description:
Redis enterprise 6.0.6-36
Regular DB with 2 shards and standard hashing policy
redis++ client fails to update list of nodes if a shard is migrated to another node (manually or during failover)

Any chance this is something fixed in the meantime?

Thanks!

_Originally posted by @mruki in https://github.com/sewenew/redis-plus-plus/issues/66#issuecomment-684814281_

**Comment by sewenew** [comment]
@mruki Redis-plus-plus support auto refresh the cluster slots info. When the slot info changes, it handles the moved and asking error. However, if you send command to Redis when the slot is migrating, the client might fail, and client will try at most 3 times.If the migration still has not finished, it throws an error. You can retry it latter.

Regards

**Comment by mruki** [comment]
ok, will give this approach a try. thanks

**Comment by mruki** [comment]
OK, so I adapted my code to be resilient to resharding of a cluster.
What I am doing is I'm catching an exception, reconstructing a connection and sending the command once again.

```
class RetryableOperation
{
    RedisConnection& parentConnection;
    int retries;
    const int retriesAllowed = 3;

    bool isRetryAllowed() const
    {
        return (retriesAllowed - retries) > 0;
    }

public:
    RetryableOperation(RedisConnection& redisConnection)
        : connection(redisConnection)
        , retries(0)
    {
    }

    template<class Lambda>
    auto execute(Lambda& redisCommand)
    {
        try
        {
            return redisCommand(connection.redisCluster);
        }
        catch (const std::exception& e)
        {
            if (isRetryAllowed())
            {
                ++retries;
                connection.reconnect(); // RedisConnection is a simple class holding RedisCluster instance and reconnect just reconstructs it, when needed
                return execute(redisCommand);
            }
            throw std::runtime_error(std::string("Cannot execute a Redis command: ") + std::string(e.what()));
        }
    }
};
```

and using this like:

```
auto command = [&key, &value](auto& redisConn) {return redisConn->set(key, value);};
auto inserted = RetryableOperation(redisConnection).execute(command);
```
I guess c++ >= 14 is required for this too work.

Maybe it's a specific setup only in my case relating to how the cluster is constructed, but the step with connection reconstruction is crucial. It's not just enough to reattempt. I need to construct new RedisCluster object using the original cluster URL. If I don't it'll keep trying to connect to the 'old' node, which is not a master node anymore. Instead it needs to connect to the original URL to get the current master node and then continue working against this node.

Thanks so much for your help and feel free to close this.
